/* resource set indices for TEPS */

#define MAINMENU   0 /* menu */
#define FILEMENU   4 /* TITLE in tree MAINMENU */
#define WORKMENU   5 /* TITLE in tree MAINMENU */
#define ABOUT      8 /* STRING in tree MAINMENU */
#define NEW       17 /* STRING in tree MAINMENU */
#define SAMLOAD   18 /* STRING in tree MAINMENU */
#define ENDE      20 /* STRING in tree MAINMENU */
#define CHGNSIGN  22 /* STRING in tree MAINMENU */

#define MAINDIAL   1 /* form/dialog */
#define SREPEAT    4 /* BOX in tree MAINDIAL */
#define MODUSBUT   6 /* BOXTEXT in tree MAINDIAL */
#define FREQBUT    7 /* BOXTEXT in tree MAINDIAL */
#define RVOLBOX   12 /* BOX in tree MAINDIAL */
#define RVOLSLID  13 /* BUTTON in tree MAINDIAL */
#define LVOLBOX   14 /* BOX in tree MAINDIAL */
#define LVOLSLID  15 /* BUTTON in tree MAINDIAL */
#define REC       17 /* BUTTON in tree MAINDIAL */
#define STOP      18 /* BUTTON in tree MAINDIAL */
#define PLAY      19 /* BUTTON in tree MAINDIAL */

#define MODI       2 /* form/dialog */
#define MODIBOX    0 /* BOX in tree MODI */
#define M8BUT      1 /* STRING in tree MODI */
#define S8BUT      2 /* STRING in tree MODI */
#define S16BUT     3 /* STRING in tree MODI */

#define FREQS      3 /* form/dialog */
#define FREQSBOX   0 /* BOX in tree FREQS */
#define F50KHZ     1 /* STRING in tree FREQS */
#define F32KHZ     2 /* STRING in tree FREQS */
#define F25KHZ     3 /* STRING in tree FREQS */
#define F20KHZ     4 /* STRING in tree FREQS */
#define F16KHZ     5 /* STRING in tree FREQS */
#define F14KHZ     6 /* STRING in tree FREQS */
#define F12KHZ     7 /* STRING in tree FREQS */
#define F11KHZ     8 /* STRING in tree FREQS */
#define F10KHZ     9 /* STRING in tree FREQS */
#define F9KHZ     10 /* STRING in tree FREQS */
#define F8KHZ     11 /* STRING in tree FREQS */
#define F7KHZ6    12 /* STRING in tree FREQS */
#define F7KHZ0    13 /* STRING in tree FREQS */
#define F6KHZ6    14 /* STRING in tree FREQS */
#define F6KHZ1    15 /* STRING in tree FREQS */

