CFLAGS =-s -v -z -m68000 -w -mshort
ASFLAGS = -m68000
vpath %.hyp doc_devp:docs
vpath %.u   doc_devp:docs
vpath %.stg doc_devp:docs
vpath %.tex docs
vpath %.dvi docs
vpath %.txt docs

hyp= c_gen_pr.hyp

all: $(hyp) c_gen.prg c_gen.txt c_gen.tex c_gen.stg
.PHONY:all update strip dodo doc TEX

OBJ = main.o rsc.o rsc_bis.o windform.o s_malloc.o code.o fenetre.o affichag.o f_expr.o
c_gen.prg: $(OBJ)
	gcc -oc_gen.prg $(CFLAGS) $(OBJ) -lgem16.olb

f_expr.o rsc.o rsc_bis.o	:c_gen.h
f_expr.o rsc_bis.o code.o affichag.o	:object.h
f_expr.o rsc.o rsc_bis.o windform.o code.o fenetre.o affichag.o	: windform.h
main.o windform.o rsc_bis.o code.h affichag.o	: s_malloc.h
rsc.o windform.o fenetre.o: not_falc.h

$(hyp): c_gen_pr.stg
	d:\program\st-guide\hcp.ttp +zz d:\gnu\sources\c_gen\doc_devp\c_gen_pr.stg
	cp c:\guides\$(hyp) d:\gnu\sources\c_gen\doc_devp\$(hyp)
	cp c:\guides\c_gen_pr.ref d:\gnu\sources\c_gen\doc_devp\c_gen_pr.ref

c_gen_pr.stg:	c_gen_pr.u windform.u intro.u struct.u stru_prg.u
	udo -s -y -l --verbose -o d:\gnu\sources\c_gen\doc_devp\c_gen_pr.stg d:\gnu\sources\c_gen\doc_devp\c_gen_pr.u
c_gen.tex: c_gen.u
	udo -t -y -l --verbose -o d:\gnu\sources\c_gen\docs\c_gen.tex d:\gnu\sources\c_gen\docs\c_gen.u
c_gen.txt: c_gen.u
	udo -a -y -l --verbose -o d:\gnu\sources\c_gen\docs\c_gen.txt d:\gnu\sources\c_gen\docs\c_gen.u
c_gen.stg: c_gen.u
	udo -s -y -l --verbose -o d:\gnu\sources\c_gen\docs\c_gen.stg d:\gnu\sources\c_gen\docs\c_gen.u


update:
	lharc.ttp a -5 -r -b -y $(ARCHIVE)
	
strip:
	strip.ttp -a $(PRG)
	
dodo: all doc update 
	cp $(ARCHIVE) a:\c_gen.lzh

TEX:
	udo -t -y -l --verbose -o d:\util\tex\inputs\c_gen_pr.tex d:\gnu\sources\c_gen\doc_devp\c_gen_pr.u


c_gen.hyp: c_gen.stg 
	d:\program\st-guide\hcp.ttp +zz d:\gnu\sources\c_gen\docs\c_gen.stg
	cp c:\guides\c_gen.hyp d:\gnu\sources\c_gen\docs\c_gen.hyp
	cp c:\guides\c_gen.ref d:\gnu\sources\c_gen\docs\c_gen.ref
c_gen.dvi: c_gen.tex
	cp d:\gnu\sources\c_gen\docs\c_gen.tex d:\util\tex\inputs\c_gen.tex
#	tex d:\gnu\sources\c_gen\docs\c_gen.tex
	cp d:\util\tex\outputs\c_gen.dvi d:\gnu\sources\c_gen\docs\c_gen.dvi

doc: c_gen.txt c_gen.hyp c_gen.dvi
#	todos d:\gnu\sources\c_gen\docs\c_gen.txt
