#!/bin/csh
#
# To initialize SB-Prolog Version 3. You need to run this file before 
# calling SB-Prolog. You may want to # include the file in your .cshrc or 
# .login for convenience.
#
set SBPDIR=/usr/local/sbprolog/v3.0     
set VERSION='Version 3.0 '                      # version number
set MEMORY=1000000                              # 1M to avoid gc's
#

echo Using SB-Prolog $VERSION
setenv SIMPATH $SBPDIR/lib:$SBPDIR/modlib:$SBPDIR/cmplib:.
alias sbp $SBPDIR/sim/sbprolog -m $MEMORY $SBPDIR/modlib/\\\$readloop
