# makefile for Lattice MultiTOS mt libs
#########################################################################
# 920629 kbad

#########################################################################
# Library specific definitions

_AES	= _aes.o
_AESIF	= _aesif.c
APSRC	= appl_get.c appl_nam.c appl_reg.c appl_sea.c
EVSRC	= evnt_emu.c evnt_rea.c
MNSRC	= menu_att.c menu_ist.c menu_own.c menu_pop.c menu_set.c
RSSRC	= objc_gcl.c objc_sys.c rsrc_rcf.c
SHSRC	= shel_bro.c shel_cha.c shel_cop.c shel_gle.c shel_gro.c shel_msg.c \
	shel_put.c shel_run.c shel_set.c shel_shu.c shel_siz.c
WISRC	= wind_bev.c wind_gbu.c wind_gco.c wind_gde.c wind_gre.c wind_gst.c \
	wind_gwo.c wind_sde.c wind_sst.c wind_upd.c

CSRC	= $(_AESIF) $(APSRC) $(EVSRC) $(MNSRC) $(RSSRC) $(SHSRC) $(WISRC)

# Definitions for 'makelib' template
LIBNAME	= mt
INSTALL = c:\lc\lib
LIBDEPS	= $(_AES) $(CSRC)
COBJ	= $(_AESIF:.c=.o) $(APSRC:.c=.o) $(EVSRC:.c=.o) $(MNSRC:.c=.o) \
	$(RSSRC:.c=.o) $(SHSRC:.c=.o) $(WISRC:.c=.o)

# Makelib template
include c:\lc\bin\makelib

CDEF = -i..

#########################################################################
# Library-specific dependencies

foo: $(LIBDEPS)
    echo $($(LIBDEPS:%.c):.c=.o)
