##### MAKEFILE fÅr SCRAP #####

###############################################################################

NAME   = scrap

###############################################################################

CFLAGS = -VPEEP

LFLAGS = -x -s -f -laes -lvdi

APP    = .prg

###############################################################################

H      = import.h export.h global.h

OBJS   = clipbrd.o desktop.o dialog.o disk.o edit.o event.o gemain.o global.o\
         graf.o image.o initerm.o menu.o meta.o power.o printer.o rcm.o\
         resource.o trash.o windows.o

###############################################################################

$(NAME)$(APP): $(OBJS)
		$(CC) $(OBJS) $(LFLAGS) -o $@

###############################################################################

clipbrd.o : $(H) windows.h $(NAME).h errors.h desktop.h dialog.h edit.h image.h meta.h trash.h resource.h clipbrd.h
desktop.o : $(H) windows.h $(NAME).h errors.h clipbrd.h dialog.h disk.h event.h menu.h printer.h trash.h desktop.h
dialog.o  : $(H) windows.h dialog.h
disk.o    : $(H) windows.h $(NAME).h errors.h dialog.h disk.h
edit.o    : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h printer.h edit.h
event.o   : $(H) windows.h desktop.h menu.h event.h
gemain.o  : $(H) windows.h initerm.h event.h gemain.h
global.o  : $(H)
graf.o    : $(H) windows.h $(NAME).h graf.h
image.o   : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h printer.h image.h
initerm.o : $(H) windows.h $(NAME).h errors.h resource.h menu.h event.h dialog.h desktop.h trash.h disk.h printer.h edit.h clipbrd.h image.h meta.h graf.h power.h initerm.h
menu.o    : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h disk.h graf.h power.h resource.h menu.h
meta.o    : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h image.h printer.h meta.h
power.o   : $(H) windows.h $(NAME).h resource.h power.h
printer.o : $(H) windows.h $(NAME).h errors.h dialog.h printer.h
rcm.o     : rcm.h
resource.o: $(H) $(NAME).h resource.h
trash.o   : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h trash.h
windows.o : $(H) windows.h

###############################################################################

