# Makefile for the Atari ST (with LynxLib) version of Sokoban

#CFLAGS = -c -VCSD -Ic:\ul\c
OBJECTS= sok.o readscreen.o showscreen.o play.o save.o score.o
sokoban: $(OBJECTS)
	cc -o sokoban.ttp $(OBJECTS)

sok.o: sok.c sokoban.h
readscreen.o: readscreen.c sokoban.h
showscreen.o: showscreen.c sokoban.h
play.o: play.c sokoban.h
save.o: save.c sokoban.h
score.o: score.c sokoban.h

sokobin.zoo : sokoban.ttp
	zoo a-P sokobin.zoo sokoban.ttp sokoban.6 sokoban.hlp screens\*.*

SRC = makefile play.c readme \
	readscre.c save.c score.c showscre.c \
	sok.c sokoban.h sokoban.hlp

sokosrc.zoo : $(SRC)
	zoo a-P sokosrc.zoo $?
