.TH SOKOBAN 6
.SH NAME
sokoban - maze-like puzzle game
.SH SYNOPSIS
.B /yale/games/sokoban
[
.BI -c
] [
.BI -r
] [
.BI -s
] [
.BI -<nn>
]
.SH DESCRIPTION
The problem is to push packets to saving positions by moving around
and pushing only one packet at a time if possible. All you have to know
when you first play the game is the command '?'. This gives you one
screenfull of information.
.PP
You are represented by @@. The packets are $$. Movement is as in
.BR vi.
You may not push packets through walls (##) or through each other.
.PP
You may make a "temporary save". This is useful if you think that all
the moves/pushes you have made are correct, but you don't know how to
go on. In this case you can temporary save (using the c command). If you
then get stucked you need not undo all (using U); you can reset to your
temporary save (with ^U).
.PP
If you have restored a saved game, a temporary save is automatically made
at the start.
.SH OPTIONS
.IP -c:
create new score table (superuser only; prompts for password)
.IP -r:
restore saved game
.IP -s:
show score table
.IP -<nn>:
play level #nn (<nn> must be greater than 0)
.SH AUTHOR
<elsewhere>!pyramid!tub!astbe!ber
