/* Indices du fichier ressource pour WINDUPDT: */

#define DL_TITRE_FENETRE 0   /* Formulaire/Dialogue: */
#define TITRE_INFO       2   /* STRING dans l'arbre DL_TITRE_FENETRE */
#define TITRE_PREFERENCE 3   /* STRING dans l'arbre DL_TITRE_FENETRE */
#define TITRE_WINDUPDATE 4   /* STRING dans l'arbre DL_TITRE_FENETRE */
#define TITRE_MODCONFIG  5   /* STRING dans l'arbre DL_TITRE_FENETRE */
#define TITRE_SAMPLEINFO 6   /* STRING dans l'arbre DL_TITRE_FENETRE */
#define TITRE_SEQ_INFO   7   /* STRING dans l'arbre DL_TITRE_FENETRE */
#define TITRE_PTRN_INFO  8   /* STRING dans l'arbre DL_TITRE_FENETRE */

#define DL_INFO_PRG      1   /* Formulaire/Dialogue: */
#define INFO_CDR_TITRE   3   /* BOX dans l'arbre DL_INFO_PRG */
#define LOGO_RENAISSANCE 5   /* IMAGE dans l'arbre DL_INFO_PRG */
#define INFO_PRG_VERSION 8   /* STRING dans l'arbre DL_INFO_PRG */
#define INFO_PRG_DATE    9   /* STRING dans l'arbre DL_INFO_PRG */
#define INFO_DBUG        10  /* TEXT dans l'arbre DL_INFO_PRG */
#define INFO_COMPIL_DATE 12  /* TEXT dans l'arbre DL_INFO_PRG */
#define INFO_COEUR_VER   14  /* TEXT dans l'arbre DL_INFO_PRG */
#define INFO_GEMLIB_VER  16  /* TEXT dans l'arbre DL_INFO_PRG */
#define INFO_GCC_VER     18  /* TEXT dans l'arbre DL_INFO_PRG */

#define DL_ICON_INFO     2   /* Formulaire/Dialogue: */

#define DL_OPT_PREF      3   /* Formulaire/Dialogue: */
#define PREF_SAVE_AUTO   1   /* BUTTON dans l'arbre DL_OPT_PREF */
#define PREF_SAVE_CONFIG 2   /* BUTTON dans l'arbre DL_OPT_PREF */

#define DL_ICON_PREF     4   /* Formulaire/Dialogue: */

#define BARRE_MENU       5   /* Menu: */
#define MN_INFO_PRG      9   /* STRING dans l'arbre BARRE_MENU */
#define MN_QUITTER       18  /* STRING dans l'arbre BARRE_MENU */
#define MN_WINDUPDATE    20  /* STRING dans l'arbre BARRE_MENU */
#define MN_PREFERENCE    22  /* STRING dans l'arbre BARRE_MENU */
#define MN_SAUVER_CONFIG 24  /* STRING dans l'arbre BARRE_MENU */

#define DL_WINDUPDATE    6   /* Formulaire/Dialogue: */
#define WU_FOND_BAR      2   /* BOX dans l'arbre DL_WINDUPDATE */
#define WU_I_FOND_BAR    3   /* IBOX dans l'arbre DL_WINDUPDATE */
#define WU_BAR_AVANT     4   /* BOX dans l'arbre DL_WINDUPDATE */
#define WU_POSITION_BAR  5   /* BOX dans l'arbre DL_WINDUPDATE */
#define WU_BAR_ARRIERE   6   /* BOX dans l'arbre DL_WINDUPDATE */
#define WU_BLOCK         7   /* BUTTON dans l'arbre DL_WINDUPDATE */
#define WU_NOBLOCK       8   /* BUTTON dans l'arbre DL_WINDUPDATE */
#define WU_REDRAW_START  11  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_REDRAW_FINISH 14  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_CONSEC_FINISH 16  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_RECORD_FINISH 18  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_REDRAW_SKIP   21  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_CONSEC_SKIP   23  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_RECORD_SKIP   25  /* BOXTEXT dans l'arbre DL_WINDUPDATE */
#define WU_BT_FULLTIME   26  /* BUTTON dans l'arbre DL_WINDUPDATE */
#define WU_NOMBRE_MODE   27  /* BUTTON dans l'arbre DL_WINDUPDATE */
#define WU_BT_RAZ        28  /* BUTTON dans l'arbre DL_WINDUPDATE */
#define WU_AES_VERSION   31  /* STRING dans l'arbre DL_WINDUPDATE */
#define WU_APPL_GETINFO  33  /* STRING dans l'arbre DL_WINDUPDATE */

#define DL_ICON_WINDUPTE 7   /* Formulaire/Dialogue: */

#define ALT_BAD_REZ      0   /* Chaine d'alerte: */

#define ALT_NO_WINDOWS   1   /* Chaine d'alerte: */

#define ALT_NORAMCONFIG  2   /* Chaine d'alerte: */

#define ALT_NO_INF_FILE  3   /* Chaine d'alerte: */

#define ALT_NO_FILE_SEL  4   /* Chaine d'alerte: */

#define ALT_NO_MORE_RAM  5   /* Chaine d'alerte: */

#define ALT_BAD_CONFIG   6   /* Chaine d'alerte: */

#define ALT_ERROR_FILE   7   /* Chaine d'alerte: */

#define ALT_ERR_SAVE_INF 8   /* Chaine d'alerte: */

#define ALT_ERR_OPEN_INF 9   /* Chaine d'alerte: */

#define ALT_ERR_STARTWIN 10  /* Chaine d'alerte: */

#define ALT_ERR_NOFUNC   11  /* Chaine d'alerte: */

#define ALT_BAD_FILE     12  /* Chaine d'alerte: */

#define ALT_FILE_NOFOUND 13  /* Chaine d'alerte: */

#define ALT_AV_BAD_FILE  14  /* Chaine d'alerte: */

#define ALT_AV_NO_FILE   15  /* Chaine d'alerte: */

#define ALT_WINFRAME_ERR 16  /* Chaine d'alerte: */

#define ALT_TAG_TOO_LONG 17  /* Chaine d'alerte: */

#define ALT_ERR_OVERWRIT 18  /* Chaine d'alerte: */
