# Makefile for the program CHAOS
# Fill in the path to the Mark Williams C header files on the line below
HDIR = 
# Fill in the path to the Mark Williams C GEM routines on the line below
ODIR = 
# The next macro specifies the compilation include the debugger stuff
# CFLAGS = -VCSD
OBJS = chaos.o do_nvert.o do_dist.o do_niter.o do_pvert.o about.o \
         writeone.o do_chaos.o fselopen.o gemstart.o lowercas.o plotline.o \
         printcha.o saverast.o scrndump.o uppercas.o do_palet.o locate.o \
         fexists.o objc_box.o
chaos.prg: $(OBJS)
   cc -o chaos.prg -VGEM $(OBJS)
about.o: chaos.h easy.h
chaos.o: chaos.h easy.h
do_chaos.o: chaos.h easy.h
do_dist.o: chaos.h easy.h
do_niter.o: chaos.h easy.h
do_nvert.o: chaos.h easy.h
do_palet.o: easy.h
do_pvert.o: easy.h
fexists.o: easy.h
fselopen.o: easy.h
gemstart.o: easy.h
locate.o: easy.h
lowercas.o: easy.h
objc_box.o: easy.h
plotline.o: easy.h
printcha.o: easy.h
saverast.o: easy.h
scrndump.o: easy.h
uppercas.o: easy.h
writeone.o: easy.h
