/* Indices du fichier ressource pour EG_RSC */

#define HWIN             0   /* Formulaire/Dialogue */
#define FWINCLS          1   /* USERDEF dans l'arbre HWIN */
#define FWINAME          2   /* BOXTEXT dans l'arbre HWIN */
#define FWINCYC          3   /* USERDEF dans l'arbre HWIN */
#define FWINICO          4   /* USERDEF dans l'arbre HWIN */
#define FWINPOP          5   /* USERDEF dans l'arbre HWIN */
#define FWINFUL          6   /* USERDEF dans l'arbre HWIN */
#define FWINVSF          7   /* BOXTEXT dans l'arbre HWIN */
#define FWINVSP          8   /* BOXTEXT dans l'arbre HWIN */
#define FWINVSI          9   /* USERDEF dans l'arbre HWIN */
#define FWINUAR          10  /* USERDEF dans l'arbre HWIN */
#define FWINDAR          11  /* USERDEF dans l'arbre HWIN */
#define FWINHSF          12  /* BOXTEXT dans l'arbre HWIN */
#define FWINHSP          13  /* BOXTEXT dans l'arbre HWIN */
#define FWINHSI          14  /* USERDEF dans l'arbre HWIN */
#define FWINLAR          15  /* USERDEF dans l'arbre HWIN */
#define FWINRAR          16  /* USERDEF dans l'arbre HWIN */
#define FWINSIZ          17  /* USERDEF dans l'arbre HWIN */

#define LWIN             1   /* Formulaire/Dialogue */

#define FPOP             2   /* Formulaire/Dialogue */
#define FPOPBOX          1   /* BOX dans l'arbre FPOP */
#define FPOPF            2   /* BOXTEXT dans l'arbre FPOP */
#define FPOPP            3   /* BOXTEXT dans l'arbre FPOP */
#define FPOPI            4   /* USERDEF dans l'arbre FPOP */
#define FPOPUP           5   /* USERDEF dans l'arbre FPOP */
#define FPOPDN           6   /* USERDEF dans l'arbre FPOP */

#define FUSER            3   /* Formulaire/Dialogue */
#define FUSDPOP          1   /* USERDEF dans l'arbre FUSER */
#define FUSDCIR          3   /* USERDEF dans l'arbre FUSER */
#define FUSDCAR          5   /* USERDEF dans l'arbre FUSER */
#define FUSDDAR          7   /* IMAGE dans l'arbre FUSER */
#define FUSDUAR          9   /* IMAGE dans l'arbre FUSER */
#define FUSDLAR          11  /* IMAGE dans l'arbre FUSER */
#define FUSDRAR          13  /* IMAGE dans l'arbre FUSER */
#define FUSDLQAR         15  /* IMAGE dans l'arbre FUSER */
#define FUSDRQAR         17  /* IMAGE dans l'arbre FUSER */

#define FMOUSE           4   /* Formulaire/Dialogue */
#define FSOUSIZ          9   /* ICON dans l'arbre FMOUSE */
#define FSOUUPDN         10  /* ICON dans l'arbre FMOUSE */
#define FSOUUP           11  /* ICON dans l'arbre FMOUSE */
#define FSOUDN           12  /* ICON dans l'arbre FMOUSE */
#define FSOUFNT          13  /* ICON dans l'arbre FMOUSE */

#define FINF             5   /* Formulaire/Dialogue */
#define FINFVER          3   /* TEXT dans l'arbre FINF */
#define FINFC1           9   /* TEXT dans l'arbre FINF */
#define FINFC2           10  /* TEXT dans l'arbre FINF */
#define FINFC3           12  /* TEXT dans l'arbre FINF */
#define FINFPT1          15  /* TEXT dans l'arbre FINF */
#define FINFPT2          16  /* TEXT dans l'arbre FINF */

#define FMEM             6   /* Formulaire/Dialogue */
#define FMEMLEN          2   /* FTEXT dans l'arbre FMEM */
#define FMEMFRE          3   /* TEXT dans l'arbre FMEM */
#define FMEMSYS          4   /* TEXT dans l'arbre FMEM */
#define FMEMMIN          5   /* BUTTON dans l'arbre FMEM */
#define FMEMMAX          6   /* BUTTON dans l'arbre FMEM */
#define FMEMMOD          7   /* BUTTON dans l'arbre FMEM */

#define FFNT             7   /* Formulaire/Dialogue */
#define FFNTGTIT         2   /* TEXT dans l'arbre FFNT */
#define FFNTGPOP         3   /* BUTTON dans l'arbre FFNT */
#define FFNTGTYP         4   /* TEXT dans l'arbre FFNT */
#define FFNTGNOM         5   /* BOXTEXT dans l'arbre FFNT */
#define FFNTHTIT         7   /* TEXT dans l'arbre FFNT */
#define FFNTHPOP         8   /* BUTTON dans l'arbre FFNT */
#define FFNTHTYP         9   /* TEXT dans l'arbre FFNT */
#define FFNTHNOM         10  /* BOXTEXT dans l'arbre FFNT */
#define FFNTTTXT         11  /* TEXT dans l'arbre FFNT */
#define FFNTTFON         12  /* TEXT dans l'arbre FFNT */
#define FFNTCTXT         13  /* BUTTON dans l'arbre FFNT */
#define FFNTCFON         14  /* BUTTON dans l'arbre FFNT */
#define FFNTHTXT         15  /* TEXT dans l'arbre FFNT */
#define FFNTHSIZ         16  /* FTEXT dans l'arbre FFNT */
#define FFNTHSET         17  /* BUTTON dans l'arbre FFNT */

#define FOPT             8   /* Formulaire/Dialogue */
#define FOPTFNT          2   /* BUTTON dans l'arbre FOPT */
#define FOPTHLP          3   /* BUTTON dans l'arbre FOPT */
#define FOPTPOP          4   /* BUTTON dans l'arbre FOPT */
#define FOPTFUL          5   /* BUTTON dans l'arbre FOPT */
#define FOPTSAV          6   /* BUTTON dans l'arbre FOPT */
#define FOPTFRM          8   /* TEXT dans l'arbre FOPT */
#define FOPTFRM1         9   /* BUTTON dans l'arbre FOPT */
#define FOPTFRM2         10  /* BUTTON dans l'arbre FOPT */
#define FOPTFRM3         11  /* BUTTON dans l'arbre FOPT */
#define FOPTDIR          13  /* TEXT dans l'arbre FOPT */
#define FOPTPHLP         14  /* TEXT dans l'arbre FOPT */
#define FOPTFR           16  /* BUTTON dans l'arbre FOPT */
#define FOPTEN           18  /* BUTTON dans l'arbre FOPT */

#define FSYS             9   /* Formulaire/Dialogue */
#define FSYSMCH          3   /* STRING dans l'arbre FSYS */
#define FSYSPROC         5   /* STRING dans l'arbre FSYS */
#define FSYSREZ          7   /* STRING dans l'arbre FSYS */
#define FSYSTOS          10  /* STRING dans l'arbre FSYS */
#define FSYSGDOS         12  /* STRING dans l'arbre FSYS */
#define FSYSAES          14  /* STRING dans l'arbre FSYS */
#define FSYSMINT         16  /* STRING dans l'arbre FSYS */
#define FSYSNVDI         18  /* STRING dans l'arbre FSYS */
#define FSYSLET          20  /* STRING dans l'arbre FSYS */
#define FSYSFILE         21  /* BUTTON dans l'arbre FSYS */

#define PLIB             10  /* Formulaire/Dialogue */
#define PLIBINF          1   /* STRING dans l'arbre PLIB */
#define PLIBMEM          2   /* STRING dans l'arbre PLIB */
#define PLIBFNT          3   /* STRING dans l'arbre PLIB */
#define PLIBOPT          4   /* STRING dans l'arbre PLIB */
#define PLIBSYS          5   /* STRING dans l'arbre PLIB */
#define PLIBCNF          6   /* STRING dans l'arbre PLIB */
#define PLIBHLP          8   /* STRING dans l'arbre PLIB */

#define PHELP            11  /* Formulaire/Dialogue */
#define PHLPIND          1   /* STRING dans l'arbre PHELP */
#define PHLPDN           2   /* STRING dans l'arbre PHELP */
#define PHLPUP           3   /* STRING dans l'arbre PHELP */
#define PHLPHIST         5   /* STRING dans l'arbre PHELP */

#define PCOUL            12  /* Formulaire/Dialogue */

#define ICONE            13  /* Formulaire/Dialogue */

#define ICINF            14  /* Formulaire/Dialogue */

#define ICMEM            15  /* Formulaire/Dialogue */

#define ICFNT            16  /* Formulaire/Dialogue */

#define ICOPT            17  /* Formulaire/Dialogue */

#define ICSYS            18  /* Formulaire/Dialogue */

#define ICHLP            19  /* Formulaire/Dialogue */

#define _0LETFLY         0   /* Chaine d'alerte */

#define _1LETFLY         1   /* Chaine d'alerte */

#define _0NOWIN          2   /* Chaine d'alerte */

#define _1NOWIN          3   /* Chaine d'alerte */

#define _0NOHLP          4   /* Chaine d'alerte */

#define _1NOHLP          5   /* Chaine d'alerte */

#define TINFC1           6   /* Chaine libre */

#define TINFC2           7   /* Chaine libre */

#define TMEMMOD          8   /* Chaine libre */

#define TFNTCOLT         9   /* Chaine libre */

#define TFNTCOLF         10  /* Chaine libre */

#define TFNTGTIT         11  /* Chaine libre */

#define TFNTHTIT         12  /* Chaine libre */

#define TFNTHTXT         13  /* Chaine libre */

#define TOPTFNT          14  /* Chaine libre */

#define TOPTHLP          15  /* Chaine libre */

#define TOPTPOP          16  /* Chaine libre */

#define TOPTFUL          17  /* Chaine libre */

#define TOPTSAV          18  /* Chaine libre */

#define TOPTFRM          19  /* Chaine libre */

#define TOPTFRM1         20  /* Chaine libre */

#define TOPTFRM2         21  /* Chaine libre */

#define TOPTFRM3         22  /* Chaine libre */

#define TOPTDIR          23  /* Chaine libre */

#define TSYSFILE         24  /* Chaine libre */

#define TPLIBINF         25  /* Chaine libre */

#define TPLIBMEM         26  /* Chaine libre */

#define TPLIBFNT         27  /* Chaine libre */

#define TPLIBOPT         28  /* Chaine libre */

#define TPLIBSYS         29  /* Chaine libre */

#define TPLIBCNF         30  /* Chaine libre */

#define TPLIBHLP         31  /* Chaine libre */

#define TPHLPIND         32  /* Chaine libre */

#define TPHLPDN          33  /* Chaine libre */

#define TPHLPUP          34  /* Chaine libre */

#define TPCOUL0          35  /* Chaine libre */

#define TPCOUL1          36  /* Chaine libre */

#define TPCOUL2          37  /* Chaine libre */

#define TPCOUL3          38  /* Chaine libre */

#define TPCOUL4          39  /* Chaine libre */

#define TPCOUL5          40  /* Chaine libre */

#define TPCOUL6          41  /* Chaine libre */

#define TPCOUL7          42  /* Chaine libre */

#define TPCOUL8          43  /* Chaine libre */

#define TPCOUL9          44  /* Chaine libre */

#define TPCOULA          45  /* Chaine libre */

#define TPCOULB          46  /* Chaine libre */

#define TPCOULC          47  /* Chaine libre */

#define TPCOULD          48  /* Chaine libre */

#define TPCOULE          49  /* Chaine libre */

#define TPCOULF          50  /* Chaine libre */

#define WINF             51  /* Chaine libre */

#define WMEM             52  /* Chaine libre */

#define WFNT             53  /* Chaine libre */

#define WOPT             54  /* Chaine libre */

#define WSYS             55  /* Chaine libre */

#define WHLP             56  /* Chaine libre */
