char *help[] =
{
"",
"   W i n L u p e - faster than light",
"  -----------------------------------",
"",
"WinLupe ist ein kleines Utility, wel-",
"ches nach dem Freeware-Prinzip verteilt",
"wird. Dies bedeutet, daž jeder das ",
"Programm kopieren, benutzen und weiter-",
"geben darf, aužer es handelt sich um PD-",
"Versender, denn diese mssen sich bei",
"mir eine schriftliche Genehmigung ein-",
"holen.",
"",
"Grunds„tzlich ist das Programm sauber",
"programmiert. Es mžte also unter allen",
"(Multi-) TOS-Versionen und auf allen",
"(MEGA) ST-(Book)/STE/TT/FALCON-Computern",
"laufen, da es keinerlei Annahmen bzgl.",
"des Bildschirmaufbaus macht, was",
"bedeutet, daž es auch Grožbildschirme,",
"Grafikkarten und True-Color-Darstellung",
"untersttzt. Eventuell bzw. wahrschein-",
"lich l„uft es somit auch unter ST-",
"Emulatoren fr MS-DOS und den Amiga.",
"",
"WinLupe l„žt sich als Programm oder als",
"Accessory durch einfaches Umbennen von",
"APP nach ACC und umgekehrt starten",
"",
"Nun zur Beschreibung der Parameter und",
"Optionen in den Dialogen 'Setup' sowie",
"'Sonstiges' :",
"",
" Setup :",
"=========",
"",
"  Darstellung :",
" ---------------",
"",
" Echtzeitvergr”žerung :",
"Die Vergr”žerung wird st„ndig mit der",
"im Dialog 'Sonstiges' eingestellten",
"Frequenz aktualisiert.",
"",
" Echtzeitschieber :",
"Die Schieber des Vergr”žerungsfensters",
"werden der Position des Bildausschnitts",
"bei aktivierter Echtzeitvergr”žerung und",
"'Mauszeiger folgen' angepažt. Dies ver-",
"langsamt die Ausgabe erheblich.",
"",
" Mauszeiger mitvergr”žern :",
"Der Mauszeiger wird - wie der Name schon",
"sagt - mitvergr”žert.",
"",
" Inverse Darstellung :",
"Die Darstellung im Vergr”žerungsfenster",
"wird invertiert.",
"",
"  Optionen :",
" ------------","",
" Mauszeiger folgen :",
"Der Ausschnitt im Vergr”žerungsfenster",
"folgt bei aktivierter Echtzeitvergr”ž-",
"erung dem Mauszeiger.",
"",
" Mauszeiger an-/ausschalten :",
"Bei deaktivierter Option wird nur dann",
"der Mauszeiger korrekt an-/ausge-",
"schaltet, wenn entweder die Echtzeit-",
"vergr”žerung deaktiviert ist oder der",
"Mauszeiger ber einem sichtbaren Teil",
"des Vergr”žerungsfensters steht. Dies",
"verhindert in der Regel ein Flackern",
"des Mauszeigers, kann aber in „užerst",
"seltenen F„llen zu minimalen Redraw-",
"Fehlern fhren, welche aber kurzfristig",
"sind und nur an den R„ndern von Fenstern",
"auftreten k”nnen. Aužerdem muž man fr",
"diesen Fall den Mauszeiger mit maximaler",
"Geschwindigkeit ber den Schirm bewegen,",
"d.h. im normalen Anwendungsalltag kommt",
"es zu keinerlei Problemen.",
"",
" Fenster abrunden :",
"Das Vergr”žerungsfenster wird auf Word-",
"grenzen gerundet, was die Ausgabe etwas",
"beschleunigt. Weiterhin wird die Gr”že",
"des Fensters dem Vergr”žerungsfaktor an-",
"gepažt.",
"",
" Kompatibilit„ts-Modus :",
"Schaltet den an sich notwendigen",
"wind_update()-Aufruf an. Nur bei ausge-",
"schalteter Option erfolgt auch bei",
"aktiven Dialogen, in der Menleiste oder",
"beim Verschieben von Desktopelementen",
"bzw. Fenstern eine Vergr”žerung. Dabei",
"kann es zu Redraw-Fehlern kommen, wenn",
"sich das Vergr”žerungs-Fenster und ein",
"Dialog bzw. Men berlappen oder wenn",
"ein Fenster ber das WinLupe-Fenster ge-",
"schoben wird. Diese Option ist nur fr",
"die Echtzeitvergr”žerung relevant und",
"funktioniert nicht bei aktiven Echtzeit-",
"schiebern.",
"",
" Grow/Shrink-Boxen zeichnen :",
"Beim ™ffnen/Schliežen von Dialogen",
"werden die blichen Grow- bzw. Shrink-",
"Boxen gezeichnet. Dies verlangsamt den",
"Dialogaufbau nicht unerheblich.",
"",
"  Vergr”žerung :",
" ----------------",
"",
"Wahl des Vergr”žerungsfaktors zwischen",
"vorgegebenen Faktoren und beliebigem",
"Faktor zwischen 2 und 32. Je gr”žer der",
"Faktor ist, desto schneller ist die Ver-",
"gr”žerung.",
"",
" Sonstiges :",
"=============",
"",
"  Dialoge :",
" -----------",
"Wechsel zwischen Fenster-Dialogen und",
"FlyDials. Fensterdialoge k”nnen st„ndig",
"ge”ffnet bleiben, funktionieren auch im",
"Hintergrund und die Vergr”žerung wird",
"weiterhin aktualisiert. FlyDials unter-",
"brechen die Vergr”žerung, ben”tigen",
"Speicher fr das Fliegen, belegen aber",
"keine Fenster.",
"",
"  Zoom-Modus :",
" --------------",
"Wahl des Vergr”žerungsmodus zwischen",
"sauberer Vergr”žerung ber VDI-Trans-",
"form oder schnellen Spezial-Routinen fr",
"Grafikkarten mit Pixel-Packed/Inter-",
"leaved-Planes oder dem Standard-Format.",
"",
"  Frequenz :",
" ------------",
"Die Vergr”žerungsfrequenz fr die Echt-",
"zeitvergr”žerung kann hier zwischen 1 Hz",
"und 100 Hz eingestellt werden, wobei",
"diese Werte nur bei entsprechend schnel-",
"len Computern/Grafikkarten bzw. kleinem",
"Vergr”žerungsfenster oder Verwendung der",
"schnellen Spezial-Vergr”žerungsroutinen",
"(Zoom-Modus) erreicht werden k”nnen.",
"",
"WinLupe wurde mit Pure C von",
"Application Systems Heidelberg und",
"meiner eigenen,erweiterten Dialog-",
"Library EnhancedGEM programmiert.",
""
};

int help_lines = (int) sizeof(help)>>2;
