char *help[] =
{
"",
"W i n L u p e - faster than light", 
"---------------------------------", 
"Winlupe is a small utility which is", 
"distributed using the Freeware",
"principle. This means that everyone", 
"may use, copy and give copies to other",
"users. PD libraries must obtain my",
"written permission.",
"",
"Winlupe is programmed to be compatible", 
"with all (Multi)-TOS versions and", 
"should run on all ST/STE/TT and Falcon", 
"models. Large screen monitors,", 
"graphics cards and True Colour boards", 
"are also supported.",
"", 
"Winlupe can run as an Application",
"(.APP) or accessory (.ACC) by renaming",
"the file with the appropriate file",
"extender shown above.",

"The following text details the Options",
"provided in the Setup menus:",
"",
"Setup:",
"======",
"",
"Display",
"-------",
"Real time zoom:",
"(default selected)", 
"The zoom window is updated at the", 
"frequency set in 'Continued' dialog.",
"",
"Real time scroll bars:",
"(default deselected)",
"The zoom window displays scroll bars",
"which indicate the position of the",
"enlarged area. This option only works",
"if the 'Real time zoom' and 'Follow",
"cursor' options are both selected.",
"Output is noticeably slower.",
"",
"Enlarged cursor:",
"(default selected)",
"No further explanation necessary.",
"",
"Inverse video:",
"(default deselected)",
"The zoom window is displayed in",
"reverse video.",
"",
"Options:",
"--------",
"Follow cursor:",
"(default selected)",
"If the 'Real time zoom' option is",
"also selected the zoom window displays",
"the area under the cursor (mouse",
"pointer) as it is moved around the",
"screen.",
"",
"Show/Hide cursor:",
"(default deselected)",
"Normally the cursor is switched on and",
"off automatically. This can cause",
"flicker problems if the 'real time",
"zoom' option is selected and the",
"frequency is set to the maximum. To",
"avoid these problems, deselect this",
"option. Otherwise this can cause",
"redraw-problems when the cursor is",
"positioned over the zoom window, title",
"bar or window edges. If you experience",
"redraw problems use this option to",
"force the cursor to be always switched",
"on and off.",
"",
"Optimise window size & position:",
"(default selected)",
"The zoom window and position of the",
"zoom window on the screen is aligned",
"on a byte boundary which speeds up",
"the redraw speed considerably.",
"",
"AES Compatibility:",
"(default deselected)",
"This option uses the wind_update call",
"when necessary. If this option is",
"deselected any desktop elements, such",
"as drop down menus or dialogs which",
"overlap the zoom window can cause",
"redraw problems. This option is only",
"useful when the 'Real time zoom'",
"option is selected and does not",
"function if the 'Real time scroll",
"bars' option is selected.",
"",
"Display Grow/Shrink boxes:",
"(default off)",
"When dialog boxes are opened and",
"closed they normally display",
"Grow/Shrink boxes. Disabling these",
"boxes speeds up dialog display",
"considerably.",
"",
"Dialogs:",
"(default Window)",
"Choose between Window or Flying",
"dialogs. Window dialogs can remain",
"permanently open in the background",
"and the zoom window continues to",
"function. Flying dialogs interrupt",
"the real time update of the zoom",
"window take up extra memory but do",
"not occupy a window slot.",
"",
"Setup (continued):",
"==================",
"",
"Zoom mode:",
"(default VDI)",
"Choose between standard mode, pure",
"VDI, or the faster special routines",
"developed for graphics cards with",
"interleaved or pixel packed bitplanes.",
"",
"Frequency:",
"(default 100)",
"This setting determines the update",
"speed of the zoom window when the",
"'Real time zoom' option is selected",
"Changing the frequency enables the",
"trade off between processing speed",
"and screen update to be fine tuned.",
"The processor speed, any graphic",
"card installed, zoom mode and size",
"of the zoom window all have an effect",
"on the redraw speed of the zoom",
"window.",
"",
"Winlupe was programmed using Pure C",
"from Applications Systems Heidelburg",
"and my own extended GEM Dialog",
"Library EnhancedGEM",
"" };

int help_lines = (int) sizeof(help)>>2;
