.TH netstat 8 MiNT-Net
.SH NAME
netstat \- show active network connections
.SH SYNOPSIS
.B "netstat [-f domain]"
.SH DESCRIPTION
.I Netstat
is used to display infomation about active communication
endpoints in either the
.B unix
or
.B inet
communication domain or both of them.
If invoked without arguments it shows only
.B unix
domain sockets.
You can specify the domain to deal with with the -f option.
.sp
For the unix domain the output of netstat consists of one line for
each socket in the system,
which contains the following entries:
.TP 15
.SM "Proto"
The protocol used by the socket, this can be one of:
.RS 15
.TP 15
.SM "unix"
This is the one and only protocol for unix sockets.
.TP
.SM "unknown"
The protocol is unknown, should never happen.
.RE
.TP 15
.SM "Flags"
These are the flags set on the socket. The output for this entry
consists of a space-separated list of tree-letter flag values.
Possible flags are:
.RS 15
.TP 15
.SM "ACC"
The socket is listening for incoming connections.
This applies only to stream sockets.
.TP
.SM "RCV"
The socket is shut down for receiving after a call to
.IR shutdown (3),
ie the socket cannot receive any messages.
.TP
.SM "SND"
The socket is shut down for sending after a call to
.IR shutdown (3),
ie it is impossible to send messages on the socket.
.TP
.SM "MRK"
If out-of-band data is handled inline, "receiving is at mark", ie
all data before the out of band data has been read.
.RE
.TP 15
.SM "State"
This field is the internal state of the socket,
the following values are possible:
.RS 15
.TP 15
.SM "VIRGIN"
The socket has just been created,
but has not been assigned a communication domain and type.
.TP
.SM "UNCONNECTED"
The socket is not connected to a peer.
.TP
.SM "CONNECTING"
The socket is about to connect to another one.
.TP
.SM "CONNECTED"
The socket is connected to another one.
.TP
.SM "DISONNECTING"
The socket is about to finish the connection to its peer.
.TP
.SM "DISCONNECTED"
The socket has finished a connection and is again unconnected.
.TP
.SM "UNKNOWN"
This should never happen.
.RE
.TP 15
.SM "Type"
This is the communication style the socket uses.
Possible values are:
.RS 15
.TP 15
.SM "STREAM"
The socket uses connection-oriented byte stream communication,
just like pipes do.
.TP
.SM "DGRAM"
The socket uses connectionless, unrelyable,
datagram oriented communication.
.TP
.SM "RAW"
This is a raw socket.
.TP
.SM "RDM"
Just like
.SM "DGRAM\c"
, except that you can rely on the packets to be delivered successfully.
.TP
.SM "SEQPACKET"
This is like
.SM "RDM\c"
, except that the receiver is guaranteed to get the packets in the
same order the sender sends them.
.TP
.SM "UNKNOWN"
This type should never happen.
.RE
.TP 15
.SM "Recv-Q"
The size of the next unread message for datagram oriented sockets,
and the number of unread bytes for stream oriented ones.
.TP
.SM "Address"
The local address of the socket, if
.IR bind (3)
was done on it.
This is a filename for the unix domain.
.SH OPTIONS
.TP 15
-f domain
Display information for active sockets in domain
.IR domain ,
overriding the default domain.
.SH FILES
.TP 15
/dev/unix
Unix domain information
.SH BUGS
Only unix domain implemented.
.SH AUTHOR
Kay Roemer <roemer@hera.rbi.informatik.uni-frankfurt.de>
