/* levels2.c */

char *levels2[]=
{
/* level 25 */
"26 35 10 50 10 20 100 0 2000 Wie-bitte?!",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   S",
"S                           b w b S",
"Swwwwwwwwwwwwwwwwwwwwwwwww  g w w S",
"S                    brrrw wwgw   S",
"S wwwwwwwwwwwwwwwwwwwbwwww wggww wS",
"S wpbllwb           wbw    wggw b S",
"S wgwllww           wbw wwwwggw w S",
"S w wwllww          wbw wl    w   S",
"S w wwwllww         wbw w ggg ww wS",
"S w wwwdllww        wdw w gdg w b S",
"S w   wddllww       wdw w ggg w w S",
"S w w wdddllww      wdw w    lw   S",
"S w w wddddllww     wdw wwwwwgww  S",
"S w w ggddddllww    wdw     w w b S",
"S w w w gddddllww   wdwwwww w w w S",
"S w w w wgwdddllww  wdwwdbw w w   S",
"S w w w w gddddllww ddd bew w ww wS",
"S w w w w wgddddllwewdSbw w w w b S",
"S w w w w w gddddllwwdSbw w w w w S",
"S w w w w w wgwwwwllwdSbw w wEw   S",
"S w w wb      wwwwwlllSbw w wwww wS",
"S w w wbwwwwwwwwwwwwllSbw wr   gb S",
"S w    d         wwwwlSbw bwwwwww S",
"S wwwwwwwwwwwww  wwwwwSbw g       S",
"S                      d  gwwwwww S",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSww S",
/* level 26 */
"26 35 14 4 100 200 200 0 1000 Take-eight",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Swwwwwwwb bggggbg gggggg  gwwwwwwwS",
"S       ggbg bggg gbggbg gg       S",
"Sdl     ggggggggg ggg gggbgl     dS",
"Swwwwwwwgg bgbgbg bgggg gbgwwwwwwwS",
"Swwwwwwwbg ggbggg lggggggggwwwwwwwS",
"S       ggbgbbg gggggbgbggg       S",
"Sdl     gbbggggbbggggg ggggl     dS",
"Swwwwwwwggggg gggggbgg ggg wwwwwwwS",
"Swwwwwwwgggggbgggggggbggb gwwwwwwwS",
"S       gg gggggbbggbgggggg       S",
"Sdl     gbbgbgbgggg g gggggl     dS",
"Swwwwwww gggg   gggggggbgggwwwwwwwS",
"SwwwwwwwgbgggbggbgbgbggggggwwwwwwwS",
"S       ggggbggbgblggg   bg       S",
"Sdl     gbg ggggggggbggggggl     dS",
"SwwwwwwwggggggbggggggggbgggwwwwwwwS",
"Swwwwwwwggbbglggggbbgg ggggwwwwwwwS",
"SggggggggggggggggbbggbgbggggggggbbS",
"Sggbggg gggbbgbggggggggggbggggggbbS",
"Sggbgbg   bgg    bgggggggggg ggggbS",
"Sg ggggggbggg gg lggg  ggggg gbggbS",
"Sgggggggbgggg bggggggl ggbgggglgggS",
"Sggpggbgggggg gbgggbggggggggggggggS",
"Sggggbggb ggggggg gggggg ggg ggggES",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 27 */
"26 12 15 30 5 100 200 1000 1000 Double-fun",
"S    SS    S",
"Sd twSSd twS",
"Sw dSSSw dSS",
"S    SS    S",
"S wtwSS wtwS",
"S  bSSS  bSS",
"S    SS    S",
"Sd twSSd twS",
"Sw dSSSw dSS",
"S    ES    E",
"Sb twSSb twS",
"Sw bSSSw bSS",
"S    SS    S",
"S wtwSS wtwS",
"Sd dSSSd dSS",
"Sw   SSw   S",
"S  twSS  twS",
"Sb bSSSb bSS",
"Sw   SSw   S",
"Sp twSSp twS",
"Sd dSSSd dSS",
"Sw   SSw   S",
"S  twSS  twS",
"Sb bSSSb bSS",
"Sw   SSw   S",
"S  twSS  twS",
/* level 28 */
"26 28 15 40 8 20 200 200 1000 Bloody-loop!",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SpggggggggggggggwggBBBBBgggS",
"Sg r r r r r rggwgggBBBggggS",
"Sgrgggggggggg ggwgggggBggggS",
"Sg gggggggggg gEwggggggggggS",
"Sgrgggggggggg ggwggggggggggS",
"Sg gggggggggg ggwggggggggggS",
"Sgrgggggggggg ggwggggggggggS",
"Sg gggggggggg ggwggggggggggS",
"Sgrgggggggggg ggwggggggggggS",
"Sg gggggggggg ggwggggggggggS",
"Sgrgggggggggg ggwggggggggggS",
"Sg gggggggggg ggwggggggggggS",
"Sgr           ggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SgggggggggggggggwggggggggggS",
"SggggggggggggggggggggggggggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 29 */
"26 35 9 30 5 10 200 1000 1000 Wish-these-were-real-walls",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Sggggggggggggg llllllllllllggdggggS",
"Sgtgdggggggggg gggggggtggggggtgdggS",
"SgggtgggSSgdgg ggggggggggggggggtggS",
"Sggggggggggtgg gggdggggdggggggggggS",
"Sgdggggdgggggg gggtggggtggggggggggS",
"SgtggggtggggggbggggggggttgggggdgggS",
"SggggggtggggggbgggggggggggggggttggS",
"SgggggggggggggpggggggdgggggdggggggS",
"Sggggggggggtdw wggggttgggggSSgggggS",
"Sgdgdggggggttw wggggggggggggggggggS",
"SgtttggggggggwwwgggggggggggggggggdS",
"SggggggggdggggggggggggggggggggggttS",
"SgggdggggtgggggggggdggggggdgdgggggS",
"SgggSggggtdggggggggtggggggttttggggS",
"SgggSdSggttgggggggtgtgggdgggggggggS",
"SgggSSSggdgggggdggggggggEgggggggggS",
"SggggggggtgggggtggggggggggggggggggS",
"SgggggggggggSggtggggggggggggdgggdgS",
"SdggggdggggggggggdggggggggggtgggtgS",
"StggggtdgggggggggtgggggtdgggtgggggS",
"SgggggttgggggggggggggggttgggggggggS",
"SggdgggtgggdgggggggdggggtgggggggggS",
"SggtggggggttgggdgggtgggggggggdggggS",
"SggtgggggggggggtgggggggggggggtggggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 30 */
"26 35 11 60 5 25 200 200 1000 Back-to-simple",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S                                 S",
"S  gdgdgdgd               gdgdgd  S",
"S  SSSSSSSSl  gdgdgdgdg   SSSSSSl S",
"S             SSSSSSSSSl          S",
"S                                 S",
"S  SSSSSSSSl              SSSSSSl S",
"S             gdgdgdgdg           S",
"S             SSSSSSSSSl          S",
"S  dgdgdgdg               gdgdgd  S",
"Sp SSSSSSSSl              SSSSSSl S",
"S                Sg               E",
"S                Sd               S",
"S  dgdgdgdgdgdg  Sg  gdgdgdgdgdg  S",
"S  SSSSSSSSSSSSl Sd  SSSSSSSSSSSl S",
"S                Sg               S",
"S                Sd               S",
"S  dgdgdgdgdgdg  Sg  gdgdgdgdgdg  S",
"S  SSSSSSSSSSSSl Sd  SSSSSSSSSSSl S",
"S                Sg               S",
"S                Sd               S",
"S  dgdgdgdgdgdg  Sg  gdgdgdgdgdg  S",
"S  SSSSSSSSSSSSl Sd  SSSSSSSSSSSl S",
"S                Sgl              S",
"S                                 S",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 31 */
"26 35 15 27 10 20 200 200 2200 No-name-for-this-level-yet",
"Swd bb w b bbw  b  w  bb w  bbbw  S",
"Swbbbb  dgbgb  bbgd  bbg  b ggb ggS",
"Swgggbgwb bggwgggbgwgbgggwbd ggwdgS",
"Swb ggbwb gggw ggbgwdgggbwbbgbgwggS",
"SwwwgwwwwwgwwwwwgwwwwwgwwwwwgwwwgbS",
"Swdgbb wg  g w bgggw gg  wdggb wgbS",
"Swgbbbgwggbggwgbgggw gbggwgggggwggS",
"Swgbggg gggbgbgbgggggggggb gggg  gS",
"Swgbggbwgggbgwbbgggwdgbggwgggggw gS",
"Swbbggbwg gbdwdgg bwbggbgw bbb wbbS",
"Swwwgwwwwwgwwwwwgwwwww wwwwwgwwwbdS",
"Sw bb  w  gg wg bggwg d gw gg  wbgE",
"Swpgbbgwgbggbwgggg w gbg w ggbbwbgS",
"Swg gbg gbbgb  gg     g    g bg ggS",
"Swgggbbwgggbdw ggg w g g wggbggwggS",
"Swb gdbw  gbbwgb dgwg   gwbbggdwbgS",
"Swwwgwwwwwgwwwwwdwwwwwbwwwww wwwggS",
"Swbgg dwb gg w bgbgw  gg w ggg wbgS",
"Swbggggwdggg wbb g w ggggwbgggbwbgS",
"Swbgggggggbggggg g  gggggbggggggbdS",
"Swb gggwggggbwgggg wgggg w  gggwggS",
"Swbbgbgwgbg bwb g bw  g dwdggggwggS",
"Swwwgwwwwwgwwwwwgwwwwwgwwwww wwwggS",
"Sggggggggg bggggggggggggbgggdgggggS",
"Sd gggggbbgdgbggbbggggdgggggggbgggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 32 */
"26 35 12 12 15 25 200 200 1500 Spirale",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S ggg lb   b  ggb   ggggg b bgg   S",
"Sggbg ggg bgbg gdgggg dbggggdgg  pS",
"Sg bg SSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S gg  S dggg   lbgggggg       bb  S",
"S  g gSggg gggggggggggggggggggbgggS",
"Sgg bgS g bbgb   ldb g    gg ggglgS",
"Sg gg Sb gggggggggggggggggg ggggggS",
"Sbggg Sbg   gggl bg  gggggggg bbggS",
"Sbg ggSggSSSSSSSSSSSSSSSSSSSSSbbggS",
"SbggggS bSl  g d ggg  gggggg SggggS",
"Sgggd SlgS ggbggg bgggg    ggSggggS",
"SgggggS gSgggbSSSSSSSSSSSSSSgSggggS",
"Slg g S gSgbggSEggggg  gg gSgSb g S",
"SbbbgbS gSgb gSlggggdgg  ggSgSb g S",
"SgggggS gSggb SSSSSSSSSSgggSgSbgggS",
"S glggS bSbggg bb g  gg gg SgSg bgS",
"S ggg S gSbgggggg gggg gggdSgSggbgS",
"Sggb  S gSgggg     l gb  gbSgSlgglS",
"Sg gg S gSSSSSSSSSSSSSSSSSSSgS bgbS",
"Sgggg Sgdgggggggggggg l     gSbbggS",
"Sgb ggSSSSSSSSSSSSSSSSSSSSSSSSbgggS",
"Sgggbg g gg  b   g b   g gg gggggdS",
"Sglgbbgggggggggggbbbgggg ggbg gggbS",
"Sgggbb gbgggg lg bgg  g g db l ggbS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 33 */
"26 35 12 50 5 8 120 1000 1300 Don't-hurry,-be-wappy!",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SgbgggggggbgggggBgggbgggggbgggggggS",
"EgggggbbggbgggggggggggbggggggbggbgS",
"SggbgggbgggggbgggbggbgggbgbgbbggggS",
"Sgggggggggggggbggggggggggggg gggggS",
"S             p                   S",
"S                                rS",
"S   r  r                          S",
"S                    r            S",
"S              r                  S",
"S                    r            S",
"S                                rS",
"S                        r        S",
"S        r       r                S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                rS",
"S                                 S",
"S rttttttttttttttttttttttttttttt  S",
"S         r          r           rS",
"S                                 S",
"S                                 S",
"S                                rS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 34 */
"20 28 10 54 5 10 200 200 1000 No-sweat",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SpgggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggrlggggggrlggggggrlggggggS",
"SggbbggggggbbggggggbbggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SgggggrlgggggggrlgggggggrlgS",
"SgggggbbgggggggbbgggggggbbgS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggEgS",
"SggggggggggggggggggggggggggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 35 */
"26 35 12 48 8 20 200 100 2000 Feels-like-I'm-going-to-loose-my-mind...",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S bgg  g wbb b    gbg gg    db  g S",
"S g gwggggggbggggbggggggggggggg ggS",
"g g  g ggggbggbggbgg  g g bgggg g S",
"S dbgggggggdgggggg b ggg gg bgg  bS",
"Sbbgggw ggggggdgbbggg b  g gggdg gS",
"S gbbgg ggggdgggggggbgggggbg gggl S",
"Sg ggg bggbggggggggwggggbgg gggg gS",
"Sbgggggggggggddgggggggg gg g g g gS",
"S gg  gg  gbgggbggdgdggg g  ggggggS",
"S  g gdgl  gggggggg gg gg dbggbg  S",
"S  gbggb gggggd g bg gg  bgg ggggdS",
"Sw gb g g  gggggdggg  gg   gg b gbS",
"S  ggg ggggdgggggg g gwgg  gdgggggS",
"S  bgggg ggggggt gg  gggg gggg wbgS",
"Sdbb  bggggggg g g  g   g b  gggggS",
"Sgggg wg gbggg ggggg gggg g g ggbgS",
"Sb ggggggpggggbg g g gg  gbg ggg gS",
"S gdgggg ggwgggggbg gdgb gggggg  gS",
"S gggb  gggg g ggggb gwg g gbggl gS",
"S gbggbggg  b  gbgggdgggdg bg  gg S",
"S bwggg g bggg dg ggg ggggbbggggggS",
"S gggdgbgwgg g g gg b  d ggggggdg S",
"Slgg bbggggggg gggg ggggbbggg ggg S",
"Sdbbdbb b  gggg b  g b bbbwgdgggb E",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 36 */
"26 35 15 20 10 20 200 200 1000 Three's-a-crowd by farnum",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSESSSS",
"SS     S wld   g w     bSSS       S",
"SS  Sd S wSdS  d w pgbgdSSS       S",
"SS b g g w wS  g w   wSdSSS       S",
"SS g   b w  w  b w w  SdSSS       S",
"SS    pg w   wpg w  w  g w        S",
"SS     g w     g w   r   w        S",
"SSr      wr      w     b w   r    S",
"SSwwwwwwwSwwwwwwwSwwwwwwwSSwwwwwwwS",
"S               S     b   S       S",
"S               S    gg   S       S",
"S           SSSSS         S       S",
"S       b  Srb     b      Sl      S",
"S       g   SbS    gg     S       S",
"S           SbSS          S       S",
"S           SbSSS         SwwwwwwwS",
"S           SbSSSS   gg   S       S",
"S  d    e    g     S      S       S",
"S Sld       ggggggd    SbSSSS     S",
"S  Sld           Sg    SbbbSS     S",
"S   Sld          Sg gg  ggggS     S",
"S    Sld         SS    SSSrS      S",
"S     Sg                  w       S",
"S                         w       S",
"S                         w       S",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 37 */
"26 35 10 60 10 20 0 0 2000 Eat-Me by farnum",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S    SdSdS                        S",
"S  b SdSSd          e e e e       S",
"S  g SdSggd                       S",
"S  b SdSdggd                      S",
"S  g SdSgdbgd                     S",
"S  b grgSgdbgd                    S",
"S  g  S  Sgdggd                   S",
"S   l   w Sgdggd    SdS           S",
"S      w   Sgdgg    dld           S",
"Sb    w    dSg      SdS           S",
"Sgd   dS  dS         Sd           S",
"Sebdg g SdSngg        Sd bbbbbbbbbS",
"Sbdb     Sd  g         SddddddddddS",
"Sdbdg  e bSd            SSSSSSSSSSS",
"Sbdb     g wd        dgggggggd    S",
"Sdgdg  Sw  dS       egbdbdbdbg    S",
"Sbdb    e dw         dgggggggd    S",
"Eebg     dw          gbdbdbdbg    S",
"ESdS    dw            gggggdg     S",
"SSbS   dw             SSSSSbS  p  S",
"S g e dw                  bnSS    S",
"S  w  Sd                gSbSSd    S",
"S wSw  wd                SbSSSe   S",
"Sdlg    wd                dSSd    S",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 38 */
"26 35 15 50 20 20 200 200 2000 Madam,-I'm-Adam",
"ddddddddddd             ddddddddddd",
"ggggggggggg             ggggggggggg",
"               wwdww               ",
"               wrwrw               ",
"                dgd                ",
"               dwwwd               ",
"              dw d wd              ",
"             dwb g bwd             ",
"            dw g d g wd            ",
"           bggggbgbggggb           ",
"           g  b gdg b  g           ",
"            gdgg g ggdg            ",
"           d g       g d           ",
"           g     p     g           ",
"                ddd                ",
"            ddd gbg ddd            ",
"      ddd   gbg  g  gbg   ddd      ",
"      gbg  e g       g e  gbg      ",
"       g                   g       ",
"                                   ",
"                                   ",
"                                   ",
"  SSS                         SSS  ",
"  eES                         SSe  ",
"  SSS                         SSS  ",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
};
