/* levels.c (niveaux separes en 2 morceaux pour limiter code objet MAC) */

char *levels1[]=
{
/* level 0 */
"26 35 15 1 0 0 200 200 1000 Title-level",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Sp                                S",
"S  www www w w w   ww  www www    S",
"S  w w w w w w w   w w w   w w    S",
"S  www w w w w w   w w ww  www    S",
"S  w w w w w w w   w w w   ww     S",
"S  www www www www ww  www w w    S",
"S                                 S",
"S                                 S",
"S     www    wwwww  wwwww  w   w  S",
"S     w  w   w   w  w      w   w  S",
"S     w   w  w   w  w      w   w  S",
"S     w   w  w   w  w      w   w  S",
"S     w   w  w   w  w      w   w  S",
"S     w   w  w   w  w      w   w  S",
"S     w   w  w   w  w      w   w  S",
"S     w   w  wwwww  wwwww  wwwww  S",
"S     w   w  w   w      w  w   w  S",
"S     w   w  w   w      w  w   w  S",
"S     w   w  w   w      w  w   w  S",
"S     w   w  w   w      w  w   w  S",
"S     w  w   w   w      w  w   w  S",
"S     www    w   w  wwwww  w   w  S",
"S                                dS",
"S                                ES",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 1 */
"26 35 9 18 10 30 200 0 700 Null-Problemo",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Spbb  gdg g g g g  gggggggggggggggS",
"Sggbb gdg g g bg g gggggggggggggggS",
"SwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwggS",
"Sg ggg b   g gd    bgg   b g   g gS",
"Sg gg gbbgg   g gg gb gbbgb   g b S",
"S    gdbg  g gggg  bgbbggbbb g bggS",
"Sg   ggbd g        ggbg  ggbbbgbbbS",
"Sg gWwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
"Sg bbgb  gdgbbgd    gggb b  gb gggS",
"Sgbbgdgg gg bb gg g gggbggggbbdbggS",
"Sggggbg ggggbbggg  gg gg gggggggbgS",
"S    g g  ggbbdgbgdgggggggggggggggS",
"Swwwwwwwwwwwwwwwwwwwwwwwwwwwwwgg gS",
"Sg     dbg  g     ggggggbggbgb gggS",
"Sgd gg gbg gg g  gdggggggggbgbgb gS",
"S g    wwwwwwwwwwwwwwwwwwwwwwwwwwww",
"S ggg  gdgbg   g   ggg ggggggggggdS",
"Swww gg dgbg g  ggggggggggggggggggS",
"SE wggggbggg ggbgbggggbgg ggg bb gS",
"Sbbwggg gggggggbdbgbggggggggg ggggS",
"SgbwwwwwwwwwwwwwwwwwwwwwwwwwwwgggbS",
"Sgbbgggggg gg   b           bdggggS",
"Sgbggdgggbggbbggbb b  bbgb  ggbbgbS",
"Sgg  ggggbgbgggbbggbbgbbgbbggdbgggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 2 */
"15 20 14 30 10 12 200 0 700 Nothing-to-it",
"SSSSSSSSSSSSSSSSSSSS",
"Sp                 S",
"Sgb d              S",
"Sgggwb d           S",
"Sww wwgwb d        S",
"Sww ww wwgwb d     S",
"SSw ww ww wwgwb d  S",
"Sww ww ww ww wwgwb S",
"Sww ww ww ww ww wwgS",
"SwS ww ww ww ww ww S",
"Sww ww ww ww ww ww S",
"SEw ww ww ww ww ww S",
"SwwrwwrwwrwwrwwrwwrS",
"SwwwwwwwwwwwwwwwwwwS",
"SSSSSSSSSSSSSSSSSSSS",
/* level 3 */
"26 35 13 20 10 30 200 0 1000 Take-care-of-the-exit",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S d w g g gwg g w wg gg w ggggwg lS",
"Sgg gbggdggwggg w w   g b g bbb   S",
"Sg gwbbg gggg   b b  gggwgggggwgg S",
"Sd dwlbgbggwg  gwgwggggbwg  ggwgdgS",
"Swwwwwwwwwwwwwwww wwwwwwwwwwwwwwwwS",
"Sgg w  g g wg g w w ggg w  gggw gdS",
"Sg  wgg  g wgg  bgggggggw b   bb gS",
"Sbggdbgbg gbgg bwgwg  gg  ggbbwg dS",
"Sbbgwbbbbbbwbbbbwgwl   gwbb gdwgdgS",
"SwwwwwwwwwwwwwwwwgwwwwwwwwwwwwwwwwS",
"Sdg wggggggwg  gwgwg  g w     wgggS",
"Sg  bg ggggggg  bg ggg gw gg gw   S",
"S dbwbg   gwggggwg  ggg b  g gb d S",
"Sdbbwbbgl  wggg wgwggggbwbg gbwb dS",
"SwwwwwwwwwwwwwwwwgwwwwwwwwwwwwwwwwS",
"Sg  wgg gggw  g wgwg gg w g ggwgggS",
"S g bgg g  ggg  wgggg  gwggggg gggS",
"Sg gwggggg wgg  bgwgg gg  ggggwgggS",
"Sgdgwgl  gdwggggwgwgggggwdggggw dgS",
"SwwwwwwwwwwwwwwwwgwwwwwwwwwwwwwwwwS",
"Sgggwg    gwgbg wgwg    w gg gwgggS",
"Sggdb  glggwgbg gg  g ggwgggggwgggS",
"Sgggwg g gdbgbg  pwggbggg ggggbgggS",
"Sgggwd   bbwdbg  Ewggbdgwg ggdwd bS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 4 */
"26 35 5 100 5 15 200 0 1000 Uncork",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SbdbbdbdbbbbbdbbdddddbbbddbdbdddbbS",
"SdgbbbbgbbdbbgbddddbdbbbbbbdbbdbbbS",
"SgbdggbgdbgbbgdbdbbbbddbdbbbbbbbdbS",
"SdgggdgdgbgbbggbbbbbbbbbbbbdddbbbbS",
"SgdbdgdbgdgbbdggbbdddbddbbdbbbdddgS",
"SggggggbbgbdggddgddbbbdbgddggggdggS",
"SgdgbdgbdggdgbggggggggggdbgdddggggS",
"SgdbgddgdgbdgddbddggdgbdddggggbddbS",
"SddgdbbbgbdgdggdgdgdbbggbddgdbbbdbS",
"SggbwwwwwgwwwwwgbgbdwwwwwgwwwwwbgbS",
"Sdgbw         wdgdgdw         wbdbS",
"Sbddw         wgddbgw         wdddS",
"Sgbgw  Ep     wdgbgdw         wdddS",
"Sdddw         wbdgddw         wdddS",
"Sbbbw         wggddgw         wdddS",
"Sbdbw         wdgggdw         wddbS",
"Sgbbw         wbdbdbw         wdbbS",
"SdgbwggWgggWggwdbdbbw         wdddS",
"Sgdgw         wbbdbdw         wddbS",
"Sgdgw         wbdbdbw         wbdbS",
"Sbddw         wwwwwww         wbdbS",
"Sbdbw                         wbdbS",
"Sdbbw         wbbddbw         wbbdS",
"SdbdwwwwwwwwwwwdddbdwwwwwwwwwwwbddS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 5 */
"26 35 9 35 10 30 200 0 1000 Hot-lava",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SbgggggEgggggbpggbBbbggggggbgggggbS",
"SgbgggggggbggggggBBbbggggggbggggbgS",
"SggbggggggbgggggggggggbgbggbgggbbbS",
"SgggggggggbggggggggggggbbgggggggggS",
"SgggggbggggbggggggggggggbgggggggggS",
"SgggggbgggggggbggggggggggbggggggggS",
"SgbggbbggggggbbgggggbggggbgggggbbgS",
"SggggggggbbggbbggggbbggggbbggggbbgS",
"SgggggggbbbggbggbgbbbbgggbggggggbgS",
"SgbbggggbggggggbbgggggbggggggggggbS",
"SgbgggggbggggggggggggggggggbggggggS",
"SgggggggggggggggggggbggggbbbggbgggS",
"SggggggggggggggggggbbggggggbggbgggS",
"SbbggggggbbbggbggggggggggggggggbggS",
"SbbggbggggbbggbggbgggbgggggggggbggS",
"SbgggbggggbggbbggggggbbgggbgggbgbgS",
"SbggggggggbgggbgbgggggbggbbgggggggS",
"SgggggbbgbbgggbggbggggbggbbbggggggS",
"SggbgggbggbggbbggggggbbbgbgbgggggbS",
"SggbgwwwwwwwwwwwwwwwwwwwwwwwwwggggS",
"Sggggr r r r r r r r r r r r rgbggS",
"SbgggbbbbbbbbbbbbbbbbbbbbbbbbbggggS",
"SggggggggggggggggggggggggggggggbggS",
"SggggggggggggggggggggggggggggbggggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 6 */
"26 35 14 4 100 200 200 0 1000 Eitje",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SpggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"Sgggg   gggg   gggg   ggggl  gggggS",
"Sgggg   gggg   ggggl  gggg   gggggS",
"Sgggg dlggggld gggg d gggg d gggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"Sgggg   gggg   gggg   ggggl  gggggS",
"Sgggg   gggg   ggggl  gggg   gggggS",
"Sgggg dlggggld gggg d gggg d gggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggggggggES",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 7 */
"26 35 15 15 10 25 200 200 1000 Funnel",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Swwgggg  gbb gggg  ggg gggbggggggwS",
"S wgb ggbdbbg g ggbgggggg b gg bwwS",
"S wwlb ggggbg  dg g ggbggggggbgwwbS",
"S bwwbp  g gl  ggg  ggb bg   bww  S",
"Sgggww  bbbgg  ggb gg gbbbgglwwgg S",
"Sbgggwwggggggbgg  b gggggg gww bg S",
"Sggg  wwg g  bbb  gbb g dbgdwgggg S",
"S      www gggggbgggbggbgbgww g g S",
"Sgglg g  wbg ggg gg ggggg ww  bgb S",
"Sgggg g  wggg ggbg  bgbgwwwgggg g S",
"Sgggbggggww  bggbgggggb w gbg g g S",
"Sg gg  gggwggbggbg gdggwwg gg g g S",
"Sgggggggggww gg ggggbgww gg g g glS",
"S bbgggb ggwwggg g  gwwgggggg g ggS",
"Sggg  ggggg w g gggggw  gbgg g gggS",
"S ggggggggbgggggggg gggggg gggg ggS",
"S gbbgg g ggggg  b gg gg gg g gg gS",
"Sggbbgg    ggg  ggggggg   ggl  g gS",
"S ggb gggglggttttttttgg ggggg gg gS",
"S gggbgggggggbggggg  gggg ggggg gbS",
"S gg gggggbg ggggg g g ggg gggg  gS",
"Sl gg g  bbgggb ggbb  ggbgg  gb bbS",
"Sggg  gg gg lgggggggggggggggggggggS",
"Sggg   bbbggg                  l  E",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 8 */
"26 35 15 25 10 20 600 0 1000 Don't-wait",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggwwwwwwwwwwwwggggggggggggS",
"SgggggggggwBBBBB      ggggggggggggS",
"SgggggggggwwwwwwwwwwwwggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SggggggggggggggggggrrrggggggggggggS",
"SggggggggggggggggggrrrggggggggggggS",
"SggggggggggggggggggrrrggggggggggggS",
"SggggggggggggggggggrrrggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggpES",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 9 */
"26 35 12 10 25 25 200 0 1000 Loop-or-kill?",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SgggggggggggggggggggggggggggggggggS",
"SpggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"Sgggggw w w w w wgggggggggggggggggS",
"Sgggggw w w w w wgggggggggggggggggS",
"Sgggggw w w w w wgggggggggggggggggS",
"Sgggggw w w w w wgbbbbbbbbbbbbbbbgS",
"Sgggggw w w w w wgggggggggggggggggS",
"SgggggwlwlwlwlwlwgggggggggggggggggS",
"SgggggwdwdwdwdwdwgggggggggggggggggS",
"SgggggwwwwwwwwwwwgggggggggggggggggS",
"SgggggwdwdwdwdwdwgggggggggggggggggS",
"SgggggwgwgwgwgwgwgggggggggggggggggS",
"SgggggwlwlwlwlwlwgggggggggggggggggS",
"Sgggggw w w w w wgggggggggggggggggS",
"Sgggggw w w w w wgggggggggggggggggS",
"Sgggggw w w w w wgggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SggggggggggggggggggggggggggggggggES",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 10 */
"26 35 11 25 10 30 200 0 1000 Hell-freezes-over",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Sbgbggggbgbgggpgbgbgbgggbg  b dggbS",
"Sggglb  ggg g ggg gbgg ggggbbggg gS",
"Sdgbgg gg      bg gg ggg  gbbgdbdbS",
"SSSSSSSSg bgg gggg g ggb  gSSSSSSSS",
"S   ggbggggbgbgg ggg g gbg gggg   S",
"S   g g gg   bb g b gggggbgg g    S",
"Slbdgbbgblbgbbg gbbgbgg gg gg gl  S",
"SEgbgggggbg ggbg ggbglg gbbggggbddS",
"SSSSSSSSggbggbg b bg bgggggSSSSSSSS",
"Sgbbggbgb g ggg ggg gbbg g g ggggbS",
"S bg gggbggg b gbb   ggbg ggg ggg S",
"Sggb  gggg g gg ggbgbg bgbbg gbgggS",
"Sggbgg lgbggg  gg g g gbgggbbgbgggS",
"Sbbbg ggbgg g b gg g ggggbggggg g S",
"Sgggg gbggbg gg   g gb  ggggg   ggS",
"S gbgl gg gg   ggb ggbg  gl g b bgS",
"Sbggggggg b bgb ggg   bg bggg glggS",
"Sg  g gbgbggggbg g gg g  gggg   ggS",
"Sg lgggbggg gbg ggg  bgbgbgbggggggS",
"S gb   gg    g g gg gggg  gg gggbgS",
"Sgggggg   g gggggg  g  g  gggggbggS",
"Sbggb gggg g   B Bgggl  ggb g bbggS",
"Sgg gb g  gggg BBBB gggg gggg gbggS",
"Sbggbgg gggglgBBBBBBBgg g g gbggg S",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 11 */
"26 35 15 12 50 250 200 0 1000 Boulder-dash-goes-PAC-MAN",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S            S       Sl           S",
"S  SSS   S   S       S   S   SSS  S",
"S  S    dS   S  SSS  S   Sd    S  S",
"S  S   SSS   S  SlS  S   SSS   S  S",
"Sd           S rSSS  S           dS",
"SSSSSSSSSSS  S       S  SSSSSSSSSSS",
"S                                 S",
"S                                 S",
"S  SSS  S                 S  SSS  S",
"S  Sl   S  SSSSS   SSSSS  S    Sl S",
"S       S  S     d     S  S       S",
"d       S  Sl    E     Sl S       d",
"S    S  S  SSSSSSSSSSSSS  S  S    S",
"S    S  S                 S  S    S",
"S    S  S        d        S  S    S",
"SSSSSS  SSSSSS   S   SSSSSS  SSSSSS",
"S                                 S",
"Sl                                S",
"S  S  SSSSSSSSSS   SSSSSSSSSS  S  S",
"S  S  S                     S  S  S",
"S  S  S                     S  S  S",
"S  S  S  SSSSSSS   SSSSSSS  S  S  S",
"S  S  S        S   S        S  S  S",
"Sd S  S       dS p Sd       S  S dS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 12 */
"15 20 15 75 5 15 64 0 1300",
"SSSSSSSSSSSSSSSSSSSS",
"SbbbbbbbbbbbbbbbbbbS",
"SggggggwwwwwwwwwwwwS",
"SggggggbbgggrggrggrS",
"SggggggwwwgggggggggS",
"SggggggwwwgggggggggS",
"SggggggwwwrgBBBBBgeS",
"SgggggpwwwggBBBBBggS",
"Sgww wwwwwrggBeBBggS",
"S       wwwwwwwwwwwS",
"S       wwwwwwwwwwwS",
"S  w    gggbBBBBBBBS",
"S       wwwwE      S",
"Sr      wwwww  e   S",
"SSSSSSSSSSSSSSSSSSSS",
/* level 13 */
"26 35 15 4 100 300 200 0 1300 Can-be-done",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SggggggggggggggggggggggggggggggddlS",
"SgwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwS",
"Sgwwwb                          glS",
"Sgwbwg                          g S",
"Sgwggw    SS SSS S  S   SS  SSS g S",
"Sgwgww    S  S S SS S   S S S   ggS",
"Sgwgww wg S  SSS S SS   SS  SS  glS",
"Sgwgww wg S  S S S  S   S S S   g S",
"Sgwgww wg SS S SbS  S   SS  SSS g S",
"Sgwgww wg      ggg              ggS",
"Sgwggw wg      ggg              glS",
"Sgwwwwwwg b                     g S",
"Sgwwwwwwgggggggggggg            g S",
"Sgwwwwwwwwwgwwww wwwww         Sg S",
"SgWwwwwwww  wwww wwwww         Sg S",
"Sgwwwwwww  wwSSw SSSwS  S SSS  SggS",
"Sgwwwwww  wwwS S S SwSS S S    SglS",
"Sgwwwww  wwwwS S S SwS SS SS   Sg S",
"Sgwwww  wwwwwS S S SwS  S S     g S",
"Sgwww  wwwwwwSSw SSSwS  S SSS  Sg S",
"Sgww  wwwwwwwwww wwwww          ggS",
"Sgw  wwwwwwwwwgwpwwwww          glS",
"Sgw wwwwwwwwwwgwwwwwww          g S",
"Sdw wwdggggggggggdWwww          g S",
"SSSSSSSESSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 14 */
"12 16 15 33 8 20 200 0 1000 Excavation",
"SSSSSSSSSSSSSSdS",
"SbbbSbdbdbdSdbbS",
"SbSd bbdbSb bdbS",
"Sb dbbdSd dbSbbS",
"SdbdSdb bSdd ddS",
"Sddbddbdd bSdbbS",
"SSbbdSdbddb dddS",
"S dbb bbdSddSbSS",
"SbSdbdbdd bb b S",
"SdbdbbdbbSdbSdbS",
"SbbdpSdbd bb bbS",
"SSSSSSSSSSSSSSES",
/* level 15 */
"14 4 15 17 10 30 200 0 1000",
"  bd",
"wddw",
" wb ",
"b dw",
"dwb ",
"d wd",
"wb b",
"Ewbd",
"  dw",
"bdb ",
"bwdw",
"d d ",
"bdwd",
"wdpd",
/* level 16 */
"10 16 15 17 30 30 200 0 1000 Be-Quick",
"wwwwwwwwwwwwwwww",
"wlllllllllllgbEw",
"wblllllllllgbdgw",
"wpdlllllllgbdgSw",
"wddblllllgbdgSww",
"w ddblllgbdgSwww",
"wwSddbllbdgSwwww",
"wwwSddbbdgSwwwww",
"wwwwSdddgSwwwwww",
"wwwwwwwwwwwwwwww",
/* level 17 */
"4 35 15 66 8 100 200 0 1000",
"SdbgdgddgdbgddgbdgdddgbdgdgdbgddgdS",
"EgddbgbdddggbddgbgdbddgddbddgddgddS",
"pggdgdgbdbddgbddgdbggddbdgdgddbgdbS",
"SddgdddgggdddggdddgdgbdggdbgdbgdbgS",
/* level 18 */
"26 35 15 64 8 25 200 0 2000 Quarry",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Sp  b  b b  b b  b  bb g b gbg g  S",
"Sg ggggggbgbb bgbbbgb  bggdbgg dbgS",
"Sgdggbdbdgb gbbdbdb bbdgb ggggb g S",
"S gbdg bgdgbgbbbbgbbbbbgbdb dggg gS",
"Sgbgbbbbdgbbbgbgbdgbgd gbbbbgdb bgS",
"Sgbgggbbbbgbbbbg bbdg bbgbggddd b S",
"Sgb bdbgggdgdb bggbb g bdb bb gdbgS",
"Sgbbdgbbb b  bbdbbgbd g gdbgbbggbgS",
"Sggbbgbdgbggbgggbgbbggbbbdbbgbggg S",
"S bggbbgdgbdbg ddbgddbbbbgbbbd bbgS",
"Sgdgb bgbbbbbggbEggbgbbgdbgb ggdb S",
"S b ggbgbgggbbbbgbbbb gb gbbbbgbbgS",
"S gbdgbgbbbbbbb bbbbgbgbgbbdgbggbgS",
"S   bggbdgbb b gbg gdbbdb ggdbdgb S",
"Sgbggdbgbbgg bb bgd bbbbbgbgb  bggS",
"Sgggd bbbgbgbggggbdbgbdbgb dggbgbgS",
"S gbgbbbgbdbbg bbbbgd bbgbgbb ggggS",
"Sgbg gggg gb bbbdgb g gbbbbgdg d  S",
"Sgggbbb bbgbggdggdbgdb dgd g gbgbgS",
"Sgdgbdbgdbdb b b bb bggbbgbdgg b gS",
"Sgbbgdgbbbgbbbbg gdb dbbgbgg ggdggS",
"Sgbgbgbgbgbgbggbgdbbggggbgbd g bggS",
"Sg gggdbgb bbgbg  gb bbgbgbgb d  gS",
"Sgdg bgggggbb g gggggggdggbgdgggggS",
"SSSSSSSSSSSSSSSSSSSdSSSSSSSSSSSSSSS",
/* level 19 */
"26 15 15 13 25 100 200 0 1500 Figure-it",
"SSSSSSSSSSSSSSS",
"Sgb dw        S",
"SgwwwwwwwwwwwwS",
"Sggwpbblbdd ewS",
"SgwwgwwwwggggwS",
"SggggwwwwggggwS",
"SgwwgggggggggwS",
"SgwwwgwwwwwwwwS",
"Sgw wwwbbbb wBS",
"Sgwgwwwbbwgww S",
"Sgwggbgbww w  S",
"Sgwwgwgww  w  S",
"Sgwwgwgw  ww BS",
"Sgwwnwgw ww   S",
"Sgwwwwgw w Be S",
"Sn   wgw wB  SS",
"S wwwwgw wB BBS",
"S wggggw w   BS",
"S wgbwww wS   S",
"S wgwww  w  e S",
"S wgww  ww e SS",
"Slwdww wwB B  S",
"S wgww w      S",
"S wgww w  e   S",
"S ggWwlwB  SBES",
"SSSSSSSSSSSSSSS",
/* level 20 */
"26 35 15 12 10 30 200 0 1000 Almost-boring",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"S          E                      S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                p                S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S                                 S",
"S b b b b b b b                   S",
"SwgwgwgwgwgwgwgwwwwwwwwwwwwwwwwwwwS",
"Snl nl  nl    nl        nl        S",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 21 */
"22 35 15 12 20 50 200 0 1000 Yet-another-left-monster-level",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"SgggggggggggggggggggggggggggggggggS",
"SwwwwwwwwwwwwpwwwwwwwwggggggggggggS",
"SwggggdgggggggggggggdwggggggggggggS",
"SwgwlwgwwwwwwgwwwwwwgwggggggggggggS",
"Swgwlw wdgggggggggdw wggggggggggggS",
"Swgwlw wgwwwwgwwwwgw wggggggggggggS",
"Swgwlw w wdgggggdw w wggggggggggggS",
"Swgwlw w wgwwgwwgw w wggggggggggggS",
"Swgwlw w w wl lw w w wggggggggggggS",
"Swgwlw w w w   w w w wggggggggggggS",
"Swgwlw w wlwl  wlw w wggggggggggggS",
"Swgwlw w wgwwwwwgw w wggggggggggggS",
"Swgwlw wlwdgggggdwlw wggggggggggggS",
"Swgwdw wgwwwwwwwwwgw wggggggggggggS",
"SwgwdwlwdgggggggggdwlwggggggggggggS",
"SwgwdwgwwwwwwwwwwwwwgwggggggggggggS",
"SwgwdwdgggggggggggggdwggggggggggggS",
"SwwwwwwwwwwwwwwwwwwwwwggggggggggggS",
"SgggggggggggggggggggggggggggggggggS",
"SgggggggggggggggggggggggggggggggggE",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 22 */
"13 32 10 34 10 500 200 0 1000",
"SSSSSSSSSSSSSSSSSSSSSSSESSSSSSSS",
"Spgbwggg gwggggdwSggdgwdwwwwwwwS",
"SgggwggSgdw ggggwgggdgwgwwwwwwwS",
"Sgglwdg ggwgggg wg gggwdwwwwwwwS",
"Sgg wggggrwgg glwgggggwgWWgggggS",
"Sdg wgggg wggSggwgg ggwdwwggSSgS",
"SSSSSSSgg w ggggw ggglwgwwgSSddS",
"SggdgbSSSSSSSSSSSSSgg wggggSdddS",
"SggSggggggggSgggggSgg wggSSSdddS",
"Sgggg gggggg   lbgSSSSSSSSddddWS",
"SgdgE gg  bggggggggggggggddddWgS",
"Sdggglgglgggggg l bgggggggggWgwS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
/* level 23 */
"20 30 15 12 20 50 200 0 1000 BSD-:-Balloons-in-the-Sky-with-Diamonds",
"SSSSSSSSSSSSSbSSSSSSS SSSSSSSS",
"SB  wpgggwggg wggggwggbgwgggbS",
"S   wggggwggg wgggbwggggwgggbS",
"S   wggggwggg wggggwggggwggggS",
"S   wggggwggg wggggwggggwggggS",
"S   wggggwggg wggggwggggwggggS",
"S   wggggwggg wggggwggggwggggS",
"S   wgngbwggg wggggwggggwggggS",
"S   wggggwggg wggggwggggwggggS",
"S   wggggwggg wggggwggggwgnggS",
"S   wggggwggg wggggwggggwggggS",
"S   wggggwggg wggggwggggwggggS",
"S    ggggwggg wggggwggggwggggS",
"S    ggggwggg wggggwggg w    S",
"S   wggggwggg wggggwggg wg ggS",
"S   wggggwggg wggggwggg wg ggS",
"S   wggggw  g wggggwggg wg ggS",
"S   wgg  w  g w    wggg wg ggS",
"S   wgg lwl g w   lwg  lw   lE",
"SSSSSSSSSSSSSbSSSSSSS SSSSSSSS",
/* level 24 */
"26 35 15 75 5 10 100 0 1000 Maze",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
"Sww wwwdwwwwwWggdggg gg   wwwdwdweS",
"SWd bgwwwggggwbwwwwwwwwwWB   dWgwdS",
"SwwwwgggggwwggbgggggggggwwwwwwwdwgS",
"Swr gggwwwwwwgwgwwwwwwwggb  w wgWgS",
"Swwwwgww     gwgg ggggwgwww w wgwgS",
"Sgbgwgw  wwwwwwww wwbgwgggw w wgggS",
"S wgwgwgwWgggggggggwwgwgwgw w wgWgS",
"Srw wgwgwB wwwgwwwggwgwgw wl  wgwgS",
"S w wgwgwwwgggggWdggwgwgw wwwwwgwdS",
"Sgw wgwgggWgww wwwwgw wgggwgggggwwS",
"Sgwdwgwgwgggw  gggg   w wgwgwgggbgS",
"SgWdwgggwgwwwlwwwwgwwww wgwgwwwbwwS",
"Sgwdwgwgwggggggggwgwggg wgwdwggggwS",
"S wwwgwgwwwgwwwwwwgggwgbwgwgwwwwgwS",
"S wgggw gggggbgg    gwgwwgggwgggBwS",
"S ggwgw wwwwwwgwwwwwwwggwggwwwwwgwS",
"Sgwgwgwgwggggg ggggggggwwwgwr  wbbS",
"Sgwgwgwwwgwgwwwwwwwwwgwwgggwww wwbS",
"SgWgwgggggwgggggggwggggggwgbgw wbbS",
"SgwgwwwwgwwgwwwwwgwwgwwwwwwwwwgwbwS",
"Sgwdgbgg    wgbdwgwgggggggggbggggwS",
"S wwwwgwwwwgwgwwwgwwwwgwwwwgwwwWdwS",
"S      Wggggw   ggggggdgWg   r wdwS",
"Sp   Wgwgwwgwgwwwwwwwwgwwwwwww wgwS",
"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSESS"
};

