#define START 0  	/* TREE */
#define ST_PBOX 4  	/* OBJECT in TREE #0 */
#define SS_VERS 6  	/* OBJECT in TREE #0 */
#define ST_VERS 8  	/* OBJECT in TREE #0 */
#define ST_MBOX 9  	/* OBJECT in TREE #0 */
#define ST_MBX1 10  	/* OBJECT in TREE #0 */
#define ST_MIC1 11  	/* OBJECT in TREE #0 */
#define ST_MNAM1 12  	/* OBJECT in TREE #0 */
#define ST_MCK1 13  	/* OBJECT in TREE #0 */
#define ST_MBX2 14  	/* OBJECT in TREE #0 */
#define ST_MIC2 15  	/* OBJECT in TREE #0 */
#define ST_MNAM2 16  	/* OBJECT in TREE #0 */
#define ST_MCK2 17  	/* OBJECT in TREE #0 */
#define ST_MBX3 18  	/* OBJECT in TREE #0 */
#define ST_MIC3 19  	/* OBJECT in TREE #0 */
#define ST_MNAM3 20  	/* OBJECT in TREE #0 */
#define ST_MCK3 21  	/* OBJECT in TREE #0 */
#define ST_MBX4 22  	/* OBJECT in TREE #0 */
#define ST_MIC4 23  	/* OBJECT in TREE #0 */
#define ST_MNAM4 24  	/* OBJECT in TREE #0 */
#define ST_MCK4 25  	/* OBJECT in TREE #0 */
#define ST_SLIDE 26  	/* OBJECT in TREE #0 */
#define ST_S_UP 27  	/* OBJECT in TREE #0 */
#define ST_S_GND 28  	/* OBJECT in TREE #0 */
#define ST_S_BTN 29  	/* OBJECT in TREE #0 */
#define ST_S_DWN 30  	/* OBJECT in TREE #0 */
#define AUTHORS 31  	/* OBJECT in TREE #0 */
#define ST_CONF 32  	/* OBJECT in TREE #0 */
