#
#	Makefile for the Unix communication domain.
#

SHELL = /bin/sh

CC = gcc
CPPFLAGS = -I../../include
CFLAGS = -Wall -mshort -O2 -fomit-frame-pointer

SRCS = unix.c dgram.c stream.c cache.c unixdev.c
OBJS = unix.o dgram.o stream.o cache.o unixdev.o

all: sock.a

.s.o:
	$(CC) -c $< -o $@

.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

sock.a: $(OBJS)
	$(AR) rs $@ $(OBJS)

clean:
	rm -f $(OBJS) sock.a

depend:
	$(CC) -MM $(CPPFLAGS) *.c > depend

ifeq (depend, $(wildcard depend))
include depend
endif
