#               Unix Makefile for Bywater BASIC Interpreter
#
CC=		gcc

CFLAGS=         -O -ansi

OFILES=		bwbasic.o bwb_int.o bwb_tbl.o bwb_cmd.o bwb_prn.o\
		bwb_exp.o bwb_var.o bwb_inp.o bwb_fnc.o bwb_cnd.o\
		bwb_ops.o bwb_dio.o bwb_str.o bwb_elx.c bwb_mth.o

HFILES=         bwbasic.h bwb_mes.h

bwbasic:	$(OFILES)
		$(CC) $(CFLAGS) $(OFILES) -lm -o bwbasic

$(OFILES):	$(HFILES)
