#
# Makefile for SCSI Tape Streamer I/O functions (32 bit library)
#

all:
	gcc-cpp -P tapebind.cpp tapebind.s
	gcc-as -o tapebind.o tapebind.s
        
	gcc -O -I../include -c getcook.c
	gcc -O -I../include -c error.c
        
	gcc-ar rv tape.olb tapebind.o getcook.o error.o


