#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c
.s.o:
	mac $(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	g:\bin\cp68.prg $(CFLAGS) $*.c l:$*.i
	g:\bin\c068.prg l:$*.i l:$*.1 l:$*.2 l:$*.3 -f
	rm l:$*.i
	g:\bin\c168.prg l:$*.1 l:$*.2 l:$*.s
	g:\bin\mac.prg -6 -o $*.o l:$*.s
	rm l:$*.1 l:$*.2 l:$*.s

TEMP = l:tmp
LIBS = vdibind aesbind gemlib libf

OBJS =	gemstart.o osbind.o mymalloc.o \
	    addr.o show.o st.o string.o 
# getln.o toascii.o
show.prg : $(OBJS)
	echo $(OBJS) $(LIBS) >$(TEMP)
	aln -s -o show.prg -c $(TEMP)


#
#  assembly-language files
#
mymalloc.o 	: mymalloc.s
osbind.o 	: osbind.s
#
#  C sources
#
addr.o 		: addr.c
st.o		: st.c
#toascii.o 	: toascii.c
#getln.o 	: getln.c
show.o 		: show.c
string.o 	: string.c
