.TH LPFLUSH 1 "July, 1993"

.SH NAME
lpflush \- clears the /dev/lp buffer

.SH SYNOPSIS
lpflush

.SH DESCRIPTION
.I lpflush
will discard all data stored in the 
.I /dev/lp 
buffer. It can be used to
abort printing when things are going very wrong. Of course,
.I lpflush
won't clear the data stored in the printer's internal buffer, but this
one is usually small enough. You may need to send a reset string to the
printer, especially if you're printing graphics.

.SH SEE ALSO
lpdev(1)

.SH AUTHOR
Thierry Bousch (bousch@suntopo.matups.fr)
