
/*
 * Copyright (c) 1988,1991 by Sozobon, Limited.  Author: Joseph M Treat
 *
 * Permission is granted to anyone to use this software for any purpose
 * on any computer system, and to redistribute it freely, with the
 * following restrictions:
 * 1) No charge may be made other than reasonable charges for reproduction.
 * 2) Modified versions must be clearly marked as such.
 * 3) The authors are not responsible for any harmful consequences
 *    of using this software, even if they result from defects in it.
 */

{"",		0,	0,	0,	"",		0 },
{"abcd$s",	O_DN,	O_DN,	S_B,	"xc%1ro40%r",	F_B },
{"abcd$s",	O_PRE,	O_PRE,	S_B,	"xc%1ro41%r",	F_B },
{"add$s",	O_IMM,	O_DST,	S_BWL,	"x5%q0$s%1e",	F_W|F_Q },
{"add$s",	O_IMM,	O_AN,	S_WL,	"x5%q0$s%1e",	F_W|F_Q },
{"add$s",	O_IMM,	O_DMEM,	S_BWL,	"x06$s%1e",	F_W },
{"add$s",	O_ALL,	O_AN,	S_W,	"xd%1ro3%e",	F_W },
{"add$s",	O_ALL,	O_AN,	S_L,	"xd%1ro7%e",	F_W },
{"add$s",	O_NAN,	O_DN,	S_BWL,	"xd%1r0$s%e",	F_W },
{"add$s",	O_AN,	O_DN,	S_WL,	"xd%1r0$s%e",	F_W },
{"add$s",	O_DN,	O_DMEM,	S_BWL,	"xd%r1$s%1e",	F_W },
{"adda$s",	O_ALL,	O_AN,	S_W,	"xd%1ro3%e",	F_W },
{"adda$s",	O_ALL,	O_AN,	S_L,	"xd%1ro7%e",	F_W },
{"addi$s",	O_IMM,	O_DST,	S_BWL,	"x06$s%1e",	F_W },
{"addq$s",	O_IMM,	O_DST,	S_BWL,	"x5%q0$s%1e",	F_W|F_Q },
{"addq$s",	O_IMM,	O_AN,	S_WL,	"x5%q0$s%1e",	F_W|F_Q },
{"addx$s",	O_DN,	O_DN,	S_BWL,	"xd%1r1$so0%r",	F_W },
{"addx$s",	O_PRE,	O_PRE,	S_BWL,	"xd%1r1$so1%r",	F_W },
{"and$s",	O_IMM,	O_DMEM,	S_BWL,	"x02$s%1e",	F_W },
{"and$s",	O_NAN,	O_DN,	S_BWL,	"xc%1r0$s%e",	F_W },
{"and$s",	O_DN,	O_DMEM,	S_BWL,	"xc%r1$s%1e",	F_W },
{"and$s",	O_IMM,	O_CCR,	S_B,	"x023c",	F_B },
{"and$s",	O_IMM,	O_SR,	S_W,	"x027c",	F_W },
{"andi$s",	O_IMM,	O_DST,	S_BWL,	"x02$s%1e",	F_W },
{"andi$s",	O_IMM,	O_CCR,	S_B,	"x023c",	F_B },
{"andi$s",	O_IMM,	O_SR,	S_W,	"x027c",	F_W },
{"as$d$s",	O_DN,	O_DN,	S_BWL,	"xe%r$d$so4%1r",F_W },
{"as$d$s",	O_IMM,	O_DN,	S_BWL,	"xe%q$d$so0%1r",F_W },
{"as$d$s",	O_DMEM,	O_NONE,	S_W,	"xeo0$d11%e",	F_W },
{"bchg$s",	O_DN,	O_DN,	S_L,	"x0%ro5%1e",	F_L },
{"bchg$s",	O_DN,	O_DMEM,	S_B,	"x0%ro5%1e",	F_B },
{"bchg$s",	O_IMM,	O_DN,	S_L,	"x0o41%1e%0L",	F_L },
{"bchg$s",	O_IMM,	O_DMEM,	S_B,	"x0o41%1e%0L",	F_B },
{"bclr$s",	O_DN,	O_DN,	S_L,	"x0%ro6%1e",	F_L },
{"bclr$s",	O_DN,	O_DMEM,	S_B,	"x0%ro6%1e",	F_B },
{"bclr$s",	O_IMM,	O_DN,	S_L,	"x0o42%1e%0L",	F_L },
{"bclr$s",	O_IMM,	O_DMEM,	S_B,	"x0o42%1e%0L",	F_B },
{"bra$s",	O_LAB,	O_NONE,	S_BW,	"x60%d",	F_PC|F_TXT },
{"bset$s",	O_DN,	O_DN,	S_L,	"x0%ro7%1e",	F_L },
{"bset$s",	O_DN,	O_DMEM,	S_B,	"x0%ro7%1e",	F_B },
{"bset$s",	O_IMM,	O_DN,	S_L,	"x0o43%1e%0L",	F_L },
{"bset$s",	O_IMM,	O_DMEM,	S_B,	"x0o43%1e%0L",	F_B },
{"bsr$s",	O_LAB,	O_NONE,	S_BW,	"x61%d",	F_PC|F_TXT },
{"btst$s",	O_DN,	O_DN,	S_L,	"x0%ro4%1e",	F_L },
{"btst$s",	O_DN,	O_MEM,	S_B,	"x0%ro4%1e",	F_B },
{"btst$s",	O_IMM,	O_DN,	S_L,	"x0o40%1e%0L",	F_L },
{"btst$s",	O_IMM,	O_MEM,	S_B,	"x0o40%1e%0L",	F_B },
{"chk$s",	O_NAN,	O_DN,	S_W,	"x4%1ro6%e",	F_W },
{"clr$s",	O_AN,	O_NONE,	S_W,	"x9%ro3%e",	F_W },
{"clr$s",	O_AN,	O_NONE,	S_L,	"x9%ro7%e",	F_W },
{"clr$s",	O_DST,	O_NONE,	S_BWL,	"x42$s%e",	F_W },
{"cmp$s",	O_ALL,	O_AN,	S_W,	"xb%1ro3%e",	F_W },
{"cmp$s",	O_ALL,	O_AN,	S_L,	"xb%1ro7%e",	F_W },
{"cmp$s",	O_IMM,	O_DMEM,	S_BWL,	"x0c$s%1e",	F_W },
{"cmp$s",	O_NAN,	O_DN,	S_BWL,	"xb%1r0$s%e",	F_W },
{"cmp$s",	O_AN,	O_DN,	S_WL,	"xb%1r0$s%e",	F_W },
{"cmp$s",	O_POST,	O_POST,	S_BWL,	"xb%1r1$so1%r",	F_W },
{"cmpa$s",	O_ALL,	O_AN,	S_W,	"xb%1ro3%e",	F_W },
{"cmpa$s",	O_ALL,	O_AN,	S_L,	"xb%1ro7%e",	F_W },
{"cmpi$s",	O_IMM,	O_DST,	S_BWL,	"x0c$s%1e",	F_W },
{"cmpm$s",	O_POST,	O_POST,	S_BWL,	"xb%1r1$so1%r",	F_W },
{"db$C$s",	O_DN,	O_LAB,	S_W,	"x5$c1x9%r%D",	F_W|F_PC|F_TXT},
{"divs$s",	O_NAN,	O_DN,	S_W,	"x8%1ro7%e",	F_W },
{"divu$s",	O_NAN,	O_DN,	S_W,	"x8%1ro3%e",	F_W },
{"eor$s",	O_IMM,	O_DST,	S_BWL,	"x0a$s%1e",	F_W },
{"eor$s",	O_DN,	O_DST,	S_BWL,	"xb%r1$s%1e",	F_W },
{"eor$s",	O_IMM,	O_CCR,	S_B,	"x0a3c",	F_B },
{"eor$s",	O_IMM,	O_SR,	S_W,	"x0a7c",	F_W },
{"eori$s",	O_IMM,	O_DST,	S_BWL,	"x0a$s%1e",	F_W },
{"eori$s",	O_IMM,	O_CCR,	S_B,	"x0a3c",	F_B },
{"eori$s",	O_IMM,	O_SR,	S_W,	"x0a7c",	F_W },
{"exg$s",	O_AN,	O_AN,	S_L,	"xc%ro51%1r",	F_L },
{"exg$s",	O_DN,	O_DN,	S_L,	"xc%ro50%1r",	F_L },
{"exg$s",	O_AN,	O_DN,	S_L,	"xc%1ro61%r",	F_L },
{"exg$s",	O_DN,	O_AN,	S_L,	"xc%ro61%1r",	F_L },
{"ext$s",	O_DN,	O_NONE,	S_W,	"x4o420%r",	F_W },
{"ext$s",	O_DN,	O_NONE,	S_L,	"x4o430%r",	F_L },
{"jmp$s",	O_STAT,	O_NONE,	0,	"x4o73%e",	F_TXT },
{"jsr$s",	O_LAB,	O_NONE,	S_BW,	"x61%d",	F_PC|F_TXT },
{"jsr$s",	O_STAT,	O_NONE,	0,	"x4o72%e",	F_TXT },
{"lea$s",	O_STAT,	O_AN,	S_L,	"x4%1ro7%e",	F_L },
{"link",	O_AN,	O_IMM,	0,	"x4o712%r%L",	0 },
{"ls$d$s",	O_DN,	O_DN,	S_BWL,	"xe%r$d$so5%1r",F_W },
{"ls$d$s",	O_IMM,	O_DN,	S_BWL,	"xe%q$d$so1%1r",F_W },
{"ls$d$s",	O_DMEM,	O_NONE,	S_W,	"xeo1$d11%e",	F_W },
{"move$s",	O_IMM,	O_DN,	S_L,	"x7%1r0%k",	F_L|F_MQ },
{"move$s",	O_ALL,	O_AN,	S_W,	"x3%1ro1%e",	F_W },
{"move$s",	O_ALL,	O_AN,	S_L,	"x2%1ro1%e",	F_L },
{"move$s",	O_NAN,	O_DST,	S_W,	"x3%1f%e",	F_W },
{"move$s",	O_NAN,	O_DST,	S_L,	"x2%1f%e",	F_L },
{"move$s",	O_NAN,	O_DST,	S_B,	"x1%1f%e",	F_B },
{"move$s",	O_AN,	O_DST,	S_W,	"x3%1f%e",	F_W },
{"move$s",	O_AN,	O_DST,	S_L,	"x2%1f%e",	F_L },
{"move$s",	O_NAN,	O_CCR,	S_W,	"x4o23%e",	F_W },
{"move$s",	O_NAN,	O_SR,	S_W,	"x4o33%e",	F_W },
{"move$s",	O_SR,	O_DST,	S_W,	"x4o03%1e",	F_W },
{"move$s",	O_USP,	O_AN,	S_L,	"x4o715%1r",	F_L },
{"move$s",	O_AN,	O_USP,	S_L,	"x4o714%r",	F_L },
{"movea$s",	O_ALL,	O_AN,	S_W,	"x3%1ro1%e",	F_W },
{"movea$s",	O_ALL,	O_AN,	S_L,	"x2%1ro1%e",	F_L },
{"movem$s",	O_REGS,	O_WRT,	S_W,	"x4o42%1e%m",	F_W },
{"movem$s",	O_REGS,	O_WRT,	S_L,	"x4o43%1e%m",	F_L },
{"movem$s",	O_RD,	O_REGS,	S_W,	"x4o62%e%1m",	F_W },
{"movem$s",	O_RD,	O_REGS,	S_L,	"x4o63%e%1m",	F_L },
{"movep$s",	O_DN,	O_DISP,	S_W,	"x0%ro61%1r",	F_W },
{"movep$s",	O_DN,	O_DISP,	S_L,	"x0%ro71%1r",	F_L },
{"movep$s",	O_DISP,	O_DN,	S_W,	"x0%ro41%1r",	F_W },
{"movep$s",	O_DISP,	O_DN,	S_L,	"x0%ro51%1r",	F_L },
{"moveq$s",	O_IMM,	O_DN,	S_L,	"x7%1r0%k",	F_L|F_MQ },
{"muls$s",	O_NAN,	O_DN,	S_W,	"xc%1ro7%e",	F_W },
{"mulu$s",	O_NAN,	O_DN,	S_W,	"xc%1ro3%e",	F_W },
{"nbcd$s",	O_DST,	O_NONE,	S_B,	"x4o40%e",	F_B },
{"neg$s",	O_DST,	O_NONE,	S_BWL,	"x44$s%e",	F_W },
{"negx$s",	O_DST,	O_NONE,	S_BWL,	"x40$s%e",	F_W },
{"nop",		O_NONE,	O_NONE,	0,	"x4e71",	0 },
{"not$s",	O_DST,	O_NONE,	S_BWL,	"x46$s%e",	F_W },
{"or$s",	O_IMM,	O_DMEM,	S_BWL,	"x00$s%1e",	F_W },
{"or$s",	O_NAN,	O_DN,	S_BWL,	"x8%1r0$s%e",	F_W },
{"or$s",	O_DN,	O_DMEM,	S_BWL,	"x8%r1$s%1e",	F_W },
{"or$s",	O_IMM,	O_CCR,	S_B,	"x003c",	F_B },
{"or$s",	O_IMM,	O_SR,	S_W,	"x007c",	F_W },
{"ori$s",	O_IMM,	O_DST,	S_BWL,	"x00$s%1e",	F_W },
{"ori$s",	O_IMM,	O_CCR,	S_B,	"x003c",	F_B },
{"ori$s",	O_IMM,	O_SR,	S_W,	"x007c",	F_W },
{"pea$s",	O_STAT,	O_NONE,	S_L,	"x4o41%e",	F_L },
{"reset",	O_NONE,	O_NONE,	0,	"x4e70",	0 },
{"ro$d$s",	O_DN,	O_DN,	S_BWL,	"xe%r$d$so7%1r",F_W },
{"ro$d$s",	O_IMM,	O_DN,	S_BWL,	"xe%q$d$so3%1r",F_W },
{"ro$d$s",	O_DMEM,	O_NONE,	S_W,	"xeo3$d11%e",	F_W },
{"rox$d$s",	O_DN,	O_DN,	S_BWL,	"xe%r$d$so6%1r",F_W },
{"rox$d$s",	O_IMM,	O_DN,	S_BWL,	"xe%q$d$so2%1r",F_W },
{"rox$d$s",	O_DMEM,	O_NONE,	S_W,	"xeo2$d11%e",	F_W },
{"rte",		O_NONE,	O_NONE,	0,	"x4e73",	0 },
{"rtr",		O_NONE,	O_NONE,	0,	"x4e77",	0 },
{"rts",		O_NONE,	O_NONE,	0,	"x4e75",	0 },
{"sbcd$s",	O_DN,	O_DN,	S_B,	"x8%1ro40%r",	F_B },
{"sbcd$s",	O_PRE,	O_PRE,	S_B,	"x8%1ro41%r",	F_B },
{"stop",	O_IMM,	O_NONE,	0,	"x4e72",	0 },
{"sub$s",	O_IMM,	O_DST,	S_BWL,	"x5%q1$s%1e",	F_W|F_Q },
{"sub$s",	O_IMM,	O_AN,	S_WL,	"x5%q1$s%1e",	F_W|F_Q },
{"sub$s",	O_ALL,	O_AN,	S_W,	"x9%1ro3%e",	F_W },
{"sub$s",	O_ALL,	O_AN,	S_L,	"x9%1ro7%e",	F_L },
{"sub$s",	O_IMM,	O_DMEM,	S_BWL,	"x04$s%1e",	F_W },
{"sub$s",	O_NAN,	O_DN,	S_BWL,	"x9%1r0$s%e",	F_W },
{"sub$s",	O_AN,	O_DN,	S_WL,	"x9%1r0$s%e",	F_W },
{"sub$s",	O_DN,	O_DMEM,	S_BWL,	"x9%r1$s%1e",	F_W },
{"suba$s",	O_ALL,	O_AN,	S_W,	"x9%1ro3%e",	F_W },
{"suba$s",	O_ALL,	O_AN,	S_L,	"x9%1ro7%e",	F_L },
{"subi$s",	O_IMM,	O_DST,	S_BWL,	"x04$s%1e",	F_W },
{"subq$s",	O_IMM,	O_DST,	S_BWL,	"x5%q1$s%1e",	F_W|F_Q },
{"subq$s",	O_IMM,	O_AN,	S_WL,	"x5%q1$s%1e",	F_W|F_Q },
{"subx$s",	O_DN,	O_DN,	S_BWL,	"x9%1r1$so0%r",	F_W },
{"subx$s",	O_PRE,	O_PRE,	S_BWL,	"x9%1r1$so1%r",	F_W },
{"swap$s",	O_DN,	O_NONE,	S_W,	"x4o410%r",	F_W },
{"tas$s",	O_DST,	O_NONE,	S_B,	"x4o53%e",	F_B },
{"trap",	O_IMM,	O_NONE,	0,	"x4e4%v",	F_TV },
{"trapv",	O_NONE,	O_NONE,	0,	"x4e76",	0 },
{"tst$s",	O_DST,	O_NONE,	S_BWL,	"x4a$s%e",	F_W },
{"unlk",	O_AN,	O_NONE,	0,	"x4o713%r",	0 },
{"",		0,	0,	0,	"",		0 }
