#
# ind.srv -- standard service database for STiK INetD (w) 1996, Peter Rottengatter
#
# The form for each entry is:
# <official service name>  <port number/protocol name>  <aliases>  # <description>
#

echo           7/tcp                 # Data Echo 
echo           7/udp                 # Data Echo
discard        9/tcp  sink null      # Discard Data
discard        9/udp  sink null      # Discard Data
systat        11/tcp  users          # Active Users
daytime       13/tcp                 # Send Time and Day 
daytime       13/udp                 # Send Time and Day
qotd          17/tcp  quote          # Quote of the Day
chargen       19/tcp  ttytst source  # Character Generator
chargen       19/udp  ttytst source  # Character Generator
ftp-data      20/tcp                 # File Transfer Protocol (Data)
ftp           21/tcp                 # File Transfer Protocol (Control)
telnet        23/tcp                 # Virtual Terminal Protocol
smtp          25/tcp                 # Simple Mail Transfer Protocol
time          37/tcp  timeserver     # Time Synchronization
time          37/udp  timeserver     # Time Synchronization
rlp           39/udp  resource       # Resource Location Protocol
whois         43/tcp  nicname        # Who Is
domain        53/tcp  nameserver     # Domain Name Service
domain        53/udp  nameserver     # Domain Name Service
bootps        67/udp                 # Bootstrap Protocol Server
bootpc        68/udp                 # Bootstrap Protocol Client
tftp          69/udp                 # Trivial File Transfer Protocol
finger        79/tcp                 # Finger Information
http          80/tcp  www            # World Wide Web HTTP
hostnames    101/tcp  hostname       # NIC Host Name Server
pop          109/tcp  postoffice     # Post Office Protocol
portmap      111/tcp  sunrpc         # SUN Remote Procedure Call
portmap      111/udp  sunrpc         # SUN Remote Procedure Call
auth         113/tcp  authentication # Authentication Service
sftp         115/tcp                 # Simple File Transfer Protocol
uucp-path    117/tcp                 # UUCP Path Service
nntp         119/tcp  readnews untp  # Network News Transfer Protocol
ntp          123/udp                 # Network Time Protocol
netbios_ns   137/tcp                 # NetBIOS Name Service
netbios_ns   137/udp                 # NetBIOS Name Service
netbios_dgm  138/tcp                 # NetBIOS Datagram Service
netbios_dgm  138/udp                 # NetBIOS Datagram Service
netbios_ssn  139/tcp                 # NetBIOS Session Service
netbios_ssn  139/udp                 # NetBIOS Session Service
bftp         152/tcp                 # Background File Transfer Protocol
snmp         161/udp  snmpd          # Simple Network Management Protocol Agent
snmp-trap    162/udp  trapd          # Simple Network Management Protocol Traps
bgp          179/tcp                 # Border Gateway Protocol

#
# UNIX services
#
biff         512/udp  comsat         # Mail Notification
exec         512/tcp                 # Remote Execution
login        513/tcp                 # Remote Login
who          513/udp  whod           # Remote Who and Uptime
shell        514/tcp  cmd            # Remote Command
syslog       514/udp                 # Remote System Logging
printer      515/tcp  spooler        # Remote Print Spooling
talk         517/udp                 # Conversation
ntalk        518/udp                 # New Talk, Conversation
route        520/udp  router routed  # Routing Information Protocol
timed        525/udp  timeserver     # Remote Clock Synchronization

lansrm       570/udp                 # SRM/UX Server
DAServer     987/tcp                 # SQL Distributed Access
rlb         1260/tcp                 # Remote Loopback Diagnostic
nft         1536/tcp                 # NS Network File Transfer
pmlockd     1889/tcp                 # SynerVision Locking Daemon
pmlockd     1889/udp                 # SynerVision Locking Daemon
nfsd        2049/udp                 # NFS Remote File System
netdist     2106/tcp                 # Update Network Distribution Service
rfa         4672/tcp                 # NS Remote File Access
lanmgrx.osB 5696/tcp                 # LAN Manager/X for OfficeShare
hcserver    5710/tcp                 # HP Cooperative Services
grmd        5999/tcp                 # Graphics Resource Manager
spc         6111/tcp                 # Sub-Process Control
iasqlsvr    7489/tcp                 # Information Access
recserv     7815/tcp                 # SharedX Receiver Service

#
# Kerberos (Project Athena/MIT) services
#
klogin       543/tcp                 # Kerberos Rlogin
kshell       544/tcp  krcmd          # Kerberos Remote Shell
ekshell      545/tcp  krcmd          # Kerberos Encrypted Remote Shell
kerberos     750/udp  kdc            # Kerberos (Server) UDP
kerberos     750/tcp  kdc            # Kerberos (Server) TCP
krbupdate    760/tcp  kreg           # Kerberos Registration
kpasswd      761/tcp  kpwd           # Kerberos "Passwd"
eklogin     2105/tcp                 # Kerberos Encrypted Rlogin

# The X10_LI server for each display listens on ports 5800 + display number.
# The X10_MI server for each display listens on ports 5900 + display number.
# The X11 server for each display listens on ports 6000 + display number.
