/* Resource Datei Indizes fÅr OEP_DEMO */

#define MENUE            0   /* Menuebaum */
#define M_ABOUT          7   /* STRING in Baum MENUE */
#define M_OPEN           16  /* STRING in Baum MENUE */
#define M_CLOSE          18  /* STRING in Baum MENUE */
#define M_UPDATE         20  /* STRING in Baum MENUE */
#define M_QUIT           22  /* STRING in Baum MENUE */

#define ABOUT            1   /* Formular/Dialog */
#define ABOUT_OK         4   /* BUTTON in Baum ABOUT */

#define DATA             2   /* Formular/Dialog */
#define DATA_BOX         0   /* BOX in Baum DATA */
#define DATA_DT          1   /* FTEXT in Baum DATA */

#define CHANGE           3   /* Formular/Dialog */
#define CHANGE_DT        1   /* FTEXT in Baum CHANGE */
#define CHANGE_OK        2   /* BUTTON in Baum CHANGE */
#define CHANGE_CANCEL    3   /* BUTTON in Baum CHANGE */

#define NOMANAGER        0   /* Alert String */
