# This is my hackup of the original ytalk makefile:
# TeSche (Torsten Scherer), itschere@techfak.uni-bielefeld.de

#DEFS = -DSYSTEM_YTALKRC=\"/usr/local/etc/ytalkrc\" -DUSE_SGTTY

CC=	gcc
CFLAGS=	-Wall -O2 -mbaserel $(DEFS)
LFLAGS=	-mbaserel
LIBS=	-lbcurses -lbsocket -lbportlib

OBJS=	main.o term.o user.o fd.o comm.o menu.o socket.o rc.o exec.o cwin.o # xwin.o

all: ytalk

ytalk: $(OBJS)
	$(CC) $(LFLAGS) $(OBJS) $(LIBS) -o ytalk

clean:
	rm -f $(OBJS)

install: ytalk ytalk.1
	cp ytalk /usr/local/bin
	chmod 0711 /usr/local/bin/ytalk
	cp ytalk.1 /usr/man/man1
	chmod 0644 /usr/man/man1/ytalk.1

$(OBJS):	header.h
main.o:		menu.h
term.o:		cwin.h xwin.h menu.h
fd.o:		menu.h
comm.o:		socket.h menu.h
menu.o:		menu.h
socket.o:	socket.h
cwin.o:		cwin.h
