'''
'''  Ytalk Version 3
'''
.de Sh
.br
.ne 5
.PP
\fB\\$1\fR
.PP
..
.TH YTalk 1 "20 Nov 1993"
.SH NAME
ytalk - A multi-user chat program. 
.SH SYNOPSIS
.B ytalk [-x] [-s] username...
.SH DESCRIPTION
.I YTalk V3.0 Patch Level 2
.PP
YTalk is in essence a multi-user chat program.  It works almost exactly like
the UNIX talk program and even communicates with the same talk daemon(s), but
YTalk allows for multiple connections.

The 
.I username
field may be formatted in several different ways:
.br
	name          - some user on your machine
.br
	name@host     - some user on a different machine
.br
	name#tty      - some user on a particular terminal
.br
	name#tty@host - some user on a particular tty on a 
.br 
				 different machine
.br
	name@host#tty - same as "name#tty@host"
.PP
You can specify multiple user names on the command line, ie:
.sp
	ytalk george fred@hissun.edu marc@grumpy.cc
.PP
The -x option disables the X11 interface (described below).
.PP
The -s option starts your YTalk window in a shell.
.PP
For each user on the command line, YTalk will attempt to connect to the talk
daemon on the specified user's host and determine if that user has left an
invitation for you to call.  If not, YTalk leaves an invitation for him
and tells his talk daemon to send an announcement to his screen.
There is not yet a dedicated YTalk daemon, but there will be.  Right now,
YTalk is able to communicate with BOTH existing versions of UNIX talk
daemons.  For any particular host, YTalk will attempt to communicate with a 
talk daemon the caller's host also supports.  If the two hosts have no daemon
in common, then UNIX talk will not function at all, but a connection is
possible through (and only through) YTalk.
.PP
Once a connection has been established between two users, they can chat back
and forth to their hearts' content.  The connection is terminated when one
of them hits control-C or selects quit off the main menu.
.PP
YTalk is perfectly compatible with UNIX talk and they can even converse
with each other without any problems.  However, many of the features of YTalk
can only operate when you are connected to a user who is also using YTalk.
For the rest of this document, it will be assumed that all connected users
are using YTalk, unless otherwise stated.
.PP
If you specified more than one user on the YTalk command line, then YTalk
will process and add each user to the conversation as they respond to your
invitation.  As each new user enters the conversation, the screen is further
subdivided into smaller and smaller windows, one for each connected user.
Right now, the number of connected users is limited by the number of lines
on your terminal (or window), for each connected user needs at least three
lines.
.PP
YTalk does implement primitive support of the X11 Windowing System.  If the
environment variable DISPLAY is set, then YTalk attempts to connect to that
X server.  Further details about the X11 interface (and how to turn it off)
are given below.
.PP
As each new user is added to the conversation, YTalk will transmit information
about that user to all other connected YTalk users so that their screens will
also subdivide and incorporate the new user.  If the new user is using UNIX
talk, then information about him will NOT be transmitted, for his screen
would be unable to accept multiple connections.  I have given brief thought
to allowing at least the output of UNIX talk users to be transmitted to
all connected YTalk users, but I have not written any code to do so.  Note
that even though UNIX talk cannot handle multiple connections, it is still
possible for YTalk to handle multiple UNIX "talk" connections.  For example,
george (using YTalk) could communicate with fred and joe (both using UNIX
talk), but fred and joe would be unaware of each other.  The best way to
understand the limitations that UNIX "talk" places on YTalk is to test
various connections between the two and see how things work.
.PP
.SH ESCAPE MENU
Whenever you are using YTalk, you can hit the 
.I ESCAPE 
key to bring up a menu which at this
moment has these options:
.sp
        a: add a user
.br
        d: delete a user
.br
        o: options
.br
        s: shell
.br
        u: user list
.br
        w: output user to file
.br
        q: quit
.PP
By choosing option "a", you are given the opportunity to type the name of any
user you wish to include into the conversation.  Again, YTalk will accept an
invitation from that user if an invitation exists, or will leave an invitation
and ring the given user.
.PP
By choosing option "d", you can select the name of a connection to terminate.
.PP
By choosing option "o", you can view and/or modify any of the YTalk options.
See the OPTIONS section below for a list of YTalk options.
.PP
By choosing option "s", you can invoke a shell in your YTalk window.  All
other users will see what happens in your shell.  YTalk will automatically
resize your window down to the size of the smallest window you are
connected to, in order to ensure that all users always see the same thing.
.PP
The "u" option displays a list of connected and unconnected users, as well
as their window sizes and what version of talk software they are running.
.PP
By choosing option "w", you can select any connected user and type the
name of a file, and all further output from that user will be dumped to the
specified file.  The file, if it exists, will be OVERWRITTEN.  By choosing
"w" and the same user again, further output to the file will be terminated.
.PP
Oh, one other thing:  when user A attempts to ytalk to user B, but user B is
already ytalking with user C, user A's YTalk program will realize that user
B is already using YTalk, and will communicate with user B's YTalk program
directly in order to initialize the conversation.  User B will see a nice
windowed message like:
.sp
	Do you wish to talk with user A?
.PP
and he will be prompted for a yes/no answer.  This, in my opinion, is much
preferable to blitting the announcement message and messing up user B's
screen.

.SH RUNTIME OPTIONS
When you select Options off of the main menu, you are given the opportunity
to edit the YTalk options.  The current options are:
.sp
	s: turn scrolling [off/on]
.br
	w: turn word-wrap [off/on]
.br
	i: turn auto-import [off/on]
.br
	v: turn auto-invite [off/on]
.br
	r: turn auto-rering [off/on]
.br
	a: turn asides [off/on]
.PP
If
.I scrolling
is turned on, then a user's window will scroll when he reaches the bottom,
instead of wrapping back around to the top.
.PP
If
.I word-wrap
is turned on, then any word which would overextend the right margin will
be automatically moved to the next line on your screen.
.PP
If
.I auto-import
is turned on, then YTalk will assume that you wish to talk to any users
which connect to other YTalk users which are connected to you.  That last
sentence does make sense; try again.  YTalk will add these users to your
session automatically, without asking you for verification.
.PP
If
.I auto-invite
is turned on, then YTalk will automatically accept any connection requested
by another user and add them to your session.  You will not be asked for
verification.
.PP
If
.I auto-rering
is turned on, then YTalk will automatically re-ring any user who does not
respond to your invitation within 30 seconds.  You will not be asked for
verification.
.PP
If
.I asides
is turned on (it may not be available), then keyboard input received while
the input focus is in a specific users' window will only be sent to that
user.  See the X11 interface description below.
.PP
Any of these options can be set to your preference in your .ytalkrc file,
as described below.
.SH YTALK STARTUP FILE
If your home directory contains a file named ".ytalkrc" then YTalk will
read this file while starting up.  All YTalk runtime options, as well as
some startup options, can be set in this file.
.Sh "SETTING BOOLEAN OPTIONS"
Boolean options can be pre-set with the following syntax:
.sp
	turn
.I option
[off | on]
.PP
where
.I option
is one of
.I scrolling ,
.I word-wrap ,
.I auto-import ,
.I auto-invite ,
.I auto-rering ,
.I asides ,
or
.I X .
Setting these options works just like described above.  Turning
.I X
on or off will enable or disable the X11 Interface described below.
For example, one could enable word-wrap with the line:
.sp
	turn word-wrap on
.Sh "SETTING RE-ADDRESS MODES"
The purpose of readdressing is to allow Ytalk connections across
point-to-point network gateways where the local machines know themselves
by a different address (and typically hostname) than the remote machines.
The basic syntax of a readdress command is this:
.sp
	readdress
.I from-address
.I to-address
.I domain
.PP
The
.I readdress
statement simply makes a claim that the machine(s) in
.I domain
communicate with the machine(s) at
.I from-address
by sending a packet to
.I to-address .
Since most users have no use for this whatsoever, I'll describe it only
briefly.
.PP
THIS IS NOT ROUTING.  For example, my machine at home is connected via
PPP to the network at my office.  My machine at home thinks its ethernet
address is 192.188.253.1 and its hostname is "talisman.com".  The network
at my office has the address 192.67.141.0.  When I'm connected via PPP,
my home machine is placed into the office network as address 192.67.141.9
with hostname "talisman.austin.eds.com".
.PP
YTalk needs to know that if it is running on domain 192.67.141.0 and
receives packets from 192.188.253.1 that it should respond to
192.67.141.9, not 192.188.253.1.  right?  right.  okay, okay, okay.
I put this line into my .ytalkrc on both ends:
.sp
	readdress talisman talisman.austin.eds.com 192.67.141.0
.PP
On my home end, this translates to:
.sp
	readdress 192.188.253.1 192.67.141.9 192.67.141.0
.PP
which tells my home machine to advertise itself as "192.67.141.9" instead
of "192.188.253.1" when YTalk-ing to machines on the network "192.67.141.0".
On the office end, the readdress command translates to:
.sp
	readdress 192.67.141.9 192.67.141.9 192.67.141.0
.PP
which the office machines basically ignore.
.PP
Enough.  For more information on how to use this, consult the source code
or send me a letter.  :-)
.SH X11 INTERFACE
If the DISPLAY environment variable is defined when YTalk starts up, then
YTalk will attempt to communicate with that X server.  A window will be
created for you and each user you are connected to.  The X11 Interface can
be disabled either by specifying -x on the command line or by putting this
line into your .ytalkrc file:
.sp
	turn X off
.PP
A window is created for each individual user in the conversation.  If the
input focus is in the main window (ie: the one with "ytalk" in the title
bar) then anything typed will be sent to all connected users.  If the input
focus is in one of the users' windows, then anything typed will be sent
as an aside to only that user.  If the "aside" option is turned off (see
above) then ytalk will beep and not accept anything typed when the input
focus is not in the main window.
.PP
YTalk consults the X11 Resource Database for these user-definable
configuration options:
.sp
    YTalk.display:  X server to connect to, defaulting to the
DISPLAY environment variable.
.sp
    YTalk.reverse:  reverse black/white pixels.
.sp
    YTalk.font:  font to use, defaulting to "9x15".
.sp
    YTalk.geometry:  window size, defaulting to  "80x24".
.SH FUTURE WORK
Work is being done on the following ideas:
.sp
.br
	1) a dedicated YTalk daemon.
.br
	2) MBCS/NLS support.
.br


.SH FILES

/usr/local/etc/ytalkrc
.br
    System-wide defaults file.
.PP
$HOME/.ytalkrc
.br
    User's local configuration file.  This file overrides
.br
    options set in the system ytalkrc file.

.SH AUTHOR

Britt Yenne
.br
yenne@austin.eds.com

.SH CONTRIBUTORS
Special thanks to Carl Edman for numerous code patches, beta testing,
and comments.  I think this guy spends as much time on ytalk as I do.
.PP
Special thanks to Tobias Hahn and Geoff W. for beta testing and
suggestions.
.PP
Thanks to Sitaram Ramaswamy for the original YTalk manpage.
.PP
Thanks to Magnus Hammerin for Solaris 2.* support.
.PP
Thanks to Thilo Wunderlich for Linux support.
.PP
Thanks to Jonas Yngvesson for aside messages in X.
.PP
Thanks to Andreas Stolcke for fixing the X resource database calls.
.PP
Thanks to Pete Wenzel for fixing the #elif directive.
.PP
Thanks to John Vanderpool, Shih-Chen Huang, Andrew Myers, Duncan Sinclair,
Evan McLean, Larry Schwimmer, J. Adam Hawkes, and Mark Musone for comments
and ideas.
.PP
The README file shipped with ytalk gives detailed attributions.

.SH BUGS

If you have any ideas, comments, or questions, I'd be happy to hear from you
at:

	ytalk@austin.eds.com

