# makefile for manpager
#
# date:    Sun Jan 13 22:12:57 1991
# version: 
#
#
#
SECT		= 1
SUBSECT		= 
TARGET		= manpager.ttp
MANPAGE		= manpager.$(SECT)$(SUBSECT)
CATPAGE		= manpager.cat
MANSRC		= manpager.man
ARCFILE		= manpager.arc
SHARFILE	= manpager.shr
UUEFILE		= manpager.uue
HEADERS		= bold.h uline.h small.h special.h standout.h roman.h
SRCS		= main.c font.c putline.c bold.c uline.c small.c normal.c \
		special.c standout.c roman.c fun.c funb.c
OBJS		= main.o font.o putline.o bold.o uline.o small.o normal.o \
		special.o standout.o roman.o fun.o funb.o
OTHERS		= readme makefile $(MANSRC)
DISTFILES	= $(OTHERS) $(SRCS)

LD		= g:\bin\aln.ttp
# define:
#	USE_FUNNY_FONT	to have -fun (try it!). this effects main.c,
#			putline.c, fun.c and funb.c
#	SM_SERIF	make the small char set serif (default is sans serif)
CFLAGS		= -DUSE_FUNNY_FONT
LDFLAGS		= -s -nf
LIBS		= -llinea -lzlib
BINDIR		= c:\bin
MANDIR		= c:\man\man$(SECT)
RUNPARM		=
RUNOUT		=



# directions...
#
directions:
		@echo type "make all" to built $(TARGET)
		@echo type "make install" to built/install $(TARGET)
		@echo type "make test" to test $(TARGET)
		@echo type "make clean" to remove objects
		@echo type "make clobber" to remove objects and $(TARGET)
		@echo type "make arc" to make source archive $(ARCFILE)
		@echo type "make shar" to make source shar file $(SHARFILE)
		@echo type "make uue" to make uuencoded $(TARGET) $(UUEFILE)


# main target...
#
all:		$(TARGET)

$(TARGET):	$(OBJS)
#		$(CC) $(LDFLAGS) -o $(TARGET) $(OBJS) $(LIBS)
		$(LD) -w -v -o $(TARGET) -c l.inp 


# manpage (use built-in .man.cat rule)...
#
manpage:	$(MANPAGE)

$(MANPAGE):	$(CATPAGE)
		colcrt $(CATPAGE) >tmp.cat
		entab tmp.cat $(MANPAGE)
		rm tmp.cat

$(CATPAGE):	$(MANSRC)



# to run it...
#
test:		$(TARGET)
		$(TARGET) $(RUNPARM) $(RUNOUT)


# to install it...
#
install:	install_bin install_man

install_bin:	$(TARGET)
		cp $(TARGET) $(BINDIR)$(TARGET)

install_man:	$(MANPAGE)
		cp $(MANPAGE) $(MANDIR)$(MANPAGE)


# others...
#
clean:
		rm $(OBJS) errs $(CATPAGE)

clobber:	clean
		rm $(TARGET) $(MANPAGE)

arc:
		$(ARC) a $(ARCFILE) $(DISTFILES)
		@echo done making $(ARCFILE)

uue:
		$(UUENCODE) $(TARGET)
		@echo done making $(UUEFILE)

shar:
		$(SHAR) $(DISTFILES) >$(SHARFILE)
		@echo done making $(SHARFILE)


# dependencies...
#
font.o:		font.c
putline.o:	putline.c
main.o:		main.c
bold.o:		bold.c bold.h
roman.o:	roman.c roman.h
special.o:	special.c special.h
uline.o:	uline.c uline.h
standout.o:	standout.c standout.h
small.o:	small.c small.h
fun.o:		fun.c fun.h
funb.o:		funb.c funb.h

