#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c

.s.o:
	mac $(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	@c:\compiler.dsk\cp68.prg $(CFLAGS) $*.c m:$*.i
	@c:\compiler.dsk\c068.prg m:$*.i m:$*.1 m:$*.2 m:$*.3 -f
	@rm m:$*.i
	@c:\compiler.dsk\c168.prg m:$*.1 m:$*.2 m:$*.s
	@c:\bin\mac.prg -6 -o $*.o m:$*.s
	@rm m:$*.1 m:$*.2 m:$*.s

TEMP = m:tmp
LIBS = gemlib

OBJS = driver.o acsi.o ide.o cmdblk.o cookie.o doit.o scsi.o\
	spscsi.o install.o

driver.prg : $(OBJS)
	echo $(OBJS) >$(TEMP)
	aln  -o driver.prg -c $(TEMP)


#
#  assembly-language files
#
acsi.o : acsi.s defs.h spscsi.h
ide.o: ide.s ide.h defs.h
cmdblk.o : cmdblk.s defs.h
cookie.o : cookie.s
driver.o : driver.s defs.h 68030.s error.h spscsi.h
doit.o : doit.s defs.h
install.o : install.s defs.h spscsi.h
scsi.o : scsi.s scsi.h defs.h
spscsi.o : spscsi.s spscsi.h defs.h

