# Bermuda makefile for MicroSoft WIN32 SDK (0393BETA)
#
!include <ntwin32.mak>

all: import.exe pack.exe crunch.exe scan.exe

import.exe: import.obj utextra.obj
  $(link) $(linkdebug) $(conflags) -out:$*.exe $** $(conlibsdll) \
    user32.lib

pack.exe: pack.obj route.obj patmat.obj utextra.obj
  $(link) $(linkdebug) $(conflags) -out:$*.exe $** $(conlibsdll) \
    user32.lib

scan.exe: scan.obj utextra.obj
  $(link) $(linkdebug) $(conflags) -out:$*.exe $** $(conlibsdll) \
    user32.lib

crunch.exe: crunch.obj utextra.obj
  $(link) $(linkdebug) $(conflags) -out:$*.exe $** $(conlibsdll) \
    user32.lib

.c.obj:
  $(cc) $(cdebug) $(cflags) $(cvarsdll) $*.c

