/* EXTERNS
 *==========================================================================
 */
extern long rs_trindex[];

extern OBJECT *tree;
extern OBJECT *Maintree;
extern OBJECT *Oxsizes;
extern OBJECT *PtSizeTree;
extern OBJECT *Oxtree;
extern OBJECT *PrevTree;
extern OBJECT *FsmTree;
extern OBJECT *CacheTree;
extern OBJECT *ad_scan;
extern OBJECT *ad_width;
extern OBJECT *ad_load;

/* PROTOTYPES
 *==========================================================================
 */


/* DEFINES
 *==========================================================================
 */
#define VERTICAL	0
#define HORIZONTAL	1
#define NULLFUNC	( void(*)())0L

