;----------------------------------------------------------------------------
;File name:	_DigCnvT.s			Revision date:	2000.08.25
;Revised by:	Ronald Andersson		Revision start:	2000.08.25
;----------------------------------------------------------------------------
_DigCnvT:
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$0001,$0203,$0405,$0607
	dc.w	$0809,$FFFF,$FFFF,$FFFF
	dc.w	$FF0A,$0B0C,$0D0E,$0F10
	dc.w	$1112,$1314,$1516,$1718
	dc.w	$191A,$1B1C,$1D1E,$1F20
	dc.w	$2122,$23FF,$FFFF,$FFFF
	dc.w	$FF0A,$0B0C,$0D0E,$0F10
	dc.w	$1112,$1314,$1516,$1718
	dc.w	$191A,$1B1C,$1D1E,$1F20
	dc.w	$2122,$23FF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
	dc.w	$FFFF,$FFFF,$FFFF,$FFFF
;----------------------------------------------------------------------------
;End of file:	_DigCnvT.s
;----------------------------------------------------------------------------
