/* [GS] 5.1d alt: alle Texte sind in der Resourcedatei
LOCAL BYTE *free_text [] =
{
  " Manager ",
  " Infozeile",
  "Manager",
  " PAPIERKORB ",
  " %d Objekte",
  " HILFE ",
  " Index",
  "Rechnenliste",
  "Abfrageliste",
  "Reportliste",
  "Batchliste",
  "Berichtsliste",
  "Rechnungen",
  "Abfragen",
  "Reports",
  "Batches",
  "Berichte",
  "Masken",
  "MEM:%5u KB",
  "TOT:%5u KB",
  "Datenbank: %s",
  " Report fÅr %s ",
  " Batch fÅr %s ",
  " %sBericht: %s ",
  " Eigenschaften ",
  "Eigenschaft: %s",
  "<namenlos>",
  "Single-User",
  "Multi-Tasking",
  "Multi-User",
  "%ld KB",
  "%s\t%s\t%ld\t%ld",
  "%s\t%s\t%s\t%s\t%s",
  "ja",
  "ASCII",
  "nein",
  "BinÑr",
  "SPOOLER",
  "Datei",
  ",.",														/* do not translate */

  "HILFE",												/* Function keys */
  "ôFFNEN",
  "SCHLIESSEN",
  "DB SCHLIESSEN",
  "SINNBILD",
  "ABFRAGE",
  "BERICHT",
  "RECHNEN",
  "BATCH",
  "BEARBEITEN",

  "*.*",													/* do not translate */
  "*.ind",												/* do not translate */
  "*.dat",												/* do not translate */
  "*.lst",												/* do not translate */
  "*.lay",												/* do not translate */
  "*.prn",												/* do not translate */
  "*.prt",												/* do not translate */
  "*.bin",												/* do not translate */
  "*.asc",												/* do not translate */
  "*.txt",												/* do not translate */
  "*.imp",												/* do not translate */
  "*.tmp",												/* do not translate */
  "*.inf",												/* do not translate */
  "*.gem",												/* do not translate */
  "*.img",												/* do not translate */
  "*.iff",												/* do not translate */
  "*.tif",												/* do not translate */
  "*.prg",												/* do not translate */
  "*.app",												/* do not translate */
  "*.286",												/* do not translate */
  "*.rpt",												/* do not translate */
  "*.qbe",												/* do not translate */
  "*.rep",												/* do not translate */
  "*.cal",												/* do not translate */
  "*.sam",												/* do not translate */

  "GEM-Programme (*.286)|*.286|DOS-Programme (*.exe)|*.exe|",
  "Alle Dateien (*.*)|*.*|",
  "GEM-Programme (*.app)|*.app|DOS-Programme (*.exe)|*.exe|",
  "Text-Dateien (*.asc)|*.asc|BinÑr-Dateien (*.bin)|*.bin|Alle Dateien (*.*)|*.*|",
  "Phoenix DB (*.dat)|*.dat|",
  "GEM Metafile (*.gem)|*.gem|",
  "GEM Image (*.img)|*.img|",
  "GEM Image (*.img)|*.img|GEM Metafile (*.gem)|*.gem|",
  "GEM Image (*.img)|*.img|GEM Metafile (*.gem)|*.gem|Text-Datei (*.txt)|*.txt|Alle Dateien (*.*)|*.*|",
  "Import-Parameter (*.imp)|*.imp|Alle Dateien (*.*)|*.*|",
  "IFF Grafik (*.iff)|*.iff|",
  "Phoenix DB (*.ind)|*.ind|",
  "Phoenix DB (*.ind)|*.ind|GEM Image (*.img)|*.img|GEM Metafile (*.gem)|*.gem|Text-Datei (*.txt)|*.txt|Alle Dateien (*.*)|*.*|",
  "Konfig-Dateien (*.inf)|*.inf|Alle Dateien (*.*)|*.*|",
  "Seitenformat (*.lay)|*.lay|Alle Dateien (*.*)|*.*|",
  "List-Dateien (*.lst)|*.lst|Alle Dateien (*.*)|*.*|",
  "GEM-Programme (*.prg)|*.prg;*.app|Accessories (*.acc)|*.ac?|TOS-Programme (*.tos)|*.tos;*.ttp|",
  "Drucker-Parameter (*.prn)|*.prn|Alle Dateien (*.*)|*.*|",
  "Drucker-Treiber (*.prt)|*.prt|Alle Dateien (*.*)|*.*|",
  "Report-Dateien (*.rpt)|*.rpt|Alle Dateien (*.*)|*.*|",
  "Sample Sound (*.sam)|*.sam|",
  "TIFF Grafik (*.tif)|*.tif|",
  "TemporÑre Dateien (*.tmp)|*.tmp|Alle Dateien (*.*)|*.*|",
  "Text-Dateien (*.txt)|*.txt|Alle Dateien (*.*)|*.*|",

  "SÑtze/Ereignis: %ld",
  "Bytes/Ereignis: %ld",
  "Datensatz:",
  "Bytes:",
  "Seite:",
  "Seite %ld von %ld",

  "$BREITE",											/* do not translate */
  "$LéNGE",												/* do not translate */
  "$OBEN",												/* do not translate */
  "$UNTEN",												/* do not translate */
  "$KOPF",												/* do not translate */
  "$FUSS",												/* do not translate */
  "$LKOPF",												/* do not translate */
  "$MKOPF",												/* do not translate */
  "$RKOPF",												/* do not translate */
  "$LFUSS",												/* do not translate */
  "$MFUSS",												/* do not translate */
  "$RFUSS",												/* do not translate */
  "$TABELLE",											/* do not translate */
  "$ASCII",												/* do not translate */
  "$POS",													/* do not translate */
  "$LINKS",												/* do not translate */
  "$LISTE",												/* do not translate */
  "$VPOS",												/* do not translate */
  "$SQL",													/* do not translate */
  "$PROP",												/* do not translate */
  "$HOCH",												/* do not translate */
  "$TIEF",												/* do not translate */
  "$KURSIV",											/* do not translate */
  "$FETT",												/* do not translate */
  "$UNTER",												/* do not translate */
  "$PICA",												/* do not translate */
  "$ELITE",												/* do not translate */
  "$NLQ",													/* do not translate */
  "$SCHMAL",											/* do not translate */
  "$BREIT",												/* do not translate */

  "Berichtskopf",
  "Berichtsfuû",
  "Seitenkopf",
  "Seitenfuû",
  "%s - Kopfbereich",
  "%s - Fuûbereich",
  "Detailbereich",
  "Breite: %s cm",
  "Hîhe: %s cm",
  "X: %s cm, Y: %s cm, Grîûe: %s x %s cm",
  "X: %s cm, Y: %s cm, Grîûe: %s x %s cm (%d Zeilen)",
  "Gruppe",
  "Klasse",
  "Flags",
  "Text",
  "Spalte",
  "Tabelle",
  "Format",
  "Wert",
  "Dateiname",
  "Berichtsname",
  "VerknÅpfen von",
  "VerknÅpfen nach",
  "Bedingung",
  "Sortierung",
  "Laufende Summe",
  "Links",
  "Oben",
  "Breite",
  "Hîhe",
  "Hintergrundart",
  "Hintergrundfarbe",
  "Spezialeffekt",
  "Rahmenart",
  "Rahmenfarbe",
  "Rahmenbreite",
  "Rahmenstil",
  "Schriftart",
  "Schriftart-Nummer",
  "Schriftgrîûe",
  "Schriftfarbe",
  "Fett",
  "Kursiv",
  "Unterstrichen",
  "Umrahmt",
  "Hell",
  "Horz. Textausrichtung",
  "Vert. Textausrichtung",
  "Rotation",
  "Sichtbar",
  "Selektiert",
  "Vergrîûerbar",
  "Verkleinerbar",
  "Duplikate ausblenden",
  "Tabelle/Abfrage",
  "Datenherkunft",
  "Seitenkopf",
  "Seitenfuû",
  "Raster X",
  "Raster Y",
  "Breite",
  "Linker Rand",
  "Rechter Rand",
  "Oberer Rand",
  "Unterer Rand",
  "Spaltenanzahl",
  "Spaltenabstand",
  "AusgabegerÑt",
  "Seitenformat",
  "Seitenausrichtung",
  "Neue Seite",
  "Hîhe",
  "Hintergrundfarbe",
  "Sichtbar",
  "Zusammenhalten",
  "Vergrîûerbar",
  "Verkleinerbar",
  "Nein;öber Gruppe;öber Alles",
  "Deckend;Transparent",
  "Weiû;Schwarz;Rot;GrÅn;Blau;Hellblau;Gelb;Rosa;Grau;Dunkelgrau;Braun;DunkelgrÅn;Marineblau;TÅrkis;Ocker;Purpur",
  "Normal;Erhîht;Vertieft",
  "Durchgezogen;Langer Strich;Punktiert;Strich Punkt;Strich;Strich Punkt Punkt",
  "Nein;Ja",
  "(Standard);LinksbÅndig;Zentriert;RechtsbÅndig",
  "(Standard);Oben;Mitte;Unten",
  "Aus Abfrage;Aus Tabelle",
  "Alle Seiten;Auûer Berichtskopf;Auûer Berichtsfuû;Auûer Berichtskopf/-fuû",
  "Keine;Vor Bereichsanfang;Nach Bereichsende;Davor und danach",
  "(Standard);A3;A4;A5;B5;Letter;Half;Legal;Double;Broad",
  "(Standard);Hochformat;Querformat",

  "Lesen+Schreiben",
  "Nur Lesen",

  " Datei îffnen... ",
  " Datei speichern... ",
  " Konfiguration laden... ",
  " Konfiguration sichern... ",
  " Export-Datei anlegen... ",
  " Import-Datei îffnen... ",
  " Dateiname fÅr Drucker... ",
  " List-Datei anlegen... ",
  " Temp-Verzeichnis... ",
  " Datei drucken... ",
  " Datei lîschen... ",
  " Drucker-Treiber laden... ",
  " Drucker-Parameter laden... ",
  " Drucker-Parameter sichern... ",
  " Seitenformat laden... ",
  " Seitenformat sichern... ",
  " Imp/Export-Parameter laden... ",
  " Imp/Export-Parameter sichern... ",
  " Programm ausfÅhren... ",
  " Text importieren... ",
  " Text exportieren... ",
  " Bild importieren... ",
  " Bild exportieren... ",
  " BLOB importieren... ",
  " BLOB exportieren... ",
  " Report-Datei anlegen... ",
  " Dateiname holen... ",

  " Prozeû: Spooling ",
  " Prozeû: Liste ausgeben ",
  " Prozeû: Liste drucken ",
  " Prozeû: Exportieren ",
  " Prozeû: Importieren ",
  " Prozeû: Suchen ",
  " Prozeû: Lîschen ",
  " Prozeû: EinfÅgen ",
  " Prozeû: Bericht erstellen ",
  " Prozeû: Report erstellen ",
  " Prozeû: Rechnen ",
  " Prozeû: Batch ",

  " öber Manager ",												/* Headlines for the dialogs */
  " Datenbank îffnen... ",
  " Konfiguration ",
  " Im/Export-Parameter ",
  " Drucker-Parameter ",
  " Seitenformat ",
  " Schriftart... ",
  " Anzeige schÅtzen... ",
  " Paûwort Ñndern... ",
  " Datenbank-Info ",
  " Tabellen-Info ",
  " Index-Info ",
  " Prozeû ",
  " Druckerwarteschlange ",
  " Programm-Parameter... ",
  " DatensÑtze lîschen... ",
  " Rechnung sichern als... ",
  " Abfrage sichern als... ",
  " Report sichern als... ",
  " Batch sichern als... ",
  " Bericht sichern als...",
  " Sortierung... ",
  " Spaltenbreite... ",
  " öber Hilfe ",
  " Klemmbrett-Name... ",
  " Suchen... ",
  " Weitere Informationen ",
  " Metadatei-Info ",
  " Maske wechseln... ",
  " Verzweigen... ",
  " Masken-Konfiguration ",
  " Datenbank reorganisieren... ",
  " Reorganisations-Parameter... ",
  " Reorganisations-Statistik ",
  " Bereich entfernen... ",
  " Neuer Prozeû... ",
  " Prozeûliste... ",
  " Benutzer-OberflÑche ",
  " Report erstellen ",
  " Parameter fÅr Abfrage ",

  "Lade %s...",
  "Tabellen",
  "Felder",
  "Indizes",
  "Beziehungen",
  "Benutzer",
  "Papierkorb",
  "Sinnbilder",
  "Tabellenattribute",
  "Formate",
  "Wertetabellen",
  "Rechnungen",
  "Masken",
  "Abfragen",
  "Reports",
  "Batches",
  "BLOBs",
  "Berichte",
  "Dummy17",
  "Dummy18",
  "Dummy19",

  "Selektierter Hintergrund",
  "Selektierter Text",
  "Deaktivierter Text",
  "SchaltflÑche",
  "Oberer und linker Rand",
  "Unterer und rechter Rand",
  "Textfarbe einer SchaltflÑche",
  "Scrollbalken Hintergrund",
  "Dialogbox Hintergrund",

  "Kreuzchen",
  "HÑkchen",

  "Knopf",
  "Raute",

  "Keile",
  "Pfeile",

  "Name",
  "Art",
  "Datum",
  "LÑnge",
  "Unsortiert",

  "Weiû",
  "Schwarz",
  "Rot",
  "GrÅn",
  "Blau",
  "Hellblau",
  "Gelb",
  "Rosa",
  "Grau",
  "Dunkelgrau",
  "Braun",
  "DunkelgrÅn",
  "Marineblau",
  "TÅrkis",
  "Ocker",
  "Purpur",
}; /* free_text */
*/
