
copy D:\000STUFF\ATARI\Emulators\steem_v3_2\TD_A.st TD_A.st
copy D:\000STUFF\ATARI\Emulators\steem_v3_2\TD_B.st TD_B.st
copy D:\000STUFF\ATARI\Emulators\steem_v3_2\TESTSIZE.ST TESTSIZE.ST


STTOMSA.EXE TD_A.ST TD_A.MSA
STTOMSA.EXE TD_B.ST TD_B.MSA
STTOMSA.EXE TESTSIZE.ST TESTSIZE.MSA


