/*****************************************************************************
 *
 * Module : VERSION.H
 * Author : Gerhard Stoll
 *
 * Creation date    : 01.11.02
 * Last modification: s.u.
 *
 *
 * Description: Verwaltung der Versionsnummer des Designer
 *
 * History:
 * 22.12.07: Version 5.2
 * 05.08.05: Version 5.1f
 * 10.01.04: Version 5.1d
 * 28.12.02: Version 5.1c
 * 27.11.02: Version 5.1b
 * 01.11.02: Define erstellt
 *****************************************************************************/

#ifndef __VERSION__
#define __VERSION__

/****** DEFINES **************************************************************/

#define DESIGNER_VERSION "Version 5.2"

#endif /* __VERSION__ */
