
NEWAWK=gawk
# you choose gawk or nawk or whatever
CINIT=-v
# this is about how variables are initialised on the
# commandline when running awk.  You need a "$(CINIT)" with
# gawk, and nothing with nawk (i.e., say "CINIT=")

test :
	@echo 1. Testing without "free" and without t-stats.
	$(NEWAWK) -f epp2tex.nawk demo.epp > epp.out
	-diff epp.out result.ft

	@echo ""; echo 2. Testing with free but not t
	$(NEWAWK) -f epp2tex.nawk $(CINIT) putfree=1 demo.epp > epp.out
	-diff epp.out result.Ft

	@echo ""; echo 3. Testing with t but not free
	$(NEWAWK) -f epp2tex.nawk $(CINIT) putt=1 demo.epp > epp.out
	-diff epp.out result.fT

	@echo ""; echo 4. Testing with t and with free
	$(NEWAWK) -f epp2tex.nawk $(CINIT) putt=1 $(CINIT) putfree=1 demo.epp > epp.out
	-diff epp.out result.FT

	@echo ""; echo 5. Testing with OLS demo
	$(NEWAWK) -f epp2tex.nawk $(CINIT) putt=1 ols.epp > epp.out
	-diff epp.out result.ols

	@/bin/rm -f epp.out

doc :
	latex epp-doc.tex
	/bin/csh /max/a/TeX/bin/dvips -r epp-doc.dvi
	rm -f tex.pro *.aux *.dvi *.log

post : clean
	shar * > /tmp/a.shar
	/bin/mv /tmp/a.shar ./epp.shar

clean :
	rm -f epp.shar epp.out epp-doc.dvi epp-doc.ps

