/* resource set indicies for CACHE */

#define FORM     0	/* form/dialog */
#define A1       3	/* BUTTON in tree FORM */
#define B1       4	/* BUTTON in tree FORM */
#define C1       5	/* BUTTON in tree FORM */
#define D1       6	/* BUTTON in tree FORM */
#define E1       7	/* BUTTON in tree FORM */
#define F1       8	/* BUTTON in tree FORM */
#define G1       9	/* BUTTON in tree FORM */
#define H1       10	/* BUTTON in tree FORM */
#define I1       11	/* BUTTON in tree FORM */
#define K1       12	/* BUTTON in tree FORM */
#define J1       13	/* BUTTON in tree FORM */
#define L1       14	/* BUTTON in tree FORM */
#define M1       15	/* BUTTON in tree FORM */
#define N1       16	/* BUTTON in tree FORM */
#define O1       17	/* BUTTON in tree FORM */
#define P1       18	/* BUTTON in tree FORM */
#define A2       22	/* BUTTON in tree FORM */
#define B2       23	/* BUTTON in tree FORM */
#define C2       24	/* BUTTON in tree FORM */
#define D2       25	/* BUTTON in tree FORM */
#define E2       26	/* BUTTON in tree FORM */
#define F2       27	/* BUTTON in tree FORM */
#define G2       28	/* BUTTON in tree FORM */
#define H2       29	/* BUTTON in tree FORM */
#define I2       30	/* BUTTON in tree FORM */
#define K2       31	/* BUTTON in tree FORM */
#define J2       32	/* BUTTON in tree FORM */
#define L2       33	/* BUTTON in tree FORM */
#define M2       34	/* BUTTON in tree FORM */
#define N2       35	/* BUTTON in tree FORM */
#define O2       36	/* BUTTON in tree FORM */
#define P2       37	/* BUTTON in tree FORM */
#define FSIZE    38	/* FTEXT in tree FORM */
#define FROM     39	/* BUTTON in tree FORM */
#define FALTH    40	/* BUTTON in tree FORM */
#define FOK      41	/* BUTTON in tree FORM */
#define FOVERH   44	/* FTEXT in tree FORM */

