# Makefile for RAMFS.XFS; the -mshort flag is mandatory

CC = gcc
AS = $(CC) -c
LD = $(CC) -nostdlib

CFLAGS = -mshort -O2 -fomit-frame-pointer -Wall

ramfs.xfs: start.o ramfs.o
	$(LD) -s -o ramfs.xfs start.o ramfs.o -lgnu16
	cp ramfs.xfs /c/mint/

archive:
	zoo aunhP: ramfs.zoo \
	atarierr.h filesys.h makefile ramfs.c start.s ramfs.xfs \
	lisez.moi readme.1st

start.o: start.s
ramfs.o: ramfs.c
