
TARGET = ../lib/mshort/libslb.a
AR= ar rs
RM= rm -f
CC= gcc
CFLAGS= -Wall -Os -m68000 -fomit-frame-pointer -mshort $(DEFS) \
	-I../include
DEFS=
OBJS= libslb.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(RM) $@
	$(AR) $@ $(OBJS)

install:
	mv $(TARGET) /usr/lib/mshort/

clean:
	$(RM) $(OBJS)

veryclean:
	$(RM) $(OBJS) $(TARGET)
