#
# Makefile for strsed
#

#
# Use gcc if you have it...
# (The MIPS cc produces a regex.o which dumps core).
#

#CC = cc

CC = gcc -z -v -Wall -Ig:/mint/include
# STDC_HEADERS is needed by regex.c
CFLAGS = -O -DSTDC_HEADERS
LD = gcc -z -v -Wall -Lg:/mint/lib
LDFLAGS = -nostdlib g:/mint/lib/crt0.o
LIBS = -liio -lgnu

EXT =.ttp

all : check

check : check1$(EXT) check2$(EXT)
	cat examples1 | ./check1
	cat examples2 | ./check2

check1$(EXT) : strsed.o regex.o check1.o
	$(LD) $(LDFLAGS) -o check1$(EXT) strsed.o regex.o check1.o $(LIBS)

check2$(EXT) : strsed.o regex.o check2.o
	$(LD) $(LDFLAGS) -o check2$(EXT) strsed.o regex.o check2.o $(LIBS)

strsed.o : regex.h
regex.o : regex.h

clean :
	rm -f check?.o

clobber : clean
	rm -f strsed.o check[12]$(EXT) MANIFEST
