/*
 * Listing 2.2, Datei : atom2.h
 * Modul              : ATOM - ATOMare Manipulationen,
 *                      2.Teil
 * Modifikationsdatum : 04-M„r-90
 * Abh„ngigkeiten     : local.h
 */

extern BOOLEAN onlyws(),
               patmat();
extern void    outline(),
               filter_dict(),
               random_number(),
               random_alpha(),
               random_month();

