#
# Makefile for make
#

#CC = c:\sozobon\bin\cc
CFLAGS = -O

OBJS1 = check.o input.o macro.o reader.o rules.o readenv.o
OBJS2 = main.o make.o ststuff.o

make.ttp : $(OBJS1) $(OBJS2)
	$(CC) $(OBJS1) $(OBJS2) -o make.ttp

touch.ttp : touch.c
	$(CC) touch.c -o touch.ttp


$(OBJS1) : h.h
$(OBJS2) : h.h astat.h

clean:
	$(RM) $(OBJS1) $(OBJS2)

clobber:
	$(RM) $(OBJS1) $(OBJS2) make.ttp touch.ttp

