/*
 * TT44TT.H
 * Resource-Header fÅr TT44TT
 * Copyright (c) 1991 by MAXON Computer
 * Autoren: Oliver Scholz & Uwe Hax
 */

#define PORTS 0         /* TREE */
#define ABOUTBOX 1      /* TREE */
#define NEWDESK 2       /* TREE */
#define MENU 3          /* TREE */
#define RTSCTS 5        /* OBJECT in TREE #0 */
#define NOPROT 6        /* OBJECT in TREE #0 */
#define XONXOFF 7       /* OBJECT in TREE #0 */
#define PARO 11         /* OBJECT in TREE #0 */
#define PARN 12         /* OBJECT in TREE #0 */
#define PARE 13         /* OBJECT in TREE #0 */
#define BAUDRATE 19     /* OBJECT in TREE #0 */
#define BAUDUP 20       /* OBJECT in TREE #0 */
#define BAUDDWN 21      /* OBJECT in TREE #0 */
#define BITS8 24        /* OBJECT in TREE #0 */
#define BITS7 26        /* OBJECT in TREE #0 */
#define PORTABRT 29     /* OBJECT in TREE #0 */
#define STOP2 33        /* OBJECT in TREE #0 */
#define STOP1 35        /* OBJECT in TREE #0 */
#define PORTOK 37       /* OBJECT in TREE #0 */
#define ABOUTOK 9       /* OBJECT in TREE #1 */
#define MFP2 1          /* OBJECT in TREE #2 */
#define SCC1 2          /* OBJECT in TREE #2 */
#define SCC2 3          /* OBJECT in TREE #2 */
#define MFP1 4          /* OBJECT in TREE #2 */
#define ABOUT 8         /* OBJECT in TREE #3 */
#define OPEN 17         /* OBJECT in TREE #3 */
#define CLOSE 18        /* OBJECT in TREE #3 */
#define QUIT 20         /* OBJECT in TREE #3 */
#define PORT 22         /* OBJECT in TREE #3 */
#define ZOOM 24         /* OBJECT in TREE #3 */
#define LOADINF 26      /* OBJECT in TREE #3 */
#define SAVEINF 27      /* OBJECT in TREE #3 */
