Title:			Tag Image File Format (TIFF) Specification
Author:			Aldus/MicroSoft
Version:		5.0
Title From:		Documentation
Author From:		Documentation
Version From:		Documentation
Publisher:		Aldus/MicroSoft
Date:			08/08/88
Keywords:		
Shareware:		No
Machine:		IBM PC
Memory requirements:	
Peripherals needed:	
Other s/ware needed:	
Local id. code:		ibmpc/e130
Date mounted/updated:	10/12/89
File names:		e130tiff.boo
Unarchived files:	1
Unarchived size:	183313
Omissions:		
See also:		

-------------------------------------------------------------------------------

Acquiring the package:

Download the BOO-format files and run the DEBOO utility to convert each to a
.ARC file. Then unpack each of these with the PKUNPAK utility to generate
the original files for the package. (The utilities needed are online in
directory micros/ibmpc/h99)

Description:

This is a document describing TIFF, a tag based file format that is designed to
promote the interchange of digital image data. TIFF was devised by Aldus and
MicroSoft in conjunction with scanner and printer manufacturers.

The fields were defined primarily with desktop publishing and related
applications in mind, although it is conceivable that other sorts of imaging
applications may find TIFF to be useful.

The general scenario for which TIFF was invented assumes that applications
software for scanning or painting creates a TIFF file, which can then be read
and incorporated into a document or publication by an application such as a
desktop publishing package.

The intent of TIFF is to organize and codify existing practice with respect to
the definition and usage of desktop digital data, not to blaze new paths or
promote unproven techniques.  Yet a very high priority has been given to
structuring the data in such a way as to minimize the pain of future additions.
TIFF was designed to be a very extensible interchange format.

TIFF is not a printer language or page description language, nor is it intended
to be a general document interchange standard.  It may be useful as is for some
image editing applications, but is probably inappropriate for and would thus
need to be translated into some intermediate data structures by other image
editing applications.  The primary design goal was to provide a rich
environment within which the exchange of image data between application
programs can be accomplished.  This richness is required in order to take
advantage of the varying capabilities of scanners and similar devices.  TIFF is
therefore designed to be a superset of existing image file formats for desktop
scanners (and paint programs and anything else that produces images with pixels
in them) and will be enhanced on a continuing basis as new capabilities arise.

