/*
 *	General Midi Instrument lists.
 *	(c) Martin Griffiths August/September 1994.
 */

#include "types.h"
 
char * gm_instrument[NO_INSTRUMENT] = 
{ "Acoustic Grand Piano",	/* 1-8 PIANO */
  "Bright Acoustic Piano",
  "Electric Grand Piano",
  "Honky-Tonk Piano",
  "Electric Piano 1",
  "Electric Piano 2",
  "Harpsichord",
  "Clav",
  "Celesta",				/* 9-16 CHROM PERCUSSION */
  "Glockenspiel",
  "Music Box",
  "Vibraphone",
  "Marimba",
  "Xylophone",
  "Tubular Bells",
  "Dulcimer",
  "Drawbar Organ",			/* 17 -24 ORGAN */
  "Percussive Organ",
  "Rock Organ",
  "Church Organ",
  "Reed Organ",
  "Accordian",
  "Harmonica",
  "Tango Accordian",
  "Acoustic Guitar(Nylon)", /* 25-32 GUITAR */
  "Acoustic Guitar(Steel)",
  "Electric Guitar(Jazz)",
  "Electric Guitar(Clean)",
  "Electric Guitar(Muted)",
  "Overdriver Guitar",
  "Distortion Guitar",
  "Guitar Harmonics", 
  "Acoustic Bass",			/* 33-40 BASS */
  "Electric Bass(finger)",
  "Electric Bass(pick)",
  "Fretless Bass",
  "Slap Bass 1", 
  "Slap Bass 2", 
  "Synth Bass 1", 
  "Synth Bass 2", 
  "Violin",					/* 41-48 STRINGS */
  "Viola",
  "Cello",
  "Contrabass",
  "Tremelo Strings",
  "Pizzicato Strings",
  "Orchestral Strings",
  "Timpani",
  "String Ensemble 1",		/* 49-56 ENSEMBLE */
  "String Ensemble 2",
  "Synth Strings 1",
  "Synth Strings 2",
  "Choir Aahs",
  "Voices Oohs",
  "Synth Voice",
  "Orchestra Hit",
  "Trumpet",				/* 57-64 BRASS */
  "Trombone",
  "Tuba",
  "Muted Trumpet",
  "French Horn",
  "Brass Section",
  "Synth Brass 1",
  "Synth Brass 2",
  "Soprano Sax",			/* 65-72 REED */
  "Alto Sax",
  "Tenor Sax",
  "Baritona Sax",
  "Oboe",
  "English Horn",
  "Bassoon",
  "Clarinet",
  "Piccolo",				/* 73-80 PIPE */
  "Flute",
  "Recorder",
  "Pan Flute",
  "Blown Bottle",
  "Skakubachi",
  "Whistle",
  "Ocarina",
  "Lead 1 (Square)",		/* 81-88 SYNTH LEAD */
  "Lead 2 (Sawtooth)",
  "Lead 3 (Calliope)",
  "Lead 4 (Chiff)",
  "Lead 5 (Charang)",
  "Lead 6 (Voice)",
  "Lead 7 (Fifths)",
  "Lead 8 (Bass+Lead)",
  "Pad 1 (new age)",		/* 89-96 SYNTH PAD */
  "Pad 2 (warm)",
  "Pad 3 (polysynth)",
  "Pad 4 (choir)",
  "Pad 5 (bowed)",
  "Pad 6 (metallic)",
  "Pad 7 (halo)",
  "Pad 8 (sweep)",
  "FX 1 (rain)",			/* 97-104 SYNTH EFFECTS */
  "FX 2 (soundtrack)",
  "FX 3 (crystal)",
  "FX 4 (atmosphere)",
  "FX 5 (brightness)",
  "FX 6 (goblins)",
  "FX 7 (echoes)",
  "FX 8 (sci-fi)",
  "Sitar",					/* 105-112 ETHNIC */
  "Banjo",
  "Shamisen",
  "Koto",
  "Kalimba",
  "Bagpipe",
  "Fiddle",
  "Shanai",
  "Tinkle Bell",			/* 113-120 Percussive */
  "Agogo",
  "Steel Drums",
  "WoodBlock",
  "Taiko Drum",
  "Melodic Tom",
  "Synth Drum",
  "Reverse Cymbal",
  "Guitar Fret Noise",		/* 121-128 SOUND EFFECTS */
  "Breath Noise",
  "Seashore",
  "Bird Tweet",
  "Telephone Ring",
  "Helicopter",
  "Applause",
  "Gunshot"
};


char * gm_percussion[NO_PERCUSSION] = 
{	"Acoustuc Bass Drum",
	"Bass Drum",
	"Side Stick",
	"Acoustic Snare",
	"Hand Clap",
	"Electric Snare",
	"Low Floor Tom",
	"Closed Hi-Hat",
	"High Floor Tom",
	"Pedal Hi-Hat",
	"Low Tom",
	"Open Hi-Hat",
	"Low-Mid Tom",
	"Hi-Mid Tom",
	"Crash Cymbal 1",
	"High Tom",
	"Ride Cynbal 1",
	"Chinese Cymbal",
	"Ride Bell",
	"Tambourine",
	"Splash Cymbal",
	"Cowbell",
	"Crash Cymbal 2",
	"Vibraslap",
	"Ride Cymbal 2",
	"Hi Bongo",
	"Low Bongo",
	"Mute Hi Conga",
	"Open Hi Conga",
	"Low Conga",
	"High Timbale",
	"Low Timbale",
	"High Agogo",
	"Low Agogo",
	"Cabasa",
	"Maracas",
	"Short Whistle",
	"Long Whistle",
	"Short Guiro",
	"Long Guiro",
	"Claves",
	"Hi Wood Block",
	"Low Wood Block",
	"Mute Cuica",
	"Open Cuica",
	"Mute Triangle",
	"Open Triangle"
};


char gm_instrument_fnames[NO_INSTRUMENT][FNAME_LEN] =
{	GMSET_PATH"acpiano.pat", 
	GMSET_PATH"britepno.pat",  
	GMSET_PATH"synpiano.pat",  
	GMSET_PATH"honky.pat",    
	GMSET_PATH"epiano1.pat",   
	GMSET_PATH"epiano2.pat",   
	GMSET_PATH"hrpschrd.pat",   
	GMSET_PATH"clavinet.pat",   
	GMSET_PATH"celeste.pat",   
	GMSET_PATH"glocken.pat",   
	GMSET_PATH"musicbox.pat",  
	GMSET_PATH"vibes.pat",     
	GMSET_PATH"marimba.pat",  
	GMSET_PATH"xylophon.pat",  
	GMSET_PATH"tubebell.pat",  
	GMSET_PATH"santur.pat",    
	GMSET_PATH"homeorg.pat",   
	GMSET_PATH"percorg.pat",   
	GMSET_PATH"rockorg.pat",   
	GMSET_PATH"church.pat",    
	GMSET_PATH"reedorg.pat",   
	GMSET_PATH"accordn.pat",   
	GMSET_PATH"harmonca.pat",  
	GMSET_PATH"concrtna.pat",  
	GMSET_PATH"nyguitar.pat",  
	GMSET_PATH"acguitar.pat",  
	GMSET_PATH"jazzgtr.pat",  
	GMSET_PATH"cleangtr.pat",  
	GMSET_PATH"mutegtr.pat",   
	GMSET_PATH"odguitar.pat",  
	GMSET_PATH"distgtr.pat",  
	GMSET_PATH"gtrharm.pat",   
	GMSET_PATH"acbass.pat",   
	GMSET_PATH"fngrbass.pat",  
	GMSET_PATH"pickbass.pat",  
	GMSET_PATH"fretless.pat",   
	GMSET_PATH"slapbas1.pat",  
	GMSET_PATH"slapbas2.pat",  
	GMSET_PATH"synbass1.pat",  
	GMSET_PATH"synbass2.pat",   
	GMSET_PATH"violin.pat",    
	GMSET_PATH"viola.pat",     
	GMSET_PATH"cello.pat", 
	GMSET_PATH"contraba.pat",   
	GMSET_PATH"tremstr.pat",  
	GMSET_PATH"pizzcato.pat",  
	GMSET_PATH"harp.pat",      
	GMSET_PATH"timpani.pat",   
	GMSET_PATH"marcato.pat",  
	GMSET_PATH"slowstr.pat",   
	GMSET_PATH"synstr1.pat",   
	GMSET_PATH"synstr2.pat",   
	GMSET_PATH"choir.pat",     
	GMSET_PATH"doo.pat",      
	GMSET_PATH"voices.pat",    
	GMSET_PATH"orchhit.pat",   
	GMSET_PATH"trumpet.pat",   
	GMSET_PATH"trombone.pat",  
	GMSET_PATH"tuba.pat",      
	GMSET_PATH"mutetrum.pat",  
	GMSET_PATH"frenchrn.pat",  
	GMSET_PATH"hitbrass.pat",  
	GMSET_PATH"synbras1.pat",  
	GMSET_PATH"synbras2.pat",  
	GMSET_PATH"sprnosax.pat",  
	GMSET_PATH"altosax.pat",   
	GMSET_PATH"tenorsax.pat",  
	GMSET_PATH"barisax.pat",   
	GMSET_PATH"oboe.pat",      
	GMSET_PATH"englhorn.pat",  
	GMSET_PATH"bassoon.pat",   
	GMSET_PATH"clarinet.pat",  
	GMSET_PATH"piccolo.pat",    
	GMSET_PATH"flute.pat",     
	GMSET_PATH"recorder.pat",   
	GMSET_PATH"woodflut.pat",   
	GMSET_PATH"bottle.pat",    
	GMSET_PATH"shakazul.pat",  
	GMSET_PATH"whistle.pat",   
	GMSET_PATH"ocarina.pat",   
	GMSET_PATH"sqrwave.pat",   
	GMSET_PATH"sawwave.pat",   
	GMSET_PATH"calliope.pat",  
	GMSET_PATH"chiflead.pat",  
	GMSET_PATH"charang.pat",   
	GMSET_PATH"voxlead.pat",   
	GMSET_PATH"lead5th.pat",   
	GMSET_PATH"basslead.pat",  
	GMSET_PATH"fantasia.pat",  
	GMSET_PATH"warmpad.pat",   
	GMSET_PATH"polysyn.pat",   
	GMSET_PATH"ghostie.pat",   
	GMSET_PATH"bowglass.pat",  
	GMSET_PATH"metalpad.pat",  
	GMSET_PATH"halopad.pat",   
	GMSET_PATH"sweeper.pat",   
	GMSET_PATH"aurora.pat",   
	GMSET_PATH"soundtrk.pat",  
	GMSET_PATH"crystal.pat",   
	GMSET_PATH"atmosphr.pat",  
	GMSET_PATH"freshair.pat",  
	GMSET_PATH"unicorn.pat",   
	GMSET_PATH"echovox.pat",   
	GMSET_PATH"startrak.pat",  
	GMSET_PATH"sitar.pat",     
	GMSET_PATH"banjo.pat",     
	GMSET_PATH"shamisen.pat",  
	GMSET_PATH"koto.pat",      
	GMSET_PATH"kalimba.pat",   
	GMSET_PATH"bagpipes.pat",  
	GMSET_PATH"fiddle.pat",    
	GMSET_PATH"shannai.pat",   
	GMSET_PATH"carillon.pat",  
	GMSET_PATH"agogo.pat",     
	GMSET_PATH"steeldrm.pat",  
	GMSET_PATH"woodblk.pat",   
	GMSET_PATH"taiko.pat",     
	GMSET_PATH"toms.pat",      
	GMSET_PATH"syntom.pat",    
	GMSET_PATH"revcym.pat",    
	GMSET_PATH"fx-fret.pat",   
	GMSET_PATH"fx-blow.pat",   
	GMSET_PATH"seashore.pat",  
	GMSET_PATH"jungle.pat",    
	GMSET_PATH"telephon.pat",  
	GMSET_PATH"helicptr.pat",  
	GMSET_PATH"applause.pat",  
	GMSET_PATH"ringwhsl.pat"  
};

char gm_percussion_fnames[NO_PERCUSSION][FNAME_LEN] = 
{	GMSET_PATH"highq.pat",
	GMSET_PATH"slap.pat",    
	GMSET_PATH"scratch1.pat",   
	GMSET_PATH"scratch2.pat",   
	GMSET_PATH"sticks.pat",     
	GMSET_PATH"sqrclick.pat",   
	GMSET_PATH"metclick.pat",   
	GMSET_PATH"metbell.pat",    
	GMSET_PATH"kick1.pat",      
	GMSET_PATH"kick2.pat",     
	GMSET_PATH"stickrim.pat",   
	GMSET_PATH"snare1.pat",    
	GMSET_PATH"claps.pat",     
	GMSET_PATH"snare2.pat",     
	GMSET_PATH"tomlo2.pat",    
	GMSET_PATH"hihatcl.pat",    
	GMSET_PATH"tomlo1.pat",   
	GMSET_PATH"hihatpd.pat",   
	GMSET_PATH"tommid2.pat",   
	GMSET_PATH"hihatop.pat",   
	GMSET_PATH"tommid1.pat",   
	GMSET_PATH"tomhi2.pat",    
	GMSET_PATH"cymcrsh1.pat",
	GMSET_PATH"tomhi1.pat",    
	GMSET_PATH"cymride1.pat", 
	GMSET_PATH"cymchina.pat",  
	GMSET_PATH"cymbell.pat",  
	GMSET_PATH"tamborin.pat",               
	GMSET_PATH"cymsplsh.pat",  
	GMSET_PATH"cowbell.pat",   
	GMSET_PATH"cymcrsh2.pat",  
	GMSET_PATH"vibslap.pat",   
	GMSET_PATH"cymride2.pat",  
	GMSET_PATH"bongohi.pat",                 
	GMSET_PATH"bongolo.pat",                 
	GMSET_PATH"congahi1.pat",   
	GMSET_PATH"congahi2.pat",   
	GMSET_PATH"congalo.pat",   
	GMSET_PATH"timbaleh.pat",  
	GMSET_PATH"imbalel.pat",  
	GMSET_PATH"agogohi.pat",    
	GMSET_PATH"agogolo.pat",    
	GMSET_PATH"cabasa.pat",    
	GMSET_PATH"maracas.pat",    
	GMSET_PATH"whistle1.pat",   
	GMSET_PATH"whistle2.pat",   
	GMSET_PATH"guiro1.pat"
};
	
/*	GMSET_PATH"guiro2.pat",    
	GMSET_PATH"clave.pat",    
	GMSET_PATH"woodblk1.pat",  
	GMSET_PATH"woodblk2.pat",  
	GMSET_PATH"cuica1.pat",    
	GMSET_PATH"cuica2.pat",    
	GMSET_PATH"triangl1.pat",  
	GMSET_PATH"triangl2.pat",  
	GMSET_PATH"shaker.pat",    
	GMSET_PATH"jingles.pat",  
	GMSET_PATH"belltree.pat",  
	GMSET_PATH"castinet.pat",  
	GMSET_PATH"surdo1.pat",    
	GMSET_PATH"surdo2.pat"
};*/
