##### MAKEFILE fÅr SCRAP #####

###############################################################################

NAME   = scrap

###############################################################################

CFLAGS = -AL -Oas -Gs

LFLAGS = /ST:12288 /SE:512 /NOI /E

APP    = .app

###############################################################################

.c.obj:
    cl -c $(CFLAGS) $*.c

.asm.obj:
    masm /Mx $*.asm;

###############################################################################

H      = import.h export.h global.h

OBJS   = clipbrd.obj desktop.obj dialog.obj disk.obj edit.obj event.obj\
         gemain.obj global.obj graf.obj image.obj initerm.obj menu.obj\
         meta.obj power.obj printer.obj rcm.obj resource.obj trash.obj\
         windows.obj

###############################################################################

clipbrd.obj : $(H) windows.h $(NAME).h errors.h desktop.h dialog.h edit.h image.h meta.h trash.h resource.h clipbrd.h

desktop.obj : $(H) windows.h $(NAME).h errors.h clipbrd.h dialog.h disk.h event.h menu.h printer.h trash.h desktop.h

dialog.obj  : $(H) windows.h dialog.h

disk.obj    : $(H) windows.h $(NAME).h errors.h dialog.h disk.h

edit.obj    : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h printer.h edit.h

event.obj   : $(H) windows.h desktop.h menu.h event.h

gemain.obj  : $(H) windows.h initerm.h event.h gemain.h

global.obj  : $(H)

graf.obj    : $(H) windows.h $(NAME).h graf.h

image.obj   : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h printer.h image.h

initerm.obj : $(H) windows.h $(NAME).h errors.h resource.h menu.h event.h dialog.h desktop.h trash.h disk.h printer.h edit.h clipbrd.h image.h meta.h graf.h power.h initerm.h

menu.obj    : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h disk.h graf.h power.h resource.h menu.h

meta.obj    : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h image.h printer.h meta.h

power.obj   : $(H) windows.h $(NAME).h resource.h power.h

printer.obj : $(H) windows.h $(NAME).h errors.h dialog.h printer.h

rcm.obj     : rcm.h

resource.obj: $(H) $(NAME).h resource.h

trash.obj   : $(H) windows.h $(NAME).h errors.h clipbrd.h desktop.h dialog.h trash.h

windows.obj : $(H) windows.h

###############################################################################

$(NAME)$(APP) : $(OBJS)
    link $(LFLAGS) @$(NAME).lnk

###############################################################################
