CFLAGS	=	-E050 -F150 -K -G+ -ID:\INCLUDE -L032 -M -P -W+ -Y
errtarg	=	error.err
endtarg	=	b.ttp
gentarg	=	main.o
bibdep	=	jpgdh.h
deptarg	=	linkfile

.SILENT:
$(endtarg):	$(errtarg) $(gentarg) $(bibtarg) $(deptarg)
		$(PLN)	-c=linkfile >> $(errtarg)
$(errtarg):
		if (-f $(errtarg)) rm $(errtarg)
main.o:		main.c $(bibdep)
		$(CC) $(CFLAGS) -o=main.o main.c >> $(errtarg)
