#define SELECTOR 0  	/* TREE */
#define ALERT 1  	/* TREE */
#define SCRLBAR 36  	/* OBJECT in TREE #0 */
#define FSVELEV 39  	/* OBJECT in TREE #0 */
#define FSVSLID 38  	/* OBJECT in TREE #0 */
#define FUPAROW 40  	/* OBJECT in TREE #0 */
#define FDNAROW 37  	/* OBJECT in TREE #0 */
#define FILEBOX 26  	/* OBJECT in TREE #0 */
#define FTITLE 8  	/* OBJECT in TREE #0 */
#define FSELECTI 5  	/* OBJECT in TREE #0 */
#define FCLSBOX 7  	/* OBJECT in TREE #0 */
#define F1NAME 27  	/* OBJECT in TREE #0 */
#define F2NAME 28  	/* OBJECT in TREE #0 */
#define F3NAME 29  	/* OBJECT in TREE #0 */
#define F4NAME 30  	/* OBJECT in TREE #0 */
#define F5NAME 31  	/* OBJECT in TREE #0 */
#define F6NAME 32  	/* OBJECT in TREE #0 */
#define F7NAME 33  	/* OBJECT in TREE #0 */
#define F8NAME 34  	/* OBJECT in TREE #0 */
#define F9NAME 35  	/* OBJECT in TREE #0 */
#define OK 41  	/* OBJECT in TREE #0 */
#define CANCEL 42  	/* OBJECT in TREE #0 */
#define FDIRECTO 3  	/* OBJECT in TREE #0 */
#define DRIVEA 10  	/* OBJECT in TREE #0 */
#define DRIVEB 11  	/* OBJECT in TREE #0 */
#define DRIVEC 12  	/* OBJECT in TREE #0 */
#define DRIVED 13  	/* OBJECT in TREE #0 */
#define DRIVEE 14  	/* OBJECT in TREE #0 */
#define DRIVEF 15  	/* OBJECT in TREE #0 */
#define DRIVEG 16  	/* OBJECT in TREE #0 */
#define DRIVEH 17  	/* OBJECT in TREE #0 */
#define DRIVEI 18  	/* OBJECT in TREE #0 */
#define DRIVEJ 19  	/* OBJECT in TREE #0 */
#define DRIVEK 20  	/* OBJECT in TREE #0 */
#define DRIVEL 21  	/* OBJECT in TREE #0 */
#define DRIVEM 22  	/* OBJECT in TREE #0 */
#define DRIVEN 23  	/* OBJECT in TREE #0 */
#define DRIVEO 24  	/* OBJECT in TREE #0 */
#define DRIVEP 25  	/* OBJECT in TREE #0 */
#define FLABEL 1  	/* OBJECT in TREE #0 */
#define DRVBOX 9  	/* OBJECT in TREE #0 */
