#define DIALOG 0  	/* TREE */
#define PINFO 1  	/* TREE */
#define COUNTDOW 2  	/* TREE */
#define MINFO 2  	/* OBJECT in TREE #0 */
#define MDATEI 3  	/* OBJECT in TREE #0 */
#define MCDOWN 4  	/* OBJECT in TREE #0 */
#define DATUM 5  	/* OBJECT in TREE #0 */
#define SENSITIV 6  	/* OBJECT in TREE #0 */
#define DINFO 7  	/* OBJECT in TREE #0 */
#define DDATEI 8  	/* OBJECT in TREE #0 */
#define DCDOWN 9  	/* OBJECT in TREE #0 */
#define Z1 11  	/* OBJECT in TREE #0 */
#define Z2 19  	/* OBJECT in TREE #0 */
#define Z3 27  	/* OBJECT in TREE #0 */
#define Z4 35  	/* OBJECT in TREE #0 */
#define P1 42  	/* OBJECT in TREE #0 */
#define P2 43  	/* OBJECT in TREE #0 */
#define SEK10 3  	/* OBJECT in TREE #2 */
#define SEK20 4  	/* OBJECT in TREE #2 */
#define SEK30 5  	/* OBJECT in TREE #2 */
