#
# Program: Rayscene
# Makefile by Jari K„hk”nen

.c.obj:
          cl -AM -Ox -c -DIBMPC $*.c

rayscene.obj : rayscene.c

readval.obj : readval.c

script.obj : script.c

Rayscene.exe : rayscene.obj readval.obj script.obj 
	del Rayscene.lnk
	echo rayscene.obj+ >>Rayscene.lnk
	echo readval.obj+ >>Rayscene.lnk
	echo script.obj  >>Rayscene.lnk
	echo Rayscene.exe >>Rayscene.lnk
	echo Rayscene.map >>Rayscene.lnk
	link @Rayscene.lnk /NOI $(LDFLAGS);
