OBJS = cl.o clutil.o
mclock.acc : $(OBJS)
	cc -VPEEP -VSMALL -o mclock.acc $(OBJS) -VGEMACC
	strip mclock.acc

cl.o : cl.c
	cc $(CFLAGS) -VPEEP -VSMALL cl.c
clutil.o : clutil.s
	mac -fmu clutil.s
