#
# Makefile for the optimizer
#

OBJ =	main.o io.o util.o sym.o func.o branch.o inst.o opcodes.o \
	peep.o health.o data.o

CFLAGS = -O

xtop.ttp : $(OBJ)
	cc $(OBJ) -o xtop.ttp

clean:
	$(RM) *.o

clobber:
	$(RM) *.o xtop.ttp
