# BloufGate makefile for MicroSoft WIN32 SDK
#  nmake nodebug=1 for release version
!include <ntwin32.mak>

all: blouf.exe nlist.exe

blouf.exe: ufg.obj fug.obj config.obj misc.obj address.obj pkt.obj \
	global.obj main.obj killdupe.obj
  $(link) $(linkdebug) $(conflags) -out:$*.exe $** $(conlibs)

nlist.exe: nlist.obj
  $(link) $(linkdebug) $(conflags) -out:$*.exe $** $(conlibs)

clean:
  del *.obj
  del *.exe
  del *.bak

.c.obj:
  $(cc) $(cdebug) $(cflags) $(cvars) $*.c

