OBJS = parser.o scanner.o hash.o
YACC = byacc
LEX = flex
CFLAGS = -O
YFLAGS = -d
TARGET = mit2mot.ttp

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

parser.o y.tab.h: parser.y 
	$(YACC) -d parser.y
	$(CP) ytab.c parser.c
	$(CC) $(CFLAGS) -c parser.c
	$(RM) ytab.c parser.c

scanner.o: scanner.l
	$(LEX) scanner.l
	$(CP) lexyy.c scanner.c
	$(CC) $(CFLAGS) -c scanner.c
	$(RM) lexyy.c scanner.c

scanner.o hash.o: global.h ytab.h
parser.o: global.h patchlev.h

clean:
	rm $(OBJS) ytab.h
