#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c
.s.o:
	mac $(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	g:\bin\cp68.prg $(CFLAGS) $*.c l:$*.i
	g:\bin\c068.prg l:$*.i l:$*.1 l:$*.2 l:$*.3 -f
	rm l:$*.i
	g:\bin\c168.prg l:$*.1 l:$*.2 l:$*.s
	g:\bin\mac.prg -6 -o $*.o l:$*.s
	rm l:$*.1 l:$*.2 l:$*.s

TEMP = :tmp
LIBS = vdibind aesbind gemlib libf

OBJS =	gemstart.o osbind.o  mymalloc.o\
	addr.o stepart.o error.o getstart.o hdx.o\
	mediach.o sect.o\
	epart.o acsi.o scsi.o doit.o cmdblk.o check.o 68030.o\
	ide.o cookie.o spscsi.o myas.o

hdxpch.prg : $(OBJS)
	echo $(OBJS) $(LIBS) >$(TEMP)
	aln -s -o hdxpch.prg -c $(TEMP)


#
#  assembly-language files
#
acsi.o		: acsi.s
scsi.o		: scsi.s
cmdblk.o	: cmdblk.s
doit.o		: doit.s
check.o		: check.s
ide.o		: ide.s
68030.o		: 68030.s
gemstart.o 	: gemstart.s
mymalloc.o 	: mymalloc.s
osbind.o 	: osbind.s
cookie.o	: cookie.s
spscsi.o	: spscsi.s
myas.o		: myas.s

#
#  C sources
#
addr.o 		: addr.c
stepart.o 	: stepart.c
epart.o 	: epart.c
error.o 	: error.c
getstart.o 	: getstart.c
hdx.o 		: hdx.c
sect.o 		: sect.c
