### 	Makefile

COPTS	=       -cf -v #-O
CMODEL	=	-w -r0 -b0
CREFS	=	
DEFINES =	
LMODEL	=	snb
LDOPTS  =       -N -td -Lanbg #-Lanbg   
#
CFLAGS	=	$(COPTS) $(CMODEL) $(CREFS) $(DEFINES)
ASFLAGS =
LDFLAGS =	$(COPTS) $(CMODEL) $(LDOPTS)
MAPOPTS =	#MAP $*.map

MENUTOOL  =	test.o menubind.o crysif.o crystal.o

.s.o:
	mac $*.s
	dr2lc $@

demo.prg:	$(MENUTOOL)
				lcc $(LDFLAGS)=$@ $(MENUTOOL)
				@gstfix $@

test.o:		mn_tools.h menubind.h demo.h 
menubind.o:
crysif.o:
crystal.o:
