/* resource set indicies for WND2XMPL */

#define MENUTREE 0	/* menu tree */
#define MENUDESK 3	/* TITLE in tree MENUTREE */
#define MENUFILE 4	/* TITLE in tree MENUTREE */
#define MENUINFO 7	/* STRING in tree MENUTREE */
#define MENUQUIT 16	/* STRING in tree MENUTREE */

#define WINDTREE 1	/* form/dialog */
#define WINDPBTH 1	/* BOX in tree WINDTREE */
#define WINDPBRB 2	/* IBOX in tree WINDTREE */
#define WINDBRME 3	/* BUTTON in tree WINDTREE */
#define WINDBRSL 4	/* BUTTON in tree WINDTREE */
#define WINDBRFA 5	/* BUTTON in tree WINDTREE */
#define WINDICI2 6	/* ICON in tree WINDTREE */
#define WINDICI1 7	/* ICON in tree WINDTREE */
#define WINDPBXB 8	/* IBOX in tree WINDTREE */
#define WINDBXSP 9	/* BUTTON in tree WINDTREE */
#define WINDBXPA 10	/* BUTTON in tree WINDTREE */
#define WINDBXGO 11	/* BUTTON in tree WINDTREE */

