# Makefile for ScoreST
# phil comeau 19-apr-88
# last edited 14-oct-89

INCL = .
LIB = \lib
DEBUG = 

OBJECTS = dialog.o edit.o entity.o file.o graph.o list.o menu.o option.o \
	page.o printer.o scorest.o select.o symbol.o util.o version.o vwk.o \
	window.o
.c.o:
	$(CC) -c $(DEBUG) -I$(INCL) $*.c

scorest.prg: $(OBJECTS)
	$(CC) $(DEBUG) -o scorest.prg $(OBJECTS)

instsst.tos: instsst.o
	$(CC) $(DEBUG) -o instsst.tos instsst.o version.o

dialog.o scorest.o page.o option.o file.o: dialog.h

list.o scorest.o page.o entity.o edit.o select.o: list.h

scorest.o window.o page.o menu.o symbol.o graph.o entity.o file.o edit.o \
	option.o select.o instsst.o: graph.h

scorest.o window.o page.o symbol.o entity.o file.o printer.o select.o \
	instsst.o: scoredef.h

scorest.o page.o symbol.o entity.o edit.o select.o: symbol.h

scorest.o page.o symbol.o entity.o edit.o select.o: entity.h

scorest.o page.o menu.o symbol.o option.o: scorest.h

scorest.o menu.o file.o edit.o option.o select.o: menu.h

scorest.o printer.o instsst.o: config.h

page.o select.o: page.h

edit.o entity.o file.o graph.o menu.o option.o page.o scorest.o select.o \
	symbol.o window.o vwk.o: graphics.h
