/* Indice du ressource pour FUN__30F */

#define FMAIN    0   /* Formulaire/Dialogue */
#define VLI      2   /* FBOXTEXT dans l'arbre FMAIN */
#define VRI      3   /* FBOXTEXT dans l'arbre FMAIN */
#define VLO      4   /* FBOXTEXT dans l'arbre FMAIN */
#define VRO      5   /* FBOXTEXT dans l'arbre FMAIN */
#define VUMETERL 8   /* IBOX dans l'arbre FMAIN */
#define LN4      9   /* BOX dans l'arbre FMAIN */
#define LN6      10  /* BOX dans l'arbre FMAIN */
#define LN7      11  /* BOX dans l'arbre FMAIN */
#define LN9      12  /* BOX dans l'arbre FMAIN */
#define LN5      13  /* BOX dans l'arbre FMAIN */
#define LN8      14  /* BOX dans l'arbre FMAIN */
#define LN3      15  /* BOX dans l'arbre FMAIN */
#define LN2      16  /* BOX dans l'arbre FMAIN */
#define LN1      17  /* BOX dans l'arbre FMAIN */
#define LN0      18  /* BOX dans l'arbre FMAIN */
#define VUMETERR 19  /* IBOX dans l'arbre FMAIN */
#define RN0      20  /* BOX dans l'arbre FMAIN */
#define RN1      21  /* BOX dans l'arbre FMAIN */
#define RN3      22  /* BOX dans l'arbre FMAIN */
#define RN4      23  /* BOX dans l'arbre FMAIN */
#define RN5      24  /* BOX dans l'arbre FMAIN */
#define RN7      25  /* BOX dans l'arbre FMAIN */
#define RN8      26  /* BOX dans l'arbre FMAIN */
#define RN6      27  /* BOX dans l'arbre FMAIN */
#define RN2      28  /* BOX dans l'arbre FMAIN */
#define RN9      29  /* BOX dans l'arbre FMAIN */
#define BOITERO  47  /* USERDEF dans l'arbre FMAIN */
#define CURSORRO 48  /* USERDEF dans l'arbre FMAIN */
#define BOITELO  49  /* USERDEF dans l'arbre FMAIN */
#define CURSORLO 50  /* USERDEF dans l'arbre FMAIN */
#define BOITERI  51  /* USERDEF dans l'arbre FMAIN */
#define CURSORRI 52  /* USERDEF dans l'arbre FMAIN */
#define BOITELI  53  /* USERDEF dans l'arbre FMAIN */
#define CURSORLI 54  /* USERDEF dans l'arbre FMAIN */
#define BDSP     60  /* USERDEF dans l'arbre FMAIN */
#define BPLAY    61  /* USERDEF dans l'arbre FMAIN */
#define BSTOP    62  /* USERDEF dans l'arbre FMAIN */
#define LEFT     63  /* USERDEF dans l'arbre FMAIN */
#define RIGHT    64  /* USERDEF dans l'arbre FMAIN */
#define QUITTER  65  /* USERDEF dans l'arbre FMAIN */

#define FINFO    1   /* Formulaire/Dialogue */
#define PHOTO    4   /* IMAGE dans l'arbre FINFO */
#define VERSION  6   /* FTEXT dans l'arbre FINFO */
#define DATEVER  7   /* FTEXT dans l'arbre FINFO */
#define FORM2EXIT 8   /* BUTTON dans l'arbre FINFO */

#define IINFO    2   /* Formulaire/Dialogue */

#define IAPPLI   3   /* Formulaire/Dialogue */

#define IMAIN    4   /* Formulaire/Dialogue */

#define MAINMENU 5   /* Arbre menu */
#define ABOUT    7   /* STRING dans l'arbre MAINMENU */
#define ENDE     16  /* STRING dans l'arbre MAINMENU */
