REM FILENAME = BILDO4.BAT FUNCTION =  BUILD & FORMAT 3.5" DISKETTE
C:
C:\DSKFMT
CD BIOSSRC
COPY @OEM4A.PRN A:
CD ..
CD BDOSOBJ
COPY @OEM4B.PRN A:
CD ..
REN A:INSTO4.BAT A:INSTALL.BAT
REM TRANSFER COMPLETED; ENTER THE APPLE KEY AND NUMERIC ENTER KEY TO
REM EJECT DISKETTE;
REM LABEL DISKETTE WITH A RED COLORED DISKETTE PAPER LABEL;
REM LABEL DISKETTE WITH A PRINTED LABEL FOR OEM , DISKETTE # 4
