REM FILENAME = BILDO1.BAT FUNCTION = BUILD & FORMAT 3.5" DISKETTE
C:
C:\DSKFMT
CD C:\
COPY C:\GEMDOSFI.SYS A:
COPY @OEM1.PRN A:
PUTBOOT A: SFBOOT.ABS
REN A:INSTO1.BAT A:INSTALL.BAT
REM TRANSFER COMPLETED; ENTER THE APPLE KEY AND NUMERIC ENTER KEY TO
REM EJECT DISKETTE;
REM LABEL DISKETTE WITH A BLUE COLORED DISKETTE PAPER LABEL;
REM LABEL DISKETTE WITH A PRINTED LABEL FOR OEM , DISKETTE # 1
