REM FILENAME INSTO3.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE SCRNDRV, MINCE AND ROOT SUBDIRECTORIES.
C:
CD C:\
MD SCRNDRV
A:
COPY @A:OEM3A.PRN C:\SCRNDRV
C:
MD MINCE
A:
COPY @A:OEM3B.PRN C:\MINCE
COPY A:MNCE.SWP C:\
C:
MD SYSBLD
A:
COPY @A:OEM3C.PRN C:\SYSBLD
C:
MD DUPINFO
A:
COPY @A:OEM3D.PRN C:\DUPINFO
COPY A:RELNOTES.PRN C:\
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
