REM FILENAME INSTO1.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE C:\ SUBDIRECTORY.
REM THIS OPERATION WILL DESTROY ANY DATA CURRENTLY ON YOUR HARD DISK!!
REM ENTER APPLEKEY AND C KEY (^C) TO ABORT
REM PRESS ANY OTHER KEY TO CONTINUE WITH HARD DISK INITIALIZATION.
PAUSE
INIT C:
COPY A:GEMDOSHI.SYS C:\
COPY A:GEMDOSHI.SYS C:\SPAREOS.SYS
PUTBOOT C: HBOOT.ABS
A:
COPY @A:OEM1.PRN C:\
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
