REM FILENAME INSTI3.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE RUNTIME SUBDIRECTORY.
C:
CD C:\
MD RUNTIME
A:
COPY @A:ISV3.PRN C:\RUNTIME
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
