OBJS = main.o input.o process.o utils.o comment.o token.o ztype.o \
       pound.o include.o hash.o macro.o define.o if_expr.o
SRCS = main.c input.c process.c utils.c comment.c token.c ztype.c \
       pound.c include.c hash.c macro.c define.c if_expr.c
TARGET = cpp.ttp
#CFLAGS = -O -DDBMALLOC
#CFLAGS = -O -DFAST -DQUERY
#CFLAGS = -8 -DDEBUG
#CFLAGS = -8 -O $(DEBUG)
CFLAGS = -O
#LDFLAGS = -8
LDFLAGS =

$(TARGET): $(OBJS)
	$(CC) -o $(TARGET) $(LDFLAGS) $(OBJS)

$(OBJS): global.h
main.o utils.o token.o ztype.o if_expr.o: ztype.h
main.o: patchlev.h

clean:
	rm $(TARGET) $(OBJS)

pretty:
	indent -T Token -T Hash -T Macro -T Directive  -T Long $(SRCS)
