#define STING 0  	/* TREE */
#define WHOLE 1  	/* OBJECT in TREE #0 */
#define VERSION 3  	/* OBJECT in TREE #0 */
#define PROTOCOL 4  	/* OBJECT in TREE #0 */
#define ICMP_BOX 5  	/* OBJECT in TREE #0 */
#define I_AMC 7  	/* OBJECT in TREE #0 */
#define I_RA 10  	/* OBJECT in TREE #0 */
#define I_RA_ED 11  	/* OBJECT in TREE #0 */
#define I_LAG 12  	/* OBJECT in TREE #0 */
#define TCP_BOX 13  	/* OBJECT in TREE #0 */
#define MSS 14  	/* OBJECT in TREE #0 */
#define RCV_WIN 15  	/* OBJECT in TREE #0 */
#define T_PORT 16  	/* OBJECT in TREE #0 */
#define DEF_TTL 17  	/* OBJECT in TREE #0 */
#define RTT_INIT 18  	/* OBJECT in TREE #0 */
#define T_ICMP 20  	/* OBJECT in TREE #0 */
#define UDP_BOX 22  	/* OBJECT in TREE #0 */
#define U_PORT 23  	/* OBJECT in TREE #0 */
#define U_ICMP 25  	/* OBJECT in TREE #0 */
#define DNS_BOX 27  	/* OBJECT in TREE #0 */
#define DNS_PREV 30  	/* OBJECT in TREE #0 */
#define DNS_IP 31  	/* OBJECT in TREE #0 */
#define DNS_NEXT 32  	/* OBJECT in TREE #0 */
#define DNS_DOM 34  	/* OBJECT in TREE #0 */
#define DNS_CSZ 36  	/* OBJECT in TREE #0 */
#define DNS_CSV 37  	/* OBJECT in TREE #0 */
#define SAVE 40  	/* OBJECT in TREE #0 */
#define SET 42  	/* OBJECT in TREE #0 */
#define CANCEL 43  	/* OBJECT in TREE #0 */
