.TH MIT2MOT 1 "May\ 30,\ 1993"
.UC 6
.SH NAME
mit2mot \- comvert assembler files from MIT to Motorola syntax
.SH SYNOPSIS
.B mit2mot
[
.B -o
.I outfile
]
.I filename
.SH DESCRIPTION
.I Mit2mot
translates 68000 assembly code from MIT syntax, as used by GCC's
.IR gas ,
into Motorola syntax, which can be assembled by HSC and most other Atari
C compilers.  MIT-style comments of the form:
.IP
\&| This is a comment.
.PP
are stripped out.
.SH OPTIONS
Only one option is available:
.RS
.IP \fB-o\fR outfile
Specifies the output file, a la
.IR cc .
By default, output goes to a file with the same base name as the input
file and extension
.BR \&.s .
.RE
.SH DIAGNOSTICS
.IP "Unsupported assembler directive"
The file used a GCC assembler directive that either doesn't have an
equivalent in Motorola syntax or
.I mit2mot
doesn't know how to translate.
.SH BUGS
None that I know of.  The assembler-directive translation may be a bit
HSC-specific, but I don't think that will be a problem.  As always,
please report any bugs you find to me, Scott Bigham, at dsb@cs.duke.edu.
