OBJECTS=	errexit.o chkalloc.o scratt.o degas.o sprites.o\
		getsprit.o pinball.o
		 
LDFLAGS=	-t aesfast.a vdifast.a
CFLAGS=		-O

pinball.prg:	$(OBJECTS)
		$(CC) $(LDFLAGS) $(OBJECTS) -o pinball.prg 
