REM FILENAME INSTI2.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE KERMIT SUBDIRECTORY.
C:
CD C:\
MD KERMIT
A:
COPY @A:ISV2.PRN C:\KERMIT
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
