#undef A_R_DISCONNECT
#undef A_R_GOT_IGNRESIDUE
#undef A_R_GOT_SDTR
#undef A_R_GOT_WDTR
#undef A_R_MSGREJECT
#undef A_R_NEEDMORE
#undef A_R_NOSELECT
#undef A_R_OK
#undef A_R_SENDREJECT
#undef A_R_TEST
#undef A_R_TEST2
#undef A_R_TRACE
#undef A_R_UNKNMESSAGE
#undef A_R_UNKNPHASE
#undef A_STATE_GOT_MSGIN
#undef A_d_command
#undef A_d_data0
#undef A_d_data1
#undef A_d_data2
#undef A_d_data3
#undef A_d_data4
#undef A_d_data5
#undef A_d_data6
#undef A_d_data7
#undef A_d_msgout
#undef A_d_select
#undef A_d_unused
#undef A_d_unused1
#undef Ent_Command
#undef Ent_Dispatch
#undef Ent_Test1
#undef Ent_Test2
#undef Ent_cleanup_data
#undef Ent_cmd2
#undef Ent_data_in
#undef Ent_data_in_end
#undef Ent_data_out
#undef Ent_data_out_end
#undef Ent_wait_reselect
