#	Makefile for c68 (TOS version)
#--------------------------------------------------------
# Use the following if compiling c68/c386 with c68
CC= cc68x
#LDFLAGS= -g
#--------------------------------------------------------
# Use the following if compiling c68 with SozobonX
# CC= cc --mint -UMC68000
# LDFLAGS=
#--------------------------------------------------------

CFLAGS= -O -DNDEBUG -DTRAP_GEN

HDR = 	chdr.h cglbdec.h expr.h gen.h version.h config.h

#	Object files common to all c68/c386 variants
OBJ=	analyze.o cglbdef.o cmain.o decl.o expr.o extern.o genicode.o \
	genieee.o genstmt.o genutil.o getsym.o init.o intexpr.o list.o \
	memmgt.o msgout.o optimize.o outgen.o stmt.o symbol.o

#	Object files specific to Motorola 680X0 variants
OBJ68K=	gen68k.o peep68k.o reg68k.o out68k_jas.o out68k_ack.o \
	out68k_cpm.o out68k_gas.o out68k_qmc.o

c68.ttp: $(OBJ) $(OBJ68K)
	 $(CC) $(LDFLAGS) -o $@ $^ -liio

clean:
	$(RM) c68.ttp $(OBJ) $(OBJ68K)

$(OBJ):		$(HDR)
$(OBJ68K):	$(HDR)
