COPTS	=       -cf -cu
CMODEL	=	-w -r0 -b0
CREFS	=	
DEFINES =	
LMODEL	=	snb
LDOPTS  =       -N -Lanbg #-td   
#
CFLAGS	=	$(COPTS) $(CMODEL) $(CREFS) $(DEFINES)
LDFLAGS =	$(COPTS) $(CMODEL) $(LDOPTS)

.c.o:
	lc -c $(CFLAGS) -o$@ $<


.s.o:
	mac $*.s
	dr2lc $@


loser1 = appl_reg.o appl_nam.o wind_sst.o shel_gro.o
loser2 = wind_gwo.o wind_bev.o evnt_emu.o wind_gre.o _aes.o
windows_OBJ = textwind.o iconwind.o windows.o gemutil.o
viewer_OBJ = viewer.o $(windows_OBJ) version.o $(loser1) $(loser2)



viewer.app: $(viewer_OBJ)

	lc $(LDFLAGS)=$@ $(viewer_OBJ)
	@gstfix $@

### Dependencies

version.o: viewer.o $(windows_OBJ)
gemutil.o: gemutil.h
textwind.o: gemutil.h windows.h textwind.h
windows.o: gemutil.h windows.h
viewer.o: gemutil.h windows.h textwind.h
appl_reg.o:
appl_nam.o:
wind_sst.o:
shel_gro.o:
wind_gwo.o:
wind_bev.o:
evnt_emu.o:
wind_gre.o:
_aes.o:
