#
# Makefile for jas
#
# 040590 Jan Bolt
#

CC      = cc
CFLAGS  = -c -O

.c.o :
	$(CC) $(CFLAGS) $<

OFILES = cbuf.o cpy.o gen.o hdr.o lex.o main.o ops.o opt.o \
parse.o pass.o scan.o sym.o

jas.ttp: $(OFILES)
	$(CC) -o jas.ttp $(OFILES)

cbuf.o: jas.h
cpy.o: jas.h
gen.o: jas.h
hdr.o: jas.h
lex.o: jas.h scan.h parse.h
main.o: jas.h
ops.o: jas.h opcodes.h
opt.o: jas.h
parse.o: jas.h parse.h
pass.o: jas.h
scan.o: jas.h scan.h parse.h
sym.o: jas.h

clean:
	$(RM) $(OFILES)

clobber:
	$(RM) $(OFILES) jas.ttp

