/* *  WinTimer *  WinDom extension to support multi timer event */
#include <stdlib.h>
#include <windom.h>typedef struct xtimer{  unsigned long timer;  void (*func)( long, WINDOW *);  WINDOW *win;  struct xtimer *next;} XTIMER;static XTIMER *root = NULL;static unsigned long timer_time = 0L;
/* fonction standard pour MU_TIMER (priv‚e) */
staticvoid std_xtimer( void) {  XTIMER *scan;  if( timer_time) {	for( scan = root; scan; scan = scan->next) {	  if( (timer_time % scan->timer) == 0 && scan->func)		(*scan->func)( timer_time, scan->win);	}  }  timer_time += evnt.timer;}/* Publique  *//* Init Timer */void TimerInit( long slice_timer) {  evnt.timer = slice_timer;
  EvntAttach( NULL, WM_XTIMER, std_xtimer);}/* Attacher une fonction … une fenetre et un temps : ajout mutliple possible */int TimerAttach( WINDOW *win, int timer, void *func) {  XTIMER *scan, *new = malloc( sizeof(XTIMER));  if( !new) return -69;  new -> timer = timer;  new -> win = win;  new -> func = func;  /* classement par timer */    if( root == NULL || timer < root->timer) {	new -> next = root;	root = new;  } else {	for( scan = root; scan->next && timer < scan->next->timer; scan = scan->next);	if( scan->next &&  timer < scan->next->timer)	  new -> next = scan -> next;    else	  new -> next = NULL;	scan -> next = new;  }  return 0;}/* Supprimer toutes les fontions d'un event Xtimer */int TimerDelete( WINDOW *win, int timer) {  XTIMER *scan, *del;  /* cas racine */  while( root && root->timer == timer && root->win == win) {	scan = root->next;	free(root);	root = scan;  }  /* sinon recherche premier ‚l‚ment */  for( scan=root; scan->next && timer != scan->next->timer 
  				 && scan->next->win == win ; scan = scan->next);  /* suppression elements */  while( scan->next && scan->next->timer == timer
  		 && scan->next->win == win) {	del = scan->next;	free(scan);	scan = del;  }
  return 0;}/* Supprimer tous les Xtimer */void TimerExit( void) {  XTIMER *scan, *del;    scan = root;  while( scan) {	del = scan->next;	free(scan);	scan = del;  }  root = NULL;  EvntDelete( NULL, WM_XTIMER);}
/* EOF */