/* Resource Datei Indizes fÅr MOUS_RSC */

#define MAIN     0   /* Formular/Dialog */
#define M_TITLE  1   /* BOXTEXT in Baum MAIN */
#define M_MS_ONOFF 3   /* BOXTEXT in Baum MAIN */
#define M_MOUSESPEEDER 4   /* STRING in Baum MAIN */
#define M_SUB1   5   /* BOX in Baum MAIN */
#define M_PAGE2  6   /* IMAGE in Baum MAIN */
#define M_MOUSEBUTTON 7   /* STRING in Baum MAIN */
#define M_MS_BUTTONSWAP 8   /* BOXTEXT in Baum MAIN */
#define M_ROTATION 9   /* FTEXT in Baum MAIN */
#define M_MRESOLUTION 10  /* FTEXT in Baum MAIN */
#define M_POLYNOMEDIT 11  /* BUTTON in Baum MAIN */
#define M_SUB2   12  /* BOX in Baum MAIN */
#define M_PAGE1  13  /* IMAGE in Baum MAIN */
#define M_ASPECTRATIO 14  /* FTEXT in Baum MAIN */
#define M_SRESOLUTION 15  /* FTEXT in Baum MAIN */
#define M_LANGTITLE 16  /* STRING in Baum MAIN */
#define M_LANGUAGE 17  /* BOXTEXT in Baum MAIN */
#define M_AUTOMATIC 18  /* BUTTON in Baum MAIN */
#define M_SAVE   20  /* BUTTON in Baum MAIN */
#define M_OK     22  /* BUTTON in Baum MAIN */
#define M_ABORT  23  /* BUTTON in Baum MAIN */

#define POLY_ED  1   /* Formular/Dialog */
#define P_TITLE  1   /* BOXTEXT in Baum POLY_ED */
#define P_EDITFIELD 2   /* BOX in Baum POLY_ED */
#define P_ZEROLINE 3   /* IBOX in Baum POLY_ED */
#define P_P1     4   /* IBOX in Baum POLY_ED */
#define P_P2     5   /* IBOX in Baum POLY_ED */
#define P_P3     6   /* IBOX in Baum POLY_ED */
#define P_PRESETPOPUP 8   /* BOXTEXT in Baum POLY_ED */
#define P_PRESETS 9   /* TEXT in Baum POLY_ED */
#define P_POLYFACBOX 10  /* BOX in Baum POLY_ED */
#define P_POLYFACTORS 11  /* TEXT in Baum POLY_ED */
#define P_PF1    12  /* FTEXT in Baum POLY_ED */
#define P_PF2    13  /* FTEXT in Baum POLY_ED */
#define P_PF3    14  /* FTEXT in Baum POLY_ED */
#define P_OK     20  /* BUTTON in Baum POLY_ED */
#define P_ABORT  21  /* BUTTON in Baum POLY_ED */
