.\" dummy line
.TH SCM "14 July 1991"
.UC 4
.SH NAME
scm \- a Scheme Language Interpreter
.SH SYNOPSIS
.B scm
[arg ...]
.br
.SH DESCRIPTION
.I Scm 
is an interactive Scheme interpreter.
.PP
If ScmInit.scm exists in (getenv "HOME") directory then it is loaded;
otherwise, each arg is given to LOAD in the order specified.
.I Scm
then evaluates and prints all expressions typed into it.
.PP
Here are some of
.I scm's
features:
.PP
Runs under Amiga, Atari-ST, MacOS, MS-DOS, NOS/VE, VMS, Unix and
similar systems.
.PP
Conforms to Revised^4 Report on the Algorithmic Language Scheme
and the IEEE P1178 specification.
.PP
Enchancements to support files open for simultaneous reading and writing.
.PP
Setable levels of monitoring and timing information printed
interactively (the `verbose' function).
.PP
User definable responses to interrupts and errors.
.PP
open-pipe, close-pipe, open-file, close-file, file-exists?,
force-output, chdir, alarm, system, quit, program-arguments, getenv,
tmpnam, software-type, ed, abort, line-number, get-decoded-time,
get-internal-run-time, get-internal-real-time, substring-move-left!,
substring-move-right!, substring-fill!, object-hash, object-unhash,
delete-file, rename-file, and try-load functions.
.PP
*Features* and *load-pathname* variables.
.PP
char-code-limit, most-positive-fixnum, most-negative-fixnum,
and internal-time-units-per-second constants.
.PP
Support for ASCII and EBCDIC character sets.
.PP
Documentation on the internal representation and how to extend or
include scm in other programs (code.doc in the source directory).
.SH AUTHOR
Aubrey Jaffer
.br
(jaffer@ai.mit.edu)
.SH BUGS
Integers larger than 30 bits are not supported.
.SH SEE ALSO
The Scheme specifications for details on specific procedures
(altorf.ai.mit.edu:archive/scheme-reports/) or
.PP
IEEE Std 1178-1990,
.br
IEEE Standard for the Scheme Programming Language,
.br
Institute of Electrical and Electronic Engineers, Inc.,
.br
New York, NY, 1991
.PP
R. Kent Dybvig, The Scheme Programming Language,
.br
Prentice-Hall Inc, Englewood Cliffs, New Jersey 07632, USA
.PP
H. Abelson, G. J. Sussman, and J. Sussman,
.br
Structure and Interpretation of Computer Programs,
.br
The MIT Press, Cambridge, Massachusetts, USA
.PP
Enchancements in
.I scm
not in the standards are detailed in MANUAL in the source directory.
