driver3.bin: null.obj driasm.obj driver3.obj scsi.obj makefile
	tlink /m null.obj driasm.obj driver3.obj scsi.obj ,driver3.exe,,\turboc\lib\cs
	exe2bin driver3.exe driver3.bin
	del driver3.exe

driver3.obj:	driver3.c driver.h scsi.h makefile
	tcc -c -mt -r- driver3.c

driver3.asm:	driver3.c driver.h scsi.h makefile
	tcc -S -mt -r- driver3.c

scsi.obj:	scsi.c scsi.h makefile
	tcc -c -mt scsi.c

null.obj:	null.c driver.h makefile
	tcc -c -mt null.c

driasm.obj:		driasm.s dheader.s
	masm driasm.s,driasm.obj,nul.lst,nul.crf

dtest:  null.obj driasm.obj driver3.obj makefile
    tcc -mt -odtest null.obj driasm.obj driver3.obj dtest.c
