.TH SUNCLOCK 1 "21 DEC 1988"
.UC 4
.SH NAME
sunclock \- Show illuminated portion of Earth
.SH SYNOPSIS
.B sunclock
.SH DESCRIPTION
.I sunclock
is a SunView application that displays a map of the Earth and
indicates the illuminated portion of the globe by drawing
sunlit areas dark on light, night areas as light on dark.
.PP
The program initially appears iconic, showing a small map in a
126 by 63 pixel double-sized icon with the local date and time
at the bottom.  If opened, a 640 by 320 pixel map is displayed
which shows both the local and Universal (GMT) time to the second.
While the window is open, pressing the right mouse button displays
a menu which lets you step the clock from the present time forward
or backward in increments of one hour, day, week, month, or year.
If you select ``Animate'' from this menu, the program steps continuously
every half second.  Try selecting ``Week'' then ``Animate'' to watch
the seasons pass.  Select ``Year'' and ``Animate'' and you can see the
(ever so subtle) precession of the equinoxes.  Selecting ``Real time''
restores the current time display.
.SH HOW IT WORKS
.I sunclock
calculates the position of the Sun using the algorithm in chapter 18 of:
.PP
.I Astronomical Formulae for Calculators
by Jean Meeus, Third Edition, Richmond: Willmann-Bell, 1985.
.PP
and Mercator projects the illuminated area onto map image.  The
Sun's position is calculated to better than one arc-second
in accuracy.
.SH BUGS
The map isn't rescaled if you resize the open window.  (I don't want
to have to store a vector database for the map.)
.PP
The illuminated area shown is the area which would be sunlit
if the Earth had no atmosphere.  The actual illuminated area is
larger because of atmospheric refraction and twilight.
.PP
Only works for dates between 1970 and 2034 due to limited range of Unix
time representation.
.SH AUTHOR
    John Walker
.br
    Autodesk, Inc.
.br
    2320 Marinship Way
.br
    Sausalito, CA  94965
.br
    USA
.br
    {sun,well,uunet}!acad!kelvin
.br
or: kelvin@acad.uu.net
.br
    Fax:   (415) 389-9418
.br
    Voice: (415) 332-2344 Ext. 2829
