#
# Makefile for CHESS
#
# Copyright (C) 1986, 1987, 1988, 1989, 1990 Free Software Foundation, Inc.
#
# This file is part of CHESS.
#
# CHESS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY.  No author or distributor
# accepts responsibility to anyone for the consequences of using it
# or for whether it serves any particular purpose or works at all,
# unless he says so in writing.  Refer to the CHESS General Public
# License for full details.
#
# Everyone is granted permission to copy, modify and redistribute
# CHESS, but only under the conditions described in the
# CHESS General Public License.   A copy of this license is
# supposed to have been given to you along with CHESS so you
# can know your rights and responsibilities.  It should be in a
# file named COPYING.  Among other things, the copyright notice
# and this notice must be preserved on all copies.
#
# gnuchess.prg  will be the Atari GEM-based chess.
#
# If you want to use the persistent transpositon table add
# -DHASHFILE=\"$(LIBDIR)/gnuchess.hash\"
# to the gnuchess.o compilation line. You also have to run gnuchess -t
# To actually create the file. -t can also be used to report
# statistics about the file or to resize it.
#
#TEMP=D:/tmp
#TMP=D:/tmp
#TMPDIR=D:/tmp
VERS=	3.1
BINDIR= /usr/gnu/bin
LIBDIR= /usr/gnu/lib
LCURSES=-lcurses -ltermcap
HASH=-DHASHFILE=$(LIBDIR)/gnuchess.hash
BOOK=-DBOOK=$(LIBDIR)/gnuchess.book
CC=gcc -W
CCC=gcc
##CXXFLAGS= -O2 -W -I/usr/gnuchess/src -DDESPERATE_FOR_RAM
CXXFLAGS= -W -I/usr/gnuchess/src -DDESPERATE_FOR_RAM
#CXXFLAGS=	-W -O2
LDFLAGS=-s
LDLIBS=-lgem++ -lg++ -lgem

LDLIBES=/usr/gnuchess/src/gnuchess.olb
LDLIBES512=/usr/gnuchess/src/gc_tiny.olb
ATARIGEMSRC=gemgui.cc popupch.cc popcolor.cc poppattn.cc
ATARIGEMOBJ=$(subst .cc,.o,$(ATARIGEMSRC))

all : ../gnuchess.prg ../gc_512k.prg

../gnuchess.prg: $(ATARIGEMOBJ) interact.o $(LDLIBES)
	$(CCC) $(LDFLAGS) $(ATARIGEMOBJ) interact.o $(LDLIBES) -lgem++ -lg++ -lgem -o ../gnuchess.prg

../gc_512k.prg: $(ATARIGEMOBJ) interact.o $(LDLIBES512)
	$(CCC) $(LDFLAGS) $(ATARIGEMOBJ) interact.o $(LDLIBES512) -lgem++ -lg++ -lgem -o ../gc_512k.prg

gnuchess.o: gnuchess.cc

interact.o: interact.cc

depend:
	$(CCC) $(CXXFLAGS) -MM $(ATARIGEMSRC) >depends

include depends
