# Makefile for the GCC MAGIC interface library (16 bit int default)

### NEEDS GNU MAKE ! ###

CC       =  gcc
DELETE   =  rm -f

# common subset of options;
COPTS    = -O2 -fomit-frame-pointer

# base options CC;
CFFLAGS  = -Wall -mshort

# normal CFLAGS
CFLAGS   = $(CFFLAGS) $(COPTS)

# libs
LLIBS    = -lmagic -lgem
#LLIBS  = -lmagic16 -lgem16 -lc16

# executables
MAGICDEM = magicdem/magicdem.prg
GDOS     = gdos/gdos.tos
WINDOW   = window/window.prg

# sources
SRC1     = magicdem/magicdem.c magicdem/magiclin.c
HDR1     = magicdem/magicdem.h magicdem/prototyp.h
SRC2     = gdos/gdos.c
SRC3     = window/window.c

all: $(MAGICDEM) $(GDOS) $(WINDOW)

$(MAGICDEM): $(SRC1) $(HDR1)
	$(CC) $(CFLAGS) -o $@ $(SRC1) $(LLIBS)

$(GDOS): $(SRC2)
	$(CC) $(CFLAGS) -o $@ $(SRC2) $(LLIBS)

$(WINDOW): $(SRC3)
	$(CC) $(CFLAGS) -o $@ $(SRC3) $(LLIBS)

clean:
	$(DELETE) $(MAGICDEM) $(GDOS) $(WINDOW)
