CC = cc68x
CFLAGS = -O -v -W5
#CC = cc68
#CFLAGS = -O -Qwarn=5
#CC = cc
#CFLAGS = -O

TARGET = cc68x.ttp
OBJS = main.o run.o utils.o

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) -liio

$(OBJS): global.h
main.o: patchlev.h

clean:
	rm -f $(TARGET) $(OBJS)
