SRC=doublebu.cc resoluti.cc screen.cc sprite.cc mousepos.cc fastcoun.cc \
			easyspri.cc joystick.cc smallgra.cc ca_pack.cc ca_unpac.cc \
			fnameext.cc timer.cc blockmap.cc terminat.cc mobilesp.cc \
			oscillat.cc sound.cc soundenv.cc fastfont.cc cookie.cc
ASMSRC=joyisr.s
OBJ=$(subst .cc,.o,$(SRC)) $(subst .s,.o,$(ASMSRC)

# WARNING: Sprite.cc may not work _without_ -O, because not enough
# free registers are available for the asm() functions.
C++FLAGS:= $(C++FLAGS) -O2 -W
LDLIBS=-lg++

LIBRARY=../lib/ams.olb
INC=../include

GXXINC:=$(INC),$(GXXINC)

$(LIBRARY): $(OBJ)
	$(AR) r $(LIBRARY) $?
	$(AR) s $(LIBRARY)

tcd.icc tcw.icc:	gentcd
	gentcd

clean:
	rm -f $(OBJ) gentcd

depend:
	$(CCC) $(C++FLAGS) -MM $(SRC) >depends

include depends
