#!/bin/csh
# $Id: tcovreport,v 1.1 91/11/26 13:17:52 pete Exp $

/bin/rm -rf tcov_cc1
touch tcov_cc1

set files=*.tcov

foreach i ($files)
    echo $i
    set p = `grep Percent $i`
    echo "	$p	`basename $i .tcov`.c" >> tcov_cc1
end

sort -n tcov_cc1 > p
mv p tcov_cc1
