.TH CS 1 "May 7, 1998" "" "User commands"
.SH NAME \"{{{roff}}}\"{{{
cs \- interactively examine C source code
.\"}}}
.SH SYNOPSIS \"{{{
.ad l
.B cs
.RB [ \-bdul ]
.RB [ \-f
.IR file ]
.RI [ file ...]
.ad b
.\"}}}
.SH DESCRIPTION \"{{{
.B cs
builds an index of the C (\fB.c\fP and \fB.h\fP) source files that are
specified as arguments or located in specified directories and allows
interactive browsing through this index to examine the C sources.
If no arguments are specified, the current directory is searched for
source files.
.PP
The input fields are used by:
.IP \fBTab\fP
Go to next input field.
.IP "\fBCursor up\fP, \fB Cursor down\fP"
Go to next/previous input field.
.IP "\fBReturn\fP
Query index with the contents of the input field.
.PP
You can browse through the index with:
.IP "\fBCursor up\fP, \fB Cursor down\fP"
Move up or down.
.IP "\fB+\fP, \fBSpace\fP, \fBNext page\fP"
Go to next page.
.IP "\fB\-\fP, \fBBackspace\fP, \fBPrev page\fP
Go to previous page.
.IP \fBReturn\fP
Edit selected file.
.IP "\fBControl d\fP"
Exit from browser.
.IP "\fBControl r\fP"
Update database.
.\"}}}
.SH OPTIONS \"{{{
.IP \fB\-b\fP
Build the index only.
.IP \fB\-d\fP
Do not update the index.
.IP \fB\-u\fP
Unconditionally build a new index.
.IP "\fB\-f\fP \fIfile\fP"
Store the index in the \fIfile\fP instead of \fBcs.out\fP.
.IP \fB\-l\fP
Work line-oriented.  This mode is useful if you want to use cs with another
program as front-end instead of using the builtin user interface.
.\"}}}
.SH ENVIRONMENT \"{{{
.IP TERM
The used terminal type.
.IP CSCOPE_VIEWER
A special editor/viewer used only for cscope.  This is used by several
people to start an editor session in a separate window in background.
.IP VISUAL
The preferred screen editor, used if \fBCSCOPE_VIEWER\fP is not set.
Emacs users might be interested in using the
supplied cemacs shell script.
.IP EDITOR
The preferred line editor.  This will be used if \fBVISUAL\fP is not set.
.\"}}}
.SH FILES \"{{{
cs.out	Default index file
.\"}}}
.SH AUTHOR \"{{{
cs is copyright (c) by Michael Haardt, 1995\(en1998.  You
may use and modify this program or derived works without charge for
personal use and at work under the condition that no copyright notices
are removed or changed.  Distributing cs under different conditions and
any commercial use like charging for copying or selling it or derived
works, alone or as part of a bigger product, needs a written license
from me.  The source code is at ftp://cantor.informatik.rwth-aachen.de/pub/unix/cs.tar.gz.
.P
I can be reached by:
.nf
Snail mail:
Michael Haardt
Fuhrweg 33
53229 Bonn
Germany

Email:
michael@cantor.informatik.rwth-aachen.de
.fi
Disclaimer: I am in no way responsible for anything caused by using this
program, so if your computer or house blows up, that's your problem.  :)
.\"}}}
.SH "SEE ALSO" \"{{{
\fIcc\fP(1), \fIctags\fP(1)
.\"}}}
