#
# szadb
# Makefile for the Atari ST  - Sozobon C compiler
# Use the second set of CFLAGS if you do not want on-line help.
#

CC=cc
CFLAGS = -c -O -DHELP
#CFLAGS = -c -O
# uncomment -t below for a symbol table in executables of your debugger.
SYMS=#-t

#	Sozobon rule
.c.o:
	$(CC) $(CFLAGS) $<

.s.o:
	$(CC) -c $<

HDRS=   adb.h lang.h
SRCS=	start.s adb.c adb1.c pcs.c trace.c dis3.c prt.c assist.s
SRC2=	fkeydefs.c help.c window.c stepping.c
OBJ=	adb.o adb1.o pcs.o trace.o dis3.o prt.o assist.o
OB2=	fkeydefs.o help.o window.o stepping.o

all : adb.ttp

help.o : $(HDRS)

adb.ttp : start.o $(OBJ) $(OB2) adb.h
	ld -o szadb.ttp $(SYMS) -f adb.lds

clean :
	$(RM) start.o $(OBJ) $(OB2)
