#define ABOUTIT 0  	/* TREE */
#define MINEMENU 1  	/* TREE */
#define ABOUT 9  	/* OBJECT in TREE #1 */
#define NEWGAME 19  	/* OBJECT in TREE #1 */
#define QUIT 18  	/* OBJECT in TREE #1 */
#define SOUND 39  	/* OBJECT in TREE #1 */
#define BOARD2 30  	/* OBJECT in TREE #1 */
#define BOARD0 28  	/* OBJECT in TREE #1 */
#define BOARD1 29  	/* OBJECT in TREE #1 */
#define BOARD3 31  	/* OBJECT in TREE #1 */
#define BOARD4 32  	/* OBJECT in TREE #1 */
#define BOARD5 33  	/* OBJECT in TREE #1 */
#define BOARD6 34  	/* OBJECT in TREE #1 */
#define BOARD7 35  	/* OBJECT in TREE #1 */
#define BOARD8 36  	/* OBJECT in TREE #1 */
#define BOARD9 37  	/* OBJECT in TREE #1 */
#define HIGHSCR 2  	/* TREE */
#define HIBD0 3  	/* OBJECT in TREE #2 */
#define HIBD1 5  	/* OBJECT in TREE #2 */
#define HIBD2 7  	/* OBJECT in TREE #2 */
#define HIBD3 9  	/* OBJECT in TREE #2 */
#define HIBD4 11  	/* OBJECT in TREE #2 */
#define HIBD5 13  	/* OBJECT in TREE #2 */
#define HIBD6 15  	/* OBJECT in TREE #2 */
#define HIBD7 17  	/* OBJECT in TREE #2 */
#define HIBD8 19  	/* OBJECT in TREE #2 */
#define HIBD9 21  	/* OBJECT in TREE #2 */
#define HINM0 2  	/* OBJECT in TREE #2 */
#define HINM1 4  	/* OBJECT in TREE #2 */
#define HINM2 6  	/* OBJECT in TREE #2 */
#define HINM3 8  	/* OBJECT in TREE #2 */
#define HINM4 10  	/* OBJECT in TREE #2 */
#define HINM5 12  	/* OBJECT in TREE #2 */
#define HINM6 14  	/* OBJECT in TREE #2 */
#define HINM7 16  	/* OBJECT in TREE #2 */
#define HINM8 18  	/* OBJECT in TREE #2 */
#define HINM9 20  	/* OBJECT in TREE #2 */
#define CLOSE 21  	/* OBJECT in TREE #1 */
#define BEST 3  	/* TREE */
#define SCOREIT 8  	/* OBJECT in TREE #3 */
#define BESTNAME 7  	/* OBJECT in TREE #3 */
#define BASEHELP 40  	/* OBJECT in TREE #1 */
#define ADVHELP 41  	/* OBJECT in TREE #1 */
#define HELP1 4  	/* TREE */
#define HELP2 5  	/* TREE */
#define FINI 6  	/* TREE */
#define BABOOM 7  	/* TREE */
#define OKBOOM 6  	/* OBJECT in TREE #7 */
#define RESETHI 22  	/* OBJECT in TREE #1 */
#define SHOWHI 24  	/* OBJECT in TREE #1 */
#define PAUSE 26  	/* OBJECT in TREE #1 */
