#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c
.s.o:
	mac $(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	@c:\alcyon\cp68.prg $(CFLAGS) -i c:\alcyon\include\ $*.c m:$*.i
	@c:\alcyon\c068.prg m:$*.i m:$*.1 m:$*.2 m:$*.3 -f
	@rm m:$*.i
	@c:\alcyon\c168.prg m:$*.1 m:$*.2 m:$*.s
	@c:\bin\mac.prg -6 -o $*.o m:$*.s
	@rm m:$*.1 m:$*.2 m:$*.s

TEMP = m:tmp
LIBS = gemlib libf osbind.o

OBJS =	gemstart.o acsi.o ide.o check.o cmdblk.o cookie.o doit.o scsi.o\
	spscsi.o tstdrive.o function.o

tstdrive.prg : $(OBJS)
	echo $(OBJS) $(LIBS) >$(TEMP)
	aln -l -o tstdrive.prg -c $(TEMP)


#
#  assembly-language files
#
acsi.o : acsi.s defs.h
check.o : check.s defs.h
ide.o: ide.s ide.h defs.h
cmdblk.o : cmdblk.s defs.h
cookie.o : cookie.s
doit.o : doit.s defs.h
gemstart.o : gemstart.s
#mymalloc.o : mymalloc.s
scsi.o : scsi.s defs.h
spscsi.o : spscsi.s defs.h


#
#  C sources
#
tstdrive.o : tstdrive.c
function.o : function.c

