#define MODE 0  	/* TREE */
#define N2F 7  	/* OBJECT in TREE #0 */
#define F2N 8  	/* OBJECT in TREE #0 */
#define DEF2 15  	/* OBJECT in TREE #0 */
#define HELPMODE 21  	/* OBJECT in TREE #0 */
#define CONVMODE 22  	/* OBJECT in TREE #0 */
#define QUITMODE 23  	/* OBJECT in TREE #0 */
#define NODEF 0  	/* STRING */
#define DEFYES 18  	/* OBJECT in TREE #0 */
#define DEFNO 19  	/* OBJECT in TREE #0 */
#define HELP 1  	/* TREE */
#define NOMEM 1  	/* STRING */
#define DFNYES 20  	/* OBJECT in TREE #0 */
#define DEF1 13  	/* OBJECT in TREE #0 */
#define RSC1 10  	/* OBJECT in TREE #0 */
#define RSC2 12  	/* OBJECT in TREE #0 */
#define PROGRESS 2  	/* TREE */
#define STRINGS 3  	/* TREE */
#define PLINE 2  	/* OBJECT in TREE #2 */
#define IMGALIGN 2  	/* OBJECT in TREE #3 */
#define RSCREAD 1  	/* OBJECT in TREE #3 */
#define BYTESWAP 3  	/* OBJECT in TREE #3 */
#define RSCWRITE 4  	/* OBJECT in TREE #3 */
#define DEFREAD 5  	/* OBJECT in TREE #3 */
#define DEFWRITE 6  	/* OBJECT in TREE #3 */
