#
# Makefile for Setboot utility
#
# Uncomment the next line if the compiler should invoke the editor on errors
#CFLAGS=-A

OBJS = setboot.o setbtgem.o

setboot.prg: $(OBJS)
	cc -VGEM $(OBJS)

clean:
	rm *.o

setboot.o: setboot.c setboot.h setbtmsg.h setbtgem.h

setbtgem.o : setbtgem.c setbtgem.h setbtmsg.h

install:
	echo "Insert TOS formatted disk into drive A."
	cp setboot.prg setboot.rsc a:\\
