REM FILENAME INSTO2.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE SCRNDRV SUBDIRECTORY.
C:
CD C:\
MD SCRNDRV
A:
COPY @A:OEM2.PRN C:\SCRNDRV
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
