REM FILENAME INSTO4.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE BIOSSRC AND BDOSOBJ SUBDIRECTORIES.
C:
CD C:\
MD BIOSSRC
A:
COPY @OEM4A.PRN C:\BIOSSRC
C:
MD BDOSOBJ
A:
COPY @OEM4B.PRN C:\BDOSOBJ
C:
MD SYSBLD
A:
COPY @OEM4C.PRN C:\SYSBLD
C:
MD DUPINFO
A:
COPY @OEM4D.PRN C:\DUPINFO
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
