REM FILENAME INSTI4.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE TOOLS SUBDIRECTORY.
C:
CD C:\
MD TOOLS
A:
COPY @A:ISV4.PRN C:\TOOLS
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
