#
#	Makefile for the socket device, on which MiNT-Net is based.
#

SHELL = /bin/sh

CC = gcc
LD = gcc

ifdef XDD
DEVDRV = sockdev.xdd
XCPPFLAGS = -DXDD
XLDFLAGS = -nostdlib -G
XSRCS = init.c
XOBJS = init.o
else
DEVDRV = sockdev.tos
endif

CPPFLAGS = -I../include $(XCPPFLAGS)
CFLAGS = -Wall -mshort -O2 -fomit-frame-pointer
LDFLAGS = $(XLDFLAGS)

SRCS = $(XSRCS) main.c sockdev.c sockutil.c intr.s
OBJS = $(XOBJS) main.o sockdev.o sockutil.o intr.o

SUBDIRS = unix
DOMAINS = unix/sock.a

all: $(DEVDRV)

.s.o:
	$(CC) -c $< -o $@

.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

$(DEVDRV): $(OBJS) subs
	$(LD) $(LDFLAGS) $(OBJS) $(DOMAINS) -lgnu16 -o $(DEVDRV)
	toglclr -super $(DEVDRV)
	chmod +x $(DEVDRV)

subs:
	@for i in $(SUBDIRS); do $(MAKE) -C $$i; done;
	
clean:
	rm -f $(OBJS)
	@for i in $(SUBDIRS); do $(MAKE) -C $$i clean; done;

depend:
	$(CC) -MM $(CPPFLAGS) *.c > depend
	@for i in $(SUBDIRS); do $(MAKE) -C $$i depend; done;

ifeq (depend, $(wildcard depend))
include depend
endif
