/***************************************************************************
 * This program is Copyright (C) 1986, 1987, 1988 by Jonathan Payne.  JOVE *
 * is provided to you without charge, and with no warranty.  You may give  *
 * away copies of JOVE, including sources, provided that this notice is    *
 * included in all the files.                                              *
 ***************************************************************************/

/* Warning:  You probably shouldn't put ifdefs anywhere *inside* the keymaps
   definitions.	 It'll screw up the stuff in comments (at least), and maybe
   a few other things.	Yes, it *WILL* screw up the comments ... but it's
   not clear that you care ... */

#include "jove.h"

keymap	mainmap = {
	(data_obj *) &commands[170],	/* C-@ */
	(data_obj *) &commands[16],	/* C-A */
	(data_obj *) &commands[7],	/* C-B */
	(data_obj *) 0,                 /* C-C */
	(data_obj *) &commands[42],	/* C-D */
	(data_obj *) &commands[67],	/* C-E */
	(data_obj *) &commands[83],	/* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) &commands[44],	/* C-H */
	(data_obj *) &commands[95],	/* C-I */
	(data_obj *) &commands[115],	/* C-J */
	(data_obj *) &commands[105],	/* C-K */
	(data_obj *) &commands[142],	/* C-L */
	(data_obj *) &commands[113],	/* C-M */
	(data_obj *) &commands[117],	/* C-N */
	(data_obj *) &commands[114],	/* C-O */
	(data_obj *) &commands[132],	/* C-P */
	(data_obj *) &commands[140],	/* C-Q */
	(data_obj *) &commands[155],	/* C-R */
	(data_obj *) &commands[153],	/* C-S */
	(data_obj *) &commands[183],	/* C-T */
	(data_obj *) &commands[90],	/* C-U */
	(data_obj *) &commands[118],	/* C-V */
	(data_obj *) &commands[101],	/* C-W */
	(data_obj *) &commands[129],	/* C-X */
	(data_obj *) &commands[196],	/* C-Y */
	(data_obj *) &commands[152],	/* C-Z */
	(data_obj *) &commands[128],	/* ESC */
	(data_obj *) &commands[153],	/* C-\ */
#ifndef MSDOS
	(data_obj *) 0,                 /* C-] */
#else /* MSDOS */
	(data_obj *) &commands[81],	/* C-] */
#endif /* MSDOS */
	(data_obj *) &commands[140],	/* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) &commands[168],	/*   */
	(data_obj *) &commands[168],	/* ! */
	(data_obj *) &commands[168],	/* " */
	(data_obj *) &commands[168],	/* # */
	(data_obj *) &commands[168],	/* $ */
	(data_obj *) &commands[168],	/* % */
	(data_obj *) &commands[168],	/* & */
	(data_obj *) &commands[168],	/* ' */
	(data_obj *) &commands[168],	/* ( */
	(data_obj *) &commands[123],	/* ) */
	(data_obj *) &commands[168],	/* * */
	(data_obj *) &commands[168],	/* + */
	(data_obj *) &commands[168],	/* , */
	(data_obj *) &commands[168],	/* - */
	(data_obj *) &commands[168],	/* . */
	(data_obj *) &commands[168],	/* / */
	(data_obj *) &commands[168],	/* 0 */
	(data_obj *) &commands[168],	/* 1 */
	(data_obj *) &commands[168],	/* 2 */
	(data_obj *) &commands[168],	/* 3 */
	(data_obj *) &commands[168],	/* 4 */
	(data_obj *) &commands[168],	/* 5 */
	(data_obj *) &commands[168],	/* 6 */
	(data_obj *) &commands[168],	/* 7 */
	(data_obj *) &commands[168],	/* 8 */
	(data_obj *) &commands[168],	/* 9 */
	(data_obj *) &commands[168],	/* : */
	(data_obj *) &commands[168],	/* ; */
	(data_obj *) &commands[168],	/* < */
	(data_obj *) &commands[168],	/* = */
	(data_obj *) &commands[168],	/* > */
	(data_obj *) &commands[168],	/* ? */
	(data_obj *) &commands[168],	/* @ */
	(data_obj *) &commands[168],	/* A */
	(data_obj *) &commands[168],	/* B */
	(data_obj *) &commands[168],	/* C */
	(data_obj *) &commands[168],	/* D */
	(data_obj *) &commands[168],	/* E */
	(data_obj *) &commands[168],	/* F */
	(data_obj *) &commands[168],	/* G */
	(data_obj *) &commands[168],	/* H */
	(data_obj *) &commands[168],	/* I */
	(data_obj *) &commands[168],	/* J */
	(data_obj *) &commands[168],	/* K */
	(data_obj *) &commands[168],	/* L */
	(data_obj *) &commands[168],	/* M */
	(data_obj *) &commands[168],	/* N */
	(data_obj *) &commands[168],	/* O */
	(data_obj *) &commands[168],	/* P */
	(data_obj *) &commands[168],	/* Q */
	(data_obj *) &commands[168],	/* R */
	(data_obj *) &commands[168],	/* S */
	(data_obj *) &commands[168],	/* T */
	(data_obj *) &commands[168],	/* U */
	(data_obj *) &commands[168],	/* V */
	(data_obj *) &commands[168],	/* W */
	(data_obj *) &commands[168],	/* X */
	(data_obj *) &commands[168],	/* Y */
	(data_obj *) &commands[168],	/* Z */
	(data_obj *) &commands[168],	/* [ */
	(data_obj *) &commands[168],	/* \ */
	(data_obj *) &commands[123],	/* ] */
	(data_obj *) &commands[168],	/* ^ */
	(data_obj *) &commands[168],	/* _ */
	(data_obj *) &commands[168],	/* ` */
	(data_obj *) &commands[168],	/* a */
	(data_obj *) &commands[168],	/* b */
	(data_obj *) &commands[168],	/* c */
	(data_obj *) &commands[168],	/* d */
	(data_obj *) &commands[168],	/* e */
	(data_obj *) &commands[168],	/* f */
	(data_obj *) &commands[168],	/* g */
	(data_obj *) &commands[168],	/* h */
	(data_obj *) &commands[168],	/* i */
	(data_obj *) &commands[168],	/* j */
	(data_obj *) &commands[168],	/* k */
	(data_obj *) &commands[168],	/* l */
	(data_obj *) &commands[168],	/* m */
	(data_obj *) &commands[168],	/* n */
	(data_obj *) &commands[168],	/* o */
	(data_obj *) &commands[168],	/* p */
	(data_obj *) &commands[168],	/* q */
	(data_obj *) &commands[168],	/* r */
	(data_obj *) &commands[168],	/* s */
	(data_obj *) &commands[168],	/* t */
	(data_obj *) &commands[168],	/* u */
	(data_obj *) &commands[168],	/* v */
	(data_obj *) &commands[168],	/* w */
	(data_obj *) &commands[168],	/* x */
	(data_obj *) &commands[168],	/* y */
	(data_obj *) &commands[168],	/* z */
	(data_obj *) &commands[168],	/* { */
	(data_obj *) &commands[168],	/* | */
	(data_obj *) &commands[123],	/* } */
	(data_obj *) &commands[168],	/* ~ */
#ifdef ASCII
	(data_obj *) &commands[44],	/* ^? */
#else
	(data_obj *) &commands[44],	/* ^? */
	(data_obj *) &commands[168],	/* M-C-@ */
	(data_obj *) &commands[168],	/* M-C-A */
	(data_obj *) &commands[168],	/* M-C-B */
	(data_obj *) &commands[168],	/* M-C-C */
	(data_obj *) &commands[168],	/* M-C-D */
	(data_obj *) &commands[168],	/* M-C-E */
	(data_obj *) &commands[168],	/* M-C-F */
	(data_obj *) &commands[168],	/* M-C-G */
	(data_obj *) &commands[168],	/* M-C-H */
	(data_obj *) &commands[168],	/* M-C-I */
	(data_obj *) &commands[168],	/* M-C-J */
	(data_obj *) &commands[168],	/* M-C-K */
	(data_obj *) &commands[168],	/* M-C-L */
	(data_obj *) &commands[168],	/* M-C-M */
	(data_obj *) &commands[168],	/* M-C-N */
	(data_obj *) &commands[168],	/* M-C-O */
	(data_obj *) &commands[168],	/* M-C-P */
	(data_obj *) &commands[168],	/* M-C-Q */
	(data_obj *) &commands[168],	/* M-C-R */
	(data_obj *) &commands[168],	/* M-C-S */
	(data_obj *) &commands[168],	/* M-C-T */
	(data_obj *) &commands[168],	/* M-C-U */
	(data_obj *) &commands[168],	/* M-C-V */
	(data_obj *) &commands[168],	/* M-C-W */
	(data_obj *) &commands[168],	/* M-C-X */
	(data_obj *) &commands[168],	/* M-C-Y */
	(data_obj *) &commands[168],	/* M-C-Z */
	(data_obj *) &commands[168],	/* M-ESC */
	(data_obj *) &commands[168],	/* M-C-\ */
	(data_obj *) &commands[168],	/* M-C-] */
	(data_obj *) &commands[168],	/* M-C-^ */
	(data_obj *) &commands[168],	/* M-C-_ */
	(data_obj *) &commands[168],	/* M-  */
	(data_obj *) &commands[168],	/* M-! */
	(data_obj *) &commands[168],	/* M-" */
	(data_obj *) &commands[168],	/* M-# */
	(data_obj *) &commands[168],	/* M-$ */
	(data_obj *) &commands[168],	/* M-% */
	(data_obj *) &commands[168],	/* M-& */
	(data_obj *) &commands[168],	/* M-' */
	(data_obj *) &commands[168],	/* M-( */
	(data_obj *) &commands[168],	/* M-) */
	(data_obj *) &commands[168],	/* M-* */
	(data_obj *) &commands[168],	/* M-+ */
	(data_obj *) &commands[168],	/* M-, */
	(data_obj *) &commands[168],	/* M-- */
	(data_obj *) &commands[168],	/* M-. */
	(data_obj *) &commands[168],	/* M-/ */
	(data_obj *) &commands[168],	/* M-0 */
	(data_obj *) &commands[168],	/* M-1 */
	(data_obj *) &commands[168],	/* M-2 */
	(data_obj *) &commands[168],	/* M-3 */
	(data_obj *) &commands[168],	/* M-4 */
	(data_obj *) &commands[168],	/* M-5 */
	(data_obj *) &commands[168],	/* M-6 */
	(data_obj *) &commands[168],	/* M-7 */
	(data_obj *) &commands[168],	/* M-8 */
	(data_obj *) &commands[168],	/* M-9 */
	(data_obj *) &commands[168],	/* M-: */
	(data_obj *) &commands[168],	/* M-; */
	(data_obj *) &commands[168],	/* M-< */
	(data_obj *) &commands[168],	/* M-= */
	(data_obj *) &commands[168],	/* M-> */
	(data_obj *) &commands[168],	/* M-? */
	(data_obj *) &commands[168],	/* M-@ */
	(data_obj *) &commands[168],	/* M-A */
	(data_obj *) &commands[168],	/* M-B */
	(data_obj *) &commands[168],	/* M-C */
	(data_obj *) &commands[168],	/* M-D */
	(data_obj *) &commands[168],	/* M-E */
	(data_obj *) &commands[168],	/* M-F */
	(data_obj *) &commands[168],	/* M-G */
	(data_obj *) &commands[168],	/* M-H */
	(data_obj *) &commands[168],	/* M-I */
	(data_obj *) &commands[168],	/* M-J */
	(data_obj *) &commands[168],	/* M-K */
	(data_obj *) &commands[168],	/* M-L */
	(data_obj *) &commands[168],	/* M-M */
	(data_obj *) &commands[168],	/* M-N */
	(data_obj *) &commands[168],	/* M-O */
	(data_obj *) &commands[168],	/* M-P */
	(data_obj *) &commands[168],	/* M-Q */
	(data_obj *) &commands[168],	/* M-R */
	(data_obj *) &commands[168],	/* M-S */
	(data_obj *) &commands[168],	/* M-T */
	(data_obj *) &commands[168],	/* M-U */
	(data_obj *) &commands[168],	/* M-V */
	(data_obj *) &commands[168],	/* M-W */
	(data_obj *) &commands[168],	/* M-X */
	(data_obj *) &commands[168],	/* M-Y */
	(data_obj *) &commands[168],	/* M-Z */
	(data_obj *) &commands[168],	/* M-[ */
	(data_obj *) &commands[168],	/* M-\ */
	(data_obj *) &commands[168],	/* M-] */
	(data_obj *) &commands[168],	/* M-^ */
	(data_obj *) &commands[168],	/* M-_ */
	(data_obj *) &commands[168],	/* M-` */
	(data_obj *) &commands[168],	/* M-a */
	(data_obj *) &commands[168],	/* M-b */
	(data_obj *) &commands[168],	/* M-c */
	(data_obj *) &commands[168],	/* M-d */
	(data_obj *) &commands[168],	/* M-e */
	(data_obj *) &commands[168],	/* M-f */
	(data_obj *) &commands[168],	/* M-g */
	(data_obj *) &commands[168],	/* M-h */
	(data_obj *) &commands[168],	/* M-i */
	(data_obj *) &commands[168],	/* M-j */
	(data_obj *) &commands[168],	/* M-k */
	(data_obj *) &commands[168],	/* M-l */
	(data_obj *) &commands[168],	/* M-m */
	(data_obj *) &commands[168],	/* M-n */
	(data_obj *) &commands[168],	/* M-o */
	(data_obj *) &commands[168],	/* M-p */
	(data_obj *) &commands[168],	/* M-q */
	(data_obj *) &commands[168],	/* M-r */
	(data_obj *) &commands[168],	/* M-s */
	(data_obj *) &commands[168],	/* M-t */
	(data_obj *) &commands[168],	/* M-u */
	(data_obj *) &commands[168],	/* M-v */
	(data_obj *) &commands[168],	/* M-w */
	(data_obj *) &commands[168],	/* M-x */
	(data_obj *) &commands[168],	/* M-y */
	(data_obj *) &commands[168],	/* M-z */
	(data_obj *) &commands[168],	/* M-{ */
	(data_obj *) &commands[168],	/* M-| */
	(data_obj *) &commands[168],	/* M-} */
	(data_obj *) &commands[168],	/* M-~ */
#if defined(IBMPC) || defined(ATARI)
	(data_obj *) &commands[130],	/* M-^? */
#else
	(data_obj *) &commands[168],	/* M-^? */
#endif	/* IBMPC */
#endif /* ASCII */
};

struct data_obj *pref1map[NCHARS] = {
	(data_obj *) &commands[170],	/* C-@ */
	(data_obj *) 0,                 /* C-A */
	(data_obj *) &commands[10],	/* C-B */
	(data_obj *) 0,                 /* C-C */
	(data_obj *) &commands[63],	/* C-D */
	(data_obj *) 0,                 /* C-E */
	(data_obj *) &commands[86],	/* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) 0,                 /* C-H */
	(data_obj *) 0,                 /* C-I */
	(data_obj *) 0,                 /* C-J */
	(data_obj *) &commands[102],	/* C-K */
	(data_obj *) &commands[31],	/* C-L */
	(data_obj *) 0,                 /* C-M */
	(data_obj *) &commands[84],	/* C-N */
	(data_obj *) 0,                 /* C-O */
	(data_obj *) &commands[8],	/* C-P */
	(data_obj *) 0,                 /* C-Q */
	(data_obj *) 0,                 /* C-R */
	(data_obj *) 0,                 /* C-S */
	(data_obj *) 0,                 /* C-T */
	(data_obj *) &commands[12],	/* C-U */
	(data_obj *) &commands[122],	/* C-V */
	(data_obj *) 0,                 /* C-W */
	(data_obj *) 0,                 /* C-X */
	(data_obj *) 0,                 /* C-Y */
	(data_obj *) 0,                 /* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) 0,                 /* C-\ */
	(data_obj *) 0,                 /* C-] */
	(data_obj *) 0,                 /* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) 0,                 /*   */
	(data_obj *) 0,                 /* ! */
	(data_obj *) 0,                 /* " */
	(data_obj *) 0,                 /* # */
	(data_obj *) 0,                 /* $ */
	(data_obj *) 0,                 /* % */
	(data_obj *) 0,                 /* & */
	(data_obj *) 0,                 /* ' */
	(data_obj *) 0,                 /* ( */
	(data_obj *) 0,                 /* ) */
	(data_obj *) 0,                 /* * */
	(data_obj *) 0,                 /* + */
	(data_obj *) &commands[17],	/* , */
	(data_obj *) &commands[51],	/* - */
	(data_obj *) &commands[68],	/* . */
	(data_obj *) 0,                 /* / */
	(data_obj *) &commands[51],	/* 0 */
	(data_obj *) &commands[51],	/* 1 */
	(data_obj *) &commands[51],	/* 2 */
	(data_obj *) &commands[51],	/* 3 */
	(data_obj *) &commands[51],	/* 4 */
	(data_obj *) &commands[51],	/* 5 */
	(data_obj *) &commands[51],	/* 6 */
	(data_obj *) &commands[51],	/* 7 */
	(data_obj *) &commands[51],	/* 8 */
	(data_obj *) &commands[51],	/* 9 */
	(data_obj *) 0,                 /* : */
	(data_obj *) 0,                 /* ; */
	(data_obj *) &commands[15],	/* < */
	(data_obj *) 0,                 /* = */
	(data_obj *) &commands[66],	/* > */
	(data_obj *) &commands[48],	/* ? */
	(data_obj *) 0,                 /* @ */
	(data_obj *) &commands[11],	/* A */
	(data_obj *) &commands[13],	/* B */
	(data_obj *) &commands[26],	/* C */
	(data_obj *) &commands[99],	/* D */
	(data_obj *) &commands[87],	/* E */
	(data_obj *) &commands[88],	/* F */
	(data_obj *) &commands[92],	/* G */
	(data_obj *) 0,                 /* H */
	(data_obj *) &commands[111],	/* I */
	(data_obj *) &commands[76],	/* J */
	(data_obj *) &commands[106],	/* K */
	(data_obj *) &commands[27],	/* L */
	(data_obj *) &commands[82],	/* M */
	(data_obj *) 0,                 /* N */
	(data_obj *) 0,                 /* O */
	(data_obj *) 0,                 /* P */
	(data_obj *) &commands[139],	/* Q */
	(data_obj *) &commands[146],	/* R */
	(data_obj *) 0,                 /* S */
	(data_obj *) 0,                 /* T */
	(data_obj *) &commands[28],	/* U */
	(data_obj *) &commands[133],	/* V */
	(data_obj *) &commands[33],	/* W */
	(data_obj *) &commands[71],	/* X */
	(data_obj *) &commands[197],	/* Y */
	(data_obj *) &commands[149],	/* Z */
	(data_obj *) &commands[9],	/* [ */
	(data_obj *) &commands[45],	/* \ */
	(data_obj *) &commands[85],	/* ] */
	(data_obj *) 0,                 /* ^ */
	(data_obj *) 0,                 /* _ */
	(data_obj *) 0,                 /* ` */
	(data_obj *) &commands[11],	/* a */
	(data_obj *) &commands[13],	/* b */
	(data_obj *) &commands[26],	/* c */
	(data_obj *) &commands[99],	/* d */
	(data_obj *) &commands[87],	/* e */
	(data_obj *) &commands[88],	/* f */
	(data_obj *) &commands[92],	/* g */
	(data_obj *) 0,                 /* h */
	(data_obj *) &commands[111],	/* i */
	(data_obj *) &commands[76],	/* j */
	(data_obj *) &commands[106],	/* k */
	(data_obj *) &commands[27],	/* l */
	(data_obj *) &commands[82],	/* m */
	(data_obj *) 0,                 /* n */
	(data_obj *) 0,                 /* o */
	(data_obj *) 0,                 /* p */
	(data_obj *) &commands[139],	/* q */
	(data_obj *) &commands[146],	/* r */
	(data_obj *) 0,                 /* s */
	(data_obj *) 0,                 /* t */
	(data_obj *) &commands[28],	/* u */
	(data_obj *) &commands[133],	/* v */
	(data_obj *) &commands[33],	/* w */
	(data_obj *) &commands[71],	/* x */
	(data_obj *) &commands[197],	/* y */
	(data_obj *) &commands[149],	/* z */
	(data_obj *) 0,                 /* { */
	(data_obj *) 0,                 /* | */
	(data_obj *) 0,                 /* } */
	(data_obj *) &commands[110],	/* ~ */
#ifdef ASCII
	(data_obj *) &commands[100],	/* ^? */
#else /* IBMPC or MAC */
	(data_obj *) &commands[100],	/* ^? */
	(data_obj *) 0,                 /* M-C-@ */
	(data_obj *) 0,                 /* M-C-A */
	(data_obj *) 0,                 /* M-C-B */
	(data_obj *) 0,                 /* M-C-C */
	(data_obj *) 0,                 /* M-C-D */
	(data_obj *) 0,                 /* M-C-E */
	(data_obj *) 0,                 /* M-C-F */
	(data_obj *) 0,                 /* M-C-G */
	(data_obj *) 0,                 /* M-C-H */
	(data_obj *) 0,                 /* M-C-I */
	(data_obj *) 0,                 /* M-C-J */
	(data_obj *) 0,                 /* M-C-K */
	(data_obj *) 0,                 /* M-C-L */
	(data_obj *) 0,                 /* M-C-M */
	(data_obj *) 0,                 /* M-C-N */
	(data_obj *) 0,                 /* M-C-O */
	(data_obj *) 0,                 /* M-C-P */
	(data_obj *) 0,                 /* M-C-Q */
	(data_obj *) 0,                 /* M-C-R */
	(data_obj *) 0,                 /* M-C-S */
	(data_obj *) 0,                 /* M-C-T */
	(data_obj *) 0,                 /* M-C-U */
	(data_obj *) 0,                 /* M-C-V */
	(data_obj *) 0,                 /* M-C-W */
	(data_obj *) 0,                 /* M-C-X */
	(data_obj *) 0,                 /* M-C-Y */
	(data_obj *) 0,                 /* M-C-Z */
	(data_obj *) 0,                 /* M-ESC */
	(data_obj *) 0,                 /* M-C-\ */
	(data_obj *) 0,                 /* M-C-] */
	(data_obj *) 0,                 /* M-C-^ */
	(data_obj *) 0,                 /* M-C-_ */
	(data_obj *) 0,                 /* M-  */
	(data_obj *) 0,                 /* M-! */
	(data_obj *) 0,                 /* M-" */
	(data_obj *) 0,                 /* M-# */
	(data_obj *) 0,                 /* M-$ */
	(data_obj *) 0,                 /* M-% */
	(data_obj *) 0,                 /* M-& */
	(data_obj *) 0,                 /* M-' */
	(data_obj *) 0,                 /* M-( */
	(data_obj *) 0,                 /* M-) */
	(data_obj *) 0,                 /* M-* */
	(data_obj *) 0,                 /* M-+ */
	(data_obj *) 0,                 /* M-, */
	(data_obj *) 0,                 /* M-- */
	(data_obj *) 0,                 /* M-. */
	(data_obj *) 0,                 /* M-/ */
	(data_obj *) 0,                 /* M-0 */
	(data_obj *) 0,                 /* M-1 */
	(data_obj *) 0,                 /* M-2 */
	(data_obj *) 0,                 /* M-3 */
	(data_obj *) 0,                 /* M-4 */
	(data_obj *) 0,                 /* M-5 */
	(data_obj *) 0,                 /* M-6 */
	(data_obj *) 0,                 /* M-7 */
	(data_obj *) 0,                 /* M-8 */
	(data_obj *) 0,                 /* M-9 */
	(data_obj *) 0,                 /* M-: */
	(data_obj *) 0,                 /* M-; */
	(data_obj *) 0,                 /* M-< */
	(data_obj *) 0,                 /* M-= */
	(data_obj *) 0,                 /* M-> */
	(data_obj *) 0,                 /* M-? */
	(data_obj *) 0,                 /* M-@ */
	(data_obj *) 0,                 /* M-A */
	(data_obj *) 0,                 /* M-B */
	(data_obj *) 0,                 /* M-C */
	(data_obj *) 0,                 /* M-D */
	(data_obj *) 0,                 /* M-E */
	(data_obj *) 0,                 /* M-F */
	(data_obj *) 0,                 /* M-G */
	(data_obj *) 0,                 /* M-H */
	(data_obj *) 0,                 /* M-I */
	(data_obj *) 0,                 /* M-J */
	(data_obj *) 0,                 /* M-K */
	(data_obj *) 0,                 /* M-L */
	(data_obj *) 0,                 /* M-M */
	(data_obj *) 0,                 /* M-N */
	(data_obj *) 0,                 /* M-O */
	(data_obj *) 0,                 /* M-P */
	(data_obj *) 0,                 /* M-Q */
	(data_obj *) 0,                 /* M-R */
	(data_obj *) 0,                 /* M-S */
	(data_obj *) 0,                 /* M-T */
	(data_obj *) 0,                 /* M-U */
	(data_obj *) 0,                 /* M-V */
	(data_obj *) 0,                 /* M-W */
	(data_obj *) 0,                 /* M-X */
	(data_obj *) 0,                 /* M-Y */
	(data_obj *) 0,                 /* M-Z */
	(data_obj *) 0,                 /* M-[ */
	(data_obj *) 0,                 /* M-\ */
	(data_obj *) 0,                 /* M-] */
	(data_obj *) 0,                 /* M-^ */
	(data_obj *) 0,                 /* M-_ */
	(data_obj *) 0,                 /* M-` */
	(data_obj *) 0,                 /* M-a */
	(data_obj *) 0,                 /* M-b */
	(data_obj *) 0,                 /* M-c */
	(data_obj *) 0,                 /* M-d */
	(data_obj *) 0,                 /* M-e */
	(data_obj *) 0,                 /* M-f */
	(data_obj *) 0,                 /* M-g */
	(data_obj *) 0,                 /* M-h */
	(data_obj *) 0,                 /* M-i */
	(data_obj *) 0,                 /* M-j */
	(data_obj *) 0,                 /* M-k */
	(data_obj *) 0,                 /* M-l */
	(data_obj *) 0,                 /* M-m */
	(data_obj *) 0,                 /* M-n */
	(data_obj *) 0,                 /* M-o */
	(data_obj *) 0,                 /* M-p */
	(data_obj *) 0,                 /* M-q */
	(data_obj *) 0,                 /* M-r */
	(data_obj *) 0,                 /* M-s */
	(data_obj *) 0,                 /* M-t */
	(data_obj *) 0,                 /* M-u */
	(data_obj *) 0,                 /* M-v */
	(data_obj *) 0,                 /* M-w */
	(data_obj *) 0,                 /* M-x */
	(data_obj *) 0,                 /* M-y */
	(data_obj *) 0,                 /* M-z */
	(data_obj *) 0,                 /* M-{ */
	(data_obj *) 0,                 /* M-| */
	(data_obj *) 0,                 /* M-} */
	(data_obj *) 0,                 /* M-~ */
	(data_obj *) 0,                 /* M-^? */
#endif /* ASCII */
};

keymap	pref2map = {
	(data_obj *) 0,                 /* C-@ */
	(data_obj *) 0,                 /* C-A */
	(data_obj *) &commands[109],	/* C-B */
	(data_obj *) &commands[74],	/* C-C */
	(data_obj *) 0,                 /* C-D */
	(data_obj *) &commands[32],	/* C-E */
	(data_obj *) &commands[79],	/* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) 0,                 /* C-H */
	(data_obj *) &commands[98],	/* C-I */
	(data_obj *) 0,                 /* C-J */
	(data_obj *) 0,                 /* C-K */
	(data_obj *) 0,                 /* C-L */
	(data_obj *) &commands[194],	/* C-M */
	(data_obj *) &commands[116],	/* C-N */
	(data_obj *) &commands[39],	/* C-O */
	(data_obj *) &commands[131],	/* C-P */
	(data_obj *) 0,                 /* C-Q */
	(data_obj *) &commands[188],	/* C-R */
	(data_obj *) &commands[148],	/* C-S */
	(data_obj *) &commands[184],	/* C-T */
	(data_obj *) 0,                 /* C-U */
	(data_obj *) &commands[188],	/* C-V */
	(data_obj *) &commands[192],	/* C-W */
	(data_obj *) &commands[70],	/* C-X */
	(data_obj *) 0,                 /* C-Y */
	(data_obj *) 0,                 /* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) &commands[148],	/* C-\ */
	(data_obj *) 0,                 /* C-] */
	(data_obj *) 0,                 /* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) 0,                 /*   */
	(data_obj *) &commands[171],	/* ! */
	(data_obj *) 0,                 /* " */
	(data_obj *) 0,                 /* # */
	(data_obj *) 0,                 /* $ */
	(data_obj *) 0,                 /* % */
	(data_obj *) 0,                 /* & */
	(data_obj *) 0,                 /* ' */
	(data_obj *) &commands[14],	/* ( */
	(data_obj *) &commands[65],	/* ) */
	(data_obj *) 0,                 /* * */
	(data_obj *) 0,                 /* + */
	(data_obj *) 0,                 /* , */
	(data_obj *) 0,                 /* - */
	(data_obj *) 0,                 /* . */
	(data_obj *) 0,                 /* / */
	(data_obj *) 0,                 /* 0 */
	(data_obj *) &commands[43],	/* 1 */
	(data_obj *) &commands[178],	/* 2 */
	(data_obj *) 0,                 /* 3 */
	(data_obj *) &commands[189],	/* 4 */
	(data_obj *) 0,                 /* 5 */
	(data_obj *) 0,                 /* 6 */
	(data_obj *) 0,                 /* 7 */
	(data_obj *) 0,                 /* 8 */
	(data_obj *) 0,                 /* 9 */
	(data_obj *) 0,                 /* : */
	(data_obj *) 0,                 /* ; */
	(data_obj *) 0,                 /* < */
	(data_obj *) 0,                 /* = */
	(data_obj *) 0,                 /* > */
	(data_obj *) &commands[49],	/* ? */
	(data_obj *) 0,                 /* @ */
	(data_obj *) 0,                 /* A */
	(data_obj *) &commands[157],	/* B */
	(data_obj *) 0,                 /* C */
	(data_obj *) &commands[46],	/* D */
	(data_obj *) &commands[72],	/* E */
	(data_obj *) 0,                 /* F */
	(data_obj *) 0,                 /* G */
	(data_obj *) 0,                 /* H */
	(data_obj *) 0,                 /* I */
	(data_obj *) 0,                 /* J */
	(data_obj *) &commands[40],	/* K */
	(data_obj *) 0,                 /* L */
	(data_obj *) 0,                 /* M */
	(data_obj *) &commands[119],	/* N */
	(data_obj *) &commands[134],	/* O */
	(data_obj *) &commands[134],	/* P */
	(data_obj *) 0,                 /* Q */
	(data_obj *) 0,                 /* R */
	(data_obj *) &commands[148],	/* S */
	(data_obj *) &commands[80],	/* T */
	(data_obj *) 0,                 /* U */
	(data_obj *) 0,                 /* V */
	(data_obj *) 0,                 /* W */
	(data_obj *) 0,                 /* X */
	(data_obj *) 0,                 /* Y */
	(data_obj *) 0,                 /* Z */
	(data_obj *) 0,                 /* [ */
	(data_obj *) 0,                 /* \ */
	(data_obj *) 0,                 /* ] */
	(data_obj *) &commands[94],	/* ^ */
	(data_obj *) 0,                 /* _ */
	(data_obj *) 0,                 /* ` */
	(data_obj *) 0,                 /* a */
	(data_obj *) &commands[157],	/* b */
	(data_obj *) 0,                 /* c */
	(data_obj *) &commands[46],	/* d */
	(data_obj *) &commands[72],	/* e */
	(data_obj *) 0,                 /* f */
	(data_obj *) 0,                 /* g */
	(data_obj *) 0,                 /* h */
	(data_obj *) 0,                 /* i */
	(data_obj *) 0,                 /* j */
	(data_obj *) &commands[40],	/* k */
	(data_obj *) 0,                 /* l */
	(data_obj *) 0,                 /* m */
	(data_obj *) &commands[119],	/* n */
	(data_obj *) &commands[134],	/* o */
	(data_obj *) &commands[134],	/* p */
	(data_obj *) 0,                 /* q */
	(data_obj *) 0,                 /* r */
	(data_obj *) &commands[148],	/* s */
	(data_obj *) &commands[80],	/* t */
	(data_obj *) 0,                 /* u */
	(data_obj *) 0,                 /* v */
	(data_obj *) 0,                 /* w */
	(data_obj *) 0,                 /* x */
	(data_obj *) 0,                 /* y */
	(data_obj *) 0,                 /* z */
	(data_obj *) 0,                 /* { */
	(data_obj *) 0,                 /* | */
	(data_obj *) 0,                 /* } */
	(data_obj *) 0,                 /* ~ */
#ifdef ASCII
	(data_obj *) &commands[104],	/* ^? */
#else /* IBMPC or MAC */
	(data_obj *) &commands[104],	/* ^? */
	(data_obj *) 0,                 /* M-C-@ */
	(data_obj *) 0,                 /* M-C-A */
	(data_obj *) 0,                 /* M-C-B */
	(data_obj *) 0,                 /* M-C-C */
	(data_obj *) 0,                 /* M-C-D */
	(data_obj *) 0,                 /* M-C-E */
	(data_obj *) 0,                 /* M-C-F */
	(data_obj *) 0,                 /* M-C-G */
	(data_obj *) 0,                 /* M-C-H */
	(data_obj *) 0,                 /* M-C-I */
	(data_obj *) 0,                 /* M-C-J */
	(data_obj *) 0,                 /* M-C-K */
	(data_obj *) 0,                 /* M-C-L */
	(data_obj *) 0,                 /* M-C-M */
	(data_obj *) 0,                 /* M-C-N */
	(data_obj *) 0,                 /* M-C-O */
	(data_obj *) 0,                 /* M-C-P */
	(data_obj *) 0,                 /* M-C-Q */
	(data_obj *) 0,                 /* M-C-R */
	(data_obj *) 0,                 /* M-C-S */
	(data_obj *) 0,                 /* M-C-T */
	(data_obj *) 0,                 /* M-C-U */
	(data_obj *) 0,                 /* M-C-V */
	(data_obj *) 0,                 /* M-C-W */
	(data_obj *) 0,                 /* M-C-X */
	(data_obj *) 0,                 /* M-C-Y */
	(data_obj *) 0,                 /* M-C-Z */
	(data_obj *) 0,                 /* M-ESC */
	(data_obj *) 0,                 /* M-C-\ */
	(data_obj *) 0,                 /* M-C-] */
	(data_obj *) 0,                 /* M-C-^ */
	(data_obj *) 0,                 /* M-C-_ */
	(data_obj *) 0,                 /* M-  */
	(data_obj *) 0,                 /* M-! */
	(data_obj *) 0,                 /* M-" */
	(data_obj *) 0,                 /* M-# */
	(data_obj *) 0,                 /* M-$ */
	(data_obj *) 0,                 /* M-% */
	(data_obj *) 0,                 /* M-& */
	(data_obj *) 0,                 /* M-' */
	(data_obj *) 0,                 /* M-( */
	(data_obj *) 0,                 /* M-) */
	(data_obj *) 0,                 /* M-* */
	(data_obj *) 0,                 /* M-+ */
	(data_obj *) 0,                 /* M-, */
	(data_obj *) 0,                 /* M-- */
	(data_obj *) 0,                 /* M-. */
	(data_obj *) 0,                 /* M-/ */
	(data_obj *) 0,                 /* M-0 */
	(data_obj *) 0,                 /* M-1 */
	(data_obj *) 0,                 /* M-2 */
	(data_obj *) 0,                 /* M-3 */
	(data_obj *) 0,                 /* M-4 */
	(data_obj *) 0,                 /* M-5 */
	(data_obj *) 0,                 /* M-6 */
	(data_obj *) 0,                 /* M-7 */
	(data_obj *) 0,                 /* M-8 */
	(data_obj *) 0,                 /* M-9 */
	(data_obj *) 0,                 /* M-: */
	(data_obj *) 0,                 /* M-; */
	(data_obj *) 0,                 /* M-< */
	(data_obj *) 0,                 /* M-= */
	(data_obj *) 0,                 /* M-> */
	(data_obj *) 0,                 /* M-? */
	(data_obj *) 0,                 /* M-@ */
	(data_obj *) 0,                 /* M-A */
	(data_obj *) 0,                 /* M-B */
	(data_obj *) 0,                 /* M-C */
	(data_obj *) 0,                 /* M-D */
	(data_obj *) 0,                 /* M-E */
	(data_obj *) 0,                 /* M-F */
	(data_obj *) 0,                 /* M-G */
	(data_obj *) 0,                 /* M-H */
	(data_obj *) 0,                 /* M-I */
	(data_obj *) 0,                 /* M-J */
	(data_obj *) 0,                 /* M-K */
	(data_obj *) 0,                 /* M-L */
	(data_obj *) 0,                 /* M-M */
	(data_obj *) 0,                 /* M-N */
	(data_obj *) 0,                 /* M-O */
	(data_obj *) 0,                 /* M-P */
	(data_obj *) 0,                 /* M-Q */
	(data_obj *) 0,                 /* M-R */
	(data_obj *) 0,                 /* M-S */
	(data_obj *) 0,                 /* M-T */
	(data_obj *) 0,                 /* M-U */
	(data_obj *) 0,                 /* M-V */
	(data_obj *) 0,                 /* M-W */
	(data_obj *) 0,                 /* M-X */
	(data_obj *) 0,                 /* M-Y */
	(data_obj *) 0,                 /* M-Z */
	(data_obj *) 0,                 /* M-[ */
	(data_obj *) 0,                 /* M-\ */
	(data_obj *) 0,                 /* M-] */
	(data_obj *) 0,                 /* M-^ */
	(data_obj *) 0,                 /* M-_ */
	(data_obj *) 0,                 /* M-` */
	(data_obj *) 0,                 /* M-a */
	(data_obj *) 0,                 /* M-b */
	(data_obj *) 0,                 /* M-c */
	(data_obj *) 0,                 /* M-d */
	(data_obj *) 0,                 /* M-e */
	(data_obj *) 0,                 /* M-f */
	(data_obj *) 0,                 /* M-g */
	(data_obj *) 0,                 /* M-h */
	(data_obj *) 0,                 /* M-i */
	(data_obj *) 0,                 /* M-j */
	(data_obj *) 0,                 /* M-k */
	(data_obj *) 0,                 /* M-l */
	(data_obj *) 0,                 /* M-m */
	(data_obj *) 0,                 /* M-n */
	(data_obj *) 0,                 /* M-o */
	(data_obj *) 0,                 /* M-p */
	(data_obj *) 0,                 /* M-q */
	(data_obj *) 0,                 /* M-r */
	(data_obj *) 0,                 /* M-s */
	(data_obj *) 0,                 /* M-t */
	(data_obj *) 0,                 /* M-u */
	(data_obj *) 0,                 /* M-v */
	(data_obj *) 0,                 /* M-w */
	(data_obj *) 0,                 /* M-x */
	(data_obj *) 0,                 /* M-y */
	(data_obj *) 0,                 /* M-z */
	(data_obj *) 0,                 /* M-{ */
	(data_obj *) 0,                 /* M-| */
	(data_obj *) 0,                 /* M-} */
	(data_obj *) 0,                 /* M-~ */
	(data_obj *) 0,                 /* M-^? */
#endif /* ASCII */
};

#if !(defined(IBMPC) || defined(ATARI))
keymap	miscmap = {0};
#else /* IBMPC || ATARI */
keymap	miscmap = {
	(data_obj *) 0,                 /* C-@ */
	(data_obj *) 0,                 /* C-A */
	(data_obj *) 0,                 /* C-B */
	(data_obj *) &commands[170],	/* C-C */
	(data_obj *) 0,                 /* C-D */
	(data_obj *) 0,                 /* C-E */
	(data_obj *) 0,                 /* C-F */
	(data_obj *) 0,                 /* C-G */
	(data_obj *) 0,                 /* C-H */
	(data_obj *) 0,                 /* C-I */
	(data_obj *) 0,                 /* C-J */
	(data_obj *) 0,                 /* C-K */
	(data_obj *) 0,                 /* C-L */
	(data_obj *) 0,                 /* C-M */
	(data_obj *) 0,                 /* C-N */
	(data_obj *) 0,                 /* C-O */
	(data_obj *) &commands[139],	/* C-P */
	(data_obj *) &commands[33],	/* C-Q */
	(data_obj *) &commands[87],	/* C-R */
	(data_obj *) &commands[146],	/* C-S */
	(data_obj *) 0,                 /* C-T */
	(data_obj *) &commands[197],	/* C-U */
	(data_obj *) &commands[28],	/* C-V */
	(data_obj *) &commands[111],	/* C-W */
	(data_obj *) 0,                 /* C-X */
	(data_obj *) 0,                 /* C-Y */
	(data_obj *) 0,                 /* C-Z */
	(data_obj *) 0,                 /* ESC */
	(data_obj *) 0,                 /* C-\ */
	(data_obj *) 0,                 /* C-] */
	(data_obj *) &commands[11],	/* C-^ */
	(data_obj *) 0,                 /* C-_ */
	(data_obj *) &commands[99],	/*   */
	(data_obj *) &commands[88],	/* ! */
	(data_obj *) &commands[92],	/* " */
	(data_obj *) 0,                 /* # */
	(data_obj *) &commands[76],	/* $ */
	(data_obj *) &commands[106],	/* % */
	(data_obj *) &commands[27],	/* & */
	(data_obj *) 0,                 /* ' */
	(data_obj *) 0,                 /* ( */
	(data_obj *) 0,                 /* ) */
	(data_obj *) 0,                 /* * */
	(data_obj *) 0,                 /* + */
	(data_obj *) &commands[149],	/* , */
	(data_obj *) &commands[71],	/* - */
	(data_obj *) &commands[26],	/* . */
	(data_obj *) &commands[133],	/* / */
	(data_obj *) &commands[13],	/* 0 */
	(data_obj *) 0,                 /* 1 */
	(data_obj *) &commands[82],	/* 2 */
	(data_obj *) 0,                 /* 3 */
	(data_obj *) 0,                 /* 4 */
	(data_obj *) 0,                 /* 5 */
	(data_obj *) 0,                 /* 6 */
	(data_obj *) 0,                 /* 7 */
	(data_obj *) 0,                 /* 8 */
	(data_obj *) 0,                 /* 9 */
	(data_obj *) 0,                 /* : */
	(data_obj *) 0,                 /* ; */
	(data_obj *) 0,                 /* < */
	(data_obj *) 0,                 /* = */
	(data_obj *) 0,                 /* > */
	(data_obj *) 0,                 /* ? */
	(data_obj *) 0,                 /* @ */
	(data_obj *) 0,                 /* A */
	(data_obj *) 0,                 /* B */
	(data_obj *) 0,                 /* C */
	(data_obj *) 0,                 /* D */
	(data_obj *) 0,                 /* E */
	(data_obj *) 0,                 /* F */
	(data_obj *) &commands[16],	/* G */
	(data_obj *) &commands[132],	/* H */
	(data_obj *) &commands[133],	/* I */
	(data_obj *) 0,                 /* J */
	(data_obj *) &commands[7],	/* K */
	(data_obj *) 0,                 /* L */
	(data_obj *) &commands[83],	/* M */
	(data_obj *) 0,                 /* N */
	(data_obj *) &commands[67],	/* O */
	(data_obj *) &commands[117],	/* P */
	(data_obj *) &commands[118],	/* Q */
	(data_obj *) &commands[121],	/* R */
	(data_obj *) &commands[42],	/* S */
	(data_obj *) 0,                 /* T */
	(data_obj *) 0,                 /* U */
	(data_obj *) 0,                 /* V */
	(data_obj *) 0,                 /* W */
	(data_obj *) 0,                 /* X */
	(data_obj *) 0,                 /* Y */
	(data_obj *) 0,                 /* Z */
	(data_obj *) 0,                 /* [ */
	(data_obj *) 0,                 /* \ */
	(data_obj *) 0,                 /* ] */
	(data_obj *) 0,                 /* ^ */
	(data_obj *) 0,                 /* _ */
	(data_obj *) 0,                 /* ` */
	(data_obj *) 0,                 /* a */
	(data_obj *) 0,                 /* b */
	(data_obj *) 0,                 /* c */
	(data_obj *) 0,                 /* d */
	(data_obj *) 0,                 /* e */
	(data_obj *) 0,                 /* f */
	(data_obj *) 0,                 /* g */
	(data_obj *) 0,                 /* h */
	(data_obj *) 0,                 /* i */
	(data_obj *) 0,                 /* j */
	(data_obj *) 0,                 /* k */
	(data_obj *) 0,                 /* l */
	(data_obj *) 0,                 /* m */
	(data_obj *) 0,                 /* n */
	(data_obj *) 0,                 /* o */
	(data_obj *) 0,                 /* p */
	(data_obj *) 0,                 /* q */
	(data_obj *) 0,                 /* r */
	(data_obj *) &commands[13],	/* s */
	(data_obj *) &commands[88],	/* t */
	(data_obj *) &commands[66],	/* u */
	(data_obj *) &commands[119],	/* v */
	(data_obj *) &commands[15],	/* w */
	(data_obj *) &commands[158],	/* x */
	(data_obj *) &commands[159],	/* y */
	(data_obj *) &commands[160],	/* z */
	(data_obj *) &commands[161],	/* { */
	(data_obj *) &commands[162],	/* | */
	(data_obj *) &commands[163],	/* } */
	(data_obj *) &commands[164],	/* ~ */
	(data_obj *) &commands[165],	/* ^? */
	(data_obj *) &commands[166],	/* M-C-@ */
	(data_obj *) &commands[167],	/* M-C-A */
	(data_obj *) 0,                 /* M-C-B */
	(data_obj *) 0,                 /* M-C-C */
	(data_obj *) &commands[134],	/* M-C-D */
	(data_obj *) 0,                 /* M-C-E */
	(data_obj *) 0,                 /* M-C-F */
	(data_obj *) 0,                 /* M-C-G */
	(data_obj *) 0,                 /* M-C-H */
	(data_obj *) 0,                 /* M-C-I */
	(data_obj *) 0,                 /* M-C-J */
	(data_obj *) 0,                 /* M-C-K */
	(data_obj *) 0,                 /* M-C-L */
	(data_obj *) 0,                 /* M-C-M */
	(data_obj *) 0,                 /* M-C-N */
	(data_obj *) 0,                 /* M-C-O */
	(data_obj *) 0,                 /* M-C-P */
	(data_obj *) 0,                 /* M-C-Q */
	(data_obj *) 0,                 /* M-C-R */
	(data_obj *) 0,                 /* M-C-S */
	(data_obj *) 0,                 /* M-C-T */
	(data_obj *) 0,                 /* M-C-U */
	(data_obj *) 0,                 /* M-C-V */
	(data_obj *) 0,                 /* M-C-W */
	(data_obj *) 0,                 /* M-C-X */
	(data_obj *) 0,                 /* M-C-Y */
	(data_obj *) 0,                 /* M-C-Z */
	(data_obj *) 0,                 /* M-ESC */
	(data_obj *) 0,                 /* M-C-\ */
	(data_obj *) 0,                 /* M-C-] */
	(data_obj *) 0,                 /* M-C-^ */
	(data_obj *) 0,                 /* M-C-_ */
	(data_obj *) 0,                 /* M-  */
	(data_obj *) 0,                 /* M-! */
	(data_obj *) 0,                 /* M-" */
	(data_obj *) 0,                 /* M-# */
	(data_obj *) 0,                 /* M-$ */
	(data_obj *) 0,                 /* M-% */
	(data_obj *) 0,                 /* M-& */
	(data_obj *) 0,                 /* M-' */
	(data_obj *) 0,                 /* M-( */
	(data_obj *) 0,                 /* M-) */
	(data_obj *) 0,                 /* M-* */
	(data_obj *) 0,                 /* M-+ */
	(data_obj *) 0,                 /* M-, */
	(data_obj *) 0,                 /* M-- */
	(data_obj *) 0,                 /* M-. */
	(data_obj *) 0,                 /* M-/ */
	(data_obj *) 0,                 /* M-0 */
	(data_obj *) 0,                 /* M-1 */
	(data_obj *) 0,                 /* M-2 */
	(data_obj *) 0,                 /* M-3 */
	(data_obj *) 0,                 /* M-4 */
	(data_obj *) 0,                 /* M-5 */
	(data_obj *) 0,                 /* M-6 */
	(data_obj *) 0,                 /* M-7 */
	(data_obj *) 0,                 /* M-8 */
	(data_obj *) 0,                 /* M-9 */
	(data_obj *) 0,                 /* M-: */
	(data_obj *) 0,                 /* M-; */
	(data_obj *) 0,                 /* M-< */
	(data_obj *) 0,                 /* M-= */
	(data_obj *) 0,                 /* M-> */
	(data_obj *) 0,                 /* M-? */
	(data_obj *) 0,                 /* M-@ */
	(data_obj *) 0,                 /* M-A */
	(data_obj *) 0,                 /* M-B */
	(data_obj *) 0,                 /* M-C */
	(data_obj *) 0,                 /* M-D */
	(data_obj *) 0,                 /* M-E */
	(data_obj *) 0,                 /* M-F */
	(data_obj *) 0,                 /* M-G */
	(data_obj *) 0,                 /* M-H */
	(data_obj *) 0,                 /* M-I */
	(data_obj *) 0,                 /* M-J */
	(data_obj *) 0,                 /* M-K */
	(data_obj *) 0,                 /* M-L */
	(data_obj *) 0,                 /* M-M */
	(data_obj *) 0,                 /* M-N */
	(data_obj *) 0,                 /* M-O */
	(data_obj *) 0,                 /* M-P */
	(data_obj *) 0,                 /* M-Q */
	(data_obj *) 0,                 /* M-R */
	(data_obj *) 0,                 /* M-S */
	(data_obj *) 0,                 /* M-T */
	(data_obj *) 0,                 /* M-U */
	(data_obj *) 0,                 /* M-V */
	(data_obj *) 0,                 /* M-W */
	(data_obj *) 0,                 /* M-X */
	(data_obj *) 0,                 /* M-Y */
	(data_obj *) 0,                 /* M-Z */
	(data_obj *) 0,                 /* M-[ */
	(data_obj *) 0,                 /* M-\ */
	(data_obj *) 0,                 /* M-] */
	(data_obj *) 0,                 /* M-^ */
	(data_obj *) 0,                 /* M-_ */
	(data_obj *) 0,                 /* M-` */
	(data_obj *) 0,                 /* M-a */
	(data_obj *) 0,                 /* M-b */
	(data_obj *) 0,                 /* M-c */
	(data_obj *) 0,                 /* M-d */
	(data_obj *) 0,                 /* M-e */
	(data_obj *) 0,                 /* M-f */
	(data_obj *) 0,                 /* M-g */
	(data_obj *) 0,                 /* M-h */
	(data_obj *) 0,                 /* M-i */
	(data_obj *) 0,                 /* M-j */
	(data_obj *) 0,                 /* M-k */
	(data_obj *) 0,                 /* M-l */
	(data_obj *) 0,                 /* M-m */
	(data_obj *) 0,                 /* M-n */
	(data_obj *) 0,                 /* M-o */
	(data_obj *) 0,                 /* M-p */
	(data_obj *) 0,                 /* M-q */
	(data_obj *) 0,                 /* M-r */
	(data_obj *) 0,                 /* M-s */
	(data_obj *) 0,                 /* M-t */
	(data_obj *) 0,                 /* M-u */
	(data_obj *) 0,                 /* M-v */
	(data_obj *) 0,                 /* M-w */
	(data_obj *) 0,                 /* M-x */
	(data_obj *) 0,                 /* M-y */
	(data_obj *) 0,                 /* M-z */
	(data_obj *) 0,                 /* M-{ */
	(data_obj *) 0,                 /* M-| */
	(data_obj *) 0,                 /* M-} */
	(data_obj *) 0,                 /* M-~ */
	(data_obj *) 0,                 /* M-^? */
};
#endif /* IBMPC || ATARI*/
