###########################################################################
# This program is Copyright (C) 1986, 1987, 1988 by Jonathan Payne.  JOVE #
# is provided to you without charge, and with no warranty.  You may give  #
# away copies of JOVE, including sources, provided that this notice is    #
# included in all the files.                                              #
###########################################################################
BIN = c:\cbin

OBJECTS = keymaps.o funcdefs.o abbrev.o ask.o buf.o c.o \
	case.o ctype.o delete.o extend.o argcount.o \
	insert.o io.o jove.o macros.o marks.o misc.o move.o \
	paragrap.o proc.o re.o re1.o scandir.o \
	table.o tune.o util.o vars.o wind.o \
	fmt.o disp.o term.o version.o fp.o screen.o getch.o atari.o

HEADERS = ctype.h io.h jove.h re.h table.h temp.h termcap.h tune.h externs.h

#CFLAGS =  -A  -DATARI -VCSD -DA_DEBUG
CFLAGS =  -A  -DATARI -VPEEP 
#CFLAGS =  -A  -DATARI -VNOOPT 
SRC = .
xjove.prg: start $(OBJECTS) $(HEADERS) 
	cc -o xjove.prg $(CFLAGS) $(OBJECTS)
	@echo Done
	@cat comp.tm
	@time
install: xjove.prg
	strip xjove.prg
	cp xjove.prg $(BIN)\jove.prg
	
$(OBJECTS): $(HEADERS)

start:
	@time > comp.tm

setmaps.prg:	setmaps.o funcdefs.c
	cc -o setmaps.prg setmaps.o 

setmaps.o:	funcdefs.c keymaps.txt
	cc $(CFLAGS) -c $(SRC)\setmaps.c

keymaps.c:	setmaps.prg keymaps.txt
	setmaps < keymaps.txt > keymaps.c

keymaps.o:	keymaps.c jove.h
	$(CC) $(CFLAGS) -I$(SRC) -c keymaps.c

# to avoid accidental loss under unix
tune.c:	tune.st
	cp tune.st tune.c

tune.o: tune.c
	$(CC) $(CFLAGS) -I$(SRC) -c tune.c

clean:
	-rm *.o setmaps.prg keymaps.c *.bak *.map

