;-------------------------------------------------------------------------------
;;;;;;;##### triangle texture mapping routine ...
; A1 A2 A3  points
; struct point { short y; short x; short u; short v; }
                RSSET 0
y:              RS.W 1
x:              RS.W 1
u:              RS.W 1
v:              RS.W 1
;-------------------------------------------------------------------------------


