#define COLOR 0  	/* TREE */
#define CSAVE 52  	/* OBJECT in TREE #0 */
#define COK 53  	/* OBJECT in TREE #0 */
#define CCANCEL 54  	/* OBJECT in TREE #0 */
#define RGBBOX 1  	/* OBJECT in TREE #0 */
#define BOX0 5  	/* OBJECT in TREE #0 */
#define RUP 37  	/* OBJECT in TREE #0 */
#define RBASE 40  	/* OBJECT in TREE #0 */
#define CUP 21  	/* OBJECT in TREE #0 */
#define CBASE 22  	/* OBJECT in TREE #0 */
#define CDOWN 24  	/* OBJECT in TREE #0 */
#define BASE16 4  	/* OBJECT in TREE #0 */
#define CRELOAD 51  	/* OBJECT in TREE #0 */
#define RGBSLIDE 33  	/* OBJECT in TREE #0 */
#define BASE2 25  	/* OBJECT in TREE #0 */
#define TWO01 26  	/* OBJECT in TREE #0 */
#define BASE4 28  	/* OBJECT in TREE #0 */
#define FOUR01 29  	/* OBJECT in TREE #0 */
#define FOUR02 30  	/* OBJECT in TREE #0 */
#define FOUR03 31  	/* OBJECT in TREE #0 */
#define FOUR04 32  	/* OBJECT in TREE #0 */
#define GUP 38  	/* OBJECT in TREE #0 */
#define BUP 39  	/* OBJECT in TREE #0 */
#define RDOWN 46  	/* OBJECT in TREE #0 */
#define GDOWN 47  	/* OBJECT in TREE #0 */
#define BDOWN 48  	/* OBJECT in TREE #0 */
#define GBASE 42  	/* OBJECT in TREE #0 */
#define BBASE 44  	/* OBJECT in TREE #0 */
#define TWO02 27  	/* OBJECT in TREE #0 */
#define BOX1 6  	/* OBJECT in TREE #0 */
#define BOX2 7  	/* OBJECT in TREE #0 */
#define BOX3 8  	/* OBJECT in TREE #0 */
#define BOX4 9  	/* OBJECT in TREE #0 */
#define BOX5 10  	/* OBJECT in TREE #0 */
#define BOX6 11  	/* OBJECT in TREE #0 */
#define BOX7 12  	/* OBJECT in TREE #0 */
#define BOX8 13  	/* OBJECT in TREE #0 */
#define BOX9 14  	/* OBJECT in TREE #0 */
#define BOX10 15  	/* OBJECT in TREE #0 */
#define BOX11 16  	/* OBJECT in TREE #0 */
#define BOX12 17  	/* OBJECT in TREE #0 */
#define BOX13 18  	/* OBJECT in TREE #0 */
#define BOX14 19  	/* OBJECT in TREE #0 */
#define BOX15 20  	/* OBJECT in TREE #0 */
#define CSLIDE 23  	/* OBJECT in TREE #0 */
#define RSLIDE 41  	/* OBJECT in TREE #0 */
#define GSLIDE 43  	/* OBJECT in TREE #0 */
#define BSLIDE 45  	/* OBJECT in TREE #0 */
#define SLIDE1 1  	/* TREE */
#define CTSLIDE 1  	/* OBJECT in TREE #1 */
#define SLIDE2 2  	/* TREE */
#define CSLIDERS 1  	/* OBJECT in TREE #2 */
#define EXIT1 2  	/* OBJECT in TREE #1 */
#define EXIT2 2  	/* OBJECT in TREE #2 */
#define CTITLE 3  	/* OBJECT in TREE #0 */
#define RTITLE 34  	/* OBJECT in TREE #0 */
#define GTITLE 35  	/* OBJECT in TREE #0 */
#define BTITLE 36  	/* OBJECT in TREE #0 */
#define BASE0 2  	/* OBJECT in TREE #0 */
#define BASE1 49  	/* OBJECT in TREE #0 */
#define BASER 50  	/* OBJECT in TREE #0 */
