/* Indice du ressource pour ALT_HELP */

#define FORM_DIALOG 0   /* Formulaire/Dialogue */
#define BTON_CANCEL 1   /* BUTTON dans l'arbre FORM_DIALOG */
#define FD_TEXT_SELECT_F 5   /* TEXT dans l'arbre FORM_DIALOG */
#define BTON_TWO_FILES 6   /* BUTTON dans l'arbre FORM_DIALOG */
#define FIELD_SCREEN_X 9   /* FTEXT dans l'arbre FORM_DIALOG */
#define FIELD_SCREEN_Y 10  /* FTEXT dans l'arbre FORM_DIALOG */
#define FIELD_SCREEN_NBP 12  /* FTEXT dans l'arbre FORM_DIALOG */
#define FIELD_GRAB_X 14  /* FTEXT dans l'arbre FORM_DIALOG */
#define FIELD_GRAB_Y 15  /* FTEXT dans l'arbre FORM_DIALOG */
#define FIELD_GRAB_W 17  /* FTEXT dans l'arbre FORM_DIALOG */
#define FIELD_GRAB_H 18  /* FTEXT dans l'arbre FORM_DIALOG */
#define BTON_QUIT_STAY 21  /* BUTTON dans l'arbre FORM_DIALOG */
