.TH CKDOOR 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
ckdoor.tos - check the doors file for errors
.SH SYNOPSIS
ckdoor
.SH DESCRIPTION
Ckdoor will check your doors file (ctdldoor.sys) to make sure that the various
files and directories exist, and that nothing else is amiss.  It expects to be
run from the directory where ctdldoor.sys lives (i.e. the #sysdir).
.SH OPTIONS
None.
.SH FILES
.DT
.ta \w'#sysdir\\ctdldoor.sys\ \ \ 'u
.br
ckdoor.tos	Door consistency checker.
.br
#sysdir\\ctdldoor.sys	Doors file.
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHORS
Originally written by David Parsons for STadel.
.PP
Used with minor changes for Fnordadel by Adrian Ashley and Royce Howland.
