.TH DUMPNET 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
dumpnet.tos - dump the net list in semi-human-readable form
.SH SYNOPSIS
dumpnet <filename>
.SH DESCRIPTION
Dumpnet will produce a listing on stdout of all the nodes in your
netlist, together with all rooms shared with each node, and other
information.  It is intended to be used with its companion program,
loadnet, to move netlists easily between versions of Fnordadel.
.PP
Dumpnet wants to be run in the directory containing ctdltabl.sys.
.SH OPTIONS
.IP <filename>
If the optional filename is supplied, dumpnet's output is
written to that file instead of to stdout.
.SH NOTES
If all you want to do is see what your net list looks like, try
using netmap.tos instead.  It's intended for that sort of thing,
whereas this program is more intended for nitty-gritty techie
stuff, or for use with loadnet.tos.
.SH FILES
.DT
.ta \w'#netdir\\ctdlnet.sys\ \ \ 'u
.br
dumpnet.tos	Net list dumper.
.br
ctdltabl.sys	System tables file.
.br
#netdir\\ctdlnet.sys	Network list.
.br
.SH SEE ALSO
.DT
.ta \w'netmap.man\ \ \ 'u
.br
netmap.man	Description of netmap.tos.
.br
The Fnordadel Reference Manual
.br
.SH AUTHOR
Originally written by David Parsons for the STadel system.
.PP
Modified for Fnordadel by Adrian Ashley and Royce Howland.
