.TH LCHANGE 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
lchange.tos - change the size of the Fnordadel user log
.SH SYNOPSIS
lchange <newsize>
.SH DESCRIPTION
Lchange will expand or shrink the Fnordadel user log file,
ctdllog.sys.  Give it the desired new size on the command line,
and lchange will munge away.  When it's finished it will remind
you to change ctdlcnfg.sys accordingly.  If you don't, you will
suffer a horrible death.  Trust us on this one.
.PP
Lchange expects to be run from the directory containing your
ctdltabl.sys file.  
.SH OPTIONS
.IP <newsize>
The desired new size of the log file.  There must be at
least 1 log entry and not more than 999 entries.
.SH NOTES
If the log is to be shrunk, lchange will keep the <newsize> most
recent log entries (i.e. the users who have called most recently), and
throw the rest away.
.PP
BACKUPS!  If you run this program without first backing up your
system, you richly deserve anything evil that could possibly
happen to you.  No, we don't predict trouble, but nobody can
avoid bad ju-ju.
.SH FILES
.DT
.ta \w'#sysdir\\ctdllog.sys\ \ \ 'u
.br
lchange.tos		The user log resizer.
.br
#sysdir\\ctdllog.sys	The user log.
.br
ctdlcnfg.sys		The configuration file.
.br
ctdltabl.sys		The system tables file.
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHORS
Originally written by David Parsons for STadel.
.PP
Modified by Adrian Ashley and Royce Howland for the Fnordadel
project.
