.TH LOGEDIT 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
logedit.tos - edit users' names & passwords
.SH SYNOPSIS
logedit
.SH DESCRIPTION
Logedit allows the Sysop to change names and/or passwords of users
in the user log.  Simply run logedit, and type the name or user log
entry number of the user to which you wish to effect a change.  Now
hit 'N' to change the user's name, 'P' to change the password, or 'K'
to kill the user entirely.  '?' will print a menu.
.PP
When you're done editing users, logedit will resort the log and
exit.
.PP
Logedit must be run from the directory containing ctdltabl.sys.
.SH OPTIONS
None.
.SH NOTES
This is a silly way of accomplishing precious little.  We promise
to either make this program more useful, or subsume its functions
into something else (like citadel.tos).  Real Soon Now, too.
.PP
Until such time, though, here it is.
.SH FILES
.DT
.ta \w'#sysdir\\ctdllog.sys\ \ \ 'u
.br
logedit.tos		The user log editor.
.br
#sysdir\\ctdllog.sys	The user log.
.br
ctdltabl.sys		The system tables file.
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHOR
Logedit was probably written by Hue, Jr., for Citadel-86 (though
we're not sure...).
.PP
It was undoubtedly modified in SOME way by David Parsons for STadel.
.PP
It was indubitably modified in ALMOST NO way by Adrian Ashley and
Royce Howland for Fnordadel.
