.TH MEXPAND 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
mexpand.tos - expand the message base
.SH SYNOPSIS
mexpand
.SH DESCRIPTION
Mexpand allows the Sysop to expand his message base.  The program
will report the current size of the message base, and ask for the
new size in kBytes.  The new number must be a multiple of 4K, or
it will be rounded up to the nearest 4K.  Mexpand will then do its
dirty work and report the new size when it is finished.
.PP
You MUST change #messagek in ctdlcnfg.sys and reconfigure the BBS.
Simply reconfiguring without changing ctdlcnfg.sys will result in an
ugly mess.  Don't do it.
.SH OPTIONS
None.
.SH NOTES
This program will only expand the message base.  The message base
can be shrunk using mshrink.tos, but it's better to pick the size
right in the first place. (-:
.SH FILES
.DT
.ta \w'#sysdir\\ctdlmsg.sys\ \ \ 'u
.br
mexpand.tos	Message base expander.
.br
ctdltabl.sys	System tables file.
.br
#sysdir\\ctdlmsg.sys	The message base.
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHORS
Mexpand was originally written (as "expand") by Hue, Jr., for
Citadel-86.
.PP
It was modified for STadel by David Parsons.
.PP
Mexpand was further munged (and renamed to "mexpand") by Adrian
Ashley and Royce Howland for Fnordadel.
