.TH NETMAP 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
netmap.tos - print a quickie synopsis of your net connections
.SH SYNOPSIS
netmap [-p]
.SH DESCRIPTION
Netmap will scan your net list and print each node name, followed
by a list of the rooms that your system is sharing with that node.
Backbone connections are flagged with an asterisk ("*").
.PP
Netmap expects to be run from the directory containing ctdltabl.sys.
.SH OPTIONS
.IP -p
Show only public rooms.
.SH NOTES
Not a lot to say, is there?
.SH FILES
.DT
.ta \w'#netdir\\ctdlnet.sys\ \ \ 'u
.br
netmap.tos	The net map printer outer.
.br
#netdir\\ctdlnet.sys	The net list.
.br
ctdltabl.sys	You don't know THIS?  RTFM! (-:
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHORS
Netmap was, we suppose, written by David Parsons for STadel.
.PP
It has been barely touched by Adrian Ashley & Royce Howland for
Fnordadel.
