.TH SCANZT 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
scanzt.tos - display the contents of the loop zap table
.SH SYNOPSIS
scanzt
.SH DESCRIPTION
Scanzt will dump the entire contents of ctdlloop.zap in a fairly
understandable format.  For each node on the whole wide network
from which your system has ever received a message, you will see
a list of all rooms in which you have received a message from that
system, and the date and message ID number from the header of the latest
message received.
.PP
Scanzt expects to be run in the directory containing ctdltabl.sys.
.SH OPTIONS
None.
.SH NOTES
The loop zapper is pretty robust.  If, however, you notice some kind of
corruption in the records (which might happen if a system on the net
simultaneously gets a whacked out date AND a corrupted message counter)
you can always run makezt.tos to regenerate the zap table.  This will
throw away all nodes except those with messages currently in your message
base, and will (hopefully) deal with any corruption.
.SH FILES
.DT
.ta \w'#netdir\\ctdlloop.zap\ \ \ 'u
.br
scanzt.tos	The zap table dumper.
.br
#netdir\\ctdlloop.zap	The zap table.
.br
ctdltabl.sys	The system table file.
.br
.SH SEE ALSO
.DT
.ta \w'makezt.man\ \ \ 'u
.br
makezt.man		Man page for makezt.tos.
.br
The Fnordadel Reference Manual
.br
.SH AUTHORS
Scanzt was written by David Parsons for STadel.
.PP
It was modified/enhanced by Adrian Ashley and Royce Howland for the
Fnordadel project.
