.TH SYSOP 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
sysop.tos - attach a background Fnordadel to the console
.SH SYNOPSIS
sysop
.SH DESCRIPTION
This program is useful only if you run Fnordadel in the background using
some sort of multitasker.  If you have placed Fnordadel in the background
using the ^Z key, this program will reattach it to the console.  It must be
run in your #sysdir, the directory where Fnordadel writes citadel.lck.
.SH OPTIONS
None.
.SH BUGS
We haven't really tested multitasking Fnordadel, so let us know if it
works.  (-:
.SH FILES
.DT
.ta \w'#sysdir\\citadel.lck\ \ \ 'u
.br
sysop.tos	Re-attacher program.
.br
#sysdir\\citadel.lck	The lockfile written by citadel.
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHORS
Written for STadel by David Parsons.
.PP
Minor modifications for Fnordadel by Adrian Ashley and Royce Howland.
