.TH VLOG 1 foo bar "FNORDADEL BBS SOFTWARE"
.SH NAME
vlog.tos - view the user log
.SH SYNOPSIS
vlog
.SH DESCRIPTION
Vlog allows the Sysop to view the contents of his user log in a highly
compact, tabular format.  It must be run from the directory in which
ctdltabl.sys resides.  Its output is sent to stdout, which may be
redirected (if running from a shell).
.PP
The users are displayed in the order in which they are stored in the
user log.  Passwords are not shown, but virtually every other piece of
information is shown.
.SH OPTIONS
None.
.SH BUGS
If there are any bugs in here, we'll be incredibly surprised.  However,
we won't guarantee anything in writing.
.SH FILES
.DT
.ta \w'#sysdir\\ctdllog.sys\ \ \ 'u
.br
vlog.tos	Userlog viewer program.
.br
ctdltabl.sys	Tables file.
.br
#sysdir\\ctdllog.sys	The user log file.
.br
.SH SEE ALSO
The Fnordadel Reference Manual
.SH AUTHORS
Originally written by Eric A. Griff, for an Amiga Citadel variant.
.PP
Probably no modifications for STadel by Davin Parsons.
.PP
Minor modifications for Fnordadel by Adrian Ashley and Royce Howland.
