#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c
.s.o:
	mac $(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	c:\bin\cp68.prg $(CFLAGS) $*.c m:$*.i
	c:\bin\c068.prg m:$*.i m:$*.1 m:$*.2 m:$*.3 -f
	rm m:$*.i
	c:\bin\c168.prg m:$*.1 m:$*.2 m:$*.s
	c:\bin\mac.prg -6 -o $*.o m:$*.s
	rm m:$*.1 m:$*.2 m:$*.s

TEMP = m:tmp
LIBS = vdibind aesbind gemlib libf

OBJS =	gemstart.o osbind.o bootstop.o blktst.o mymalloc.o reboot.o\
	addr.o bsl.o dsmark.o stepart.o error.o fmt.o getln.o getstart.o hdx.o\
	markbad.o mediach.o part.o sect.o ship.o st.o string.o toascii.o tstbus.o\
	wincap.o zero.o epart.o acsi.o scsi.o doit.o cmdblk.o check.o 68030.o

hdx.prg : $(OBJS)
	echo $(OBJS) $(LIBS) >$(TEMP)
	aln -s -o hdx.prg -c $(TEMP)


#
#  assembly-language files
#
acsi.o		: acsi.s
scsi.o		: scsi.s
cmdblk.o	: cmdblk.s
doit.o		: doit.s
check.o		: check.s
68030.o		: 68030.s
tstbus.o	: tstbus.s
blktst.o 	: blktst.s
bootstop.o 	: bootstop.s
gemstart.o 	: gemstart.s
mymalloc.o 	: mymalloc.s
osbind.o 	: osbind.s
ship.o 		: ship.s
reboot.o 	: reboot.s

#
#  C sources
#
addr.o 		: addr.c
bsl.o 		: bsl.c
toascii.o 	: toascii.c
dsmark.o 	: dsmark.c
stepart.o 	: stepart.c
epart.o 	: epart.c
error.o 	: error.c
fmt.o 		: fmt.c
getln.o 	: getln.c
getstart.o 	: getstart.c
hdx.o 		: hdx.c
markbad.o 	: markbad.c
part.o 		: part.c
sect.o 		: sect.c
st.o 		: st.c
string.o 	: string.c
wincap.o 	: wincap.c
zero.o 		: zero.c
