# The makefile I used to make the program/accessory with Laser C
# The variable $(SINIT) is defined in my environment as my
# startup code. After it is made this makefile copies it to the
# root directory of drive C to be used as an accessory

boinkout.prg : boinkout.o bout2.o bout3.o bout4.o boinkout.h
	$(LINKER) -o boinkout.prg lasinit.o lasstack.o\
 boinkout.o bout2.o bout3.o bout4.o svro.o $(CLIB)

boinkout.o bout2.o bout3.o bout4.o : boinkout.h
