.\" Info-ZIP grants permission to any individual or institution to use, copy,
.\" or redistribute this software, so long as:  (1) all of the original files
.\" are included; (2) it is not sold for profit; and (3) this notice is re-
.\" tained.  See the UnZip COPYING file for details.
.\"
.\" funzip.1 by Greg Roelofs and others.
.\"
.\" =========================================================================
.\" define .Y macro (for user-command examples; normal Courier font):
.de Y
.ft CW
.in +4n
.nf
\&\\$1
.ft
.in
.fi
..
.\" =========================================================================
.TH FUNZIP 1 "2 Aug 94 (v3.83)"
.SH NAME
funzip \- filter for extracting from a ZIP archive in a pipe
.\" =========================================================================
.SH SYNOPSIS
[.\|.\|.]  |\ \ \fBfunzip\fP [\fB\-password\fP]\ \ |  [.\|.\|.]
.LP
\fBfunzip\fP [\fB\-password\fP] \fIinput.zip\fP\ \ |  [.\|.\|.]
.\" =========================================================================
.SH ARGUMENTS
.IP [\fI\-password\fP]
Optional password to be used if ZIP archive is encrypted.  Decryption
may not be supported at some sites.  See DESCRIPTION for more details.
.PD
.\" =========================================================================
.SH DESCRIPTION
.I funzip
acts as a filter; that is, it assumes that a ZIP archive is being piped into
standard input, and it extracts the first member from the archive to stdout.
If there is an argument, then the input comes from the specified file
instead of from stdin.  A password for encrypted zip files can be specified
on the command line (preceding the file name, if any) by prefixing the
password with a dash.  Note that this constitutes a security risk on many
systems; currently running processes are often visible via simple commands
(e.g., \fIps\fP(1) under Unix), and command-line histories can be read.
If the first entry of the zip file is encrypted and
no password is specified on the command line, then the user is prompted for
a password and the password is not echoed on the console.
.LP
Given the limitation on single-member extraction, \fIfunzip\fP is most
useful in conjunction with a secondary archiver program such as \fItar\fP(1).
The following section includes an example illustrating this usage in the
case of disk backups to tape.
.PD
.\" =========================================================================
.SH EXAMPLES
To use \fIfunzip\fP to extract the first member file of the archive test.zip
and to pipe it into \fImore\fP(1):
.LP
.Y "funzip test.zip | more"
.LP
To use \fIfunzip\fP to test the first member file of test.zip (any errors
will be reported on standard error):
.LP
.Y "funzip test.zip > /dev/null"
.LP
To use \fIzip\fP and \fIfunzip\fP in place of \fIcompress\fP(1) and
\fIzcat\fP(1) (or \fIgzip\fP(1L) and \fIgzcat\fP(1L)) for tape backups:
.LP
.PD 0
.Y "tar cf \- . | zip \-7 | dd of=/dev/nrst0 obs=8k"
.Y "dd if=/dev/nrst0 ibs=8k | funzip | tar xf \-"
.PD
.LP
(where, for example, nrst0 is a SCSI tape drive).
.PD
.\" =========================================================================
.SH BUGS
When piping an encrypted file into \fImore\fP and allowing \fIfunzip\fP
to prompt for password, the terminal may sometimes be reset to a non-echo
mode.  This is apparently due to a race condition between the two programs;
\fIfunzip\fP changes the terminal mode to non-echo before \fImore\fP reads
its state, and \fImore\fP then ``restores'' the terminal to this mode before
exiting.  To recover, run \fIfunzip\fP on the same file but redirect to
/dev/null rather than piping into more; after prompting again for the 
password, \fIfunzip\fP will reset the terminal properly.
.LP
There is presently no way to extract any member but the first from a ZIP
archive.  This would be useful in the case where a ZIP archive is included
within another archive.  In the case where the first member is a directory,
\fIfunzip\fP simply creates the directory and exits.
.LP
The functionality of \fIfunzip\fP should be incorporated into \fIunzip\fP
itself (future release).
.PD
.\" =========================================================================
.SH SEE ALSO
\fIgzip\fP(1L), \fIunzip\fP(1L), \fIunzipsfx\fP(1L), \fIzip\fP(1L),
\fIzipcloak\fP(1L), \fIzipinfo\fP(1L), \fIzipnote\fP(1L), \fIzipsplit\fP(1L)
.PD
.\" =========================================================================
.SH AUTHOR
Mark Adler (Info-ZIP)
