#define LOGCTRL 0  	/* TREE */
#define CLI_API 1  	/* TREE */
#define MOD_API 2  	/* TREE */
#define VERSION 4  	/* OBJECT in TREE #0 */
#define ACTIVE 6  	/* OBJECT in TREE #0 */
#define PARAS 9  	/* OBJECT in TREE #0 */
#define POINTER 12  	/* OBJECT in TREE #0 */
#define BUFFER 15  	/* OBJECT in TREE #0 */
#define INTERNAL 18  	/* OBJECT in TREE #0 */
#define CACHE 21  	/* OBJECT in TREE #0 */
#define FILE 25  	/* OBJECT in TREE #0 */
#define FILENAM 27  	/* OBJECT in TREE #0 */
#define PIPE 28  	/* OBJECT in TREE #0 */
#define PIPENAM 29  	/* OBJECT in TREE #0 */
#define CLIENT 30  	/* OBJECT in TREE #0 */
#define TERM 31  	/* OBJECT in TREE #0 */
#define MODULE 32  	/* OBJECT in TREE #0 */
#define FIX 33  	/* OBJECT in TREE #0 */
#define CANCEL 34  	/* OBJECT in TREE #0 */
#define C_TOPEN 4  	/* OBJECT in TREE #1 */
#define C_TCLOSE 7  	/* OBJECT in TREE #1 */
#define C_TSEND 10  	/* OBJECT in TREE #1 */
#define C_TSTATE 13  	/* OBJECT in TREE #1 */
#define C_TACK 16  	/* OBJECT in TREE #1 */
#define C_TINFO 19  	/* OBJECT in TREE #1 */
#define C_UOPEN 23  	/* OBJECT in TREE #1 */
#define C_UCLOSE 26  	/* OBJECT in TREE #1 */
#define C_USEND 29  	/* OBJECT in TREE #1 */
#define C_ISEND 33  	/* OBJECT in TREE #1 */
#define C_IHNDLR 36  	/* OBJECT in TREE #1 */
#define C_IDSCRD 39  	/* OBJECT in TREE #1 */
#define C_CGNDB 43  	/* OBJECT in TREE #1 */
#define C_CGBLK 46  	/* OBJECT in TREE #1 */
#define C_CGCHAR 49  	/* OBJECT in TREE #1 */
#define C_CGS 52  	/* OBJECT in TREE #1 */
#define C_CBCNT 55  	/* OBJECT in TREE #1 */
#define C_CGINFO 58  	/* OBJECT in TREE #1 */
#define C_CKICK 61  	/* OBJECT in TREE #1 */
#define C_KMALL 65  	/* OBJECT in TREE #1 */
#define C_KREALL 68  	/* OBJECT in TREE #1 */
#define C_KFREE 71  	/* OBJECT in TREE #1 */
#define C_KGETFR 74  	/* OBJECT in TREE #1 */
#define C_GTVSTR 78  	/* OBJECT in TREE #1 */
#define C_STVSTR 81  	/* OBJECT in TREE #1 */
#define C_ONPRT 85  	/* OBJECT in TREE #1 */
#define C_OFFPRT 88  	/* OBJECT in TREE #1 */
#define C_QUPRT 91  	/* OBJECT in TREE #1 */
#define C_CTLPRT 94  	/* OBJECT in TREE #1 */
#define C_RSLV 97  	/* OBJECT in TREE #1 */
#define C_SETFLG 101  	/* OBJECT in TREE #1 */
#define C_CLRFLG 104  	/* OBJECT in TREE #1 */
#define C_ERRTXT 107  	/* OBJECT in TREE #1 */
#define C_HSKEEP 111  	/* OBJECT in TREE #1 */
#define C_CARDET 114  	/* OBJECT in TREE #1 */
#define C_SEREN 117  	/* OBJECT in TREE #1 */
#define C_SERDIS 120  	/* OBJECT in TREE #1 */
#define C_ALL 127  	/* OBJECT in TREE #1 */
#define C_NONE 128  	/* OBJECT in TREE #1 */
#define C_OK 129  	/* OBJECT in TREE #1 */
#define C_CANCEL 130  	/* OBJECT in TREE #1 */
#define M_IPSEND 4  	/* OBJECT in TREE #2 */
#define M_IPFTCH 7  	/* OBJECT in TREE #2 */
#define M_IPHAND 10  	/* OBJECT in TREE #2 */
#define M_IPDISC 13  	/* OBJECT in TREE #2 */
#define M_PANNOU 17  	/* OBJECT in TREE #2 */
#define M_PGTPAR 20  	/* OBJECT in TREE #2 */
#define M_PREQU 23  	/* OBJECT in TREE #2 */
#define M_PRELEA 26  	/* OBJECT in TREE #2 */
#define M_PLOOK 29  	/* OBJECT in TREE #2 */
#define M_EXEC 32  	/* OBJECT in TREE #2 */
#define M_TCALL 36  	/* OBJECT in TREE #2 */
#define M_TNOW 39  	/* OBJECT in TREE #2 */
#define M_TELAPS 42  	/* OBJECT in TREE #2 */
#define M_SETTTL 46  	/* OBJECT in TREE #2 */
#define M_CHKTTL 49  	/* OBJECT in TREE #2 */
#define M_SETSYS 52  	/* OBJECT in TREE #2 */
#define M_QUCHNS 55  	/* OBJECT in TREE #2 */
#define M_GTROUT 59  	/* OBJECT in TREE #2 */
#define M_STROUT 62  	/* OBJECT in TREE #2 */
#define M_LDROUT 65  	/* OBJECT in TREE #2 */
#define M_ALL 72  	/* OBJECT in TREE #2 */
#define M_NONE 73  	/* OBJECT in TREE #2 */
#define M_OK 74  	/* OBJECT in TREE #2 */
#define M_CANCEL 75  	/* OBJECT in TREE #2 */
