#
# The 'T' macro determines the target to be made in each subdirectory.
# If unassigned, the default target will be used. To clean up the
# subdirectories, invoke make as follows:
#
#	make T=clean
#
# To run make in specific subdirectories, use a command like:
#
#	make T=clobber tools lib top
#

PROGS = hcc jas ld make tools top

LIBS = libfp

ALL = $(PROGS) $(LIBS)

all: $(ALL)

progs: $(PROGS)

libs: $(LIBS)

$(ALL):
	make -c $@ $(T)
