#
#	Toplevel Makefile for MiNT-Net, a networking extension based on
#	the MiNT multitasking operating system extension for Atari
#	Computers.
#

SHELL = /bin/sh

SUBDIRS = net lib tool test

all: netdev library tool

library:
	$(MAKE) -C lib

netdev:
	$(MAKE) -C net XDD="a"

tests:
	$(MAKE) -C test

tools:
	$(MAKE) -C tool

clean:
	@for i in $(SUBDIRS); do $(MAKE) -C $$i clean; done;

depend:
	@for i in $(SUBDIRS); do $(MAKE) -C $$i depend; done;
