
OBJ   =  cpxstart.o sample.o

sample.cp:	$(OBJ)
		ld -o sample.cp $(OBJ) c:\mwc\lib\libaes.a c:\mwc\lib\libvdi.a c:\mwc\lib\libc.a
		
sample.o:	sample.c sample.h sample.rsh
		cc -c sample.c

cpxstart.o:	cpxstart.s
		mac -fmu cpxstart.s
				
