	; Indice du ressource pour PROJECT *

MENU_PRINCIPAL = 0	; Arbre menu *
MNU_DESK_INFO = 7	; STRING dans l'arbre MENU_PRINCIPAL *
MNU_FILE_OPEN = 16	; STRING dans l'arbre MENU_PRINCIPAL *
MNU_FILE_QUIT = 17	; STRING dans l'arbre MENU_PRINCIPAL *

FORM_INFORMATION = 1	; FormulaireDialogue *

FORM_BACKGROUND = 2	; FormulaireDialogue *

ALERT1 = 0   	; Chaine d'alerte *

ALERT_NO_ACC_RUN = 1	; Chaine d'alerte *
