.TH DEFRAG 8 "December 23, 1992"
.SH NAME
[e]defrag - defragment file systems.
.SH SYNOPSIS
.B defrag
|
.B defrag2 
[
.B -Vdrsv
] [
.B -p 
.I pool-size
]
.I X:

.SH DESCRIPTION
.I Defrag 
will reorganise data on a minix file system partition in order
to improve the file system's performance.
.I Defrag2 
is the equivalent
program for the V2 file system.
.PP
Remember, if
.I defrag
fails for any reason (including power glitches, kernel bugs etc.), you
will be left with a terminally sick file system, so backup any
valuable data before you start.
.SH OPTIONS
.TP
.B -V
Supply full version information.  If you are sending bug reports,
please include this information.
.TP
.B -d
Run in debugging mode.  This will not be available if disabled at
compile-time.
.TP
.B -r
Readonly mode.  
.I Defrag
will scan the file system and simulate the job
of defragmentation, but will not write to the file system.  This can
be used for debugging or testing.  It may also be used to find out how
much work
.I defrag
will have to do, in order to choose a sensible
.I pool-size
.
.TP
.B -s
Summarise file system information and
.I
defrag
performance statistics.
.TP
.B -v
Verbose - gives a progress report as defragmentation proceeds.  If
.B -v
is given twice, then a more detailed report is supplied.
.TP
.BI -p " number"
Selects the number of (1KB) buffers allocated to the defragmenter's
buffer pool.  These buffers are used when relocating data, so the more
buffers allocated, the more efficient the relocation process.  The
number you choose will depend on how much physical and virtual memory
you have available.
.SH BUGS
Maybe, but then that's why you backed up your data first, isn't it?
.SH AUTHORS
.LP
Written by Stephen Tweedie.  The initial version was based on the
.I fsck
/
.I efsck
programs by Linus Torvalds and Remy Card.
Atari ST version modified for MiNT/Minixfs by S N Henson. Bug reports to
shenson@nyx.cs.du.edu please.
