#
# Makefile for pclcomp using gcc
#
CC = gcc
CFLAGS = -O2 -fomit-frame-pointer
LIBS =

OBJS = getopt.o pclcomp.o

all: pclcomp

pclcomp: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) -o pclcomp

# -eof-
