/* Indices de ressource pour BIGDEMO */

#define MENU     0   /* Menu */
#define T_BUREAU 3   /* TITLE dans l'arbre MENU */
#define T_FICHIER 4   /* TITLE dans l'arbre MENU */
#define T_FENETRES 5   /* TITLE dans l'arbre MENU */
#define M_INFOS  8   /* STRING dans l'arbre MENU */
#define M_FORMLIBRE 17  /* STRING dans l'arbre MENU */
#define M_ALERTE 18  /* STRING dans l'arbre MENU */
#define M_QUITTER 19  /* STRING dans l'arbre MENU */
#define M_WFORMPETIT 21  /* STRING dans l'arbre MENU */
#define M_WFORMGRAND 22  /* STRING dans l'arbre MENU */
#define M_WWIND  23  /* STRING dans l'arbre MENU */
#define M_WMENU  24  /* STRING dans l'arbre MENU */

#define BUREAU   1   /* Formulaire/Dialogue */
#define BU_ICN   1   /* ICON dans l'arbre BUREAU */
#define BU_BOXTXT 2   /* BOX dans l'arbre BUREAU */
#define BU_TXT1  3   /* STRING dans l'arbre BUREAU */
#define BU_TXT2  4   /* STRING dans l'arbre BUREAU */

#define FORMULAIRE 2   /* Formulaire/Dialogue */
#define CADRE1   3   /* BUTTON dans l'arbre FORMULAIRE */
#define CADRE2   6   /* BUTTON dans l'arbre FORMULAIRE */
#define TXT1     16  /* FTEXT dans l'arbre FORMULAIRE */
#define TXT2     17  /* FTEXT dans l'arbre FORMULAIRE */
#define P_CONFIRME 18  /* BUTTON dans l'arbre FORMULAIRE */
#define P_AIDE   19  /* BOXTEXT dans l'arbre FORMULAIRE */
#define P_ANNULE 20  /* BUTTON dans l'arbre FORMULAIRE */

#define POP_UP1  3   /* Formulaire/Dialogue */

#define POP_UP2  4   /* Formulaire/Dialogue */

#define INFOS    5   /* Formulaire/Dialogue */
#define INF_INFOS 14  /* BOXTEXT dans l'arbre INFOS */
#define INF_SORTIE 15  /* BUTTON dans l'arbre INFOS */

#define AIDE1    6   /* Formulaire/Dialogue */

#define PETITFORM 7   /* Formulaire/Dialogue */
#define TRAME_1  3   /* BOX dans l'arbre PETITFORM */
#define TRAME_2  4   /* BOX dans l'arbre PETITFORM */
#define TRAME_3  5   /* BOX dans l'arbre PETITFORM */
#define TRAME_4  6   /* BOX dans l'arbre PETITFORM */
#define TRAME_5  7   /* BOX dans l'arbre PETITFORM */
#define TRAME_6  8   /* BOX dans l'arbre PETITFORM */
#define TRAME_7  9   /* BOX dans l'arbre PETITFORM */
#define TRAME_8  10  /* BOX dans l'arbre PETITFORM */
#define PF_CHAMP1 13  /* FTEXT dans l'arbre PETITFORM */
#define PF_CHAMP2 14  /* FTEXT dans l'arbre PETITFORM */
#define PF_CHAMP3 15  /* FTEXT dans l'arbre PETITFORM */
#define PF_CHAMP4 16  /* FTEXT dans l'arbre PETITFORM */
#define PF_CONFIRME 17  /* BUTTON dans l'arbre PETITFORM */
#define PF_ANNULE 18  /* BUTTON dans l'arbre PETITFORM */
#define PF_AIDE  19  /* BOXTEXT dans l'arbre PETITFORM */
#define PF_APPLIQUE 20  /* BUTTON dans l'arbre PETITFORM */
#define PF_RAZ   21  /* BUTTON dans l'arbre PETITFORM */

#define GRANDFORM 8   /* Formulaire/Dialogue */
#define GF_ICN   20  /* IMAGE dans l'arbre GRANDFORM */
#define GF_PU1   21  /* BUTTON dans l'arbre GRANDFORM */
#define GF_PU2   22  /* BUTTON dans l'arbre GRANDFORM */
#define GF_CONFIRME 23  /* BUTTON dans l'arbre GRANDFORM */
#define GF_ANNULE 24  /* BUTTON dans l'arbre GRANDFORM */
#define GF_AIDE  25  /* BOXTEXT dans l'arbre GRANDFORM */
#define GF_APPLIQUE 26  /* BUTTON dans l'arbre GRANDFORM */
#define GF_RAZ   27  /* BUTTON dans l'arbre GRANDFORM */

#define W_MENU   9   /* Menu */
#define TW_BUREAU 3   /* TITLE dans l'arbre W_MENU */
#define TW_OPTIONS 4   /* TITLE dans l'arbre W_MENU */
#define TW_ALERTS 5   /* TITLE dans l'arbre W_MENU */
#define MW_INFOS 8   /* STRING dans l'arbre W_MENU */
#define MW_IMAGE 17  /* STRING dans l'arbre W_MENU */
#define MW_ALERTE 18  /* STRING dans l'arbre W_MENU */
#define MW_ICN   20  /* STRING dans l'arbre W_MENU */

#define MHIERA   10  /* Formulaire/Dialogue */
#define MH_HISTO 3   /* STRING dans l'arbre MHIERA */

#define POPUP_ICN 11  /* Formulaire/Dialogue */

#define PU_LIBRE 12  /* Formulaire/Dialogue */
#define PUL_ALERT 3   /* STRING dans l'arbre PU_LIBRE */
#define PUL_WMENU 9   /* STRING dans l'arbre PU_LIBRE */

#define CONTACT  13  /* Formulaire/Dialogue */

#define AIDE2    14  /* Formulaire/Dialogue */

#define HIERWIND 15  /* Formulaire/Dialogue */
#define MWH_ICN0 1   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN1 2   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN2 3   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN3 4   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN4 5   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN5 6   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN6 7   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN7 8   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN8 9   /* STRING dans l'arbre HIERWIND */
#define MWH_ICN9 10  /* STRING dans l'arbre HIERWIND */

#define ALERTE   0   /* Chaåne d'alerte */

#define AL_ICONES 1   /* Chaåne d'alerte */

#define AL_POINTEUR 2   /* Chaåne d'alerte */

#define TITRE_PF 3   /* Chaåne libre */

#define TITRE_GF 4   /* Chaåne libre */

#define CHARGETXT 5   /* Chaåne libre */

#define CHARGEIMG 6   /* Chaåne libre */

#define TIT_TXT  7   /* Chaåne libre */

#define TIT_IMG  8   /* Chaåne libre */

#define TIT_MENU 9   /* Chaåne libre */

#define TIT_HIST 10  /* Chaåne libre */

#define INF_HIST 11  /* Chaåne libre */
