FSMACC = fsmacc.o fsmfon.o fsmio.o fsmdev.o textblit.o
CFLAGS = -A

fsmacc:
	cc -c -A -DDESKACC fsmacc.c
	cc -c -A -DDESKACC fsmfon.c
	cc -c -A -DDESKACC fsmio.c
	cc -c -A -DDESKACC fsmdev.c
	cc -o fontman.acc -VGEMACC $(FSMACC)

fsmprg:
	cc -c -A -UDESKACC fsmacc.c
	cc -c -A -UDESKACC fsmfon.c
	cc -c -A -UDESKACC fsmio.c
	cc -c -A -UDESKACC fsmdev.c
	cc -o fontman.prg -VGEM $(FSMACC)

fon:
	cc -c -A -UDESKACC fsmfon.c
	cc -o fontman.prg -VGEM $(FSMACC)
io:
	cc -c -A -UDESKACC fsmio.c
	cc -o fontman.prg -VGEM $(FSMACC)
acc:
	cc -c -A -UDESKACC fsmacc.c
	cc -o fontman.prg -VGEM $(FSMACC)

dev:
	cc -c -A -UDESKACC fsmdev.c
	cc -o fontman.prg -VGEM $(FSMACC)

link:
	cc -o fontman.prg -VGEM $(FSMACC)

linkacc:
	cc -o fontman.acc -VGEMACC $(FSMACC)

acconly:
	cc -c -DDESKACC fsmacc.c
	cc -o fontman.acc -VGEMACC $(FSMACC)

accbitcache:
	cc -c -DDESKACC fsmacc.c
	cc -c -DDESKACC fsmfon.c
	cc -c -DDESKACC fsmdev.c
	cc -c -UFSM_CACHE -DDESKACC fsmio.c
	cc -o fontman.acc -VGEMACC $(FSMACC)

accfsmcache:
	cc -c -A -DDESKACC fsmacc.c
	cc -c -A -DDESKACC fsmfon.c
	cc -c -A -DDESKACC fsmdev.c
	cc -c -A -DFSM_CACHE -DDESKACC fsmio.c
	cc -o fontman.acc -VGEMACC $(FSMACC)
