DUMPFLAGS	= -cusrt -ff -m0 -q5w5e -O -v
LIBSFFP	= lib:lcmffp.lib lib:lcnb.lib lib:amiga.lib

dump2iff:	dump2iff.o palette.o showprioq.o gio.o iffw.o ilbmw.o putpict.o\
                packer.o
		blink FROM lib:c.o dump2iff.o palette.o showprioq.o gio.o iffw.o\
		ilbmw.o putpict.o packer.o LIB $(LIBSFFP) TO dump2iff

dump2iff.o:	dump2iff.c
		$(CC) $(DUMPFLAGS) $*

palette.o:	palette.c showprioq.h
		$(CC) $(DUMPFLAGS) $*

showprioq.o:	showprioq.c showprioq.h
		$(CC) $(DUMPFLAGS) $*

gio.o:		gio.c
		$(CC) $(DUMPFLAGS) $*

iffw.o:		iffw.c
		$(CC) $(DUMPFLAGS) $*

ilbmw.o:		ilbmw.c
		$(CC) $(DUMPFLAGS) $*

putpict.o:		putpict.c
		$(CC) $(DUMPFLAGS) $*

packer.o:		packer.c
		$(CC) $(DUMPFLAGS) $*
