#
# Floating point code written by Johann. Single-precision only, using
# the "Fast Floating Point" representation. The file "fpdiv.s" is
# actually derived from "_fpdiv.c" but has to be modified by hand
# to create an entry point without a leading underscore.
#

OBJ=	fpcmp.o \
	fpconv.o \
	fpdiv.o \
	fpadd.o \
	fpmul.o \
	fp_prt.o \
	fp_scan.o \
	printf.o \
	scanf.o

LIBM=libm.a

CC=cc
AR=ar

CFLAGS= -O -DFLOATS=1
ARMODE= q

.c.o :
	$(CC) -c $(CFLAGS) $<
	$(AR) $(ARMODE) $(LIBM) $*.o

.s.o :
	$(CC) -c $(CFLAGS) $<
	$(AR) $(ARMODE) $(LIBM) $*.o

all: $(LIBM)
	$(ECHO) Floating Point Library complete

$(LIBM): $(OBJ)

clean:
	$(RM) $(LIBM)
