#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c
.s.o:
	mac $(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	@c:\alcyon\cp68.prg $(CFLAGS) -i c:\alcyon\include\ $*.c m:$*.i
	@c:\alcyon\c068.prg m:$*.i m:$*.1 m:$*.2 m:$*.3 -f
	@rm m:$*.i
	@c:\alcyon\c168.prg m:$*.1 m:$*.2 m:$*.s
	@c:\bin\mac.prg -6 -o $*.o m:$*.s
	@rm m:$*.1 m:$*.2 m:$*.s

TEMP = m:tmp
LIBS = vdibind aesbind gemlib libf osbind.o

OBJS =	gemstart.o bootstop.o acsi.o blktst.o check.o cmdblk.o cookie.o\
	doit.o ide.o mediach.o mymalloc.o reboot.o scsi.o spscsi.o ship.o\
	addr.o assist.o bsl.o bslscrol.o convert.o deflst.o defscrol.o\
	dsmark.o epart.o error.o fhdx.o fmt.o getln.o part.o sect.o\
	st.o string.o wincap.o

fhdx.prg : $(OBJS)
	echo $(OBJS) $(LIBS) >$(TEMP)
	aln -l -o fhdx.prg -c $(TEMP)


#
#  assembly-language files
#
acsi.o : acsi.s defs.h
blktst.o : blktst.s
bootstop.o : bootstop.s
check.o : check.s
cmdblk.o : cmdblk.s
cookie.o : cookie.s
doit.o : doit.s
gemstart.o : gemstart.s
ide.o : ide.s ide.h mfp.h
mymalloc.o : mymalloc.s
reboot.o : reboot.s
scsi.o : scsi.s defs.h mfp.h
ship.o : ship.s
spscsi.o : spscsi.s defs.h spscsi.h acsi.h

#
#  C sources
#
assist.o : assist.c
bsl.o : bsl.c
bslscrol.o : bslscrol.c
convert.o : convert.c
deflst.o : deflst.c
defscrol.o : defscrol.c
dsmark.o : dsmark.c
epart.o : epart.c
error.o : error.c
fhdx.o : fhdx.c fhdx.h
fmt.o : fmt.c
getln.o : getln.c
part.o : part.c
sect.o : sect.c
st.o : st.c
string.o : string.c
wincap.o : wincap.c

