#
# makefile fuer das Probeprogramm zu GEM-Manager
# 
#
OBJ = gemprog.o gem_allg.o gem_key.o gem_objc.o gem_wind.o
gemprog.prg:    $(OBJ)
                cc   -VGEM -o gemprog.prg $(OBJ) -lmans
gemprog.o:	gemprog.h gemprog1.h
gem_allg.o:	gemprog1.h
gem_wind.o:	gemprog1.h

