# Makefile for start.prg   

CFLAGS = -A -DDEBUG -VCSD
CFFLAGS = -A

AUTO = c:\auto

all: start.prg run.prg
start.prg: start.c
	cc $(CFLAGS) -o start.prg start.c


run.prg:	run.c
	cc $(CFLAGS) -o run.prg run.c	

install: start.c
	cc $(CFFLAGS) -o start.prg start.c
	mv start.prg $(AUTO)
	mv run.prg $(AUTO)\run.prx
