# disable the code improver for faster compiles, change to an echo command
MMIMP = %e

twister.prg : mmtwst.o twister.o
		$(LINKER) twister.o mmtwst.o -o twister.prg

twister.o : twister.h twster.rsh

twster.rsh : twister.rsh
		$(CPATH)\nolast.ttp twister.rsh twster.rsh

