

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0FILES\KERNEL\KERNEL.PRG		0FILES.A\KERNEL.NRV



pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\88COMPR\ST.TC\TCVQ_ST.PRG	0FILES\TCVQ_ST.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\BOUNCE\BOUNCE.PRG			0FILES\BOUNCE.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\BUMP\TD_BUMP.PRG				0FILES\TD_BUMP.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\ENGE\ENGE.PRG				0FILES\ENGE.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\ICIRCLES\ICIRCLES.PRG		0FILES\ICIRCLES.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\INSPHERE\INSPHERE.PRG		0FILES\INSPHERE.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\INTRO\INTRO.PRG				0FILES\INTRO.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\MACHINE\MACHINE.PRG			0FILES\MACHINE.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\MORPHDOT\MORPHDOT.PRG		0FILES\MORPHDOT.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\OSZI\OSZI.PRG				0FILES\OSZI.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\RMARCH.INT\RMINTRO.PRG		0FILES\RMINTRO.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\RMARCH\RAYMARCH.PRG			0FILES\RAYMARCH.NRV	

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\SHDBOBS\SHDBOBS.PRG			0FILES\SHDBOBS.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\SPLINES\SPLFILL.PRG			0FILES\SPLFILL.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\SQRFEEDB\SQRFEEDB.PRG		0FILES\SQRFEEDB.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\TD_BIG\TD_BIG.PRG			0FILES\TD_BIG.NRV



pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\PT2_LOAD\PT2_LOAD.PRG		0FILES\PT2_LOAD.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0FILES\BOOT\LOADEFF\LOAD1.PRG	0FILES\LOAD1.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\CPTLUCAS\CPTLUCAS.PRG			0FILES\CPTLUCAS.NRV




REM pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0VQSPL.ST\DRIVER.PRG		0FILES.A\DRIVER.NRV

REM DISK 2 FILES
pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\88COMPR\ST.TC\PC_ST_TC_ENC\VIDSTR_0.DAT	0FILES.B\VIDSTR_0.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\RMARCH\PC_PREC\RMDATA.DAT				0FILES.B\RMDATA.NRV




