# makefile fÅr EULER

# Change 8x13 to your favorite text font.
# Delete -DRS6000 on non IBM RS6000 machines.

CC=cc
CFLAGS=-O -DFONT=\"8x13\" -DGFONT=\"8x13\" -DRS6000

euler: sysdepx.o edit.o mainloop.o express.o funcs.o matheh.o extend.o\
		polynom.o helpf.o graphics.o makefile
	$(CC) -o xeuler sysdepx.o edit.o mainloop.o express.o\
		matheh.o extend.o polynom.o helpf.o funcs.o\
		graphics.o -lm -lX11

sysdepx.o: header.h sysdep.h icon.h sysdepx.c

edit.o: header.h sysdep.h graphics.h

funcs.o: header.h sysdep.h funcs.h graphics.h

express.o: header.h sysdep.h funcs.h

funcs.o: header.h sysdep.h funcs.h matheh.h polynom.h helpf.h graphics.h

matheh.o: header.h sysdep.h matheh.h

extend.o: header.h

polynom.o: header.h polynom.h funcs.h matheh.h

helpf.o: header.h funcs.h helpf.h matheh.h

graphics.o: header.h graphics.h

mainloop.o: header.h sysdep.h funcs.h graphics.h

install:
	mv xeuler ../progs/xeuler

tar:
	rm -f euler.tar euler.tar.z
	tar -cf euler.tar\
		*.c *.h makefile readme.*\
		../progs/euler.doc ../progs/util.e\
		../progs/demo.e ../progs/help.e ../progs/euler.cfg
	gzip euler.tar
