CFLAGS = -Wall -O -mshort -fomit-frame-pointer

OBJS= main.o fsck1.o fsck2.o io.o common.o ../hdio.o ../tinyxhdi.o

all: fsck.ttp

include ../dirs

$(OBJS): fs.h fsck.h proto.h stproto.h global.h

fsck1.o: fsck.c
	$(CC) -DV1 $(CFLAGS) -c -o fsck1.o fsck.c

fsck2.o: fsck.c
	$(CC) -DV2 $(CFLAGS) -c -o fsck2.o fsck.c

../hdio.o: ../minixfs/hdio.c
	$(CC) $(CFLAGS) -c ../minixfs/hdio.c -o ../hdio.o

../tinyxhdi.o: ../minixfs/tinyxhdi.c
	$(CC) $(CFLAGS) -DTINY_XHDI -c ../minixfs/tinyxhdi.c -o ../tinyxhdi.o

fsck.ttp: $(OBJS)
	$(CC) $(CFLAGS) -o fsck.ttp $(OBJS) -liio16

install: fsck.ttp
	$(INSTALL) fsck.ttp $(UTILDIR)

clean:
	rm -f $(OBJS)

clobber:
	rm -f $(OBJS) fsck.ttp
