
.\" whirlgif.1 
.\"
.TH WHIRLGIF 1 "Feb 5, 1996"
.AT 3
.SH NAME
whirlgif \- a quick program that reads a series of GIF files, and produces
a single gif file composed of those images.
.SH SYNOPSIS
.B whirlgif
[
.B \-v
] [
.B \-trans
index ] [
.B \-time
delay] [
.B \-o
outfile] [
.B \-loop
] [
.B \-disp
method
] [
.B \-i
incfile] file1 [ 
.B \-time
delay] file2
.SH DESCRIPTION
.PP
.TP
.B \-v
verbose mode
.TP
\fB\-loop\fP [count]
add the Netscape 'loop' extension.
.TP
\fB\-disp\fP method
Sets the image 'disposal' method.
.TP
\fB\-time\fP delay
inter\-frame timing.
.TP
\fB\-trans\fP index
set the colormap index 'index' to be transparent
.TP
\fB\-o\fP outfile
write the results to 'outfile'
.TP
\fB\-i\fP incfile
read a list of names from 'incfile'
.SH TIPS
.PP
If you don't specify an output file, the GIF will be sent to stdout. This is
a good thing if you're using this in a CGI script, a very bad thing if you
run this from a terminal and forget to redirect stdout.

The output file (if any) and \-loop _MUST_ be specified before any gif images.

You can specify several delay statements on the command line to change
the delay between images in the middle of an animation, e.g.

whirlgif \-time 5 a.gif b.gif c.gif \-time 100 d.gif \-time 5 e.gif f.gif

Although it's generally considered to be evil, you can also specify
several transparency statements on the command line, to change the transparent
color in the middle of an animation. This may cause problems for some programs.


.SH BUGS
.PP

The loop 'count' is ineffective because Netspcape always loops infinitely.

should be able to specify delay in an 'incfile' list (see next bug).

Does not handle filenames starting with a \- (hypen), except in 'incfile'.

Needs better documentation.

.SH TODO
.PP

Only save colormaps that are different from preceeding ones.

have an option that compares current image with previous and then
only save the smallest rectangle that encompasses changes. I need sample
code\- the most efficient algorithms are patented?

option for luma sorting of colormaps

define extension block in order to have frame lists.


.PP
This program is available from
.br
.B http://www.msg.net/utility/whirlgif/

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
.SH AUTHOR
.PP
V2.01 Kevin Kadow	kadokev@msg.net

Based on 'txtmerge' written by:
.br
Mark Podlipec	podlipec@wellfleet.com
.br
Man Page by Mintak Ng <mintak@hitak.com>
