# Makefile for the PURE C MAGIC interface library

### NEEDS GNU MAKE ! ###

### Fit this to your taste #####
COMPILERDIR  = e:/develop/pure_c/pc
INCDIR1      = e:\\develop\\pure_c\\include
INCDIR2      = e:\\develop\\magic\\include
LIBDIR       = e:\\develop\\pure_c\\lib
DIRSEP       = \\
################################

PCC      =  $(COMPILERDIR)/pcc.ttp
PLINK    =  $(COMPILERDIR)/plink.ttp
DELETE   =  rm.ttp -f

# libs
LLIBS    = $(LIBDIR)\\pcstdlib.lib $(LIBDIR)\\pctoslib.lib \
           $(LIBDIR)\\pcgemlib.lib $(LIBDIR)\\magiclib.lib

#startup
STARTUP  = $(LIBDIR)\\pcstart.o

# executables
MAGICDEM = magicdem/magicdem.prg
GDOS     = gdos/gdos.tos
WINDOW   = window/window.prg

# objects
OBJCS1   = magicdem/magicdem.o magicdem/magiclin.o
OBJCS2   = gdos/gdos.o
OBJCS3   = window/window.o

all: $(MAGICDEM) $(GDOS) $(WINDOW)

$(MAGICDEM): $(OBJCS1)
	$(PLINK) -O=$(subst /,$(DIRSEP),$@) $(STARTUP) $(subst /,$(DIRSEP),$(OBJCS1)) $(LLIBS)

$(GDOS): $(OBJCS2)
	$(PLINK) -O=$(subst /,$(DIRSEP),$@) $(STARTUP) $(subst /,$(DIRSEP),$(OBJCS2)) $(LLIBS)

$(WINDOW): $(OBJCS3)
	$(PLINK) -O=$(subst /,$(DIRSEP),$@) $(STARTUP) $(subst /,$(DIRSEP),$(OBJCS3)) $(LLIBS)

%.o: %.c
	$(PCC) -I$(INCDIR1) -I$(INCDIR2) $(subst /,$(DIRSEP),$<)

clean:
	$(DELETE) $(OBJCS1) $(OBJCS2) $(OBJCS3)

realclean: clean
	$(DELETE) $(M_DEMO) $(GDOS) $(WINDOW)
