#----------------------------------------------------------------------------
#		    Makefile to make the program 'rsctoc.ttp'
#----------------------------------------------------------------------------

OBJECT = rsctoc.ttp
FILES1 = main.o

$(OBJECT): $(FILES1)
	$(CC) $(FILES1) -o $(OBJECT)

clean:
	$(RM) $(FILES1)
	$(RM) $(OBJECT)

arc:
	arc a rsctoc main.c makefile rsctoc.doc readme

#----------------------------------------------------------------------------
