CC = m68k-atari-mint-gcc
FIX = m68k-atari-mint-fixstk
STRIP = m68k-atari-mint-xstrip
SIZE = m68k-atari-mint-size68

EXE = tiny_60.ldg

CFLAGS = -O2 -fomit-frame-pointer -m68060 mcpu=68060


LFLAGS = -o $(EXE)

# Make's implicit rules for making a .o file from a .c file...
#
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@


OBJ = tiny_ldg.o api.o zmath.o zdither.o zbuffer.o vertex.o texture.o \
specbuf.o select.o misc.o matrix.o list.o light.o init.o glx.o get.o \
error.o clip.o clear.o arrays.o zline.o image_ut.o ztriangl.o mem.o

all: tiny

clean:
	rm *.o
	
tiny: $(OBJ)
	$(CC) $(LFLAGS) $(OBJ) -lm -lc -lldg
#	$(FIX) 16k $(EXE)
#	$(STRIP) $(EXE)
#	$(SIZE) $(EXE)
