#define FRGOK 14  	/* OBJECT in TREE #1 */
#define FRGCAN 15  	/* OBJECT in TREE #1 */
#define FRGSAVE 16  	/* OBJECT in TREE #1 */
#define ITACAN 48  	/* OBJECT in TREE #1 */
#define ITASAVE 49  	/* OBJECT in TREE #1 */
#define ITAOK 47  	/* OBJECT in TREE #1 */
#define SWEOK 58  	/* OBJECT in TREE #1 */
#define SWECAN 59  	/* OBJECT in TREE #1 */
#define SWESAVE 60  	/* OBJECT in TREE #1 */
#define SPAOK 36  	/* OBJECT in TREE #1 */
#define SPACAN 37  	/* OBJECT in TREE #1 */
#define SPASAVE 38  	/* OBJECT in TREE #1 */
#define FRAOK 25  	/* OBJECT in TREE #1 */
#define FRACAN 26  	/* OBJECT in TREE #1 */
#define FRASAVE 27  	/* OBJECT in TREE #1 */
#define WCOLPANL 0  	/* TREE */
#define BGBOX 6  	/* OBJECT in TREE #0 */
#define BGTITLE 7  	/* OBJECT in TREE #0 */
#define BGNAME 8  	/* OBJECT in TREE #0 */
#define BGINFO 10  	/* OBJECT in TREE #0 */
#define BGDATA 11  	/* OBJECT in TREE #0 */
#define BGWORK 12  	/* OBJECT in TREE #0 */
#define BVELEV 17  	/* OBJECT in TREE #0 */
#define BHELEV 22  	/* OBJECT in TREE #0 */
#define BGSIZER 13  	/* OBJECT in TREE #0 */
#define TBOX 24  	/* OBJECT in TREE #0 */
#define TTITLE 25  	/* OBJECT in TREE #0 */
#define TCLOSER 26  	/* OBJECT in TREE #0 */
#define TFULLER 27  	/* OBJECT in TREE #0 */
#define TNAME 28  	/* OBJECT in TREE #0 */
#define TINFO 29  	/* OBJECT in TREE #0 */
#define TDATA 30  	/* OBJECT in TREE #0 */
#define TWORK 31  	/* OBJECT in TREE #0 */
#define TVBAR 51  	/* OBJECT in TREE #0 */
#define TUP 52  	/* OBJECT in TREE #0 */
#define TDN 53  	/* OBJECT in TREE #0 */
#define TVSLID 54  	/* OBJECT in TREE #0 */
#define TVELEV 55  	/* OBJECT in TREE #0 */
#define THBAR 56  	/* OBJECT in TREE #0 */
#define TLF 57  	/* OBJECT in TREE #0 */
#define TRT 58  	/* OBJECT in TREE #0 */
#define THSLID 59  	/* OBJECT in TREE #0 */
#define THELEV 60  	/* OBJECT in TREE #0 */
#define TSIZER 61  	/* OBJECT in TREE #0 */
#define SAVE 2  	/* OBJECT in TREE #0 */
#define OK 4  	/* OBJECT in TREE #0 */
#define CANCEL 5  	/* OBJECT in TREE #0 */
#define MODE 38  	/* OBJECT in TREE #0 */
#define BORDSLID 32  	/* OBJECT in TREE #0 */
#define BORDELEV 33  	/* OBJECT in TREE #0 */
#define TEXTSLID 34  	/* OBJECT in TREE #0 */
#define TEXTELEV 35  	/* OBJECT in TREE #0 */
#define FILLSLID 36  	/* OBJECT in TREE #0 */
#define FILLELEV 37  	/* OBJECT in TREE #0 */
#define FILL0 40  	/* OBJECT in TREE #0 */
#define FILL1 41  	/* OBJECT in TREE #0 */
#define FILL2 42  	/* OBJECT in TREE #0 */
#define FILL3 43  	/* OBJECT in TREE #0 */
#define FILL4 44  	/* OBJECT in TREE #0 */
#define FILL5 45  	/* OBJECT in TREE #0 */
#define FILL6 46  	/* OBJECT in TREE #0 */
#define FILL7 47  	/* OBJECT in TREE #0 */
#define FLOATER 62  	/* OBJECT in TREE #0 */
#define FILLS 39  	/* OBJECT in TREE #0 */
#define ALERT 0  	/* STRING */
#define FRGWIND 17  	/* OBJECT in TREE #1 */
#define FRGINFO 18  	/* OBJECT in TREE #1 */
#define FRGBORD 19  	/* OBJECT in TREE #1 */
#define FRGTEXT 20  	/* OBJECT in TREE #1 */
#define FRGMODE 22  	/* OBJECT in TREE #1 */
#define BORD 48  	/* OBJECT in TREE #0 */
#define TEXT 49  	/* OBJECT in TREE #0 */
#define FILL 50  	/* OBJECT in TREE #0 */
#define FRGFILL 21  	/* OBJECT in TREE #1 */
#define FRAWIND 28  	/* OBJECT in TREE #1 */
#define FRAINFO 29  	/* OBJECT in TREE #1 */
#define FRABORD 30  	/* OBJECT in TREE #1 */
#define FRATEXT 31  	/* OBJECT in TREE #1 */
#define FRAFILL 32  	/* OBJECT in TREE #1 */
#define FRAMODE 33  	/* OBJECT in TREE #1 */
#define SPAWIND 39  	/* OBJECT in TREE #1 */
#define SPAINFO 40  	/* OBJECT in TREE #1 */
#define SPABORD 41  	/* OBJECT in TREE #1 */
#define SPATEXT 42  	/* OBJECT in TREE #1 */
#define SPAFILL 43  	/* OBJECT in TREE #1 */
#define SPAMODE 44  	/* OBJECT in TREE #1 */
#define ITAWIND 50  	/* OBJECT in TREE #1 */
#define ITAINFO 51  	/* OBJECT in TREE #1 */
#define ITABORD 52  	/* OBJECT in TREE #1 */
#define ITATEXT 53  	/* OBJECT in TREE #1 */
#define ITAFILL 54  	/* OBJECT in TREE #1 */
#define ITAMODE 55  	/* OBJECT in TREE #1 */
#define SWEWIND 61  	/* OBJECT in TREE #1 */
#define SWEINFO 62  	/* OBJECT in TREE #1 */
#define SWEBORD 63  	/* OBJECT in TREE #1 */
#define SWETEXT 64  	/* OBJECT in TREE #1 */
#define SWEFILL 65  	/* OBJECT in TREE #1 */
#define SWEMODE 66  	/* OBJECT in TREE #1 */
#define FRGLERT 1  	/* STRING */
#define FRALERT 2  	/* STRING */
#define SPALERT 3  	/* STRING */
#define ITALERT 4  	/* STRING */
#define SWELERT 5  	/* STRING */
#define XLATE 1  	/* TREE */
#define USAOK 3  	/* OBJECT in TREE #1 */
#define USACAN 4  	/* OBJECT in TREE #1 */
#define USASAVE 5  	/* OBJECT in TREE #1 */
#define USAWIND 6  	/* OBJECT in TREE #1 */
#define USAINFO 7  	/* OBJECT in TREE #1 */
#define USABORD 8  	/* OBJECT in TREE #1 */
#define USATEXT 9  	/* OBJECT in TREE #1 */
#define USAFILL 10  	/* OBJECT in TREE #1 */
#define USAMODE 11  	/* OBJECT in TREE #1 */
#define BFULLER 9  	/* OBJECT in TREE #0 */
#define BUP 15  	/* OBJECT in TREE #0 */
#define BDN 16  	/* OBJECT in TREE #0 */
#define BVSLID 18  	/* OBJECT in TREE #0 */
#define BGVBAR 14  	/* OBJECT in TREE #0 */
#define BRT 21  	/* OBJECT in TREE #0 */
#define BLF 20  	/* OBJECT in TREE #0 */
#define BHSLID 23  	/* OBJECT in TREE #0 */
#define BGHBAR 19  	/* OBJECT in TREE #0 */
