#define START 0  	/* TREE */
#define PU_S_TL 1  	/* TREE */
#define ICONIFY 2  	/* TREE */
#define CREDITS 3  	/* TREE */
#define DIALER 4  	/* TREE */
#define PASSWORD 5  	/* TREE */
#define CONF 6  	/* TREE */
#define PU_C_TYP 7  	/* TREE */
#define PU_C_PRT 8  	/* TREE */
#define O_MEM 9  	/* TREE */
#define O_STAT 10  	/* TREE */
#define PU_S_PRT 11  	/* TREE */
#define PU_S_LAY 12  	/* TREE */
#define O_ROUTE 13  	/* TREE */
#define O_RSLV 14  	/* TREE */
#define O_PING 15  	/* TREE */
#define OP_DOIT 16  	/* TREE */
#define O_TRACE 17  	/* TREE */
#define OT_DOIT 18  	/* TREE */
#define ST_PBOX 5  	/* OBJECT in TREE #0 */
#define DL_VERS 8  	/* OBJECT in TREE #0 */
#define ST_VERS 10  	/* OBJECT in TREE #0 */
#define MOD_STAT 12  	/* OBJECT in TREE #0 */
#define ST_BOX 15  	/* OBJECT in TREE #0 */
#define ST_CNCT 16  	/* OBJECT in TREE #0 */
#define ST_ABLE 17  	/* OBJECT in TREE #0 */
#define ST_STUFF 18  	/* OBJECT in TREE #0 */
#define ST_CONF 19  	/* OBJECT in TREE #0 */
#define TL_TTL 20  	/* OBJECT in TREE #0 */
#define AUTHORS 21  	/* OBJECT in TREE #0 */
#define ST_EXIT 22  	/* OBJECT in TREE #0 */
#define DL_STAT 5  	/* OBJECT in TREE #4 */
#define DL_STRNG 6  	/* OBJECT in TREE #4 */
#define DL_SPEED 7  	/* OBJECT in TREE #4 */
#define DL_IP 8  	/* OBJECT in TREE #4 */
#define DL_TIMER 9  	/* OBJECT in TREE #4 */
#define DL_RDIAL 11  	/* OBJECT in TREE #4 */
#define DL_ABORT 12  	/* OBJECT in TREE #4 */
#define PW_BUTT 4  	/* OBJECT in TREE #5 */
#define PW_STRNG 9  	/* OBJECT in TREE #5 */
#define CON_BOX 4  	/* OBJECT in TREE #6 */
#define CC_SCRPT 5  	/* OBJECT in TREE #6 */
#define CM_BOX 6  	/* OBJECT in TREE #6 */
#define CM_INIT 9  	/* OBJECT in TREE #6 */
#define CM_DIAL 10  	/* OBJECT in TREE #6 */
#define CM_HANG 11  	/* OBJECT in TREE #6 */
#define CM_CTOUT 12  	/* OBJECT in TREE #6 */
#define CM_RDLAY 13  	/* OBJECT in TREE #6 */
#define CM_CON1 16  	/* OBJECT in TREE #6 */
#define CM_CON2 17  	/* OBJECT in TREE #6 */
#define CM_CON3 18  	/* OBJECT in TREE #6 */
#define CM_RED1 20  	/* OBJECT in TREE #6 */
#define CM_RED2 21  	/* OBJECT in TREE #6 */
#define CM_RED3 22  	/* OBJECT in TREE #6 */
#define CM_ABO1 24  	/* OBJECT in TREE #6 */
#define CM_ABO2 25  	/* OBJECT in TREE #6 */
#define CM_ABO3 26  	/* OBJECT in TREE #6 */
#define CP_BOX 28  	/* OBJECT in TREE #6 */
#define CP_IP 30  	/* OBJECT in TREE #6 */
#define CP_MTU 31  	/* OBJECT in TREE #6 */
#define CP_PID 32  	/* OBJECT in TREE #6 */
#define CP_PPTXT 33  	/* OBJECT in TREE #6 */
#define CP_PPASS 34  	/* OBJECT in TREE #6 */
#define CP_FPPW 36  	/* OBJECT in TREE #6 */
#define CP_PPPW 37  	/* OBJECT in TREE #6 */
#define CP_TPPW 38  	/* OBJECT in TREE #6 */
#define CP_SLIP 41  	/* OBJECT in TREE #6 */
#define CP_PPP 43  	/* OBJECT in TREE #6 */
#define CP_VJHC 46  	/* OBJECT in TREE #6 */
#define CP_LAN 49  	/* OBJECT in TREE #6 */
#define CP_LTXT 50  	/* OBJECT in TREE #6 */
#define CA_BOX 52  	/* OBJECT in TREE #6 */
#define CA_USER 54  	/* OBJECT in TREE #6 */
#define CA_FULL 55  	/* OBJECT in TREE #6 */
#define CA_FQDN 57  	/* OBJECT in TREE #6 */
#define CA_PREV 60  	/* OBJECT in TREE #6 */
#define CA_DNS 61  	/* OBJECT in TREE #6 */
#define CA_NEXT 62  	/* OBJECT in TREE #6 */
#define CA_ADD 63  	/* OBJECT in TREE #6 */
#define CA_GETNS 65  	/* OBJECT in TREE #6 */
#define CA_NSTXT 66  	/* OBJECT in TREE #6 */
#define CG_BOX 68  	/* OBJECT in TREE #6 */
#define CG_PORT 72  	/* OBJECT in TREE #6 */
#define CG_DEFRT 75  	/* OBJECT in TREE #6 */
#define CG_MASQU 78  	/* OBJECT in TREE #6 */
#define CG_MTXT 79  	/* OBJECT in TREE #6 */
#define CG_LOGIN 81  	/* OBJECT in TREE #6 */
#define CG_CIX 84  	/* OBJECT in TREE #6 */
#define CG_RESI 87  	/* OBJECT in TREE #6 */
#define CG_RTXT 88  	/* OBJECT in TREE #6 */
#define CG_DEBUG 90  	/* OBJECT in TREE #6 */
#define CT_BOX 93  	/* OBJECT in TREE #6 */
#define CT_PREV 97  	/* OBJECT in TREE #6 */
#define CT_NUM 98  	/* OBJECT in TREE #6 */
#define CT_NEXT 99  	/* OBJECT in TREE #6 */
#define CT_ADD 100  	/* OBJECT in TREE #6 */
#define CT_FEE 101  	/* OBJECT in TREE #6 */
#define CI_TU 104  	/* OBJECT in TREE #6 */
#define CI_TC 105  	/* OBJECT in TREE #6 */
#define CI_SU 106  	/* OBJECT in TREE #6 */
#define CI_SC 107  	/* OBJECT in TREE #6 */
#define CI_RU 108  	/* OBJECT in TREE #6 */
#define CI_RC 109  	/* OBJECT in TREE #6 */
#define CD_BOX 112  	/* OBJECT in TREE #6 */
#define CD_TOUT 114  	/* OBJECT in TREE #6 */
#define CD_IBOX 115  	/* OBJECT in TREE #6 */
#define CD_PREV 118  	/* OBJECT in TREE #6 */
#define CD_STEP 119  	/* OBJECT in TREE #6 */
#define CD_NEXT 120  	/* OBJECT in TREE #6 */
#define CD_INS 121  	/* OBJECT in TREE #6 */
#define CD_DEL 122  	/* OBJECT in TREE #6 */
#define CD_TIME 123  	/* OBJECT in TREE #6 */
#define CD_REPT 124  	/* OBJECT in TREE #6 */
#define CD_FIND 125  	/* OBJECT in TREE #6 */
#define CD_RESP 126  	/* OBJECT in TREE #6 */
#define CN_BOX 128  	/* OBJECT in TREE #6 */
#define CN_PREV 132  	/* OBJECT in TREE #6 */
#define CN_OFF 133  	/* OBJECT in TREE #6 */
#define CN_NEXT 134  	/* OBJECT in TREE #6 */
#define CN_ADD 135  	/* OBJECT in TREE #6 */
#define CN_BIGBX 136  	/* OBJECT in TREE #6 */
#define CN_ED1 137  	/* OBJECT in TREE #6 */
#define CN_ED2 138  	/* OBJECT in TREE #6 */
#define CN_ED3 139  	/* OBJECT in TREE #6 */
#define CN_ED4 140  	/* OBJECT in TREE #6 */
#define CN_ED5 141  	/* OBJECT in TREE #6 */
#define CN_ED6 142  	/* OBJECT in TREE #6 */
#define CN_ED7 143  	/* OBJECT in TREE #6 */
#define CN_SLDBX 144  	/* OBJECT in TREE #6 */
#define CN_UP 145  	/* OBJECT in TREE #6 */
#define CN_BACK 146  	/* OBJECT in TREE #6 */
#define CN_SLDR 147  	/* OBJECT in TREE #6 */
#define CN_DOWN 148  	/* OBJECT in TREE #6 */
#define CC_M_NAM 150  	/* OBJECT in TREE #6 */
#define CC_SAVE 151  	/* OBJECT in TREE #6 */
#define CC_SET 152  	/* OBJECT in TREE #6 */
#define OM_BOX 4  	/* OBJECT in TREE #9 */
#define OM_STING 5  	/* OBJECT in TREE #9 */
#define SKR_TTL 7  	/* OBJECT in TREE #9 */
#define SKR_LBLK 8  	/* OBJECT in TREE #9 */
#define OM_STRAM 10  	/* OBJECT in TREE #9 */
#define STR_TTL 12  	/* OBJECT in TREE #9 */
#define STR_LBLK 13  	/* OBJECT in TREE #9 */
#define OM_ARAM 15  	/* OBJECT in TREE #9 */
#define ALR_TTL 17  	/* OBJECT in TREE #9 */
#define ALR_LBLK 18  	/* OBJECT in TREE #9 */
#define OS_LOMEM 8  	/* OBJECT in TREE #10 */
#define OS_TTLEX 9  	/* OBJECT in TREE #10 */
#define OS_WCHKS 10  	/* OBJECT in TREE #10 */
#define OS_UNDEL 11  	/* OBJECT in TREE #10 */
#define OS_TOTAL 12  	/* OBJECT in TREE #10 */
#define OS_PORT 16  	/* OBJECT in TREE #10 */
#define OSP_DROP 17  	/* OBJECT in TREE #10 */
#define OSP_SENT 18  	/* OBJECT in TREE #10 */
#define OSP_RECV 19  	/* OBJECT in TREE #10 */
#define OS_LAYER 23  	/* OBJECT in TREE #10 */
#define OSL_DROP 24  	/* OBJECT in TREE #10 */
#define OU_BIGBX 10  	/* OBJECT in TREE #13 */
#define OU_NET1 11  	/* OBJECT in TREE #13 */
#define OU_MSK1 12  	/* OBJECT in TREE #13 */
#define OU_PRT1 13  	/* OBJECT in TREE #13 */
#define OU_GTW1 14  	/* OBJECT in TREE #13 */
#define OU_NET2 15  	/* OBJECT in TREE #13 */
#define OU_MSK2 16  	/* OBJECT in TREE #13 */
#define OU_PRT2 17  	/* OBJECT in TREE #13 */
#define OU_GTW2 18  	/* OBJECT in TREE #13 */
#define OU_NET3 19  	/* OBJECT in TREE #13 */
#define OU_MSK3 20  	/* OBJECT in TREE #13 */
#define OU_PRT3 21  	/* OBJECT in TREE #13 */
#define OU_GTW3 22  	/* OBJECT in TREE #13 */
#define OU_NET4 23  	/* OBJECT in TREE #13 */
#define OU_MSK4 24  	/* OBJECT in TREE #13 */
#define OU_PRT4 25  	/* OBJECT in TREE #13 */
#define OU_GTW4 26  	/* OBJECT in TREE #13 */
#define OU_NET5 27  	/* OBJECT in TREE #13 */
#define OU_MSK5 28  	/* OBJECT in TREE #13 */
#define OU_PRT5 29  	/* OBJECT in TREE #13 */
#define OU_GTW5 30  	/* OBJECT in TREE #13 */
#define OU_NET6 31  	/* OBJECT in TREE #13 */
#define OU_MSK6 32  	/* OBJECT in TREE #13 */
#define OU_PRT6 33  	/* OBJECT in TREE #13 */
#define OU_GTW6 34  	/* OBJECT in TREE #13 */
#define OU_NET7 35  	/* OBJECT in TREE #13 */
#define OU_MSK7 36  	/* OBJECT in TREE #13 */
#define OU_PRT7 37  	/* OBJECT in TREE #13 */
#define OU_GTW7 38  	/* OBJECT in TREE #13 */
#define OU_NET8 39  	/* OBJECT in TREE #13 */
#define OU_MSK8 40  	/* OBJECT in TREE #13 */
#define OU_PRT8 41  	/* OBJECT in TREE #13 */
#define OU_GTW8 42  	/* OBJECT in TREE #13 */
#define OU_NET9 43  	/* OBJECT in TREE #13 */
#define OU_MSK9 44  	/* OBJECT in TREE #13 */
#define OU_PRT9 45  	/* OBJECT in TREE #13 */
#define OU_GTW9 46  	/* OBJECT in TREE #13 */
#define OU_NET10 47  	/* OBJECT in TREE #13 */
#define OU_MSK10 48  	/* OBJECT in TREE #13 */
#define OU_PRT10 49  	/* OBJECT in TREE #13 */
#define OU_GTW10 50  	/* OBJECT in TREE #13 */
#define OU_SLDBX 51  	/* OBJECT in TREE #13 */
#define OU_UP 52  	/* OBJECT in TREE #13 */
#define OU_PRNT 53  	/* OBJECT in TREE #13 */
#define OU_SLDR 54  	/* OBJECT in TREE #13 */
#define OU_DOWN 55  	/* OBJECT in TREE #13 */
#define OR_BOX 4  	/* OBJECT in TREE #14 */
#define R_HOST 7  	/* OBJECT in TREE #14 */
#define RA_BOX 9  	/* OBJECT in TREE #14 */
#define R_ALIAS 10  	/* OBJECT in TREE #14 */
#define RM_BOX 12  	/* OBJECT in TREE #14 */
#define RIP_BOX 13  	/* OBJECT in TREE #14 */
#define RIP_FRM 14  	/* OBJECT in TREE #14 */
#define R_IP1 15  	/* OBJECT in TREE #14 */
#define R_IP2 16  	/* OBJECT in TREE #14 */
#define R_IP3 17  	/* OBJECT in TREE #14 */
#define R_IP4 18  	/* OBJECT in TREE #14 */
#define R_IP5 19  	/* OBJECT in TREE #14 */
#define R_IP6 20  	/* OBJECT in TREE #14 */
#define R_IP7 21  	/* OBJECT in TREE #14 */
#define R_IP8 22  	/* OBJECT in TREE #14 */
#define DO_RSLV 24  	/* OBJECT in TREE #14 */
#define OP_HOST 7  	/* OBJECT in TREE #15 */
#define OP_OK 9  	/* OBJECT in TREE #15 */
#define OP_IP 5  	/* OBJECT in TREE #16 */
#define OP_SENT 6  	/* OBJECT in TREE #16 */
#define OP_STOP 7  	/* OBJECT in TREE #16 */
#define OP_RECVD 8  	/* OBJECT in TREE #16 */
#define OP_RTTBX 11  	/* OBJECT in TREE #16 */
#define OP_RTT1 12  	/* OBJECT in TREE #16 */
#define OP_RTT2 13  	/* OBJECT in TREE #16 */
#define OP_RTT3 14  	/* OBJECT in TREE #16 */
#define OP_STBOX 18  	/* OBJECT in TREE #16 */
#define OP_MINI 19  	/* OBJECT in TREE #16 */
#define OP_AVE 20  	/* OBJECT in TREE #16 */
#define OP_MAXI 21  	/* OBJECT in TREE #16 */
#define OT_HOST 7  	/* OBJECT in TREE #17 */
#define OT_OK 9  	/* OBJECT in TREE #17 */
#define OT_DEST 5  	/* OBJECT in TREE #18 */
#define OT_STATE 6  	/* OBJECT in TREE #18 */
#define OT_BIGBX 10  	/* OBJECT in TREE #18 */
#define OT_HOP1 11  	/* OBJECT in TREE #18 */
#define OT_IP1 12  	/* OBJECT in TREE #18 */
#define OT_DN1 13  	/* OBJECT in TREE #18 */
#define OT_HOP2 14  	/* OBJECT in TREE #18 */
#define OT_IP2 15  	/* OBJECT in TREE #18 */
#define OT_DN2 16  	/* OBJECT in TREE #18 */
#define OT_HOP3 17  	/* OBJECT in TREE #18 */
#define OT_IP3 18  	/* OBJECT in TREE #18 */
#define OT_DN3 19  	/* OBJECT in TREE #18 */
#define OT_HOP4 20  	/* OBJECT in TREE #18 */
#define OT_IP4 21  	/* OBJECT in TREE #18 */
#define OT_DN4 22  	/* OBJECT in TREE #18 */
#define OT_HOP5 23  	/* OBJECT in TREE #18 */
#define OT_IP5 24  	/* OBJECT in TREE #18 */
#define OT_DN5 25  	/* OBJECT in TREE #18 */
#define OT_HOP6 26  	/* OBJECT in TREE #18 */
#define OT_IP6 27  	/* OBJECT in TREE #18 */
#define OT_DN6 28  	/* OBJECT in TREE #18 */
#define OT_HOP7 29  	/* OBJECT in TREE #18 */
#define OT_IP7 30  	/* OBJECT in TREE #18 */
#define OT_DN7 31  	/* OBJECT in TREE #18 */
#define OT_HOP8 32  	/* OBJECT in TREE #18 */
#define OT_IP8 33  	/* OBJECT in TREE #18 */
#define OT_DN8 34  	/* OBJECT in TREE #18 */
#define OT_HOP9 35  	/* OBJECT in TREE #18 */
#define OT_IP9 36  	/* OBJECT in TREE #18 */
#define OT_DN9 37  	/* OBJECT in TREE #18 */
#define OT_HOP10 38  	/* OBJECT in TREE #18 */
#define OT_IP10 39  	/* OBJECT in TREE #18 */
#define OT_DN10 40  	/* OBJECT in TREE #18 */
#define OT_SLDBX 41  	/* OBJECT in TREE #18 */
#define OT_UP 42  	/* OBJECT in TREE #18 */
#define OT_PRNT 43  	/* OBJECT in TREE #18 */
#define OT_SLDR 44  	/* OBJECT in TREE #18 */
#define OT_DOWN 45  	/* OBJECT in TREE #18 */
