#Makefile for minixfs and friends 

AS=gcc-as

CFLAGS=-Wall -mshort -O -fomit-frame-pointer -I.

include ../dirs

OBJS= init.o minixfs.o minixdev.o io.o cache.o dir.o inode.o zone.o main.o \
	trans.o misc.o bitmap.o check.o tinyxhdi.o kludge.o hdio.o \
	dummyfs.o stack.o
all: minix.xfs

tinyxhdi.o: tinyxhdi.c xhdi.h
	$(CC) $(CFLAGS) -DSUPER_CALL -DTINY_XHDI -c tinyxhdi.c

main.o: version.h

hdio.o: hdio.c hdio.h
	$(CC) $(CFLAGS) -DMFS_XFS -c hdio.c

minix.xfs: $(OBJS)
	$(CC) -nostdlib -G -o minix.xfs $(OBJS) -lgnu16
#	xstrip -l syms.mfs minix.xfs

$(OBJS): config.h minixfs.h atarierr.h filesys.h global.h

clean:
	rm -f $(OBJS)

clobber:
	rm -f $(OBJS) minix.xfs

install: minix.xfs
	$(INSTALL) minix.xfs $(FSDIR)
