.TH LP_SOLVE 1ES
.SH NAME
lp_solve	- Solve (mixed integer) linear programming problem.
.SH SYNOPSIS
lp_solve [option]* "<" <input-file>
.SH OPTIONS
.TP 1.2i
-v
Verbose mode
.TP
-h
Help mode, prints the usage
.TP
-d
Debug mode, all intermediate results are printed, and the branch-and-bound
decissions in case of (mixed) integer problems.
.TP
-b <bound>
Specify a lower limit for the value of the objective function
to the program. Only useful for (mixed) integer problems.
If close enough, may speed up the calculations.
.TP
-i
Print all intermediate valid solutions. Can give you useful
solutions even if the total run time is too long.
Only useful for (mixed) integer problems.
.SH DESCRIPTION
The linear programming problem can be formulated as: Solve A.x >= V1, with
V2.x maximal. A is a matrix, x a vector of variables, V1 a vector called
the right hand side, and V2 a vector specifying the objective function.
.br
Any of the variables may be specified integer.
.br
This program solves problems of this kind. It is slightly more general
than the above problem, in that every row of A (specifying one equation)
can have its own (un)equality, <=, >= or =. Also there is a possibility to
specify bounds and ranges for individual variables (which could also be done
in A of course). The result specifies values for all variables.
.br
Uses a 'Simplex' algorithm and sparse matrix methods, for pure LP problems.
If one or more of the variables is declared integer, the Simplex algorithm is
iterated with a branch and bound algorithm, until the desired optimal
solution is found.
.SH "INTERRUPT"
In order to make it possible to get useful solutions for a mixed integer
problem which takes too long to finish completely, the "interrupt" signal
(kill -INT, ^C for many people) will not terminate the program, but print the
best valid solution found sofar. If you see all zeros, it implies that no
valid solution has been found yet. To really terminate the program, use a
different signal, like KILL.
.SH "INPUT SYNTAX"
The input syntax is a set of algebraic expressions and "int" declarations in
the following order:
.sp
<objective function>
.br
<constraint>+
.br
<declaration>*
.sp
where:
.TP 0.2i
-
<objective function> is a linear combination of variables, ending with a semicolon.
.TP
-
<constraint> is a linear combination of variables and constants,
followed by a relational operator, followed again by a linear combination of
variables and constants, ending with a semicolon. The relational operator can
be any of the following: "<" "<=" "=" ">" ">=".
.TP
-
<declaration> is of the form: "int" <var>+ ";" Commas are allowed between
variables.
.sp
So, the simplest linear problem consists of an objective function and 1
constraint.
.SH EXAMPLE
The simple problem:
.sp
x1 >= 1
.br
x2 >= 1
.br
minimise x1 + x2 (= maximise -(x1 + x2)), with x1 integer
.sp
can be written as follows:
.sp
-x1 + -x2;
.br
x1 > 1;
.br
x2 > 1;
.br
int x1;
.sp
The correct result for (x1, x2) is of course (1, 1).
.SH BUGS
Due to the implementation, bounds (constraints on just one variable), do not enter into the A-matrix. Therefore, extremely simple problems with only bounds sometimes cannot be solved, because they define the empty problem. Real-life examples probably never have this property.
.SH SEE ALSO
The implementation of the simplex kernel was mainly based on:
.br
W. Orchard-Hays: "Advanced Linear Programming Computing Techniques", McGrawhill
1968
.SH CONTRIBUTED BY
M.R.C.M. Berkelaar
.br
Eindhoven University of Technology
.br
Design Automation Section
.br
P.O. Box 513
.br
NL-5600 MB Eindhoven, The Netherlands
.br
phone ...-31-40-473345
.br
E-mail: michel@es.ele.tue.nl
.SH STATUS
Use at own risk. Bug reports are welcome, as well as succes stories.
