# directory access tests
#
# Set -DPOINTER_ALIGN to a value that the target machine needs
# for pointer aligning. If you don't know it, leave it undefined.
# (sizeof(void*) will be used then)
#
# (w) 1996 by Eero Tamminen

CC	= cc
CPFLAGS	= #-DPOINTER_ALIGN=2
CFLAGS	= -O #-Wall
LDFLAGS	=
DOBJS	= print.o entries.o
FOBJS	= filesel.o entries.o

all: dirri filesel

*.o: entries.h

dirri: $(DOBJS)
	$(CC) -o $@ $(DOBJS) $(LDFLAGS)

filesel: $(FOBJS)
	$(CC) -o $@ $(FOBJS) $(LDFLAGS) -lbWt -lbW -lbsocket

