

.c.o:
	mmcc.ttp $*.c
	mmimp.ttp $*.o

compile: checks.o clip.o convert.o deadpoin.o function.o generic.o geometry.o \
 jimlib.o lotsofli.o lprintf.o \
 moveclon.o names.o opmatrix.o predrawp.o raster.o \
 readscri.o replay.o rfont.o scanedge.o softtwee.o symbols.o tubes.o

improve:
	mmimp.ttp checks.o clip.o deadpoin.o function.o generic.o geometry.o
	mmimp.ttp jimlib.o lotsofli.o lprintf.o 
	mmimp.ttp moveclon.o names.o opmatrix.o predrawp.o raster.o
	mmimp.ttp readscri.o replay.o rfont.o softtwee.o symbols.o tubes.o

