LIBRARY=../lib/gem++.olb
INC=../include

SRC=gemap.cc gemd.cc gemfw.cc gemm.cc gemo.cc gemr.cc gemw.cc gema.cc gemf.cc \
	gemt.cc gemsb.cc gemda.cc gemto.cc gemimgo.cc gemuo.cc gemvo.cc geme.cc \
	gemrec.cc gemks.cc gemhf.cc gemfs.cc gemal.cc gemsl.cc gempa.cc \
	gemrawo.cc gemfiw.cc gemfl.cc gemfn.cc gemc.cc gemscro.cc gemst.cc gemcha.cc \
	img.cc grect.cc vdi.cc \
	rsc_fix.cc rsc_gobj.cc \
	flyform.cc
OBJ=$(subst .cc,.o,$(SRC))
LDLIBS=-lgem -lg++
LDFLAGS=-s

GXXINC:=$(INC),$(GXXINC)

# Optimized takes about 20 minutes on TT, TOSWIN, without ICD disk cache.
C++FLAGS=-O2 -DDCL_AES_DEBUG

# Not optimized
#C++FLAGS=-Wall -DDCL_AES_DEBUG

all:	$(LIBRARY)

$(LIBRARY):	$(OBJ)
	$(AR) rs $(LIBRARY) $?

depend:
	-$(CC) -M $(SRC) >/tmp/make.123
	sed 's/[a-z]:[^ ]*//g' /tmp/make.123 >depends
	rm /tmp/make.123

clean:
	rm -f $(OBJ)

clobber: clean
	rm $(LIBRARY)

include depends
