#
# Makefile for Mines
# Copyright 1992 K.Soohoo
#

CFLAGS = -VPEEP
LANDMINE = initwind.o dialog.o stwin.o sounds.o landmine.o playit.o cookie.o\
	   poof.o chime.o chink.o explode2.o yeah.o horn.o

landmine.prg: $(LANDMINE)
	cc -o landmine.prg -VGEM $(LANDMINE)
	strip landmine.prg
	flags landmine.prg -g

landmine.o: landmine.c landmine.h mstruct.h
dialog.o: dialog.c dialog.h
stwin.o: stwin.c
sounds.o: sounds.c
playit.o: playit.s
cookie.o: cookie.c

poof.o: poof.c
chime.o: chime.c
chink.o: chink.c
explode2.o: explode2.c
yeah.o: yeah.c
horn.o: horn.c


