/* resource set indices for DISK-NEW */

#define TREE001    0 /* form/dialog */
#define BT00       1 /* box select fonction -------------- */
#define BT01       2 /* cr‚er */
#define BT02       3 /* effacer */
#define BT03       4 /* renomer */
#define BT04       5 /* deplacer */
#define BT05       6 /* copier */
#define BT06       7 /* info fichier */
#define BT10       8 /* fichier */
#define BT11       9 /* dossier */
#define BT12      10 /* disque */
#define BT13      11 /* info */
#define BT14      12 /* datte et heure systŠme */
#define BT15      13 /* 50/60 Hz */
#define FBT0      14 /* box : attribut --------------------- */
#define FBT1      15 /* type_fichier + file$ */
#define FBT2      16 /* taille fichier */
#define FBT3      17 /* date fichier */
#define FBT4      18 /* heure fichier */
#define BT22      19 /* bouton " autre" */
#define FBT5      22 /* txt att */
#define FBT6      23 /* att 0 */
#define FBT7      24 /* att 1 */
#define FBT8      25 /* att 2 */
#define FBT9      26 /* att 4 */
#define FBT10     27 /* att 8 */
#define FBT11     28 /* att 16 */
#define S00       29 /* box systŠme ------------------ */
#define S01       31 /* datte */
#define S02       32 /* heure */
#define SO3       33 /* ram dispo 10 ( 9 ) */
#define SO4       34 /* ram ocup‚ */
#define SO5       35 /* total ram */
#define BT19      36 /* jour et datte (19 x ) */
#define BT20      37 /* ok */
#define BT21      38 /* quitter */

