char	*mainhelp[]=
{
"WinSet",
"------",
" ",
"Eins vorweg: Jede Einstellung, die Sie ber",
"WinSet t„tigen, wird SOFORT in WinCom aktiv!",
"Wenn Sie also z.B. unter \'Optionen\' eine",
"andere Mover-Zeit einstellen, dann k”nnen",
"Sie diese sofort testen und mssen nicht erst",
"[OK] drcken. Nein, das ist nicht verwirrend,",
"das ist bequem!",
" ",
"M”glichkeiten im Men \'Datei\':",
" ",
"Mit \'Sichern\' k”nnen Sie alle Einstellungen",
"abspeichern, so da sie Ihnen beim n„chsten",
"Start von WinCom wieder zur Verfgung stehen.",
"Vergessen Sie nicht, WINPUT.PRG in den APPS-",
"Ordner zu legen!",
"Falls Sie nderungen an der Tastatureinstellung",
"get„tig haben und eine ST-GUIDE INF-Datei vorhanden",
"ist, werden Sie auerdem gefragt, ob die Schnell-",
"bersicht aktualisiert werden soll. Die Schnell-",
"bersicht wird in das erste Verzeichnis, das in der",
"ST-GUIDE Variablen \'PATHS\' gespeichert ist, ge-",
"schrieben. Die Datei erh„lt den Namen WINKEY.TXT.",
" ",
"šber \'Beenden\' verlassen Sie WinSet. Dabei bleiben",
"alle Einstellungen erhalten und Sie k”nnen Sie",
"erstmal ausprobieren. Wenn Sie WinSet zu einem",
"sp„teren Zeitpunkt nocheinmal starten, k”nnen Sie",
"die Einstellungen immer noch abspeichern, sofern",
"WinCom noch aktiv ist.",
" ",
"M”glichkeiten im Men \'Einstellungen\':",
"----------------------------------------",
" ",
"šber \'Tastatur...\' k”nnen Sie alle WinCom-",
"Funktionen mit Shortcuts Ihrer Wahl belegen.",
"Achtung! Solange dieser Dialog aktiv, also",
"im obersten Fenster ist, solange ist WinCom",
"natrlich gesperrt (warum? ...scharf nach-",
"denken). Um die Krzel zu testen, mssen Sie",
"also erst ein anderes Fenster (z.B. Hilfe)",
"aktivieren.",
" ",
"šber \'Optionen...\' k”nnen Sie Verz”gerungs-",
"zeiten und ein Raster fr die Echtzeitbedienung",
"der Fenster einstellen. Auerdem k”nne Sie dort",
"die Tastenkombinationen zum Aufruf der Accessories",
"ausw„hlen.",
" ",
"In \'Auto-Topping\' k”nnen Sie alle Einstellungen",
"t„tigen, die das automatische Fenstertoppen von",
"WinCom beeinflussen.",
" ",
"\'Diverses\' ist der Dialog, der Ihnen alle Vor-",
"einstellungen von WinCom zug„nglich macht.",
"Damit k”nnen Sie WinCom weitestgehend an",
"Ihre pers”nlichen Vorlieben anpassen.",
" ",
"šber \'Ausnahmeliste\' k”nnen Sie Programme",
"w„hlen, die im Taskswitch-Popup von WinCom",
"nicht erscheinen sollen.",
" ",
"Mit \'Tastatur šbersicht\' k”nnen Sie sich die",
"Belegung aller WinCom-Hotkeys auf einmal an-",
"schauen. Auerdem haben Sie hier die M”glichkeit",
"eine Liste im Clipboard anlegen zu lassen, die",
"Sie z.B. Ausdrucken k”nnen.",
" ",
"\'Status\' zeigt Ihnen die momentane Einstellung",
"aller Optionen, die Sie mit WinSet nicht „ndern",
"k”nnen (sondern nur direkt ber die WinCom-Hotkeys),",
"die beim Sichern der Einstellungen aber trotzdem",
"bercksichtigt werden.",
" ",
"Der Eintrag \'Registrierung...\' fhrt in einen",
"Dialog, in dem Sie Ihren Namen und den Schlssel",
"eingeben k”nnen. Letzteren erhalten Sie durch",
"Bezahlung des Sharewarebetrags, n„heres dazu",
"entnehmen Sie bitte der Anleitung.",
" ",
"Sonstiges:",
"----------",
" ",
"Falls ST-GUIDE installiert ist, dann erhalten Sie",
"ber die in allen Dialogen vorhandenen \'Hilfe\'-",
"Buttons nicht die WinSet-eigene Hilfe. Stattdessen",
"wird der ST-GUIDE mit der entsprechenden Hilfe-Seite",
"aufgerufen. Dazu mu die ST-GUIDE Hilfe entsprechend",
"den Angaben in der Anleitung vorhanden sein.",
/*
" ", 
"Wenn Sie Let'em Fly verwenden, dann sind alle",
"Dialoge tastaturbedienbar.",
*/
""
};

char	*keyshelp[]=
{
"Der Tastaturdialog",
"--------------------------",
" ",
"Wichtig: Welche Tasten k”nnen Sie nicht verwenden?",
"Ganz einfach: Zuerstmal sind das alle Tasten, die",
"Systemfunktionen ausl”sen, also [CTRL]+[Alt]+[Del],",
"dasselbe mit [Rshift], auerdem [Alt]+[Help] und die",
"Tasten zur Maussteuerung, also [Alt](+[Lshift])+Cursor",
"und [Alt]+[Ins]/[Clr].",
"Auerdem sind einige Tasten zur Steuerung dieses Dialogs",
"reserviert. Welche das sind und was sie bewirken, sehen",
"Sie an den kleinen Texten unter den Buttons. Ein Druck",
"auf die jeweilige Taste (ohne [Alt] oder sonstwas) ent-",
"spricht einem Mausklick auf den jeweiligen Button.",
"šber Cursor auf/ab k”nnen Sie auerdem die Auswahl „ndern.",
" ",
"M”glichkeiten im Tastaturdialog:",
"--------------------------------",
" ",
"W„hlen Sie in der Funktionsliste die zu „ndernde",
"Funktion. Dazu Klicken Sie entweder mit der Maus darauf",
"oder sie bewegen den Balken mit den Cursortasten dorthin.",
"Im \'Auswahl\'-Feld sehen Sie nun die gew„hlte Funktion",
"und die aktuelle Belegung. Wenn Sie genauere Angaben",
"ber die Funktion wnschen, dann klicken Sie auf den",
"Button \'Genauer...\'",
"Wenn Sie einen Starter-Hotkey angew„hlt haben, gelangen",
"Sie ber \'Genauer...\' in den Konfigurations-Dialog, in",
"dem Sie das zu startende Programm bestimmen, ansonsten",
"erscheint ein kleines Fenster mit einem kurzen Hilfs-",
"text. (Wenn der ST-Guide installiert ist, erscheint",
"stattdessen die entsprechende Seite des Hypertextes.)",
"Anstelle der Anzeige \'Starter x\' erscheint der Name",
"des dafr angemeldeten Programms, wenn sowohl ein",
"Programm als auch eine Tastenkombination fr einen",
"Starter-Hotkey festgelegt wurden.",
" ",
"Drcken Sie jetzt einfach die Tastenkombination, die",
"die gew„hlte Funktion ausl”sen soll. Sie k”nnen jede",
"beliebige Kombination verwenden. Fr manche Funktionen",
"ist allerdings die linke Shift-Taste reserviert, um die",
"Funktion \'rckw„rts\' auszul”sen. Sollten Sie es trotz-",
"dem Versuchen, so erhalten Sie eine Warnung.", 
" ",
"šber den \'L”schen\'-Button k”nnen Sie den Shortcut",
"l”schen, d.h. diese Funktion kann nicht mehr aufgerufen",
"werden. In der Anzeige fr die gew„hlte Taste sehen Sie",
"dann \'keine\'. Durch Eingabe eines neuen Shortcuts k”nnen",
"Sie die Funktion jederzeit wieder aktivieren.",
" ",
"šber \'Ooops\' k”nnen Sie eine Fehleingabe rckg„ngig machen.",
" ",
"Mit \'šbersicht\' erhalten Sie eine komplette šbersicht",
"ber alle belegten Funktionen.",
" ",
"Wenn Sie den Dialog mit [OK] beenden, dann werden Ihre",
"Eingaben untersucht.",
"Falls eine Eingabe bereits vergeben ist, so erhalten Sie",
"eine Warnung. Vor dem Beenden des Dialogs mssen Sie",
"alle Doppelbelegungen beseitigen.",
"Nein, Sie werden nicht gleich beim Definieren vor Doppel-",
"belegungen gewarnt, weil das z.B. beim Vertauschen von",
"Tasten extrem l„stig ist, da immer erst beide Belegungen",
"gel”scht werden mten.",
"Sollte Ihre Eingabe eine allgemeine Standardbelegung auer",
"Kraft setzen, so werden Sie ebenfalls gewarnt. Auerdem",
"werden Sie noch bei trivialen Eingaben davor gewarnt, da",
"dies zu šberschneidungen mit g„ngigen Programmen fhren",
"kann. Bei Nichtbeachtung steht Ihnen idR nur noch die",
"WinCom-Funktion zur Verfgung!",
"Sollten Sie Warnmeldungen erhalten, da Ihre Belegung eine",
"Let 'em Fly!-Funktion auer Kraft setzt, dann bezieht sich",
"das nur auf Fensterdialoge, die Let 'em Fly! untersttzen",
"Normale Dialoge bleiben davon unbeeinflut.",
" ",
"\'Abbruch\' beendet den Dialog und macht ALLE von Ihnen",
"get„tigten Eingaben rckg„ngig. Falls das nicht gerade",
"wenig waren, erfolgt eine Sicherheitsabfrage.",
""
};

char *listhelp[]=
{
"Der šbersichtsdialog",
"--------------------",
" ",
"Die šbersicht zeigt Ihnen alle WinCom-Funktionen an,",
"fr die ein Tastaturshortcut vergeben wurde. Nicht",
"belegte Funktionen erhalten das Krzel \'keine\'.",
"šber \'Clipboard\' k”nnen Sie diese Liste ins GEM-",
"Clipboard schreiben und von dort mit jedem her-",
"k”mmlichen Editor weiterbearbeiten oder ausdrucken.",
"Da Sie dann mit den Pfeilsymbolen wohl wenig anfangen,",
"werden die Cursortasten durch die Krzel LEFT, RIGHT,",
"UP, DOWN repr„sentiert.",
"šbrigens: Mittels MT-PRINTER k”nnen Sie den Clipboardinhalt",
"auch direkt ausdrucken.",
""
};

char *optionhelp[]=
{
"Der Optionen-Dialog",
"-------------------",
" ",
"Mittels den Slidern k”nnen Sie verschiedene Verz”gerungs-",
"zeiten fr WinCom einstellen. MOVER ver„ndert die Zeit fr",
"das Echtzeit-Bewegen von Fenstern, SIZER fr das Verg”ern",
"und Verkleinern. Sie mssen diese Werte nur dann erh”hen,",
"wenn Sie bei den einzelnen Aktionen Redraw-Fehler erhalten.",
"Je gr”er der eingestellte Wert, umso gr”er die Verz”gerung,",
"umso eher klappts.",
"Falls ein Fenster auerdem nur sehr langsam und in sehr",
"kleinen Schritten der Maus folgt, sollten Sie ebenfalls",
"gr”ere Werte einstellen.",
"šber \'Empfehlung\' k”nnen Sie sich auch von WinSet eine",
"Empfehlung geben lassen, die auf einem kleinen Test Ihres",
"Systems beruht. Diese Empfehlung ist natrlich v”llig",
"unverbindlich, probieren Sie ruhig ein wenig herum.",
" ",
"Da alle Einstellungen sofort aktiv werden und nicht erst",
"nach bet„tigen des [OK]-Buttons, ist keine Anti-GEM-Schikane,",
"sonden soll das Finden der richtigen Einstellung er-",
"leichtern. Nach jeder nderung k”nnen Sie die Wirkung z.B.",
"sofort am Hilfe-Fenster testen. Freunden Sie sich also besser",
"damit an, ich werde es n„mlich bestimmt nicht „ndern.",
" ",
"šber ARROW stellen Sie die Verz”gerung fr das Scrollen,",
"also den Klick auf einen Fensterpfeil, ein.",
"WAIT gibt dabei an, wie lange nach dem Mausklick gewartet",
"werden soll, REPEAT gibt an, wie schnell das Scrollen",
"sein soll. Das funktioniert praktisch genau so, wie beim",
"Tastatur-Repeat, den Sie ja sicher vom Kontrollfeld her",
"kennen.",
" ",
"Mit den beiden unteren Slidern \`Raster fr MOVE & SIZE\'",
"k”nnen Sie ein Raster in horizontaler und vertikaler",
"Richtung bestimmen, das von WinCom bei Benutzung der Echt-",
"zeitfunktionen bercksichtigt wird. Stellen Sie z.B. beide",
"Werte auf 8, dann lassen sich Fenster nur noch in Schritten",
"von 8 Pixeln bewegen, was das ganze etwas schneller macht.",
"Mit der \'Alternate\'-Taste k”nnen Sie diese Option in",
"WinCom unterdrcken.",
" ",
"Im Feld \'Accessories\' stellen Sie ein, ber welche Tasten",
"die Accessories aufgerufen werden. Beachten Sie dabei, da",
"automatisch die Belegung mit den 10 Merkern gewechselt wird.",
"Wenn Sie also die Accessories ber die Funktionstasten auf-",
"rufen, dann Steuern Sie die Merker ber [1]-[0]. Wenn Sie",
"den Button \'Funktionstasten\' nicht aktivieren, dann liegen",
"die Accessories auf den Tasten [1]-[6] und die Merker auf den",
"Funktionstasten, alles klar?",
"Zus„tzlich k”nnen Sie bestimmen, welche Umschalttasten zum",
"Aufruf der Accessories n”tig sind. Die Umschalttasten fr",
"die Merker k”nnen Sie aber nicht „ndern!",
" ",
"Mittels \'Abbruch\' verlassen Sie den Dialog, wobei alle",
"get„tigten Einstellungen rckg„ngig gemacht werden.",
"šber \'OK\' werden alle Einstellungen bernommen.",
""
};

char *empfehltx[]=
{
"WinSet Empfehlung",
"-----------------",
" ",
"01 fr den Mover",
"01 fr den Sizer",
"05 fr Wait",
"01 fr Repeat",
""
};

char	*defhelp[]=
{
"Default-Einstellungen",
"---------------------",
" ",
"In diesem Dialog k”nnen Sie die Einstellungen treffen,",
"die beim Start von WinCom gelten sollen. Diejenigen",
"Funktionen, die sich direkt in WinCom aktivieren bzw.",
"deaktivieren lassen, k”nnen Sie hier nicht einstellen",
"(z.B. die Ausblend- oder die Maus-Automatik).",
"Trotzdem werden beim Sichern natrlich auch solche Ein-",
"stellungen bercksichtigt und stehen dann beim n„chsten",
"Start automatisch zur Verfgung.",
" ",
"Die meisten Optionen sollten selbsterkl„rend sein, deshalb",
"hier nur die wichtigsten:",
" ",
"Falls Sie MagiC 3.0 verwenden, so k”nnen Sie in der MAGX.INF-",
"Datei einstellen, ob der Backdropper fr alle Fenster an-",
"gemeldet werden soll oder fr keines. Geben Sie unter",
"\'Backdropper ist in MAGX.INF...\' bitte unbedingt an,",
"welche Einstellung Sie in Ihrer MAGX.INF-Datei get„tigt haben!",
" ",
"Wenn Sie \'Maxi-/Minimize nur wenn Sizer existier\' auf \'Ein\' ",
"stellen, dann werden die Fuller-Funktionen Maximize und ",
"Minimize nur dann ausgefhrt, wenn das Fenster auer einem",
"Fuller auch einen Sizer besitzt. Manche Programme k”nnen",
"allergisch reagieren, wenn man versucht Ihre Fenstergr”e",
"zu „ndern, obwohl sie keinen Sizer (aber einen Fuller)",
"besitzen (wie z.B. GEM-View oder die Gemini-Console).",
" ",
"\'Auch horizontal minimale Gr”e\'",
"Hier legen Sie fest, ob beim Aktivieren der Minimize-",
"Funktion das Fenster nur vertikal verkleinert werden soll",
"(\'Aus\'). Alternativ dazu k”nnen Sie ein Fenster auch",
"horizontal verkleinern. Das geschieht wahlweise nur dann,",
"wenn Minimize ber die Tastatur (\'Taste\'), ber die Maus",
"(\'Maus\') oder egal womit (\'Beides\') aufgerufen wird.",
" ",
"\'Fenster immer toppen bei Rechtsklick mit\' gibt an,",
"mit welcher Umschalttaste ein Rechtsklick immer zum",
"Toppen des angeklickten Fensters fhrt (egal, ob ein",
"Fensterelement angeklickt wurde). Die jeweils andere",
"Taste sorgt dann im Zusammenhang mit einem Rechtsklick",
"dafr, da ALLE Fenster der betreffenden Applikation",
"getopped werden. Beachten Sie, da dabei auch gleich-",
"zeitig die Umschalttaste fr die zus„tzliche Sizer-",
"Funktion ge„ndert wird!",
" ",
"Speziell fr EASE-Benutzer l„t sich das Abfangen",
"des Alt+Rechtsklick auch abschalten. Stellen Sie",
"dazu einfach \'Alt+Rechtsklick nicht abfangen\'",
"auf \'An\'.",
" ",
"\'Wenn App Backdrop nicht untersttzt:\'",
"Hier stellen Sie ein, wie die Fenster bei Verwendung",
"der Backdrop-Funktion behandelt werden sollen, wenn die",
"jeweilige Applikation das Backdroppen nicht untersttzt",
"(„ltere Programme).",
"Mit \'Alle Fenster toppen\' werden einfach alle anderen",
"Fenster getopped, was zwar dasselbe Ergebnis liefert,",
"dafr aber l„nger dauert.",
"Mit \'N„chstes Fenster toppen\' wird nur das Fenster",
"nach oben geholt, das unter dem zu backdroppenden",
"Fenster liegt.",
"Mit \'Letztes Fenster toppen\' wird das Fenster nach",
"oben geholt, das sich an unterster Stelle im Fenster-",
"stapel befindet.",
"šber die Einstellung \'Backrop erzwingen\' wird die jeweilige",
"Applikation gezwungen, ihr Fenster nach hinten zu legen.",
"Damit wird genau dasselbe wie beim normalen Backdroppen",
"erreicht aber nicht alle Applikationen vertragen dieses",
"Verfahren. Normalerweise ergeben sich in der Praxis aber",
"keine Probleme mit dieser Einstellung, weshalb sie als",
"Standardeinstellung zu empfehlen ist.",
"",
};

char *tophelp[]=
{
"Auto-Topping",
"------------",
" ",
"Im Feld \'Topping\' treffen Sie alle Einstellungen",
"fr das automatische Toppen von Fenstern.",
"\'Wartezeit\' gibt an, wann ein Fenster getopped werden",
"soll. Ist die Wartezeit 0, dann wird ein Fenster in dem",
"Moment getopped, in dem die Maus es berhrt.",
"Hat die Wartezeit aber einen Wert von 1-5, dann mu der",
"Maus-Zeiger erst auf dem Fenster zur Ruhe kommen, bevor",
"es durch WinCom getopped wird. \'šberfahrene\' Fenster",
"werden auf diese Art in Ruhe gelassen. Je gr”er der",
"eingestellte Wert, umso l„nger mu der Mauszeiger auf",
"dem Fenster liegen, bevor es getopped wird.",
"\'Mindestbewegung\' gibt an, um wie viele Pixel die Maus",
"mindestens bewegt werden mu, bis daraus berhaupt eine",
"Topping-Anforderung entsteht. Wenn Sie also ”fters mal",
"die Maus versehentlich anstoen, k”nnen Sie hier einen",
"Wert gr”er 1 einstellen, je nach Elan.",
"Im Feld mit den Buttons CTRL/Alt/LShft/RShft k”nnen Sie",
"eine beliebige Kombination an Umschalttasten fest-",
"legen. Das Topping wird immer dann unterdrckt, wenn",
"entweder eine oder alle der angegebenen Tasten gedrckt",
"sind. Letzteres stellen Sie ber das Popup \'Eine/Alle\'",
"ein.",
" ",
"Normalerweise wird ein Fenster nicht von WinCom getopped,",
"wenn dadurch das oberste Fenster vollst„ndig verdeckt",
"wrde. Wenn Sie dieses Verhalten st”rt, k”nnen Sie es",
"durch die Option \'Verdecken des obersten Fensters erlauben\'",
"abschalten.",
" ",
"Auerdem k”nnen Sie festlegen, ob das automatische Toppen",
"nur erfolgen soll, wenn sich die Maus im Arbeitsbereich eines",
"Fensters, d.h. nicht auf den Bedienelementen eines Fensters,",
"befindet.",
""
};

char	*reghelp[]=
{
"Registrierung",
"-------------",
" ",
"Tragen Sie im Feld \'Name\' Ihren Namen ein. Falls Ihr",
"Name Umlaute enth„lt, dann ersetzen Sie diese bitte",
"durch die entsprechenden Vokale. Senden Sie mir Ihren",
"Namen genau so zu, wie Sie ihn hier eingetragen haben.",
"Wenn Sie die Shareware-Gebhr bezahlt haben, so erhalten",
"Sie von mir einen Schlssel, den Sie im Feld \'Schlssel\'",
"eintragen. Bet„tigen Sie anschlieend Return oder klicken",
"Sie auf den OK-Button.",
"Sie sind damit registrierter WinCom-Benutzer. W„hlen Sie",
"nun \'Sichern\' im Hauptdialog und vergessen Sie nicht,",
"WinPut in den APPS-Ordner zu legen.",
" ",
"Genaueres ber die Shareware-Gebhr sowie meine Adresse",
"erfahren Sie in der WinCom-Anleitung.",
""
};

char	*starthelp[]=
{
"Starter-Hotkeys",
"---------------",
" ",
"Klicken Sie auf den \'Prg\'-Button und w„hlen Sie im dann",
"erscheinenden Fileselector das Programm, das gestartet",
"werden soll. Dabei kann es sich auch um ein Accessory handeln.",
"Lautet die Endung \'TOS\' oder \'TTP\' so wird das Popup",
"auf TOS eingestellt, was Sie aber jederzeit „ndern k”nnen.",
" ",
"Unter \'Cmd\' k”nnen Sie entweder \'von Hand\' eine  max.",
"76 Zeichen lange Kommandozeile eintragen, oder ber den",
"Fileselector eine zu bergebende Datei ausw„hlen, indem",
"Sie direkt auf den Button \'Cmd\' klicken. Dabei wird aber",
"ein evtl. bereits vorhandener Cmd-Eintrag berschrieben!",
" ",
"Beide Eintr„ge k”nnen auch per AV-Drag & Drop aus anderen",
"Applikationen bergeben werden.",
" ",
"šber das GEM/TOS-Popup k”nnen Sie einstellen, ob es sich",
"um eine GEM oder TOS-Applikation handelt. GEM-Applikationen",
"werden einfach gestartet w„hrend TOS-Applikationen zusammen",
"mit VT52 aufgerufen werden, sofern dies in MAGX.INF einge-",
"tragen ist.",
" ",
"Wenn Sie einen Starter-Hotkey aufrufen, untersucht WinCom",
"anhand des Dateinamens, ob das zu startende Programm",
"bereits aktiv ist. Fr diesen Fall k”nnen Sie unter drei",
"M”glichkeiten w„hlen:",
"\'VA_START\' sendet dem Programm eine VA_START-Meldung, wobei",
"auch die angegebene Kommandozeile bergeben wird. Diese",
"Meldung verstehen aber nicht alle Programme.",
"\'Aktivieren\' holt die Applikation in den Vordergrund, oder",
"(falls es sich um ein Accessory handelt) sendet ein AC_OPEN.",
"Eine Kommandozeile wird dabei ignoriert, dafr funktioniert",
"dieses Verfahren mit allen Programmen.",
"\'Nochmal starten\' startet das Programm einfach nochmal, es",
"befindet sich dann zweimal im Speicher. Hierbei wird eben-",
"falls die Kommandozeile bercksichtigt. Ein Accessory wird",
"dabei einfach als Programm gestartet.",
""
};

char *ashelp[]=
{
"Ausnahmeliste",
"-------------",
" ",
"In die Ausnahmeliste k”nnen Sie bis zu 16 Programme ein-",
"tragen, die im Taskswitch-Popup von WinCom nicht erscheinen",
"sollen. Diese Option ist fr Programme gedacht, die st„ndig",
"im Hintergrund aktiv sind, die Sie aber nie ber das Popup",
"anw„hlen, sondern z.B. per Mausklick oder ber einen Starter-",
"Hotkey. Oder Programme, die nur eine Anzeigefunktion er-",
"fllen. Solche Programme k”nnen z.B. CLOCK.APP oder",
"PINPOINT.PRG sein.",
" ",
"Um ein Programm einzutragen, klicken Sie einen Eintrag der",
"Liste an. Klicken Sie dann auf den Button \'ndern\' und",
"w„hlen Sie im erscheinenden Fileselector das gewnschte",
"Programm. Es wird in die Liste bernommen und Sie k”nnen",
"den Effekt sofort ausprobieren indem Sie den Taskwechsel-",
"Hotkey bet„tigen.",
"Wenn ein Programm wieder angezeigt werden soll, w„hlen Sie",
"dein entsprechenden Eintrag an und klicken Sie auf den",
"Button \'L”schen\'.",
""
};