# Makefile for clipboard files

testclip.prg : clipboar.obm testclip.obm
	$(M2LINK) testclip
	$(CP) testclip.tos testclip.prg
	$(RM) testclip.tos
	$(ECHO) testclip made

clean:
	$(RM) *.obm *.sbm *.rfm
