
CP68 DT.C DT.I
C068 DT.I DT.1 DT.2 DT.3 -F
DEL DT.I
C168 DT.1 DT.2 DT.S
DEL DT.1
DEL DT.2
AS68 -T -L -U -S c:\alyc\ DT.S
DEL DT.S
AS68 -T -L -U -S c:\alyc\ DTS.S
DEL DTS.S
CP68 TIME.C TIME.I
C068 TIME.I TIME.1 TIME.2 TIME.3 -F
DEL TIME.I
C168 TIME.1 TIME.2 TIME.S
DEL TIME.1
DEL TIME.2
AS68 -T -L -U -S c:\alyc\ TIME.S
DEL TIME.S
LINK68 TIME.PRG = TIME.O, DT.O, DTS.O
CP68 DATE.C DATE.I
C068 DATE.I DATE.1 DATE.2 DATE.3 -F
DEL DATE.I
C168 DATE.1 DATE.2 DATE.S
DEL DATE.1
DEL DATE.2
AS68 -T -L -U -S c:\alyc\ DATE.S
DEL DATE.S
LINK68 DATE.PRG = DATE.O, DT.O, DTS.O
