#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = aranym ehci ethernat netusbee unicorn

srcdir = .
top_srcdir = ../../..
subdir = ucd

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
