
NAME = vditest
HMAKE = ../hmake.sh

SRCS = contour.c fvdibug.c vdicolor.c vdifill.c vdiline.c vdimark.c vditext.c #vdiblit.c
PRGS = $(patsubst %.c, %.prg, $(SRCS))

all: $(PRGS)

fvdibug.prg: fvdibug.c
	$(HMAKE) $(NAME)/$@

contour.prg: contour.c cos.h vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

vdiblit.prg: vdiblit.c vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

vdicolor.prg: vdicolor.c vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

vdifill.prg: vdifill.c vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

vdiline.prg: vdiline.c vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

vdimark.prg: vdimark.c vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

vditext.prg: vditext.c vdiutil.c vdiutil.h
	$(HMAKE) $(NAME)/$@

# -----------------------------------

# remove compilation, check and AHCC stuff
clean:
	$(RM) *~ *.o *.O *.adb *.ADB *.map *.MAP

veryclean: clean
	$(RM) $(PRGS) *.PRG

PKG := $(NAME)-$(shell date -I).zip

package: $(PRGS) clean
	cd ..; \
	$(RM) $(PKG); \
	zip -r $(PKG) tests.vdi/*
