ARCHIV = gcc-ar.ttp
WINLIB = wx_lib.olb
LIBHDR = wx_lib.h
REPLAC = -r
WINTST = wx_tst.prg
LIBOBJ = wx_clear.o wx_close.o wx_free.o wx_full.o wx_get.o\
wx_info.o wx_init.o wx_move.o wx_name.o wx_new.o wx_open.o wx_print.o\
wx_puts.o wx_outst.o wx_fscro.o wx_setcl.o wx_setty.o wx_size.o
LIBG = -lwx_lib -lgem

all : clean $(WINLIB) $(WINTST)

$(WINLIB) : $(LIBOBJ)
	$(ARCHIV) $(REPLAC) $(WINLIB) $(LIBOBJ)

$(WINTST) : $(WINLIB)

$(LIBOBJ) : $(LIBHDR)

clean :
	$(RM) *.o
