#!/bin/sh
#
#	tellconfig - Tell the value of a <minix/config.h> parameter
#						Author: Volker Seebode
# Die sed-Version braucht 2 Sekunden gegenueber 3 der awk-Version
#
CONFIGFILE=../../include/minix/config.h

#awk '/#define.*'$1'.*$/{print $3;exit}{next}' <$CONFIGFILE
#/u2/src/commands/awk/awk '/#define.*'$1'.*$/{print $3;exit}{next}' <$CONFIGFILE
#gawk '/#define.*'$1'.*$/{print $3;exit}{next}' <$CONFIGFILE
#exit 0

# sed tuts auch
grep "^#.*define.*"$1 $CONFIGFILE | \
  sed 's/^.*\([0-1]\).*$/\1/g'

# EOF
