
CFLAGS= -Ie:\include

O= aline.o clock.o kamikaze.o droid.o fastrand.o graphics.o init.o \
input.o legal.o memory.o moves.o pieces.o simple.o tables.o

kamikaze: $O
	ln -o kamikaze.prg -f kamikaze.lnk e:\lib\c.lib e:\lib\gem.lib
