
#include "kamikaze.h"


extern int check_rook(), check_knight(), check_bishop(),
    check_queen(), check_king(), check_pawn();

/**** Start out with some pretty boring tables.  The first set of tables 
  is a list of all concievable moves for each piece.  (Castling is considered a
  king's move) ****/

Piece_move rook_moves[] =
    {
        {0, -7},
        {0, -6},
        {0, -5},
        {0, -4},
        {0, -3},
        {0, -2},
        {0, -1},
        {0, 1},
        {0, 2},
        {0, 3},
        {0, 4},
        {0, 5},
        {0, 6},
        {0, 7},
        {-7, 0},
        {-6, 0},
        {-5, 0},
        {-4, 0},
        {-3, 0},
        {-2, 0},
        {-1, 0},
        {1, 0},
        {2, 0},
        {3, 0},
        {4, 0},
        {5, 0},
        {6, 0},
        {7, 0},
    };
Piece_move knight_moves[] =
    {
        {-2, -1},
        {-2, 1},
        {2, -1},
        {2, 1},
        {-1, -2},
        {-1, 2},
        {1, -2},
        {1, 2},
    };
Piece_move bishop_moves[] =
    {
        {-7, -7},
        {-6, -6},
        {-5, -5},
        {-4, -4},
        {-3, -3},
        {-2, -2},
        {-1, -1},
        {1, 1},
        {2, 2},
        {3, 3},
        {4, 4},
        {5, 5},
        {6, 6},
        {7, 7},
        {-7, 7},
        {-6, 6},
        {-5, 5},
        {-4, 4},
        {-3, 3},
        {-2, 2},
        {-1, 1},
        {1, -1},
        {2, -2},
        {3, -3},
        {4, -4},
        {5, -5},
        {6, -6},
        {7, -7},
    };
Piece_move king_moves[] =
    {
        {-1, -1},
        {-1, 0},
        {-1, 1},
        {0, 1},
        {1, 1},
        {1, 0},
        {1, -1},
        {0, -1},
        {0, 2},
        {0, -2},
    };
Piece_move queen_moves[] =
    {
        {0, -7},
        {0, -6},
        {0, -5},
        {0, -4},
        {0, -3},
        {0, -2},
        {0, -1},
        {0, 1},
        {0, 2},
        {0, 3},
        {0, 4},
        {0, 5},
        {0, 6},
        {0, 7},
        {-7, 0},
        {-6, 0},
        {-5, 0},
        {-4, 0},
        {-3, 0},
        {-2, 0},
        {-1, 0},
        {1, 0},
        {2, 0},
        {3, 0},
        {4, 0},
        {5, 0},
        {6, 0},
        {7, 0},
        {-7, -7},
        {-6, -6},
        {-5, -5},
        {-4, -4},
        {-3, -3},
        {-2, -2},
        {-1, -1},
        {1, 1},
        {2, 2},
        {3, 3},
        {4, 4},
        {5, 5},
        {6, 6},
        {7, 7},
        {-7, 7},
        {-6, 6},
        {-5, 5},
        {-4, 4},
        {-3, 3},
        {-2, 2},
        {-1, 1},
        {1, -1},
        {2, -2},
        {3, -3},
        {4, -4},
        {5, -5},
        {6, -6},
        {7, -7},
    };
Piece_move wpawn_moves[4] =
    {
        {0, 1},
        {1, 1},
        {-1, 1},
        {0, 2},
    };
Piece_move bpawn_moves[4] =
    {
        {0, -1},
        {1, -1},
        {-1, -1},
        {0, -2},
    };

extern unsigned WORD
    iwhite_pawn[], iwhite_knight[], iwhite_bishop[], iwhite_rook[], 
    iwhite_queen[], iwhite_king[],
    iblack_pawn[], iblack_knight[], iblack_bishop[], iblack_rook[], 
    iblack_queen[], iblack_king[];

Piece white_pieces[16];
Piece black_pieces[16];

/* These are the data structures for the pieces.  They include the
   board position, info if piece alive, type of piece, color, 
   a name for the piece, an image for the piece, 
   a function to call to see if the piece
   can actually make a potential move (ie is it blocked?), a list
   of all potential moves, the value of the piece (which isn't
   much like normal chess at all, a pawn is worth more than a queen
   since it's harder to get rid of), and finally the index of the
   piece in this array */
Piece w_pieces[16] =
    {
        {
        0, 0, 0, ROOK,
        WHITE,
        "Rk",
        iwhite_rook,
        check_rook,
        rook_moves,
        Array_els(rook_moves),
        6,
        0,
        },
        {
        1, 0, 0, KNIGHT,
        WHITE,
        "Kt",
        iwhite_knight,
        check_knight,
        knight_moves,
        Array_els(knight_moves),
        2,
        1,
        },
        {
        2, 0, 0, BISHOP,
        WHITE,
        "Bp",
        iwhite_bishop,
        check_bishop,
        bishop_moves,
        Array_els(bishop_moves),
        4,
        2,
        },
        {
        3, 0, 0, KING,
        WHITE,
        "Kg",
        iwhite_king,
        check_king,
        king_moves,
        Array_els(king_moves),
        127,
        3,
        },
        {
        4, 0, 0, QUEEN,
        WHITE,
        "Qn",
        iwhite_queen,
        check_queen,
        queen_moves,
        Array_els(queen_moves),
        2,
        4,
        },
        {
        5, 0, 0, BISHOP,
        WHITE,
        "Bp",
        iwhite_bishop,
        check_bishop,
        bishop_moves,
        Array_els(bishop_moves),
        4,
        5,
        },
        {
        6, 0, 0, KNIGHT,
        WHITE,
        "Kt",
        iwhite_knight,
        check_knight,
        knight_moves,
        Array_els(knight_moves),
        2,
        6,
        },
        {
        7, 0, 0, ROOK,
        WHITE,
        "Rk",
        iwhite_rook,
        check_rook,
        rook_moves,
        Array_els(rook_moves),
        6,
        7,
        },
        {
        0, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        8,
        },
        {
        1, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        9,
        },
        {
        2, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        10,
        },
        {
        3, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        11,
        },
        {
        4, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        12,
        },
        {
        5, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        13,
        },
        {
        6, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        14,
        },
        {
        7, 1, 0, PAWN,
        WHITE,
        "Pn",
        iwhite_pawn,
        check_pawn,
        wpawn_moves,
        Array_els(wpawn_moves),
        3,
        15,
        },
    };

Piece b_pieces[16] =
    {
        {
        0, 7, 0, ROOK,
        BLACK,
        "Rk",
        iblack_rook,
        check_rook,
        rook_moves,
        Array_els(rook_moves),
        6,
        0,
        },
        {
        1, 7, 0, KNIGHT,
        BLACK,
        "Kt",
        iblack_knight,
        check_knight,
        knight_moves,
        Array_els(knight_moves),
        2,
        1,
        },
        {
        2, 7, 0, BISHOP,
        BLACK,
        "Bp",
        iblack_bishop,
        check_bishop,
        bishop_moves,
        Array_els(bishop_moves),
        4,
        2,
        },
        {
        3, 7, 0, KING,
        BLACK,
        "Kg",
        iblack_king,
        check_king,
        king_moves,
        Array_els(king_moves),
        127,
        3,
        },
        {
        4, 7, 0, QUEEN,
        BLACK,
        "Qn",
        iblack_queen,
        check_queen,
        queen_moves,
        Array_els(queen_moves),
        2,
        4,
        },
        {
        5, 7, 0, BISHOP,
        BLACK,
        "Bp",
        iblack_bishop,
        check_bishop,
        bishop_moves,
        Array_els(bishop_moves),
        4,
        5,
        },
        {
        6, 7, 0, KNIGHT,
        BLACK,
        "Kt",
        iblack_knight,
        check_knight,
        knight_moves,
        Array_els(knight_moves),
        2,
        6,
        },
        {
        7, 7, 0, ROOK,
        BLACK,
        "Rk",
        iblack_rook,
        check_rook,
        rook_moves,
        Array_els(rook_moves),
        6,
        7,
        },
        {
        0, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        8,
        },
        {
        1, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        9,
        },
        {
        2, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        10,
        },
        {
        3, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        11,
        },
        {
        4, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        12,
        },
        {
        5, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        13,
        },
        {
        6, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        14,
        },
        {
        7, 6, 0, PAWN,
        BLACK,
        "Pn",
        iblack_pawn,
        check_pawn,
        bpawn_moves,
        Array_els(bpawn_moves),
        3,
        15,
        },
    };

Piece *pieces[2] = {white_pieces, black_pieces};

/* Our chessboard.  */
Square board[8][8]; 

/* Some data structure for the 'artificial stupidity' algorithms to
   have the ST move a piece (see droid.c) and in fact
   just to check if a move is legal.  Must find out if any of the
   moves could take a piece 1st, and if so dis-allow all other moves. */

Move probable_moves[
    Array_els(rook_moves)*2 +
    Array_els(knight_moves)*2 +
    Array_els(bishop_moves)*2 +
    Array_els(queen_moves) +
    Array_els(king_moves) +
    Array_els(wpawn_moves)*8 ];
Move *sorted_moves[
    Array_els(rook_moves)*2 +
    Array_els(knight_moves)*2 +
    Array_els(bishop_moves)*2 +
    Array_els(queen_moves) +
    Array_els(king_moves) +
    Array_els(wpawn_moves)*8 ];

WORD probable_count;
WORD sorted_count;

