.TH AS6809 1L
.SH NAME
as6809 \- cross assembler for microcomputers
.SH SYNOPSIS
.nf
as6809 [-p cpu] [-l listfile] [-o hexfile] [-d] [-s symbolfile] input
.fi
.SH DESCRIPTION
The as6809 command assembles the input file into a
text output file representing the program memory for a microcomputer.

Options
.IP "-p cpu"
Ignored by this program.
.IP "-l listfile"
Output a file formated with the memory address, data, and source input lines.
.IP "-o hexfile"
Output the memory data image in a form accepted by most prom programmers.
.IP "-h hexfile"
Same as \-o.
.IP \-d
Save the intermediate data file (see FILE) and abort the execution at the
end of processing.
.IP "-s symbolfile"
Print the symbol table values and names, one per line in the specified file.
.SH FILES
/usr/tmp/frtXXXXXX
.SH SEE ALSO
Frankenstein Cross Assemblers Users Manual (file base.doc)
Appendix for as6809 Frankenstein Assembler (file as6809.doc)
.SH NOTES
There is only one input file.
