CP = e:\gemini2\bin\cp.ttp
SRC1 = e:\pure_c\zorg
SRC2 = f:\textes\zorg
HYP = e:\docs\st-guide.hyp
SRC3 = e:\pure_c\zorg\tos_40x.bug
DEST1 = a:\zorg
DEST2 = a:\textes
DEST3 = a:\zorg\tos_40x.bug

all: src_c src_h doc divers

src_c: $(DEST1)\boot.c \
	$(DEST1)\brut.c \
	$(DEST1)\curseur.c \
	$(DEST1)\config.c \
	$(DEST1)\deplace.c \
	$(DEST1)\desk.c \
	$(DEST1)\dialog.c \
	$(DEST1)\fat.c \
	$(DEST1)\fenetre.c \
	$(DEST1)\info.c \
	$(DEST1)\init.c \
	$(DEST1)\lance.c \
	$(DEST1)\link.c \
	$(DEST1)\main.c \
	$(DEST1)\menu.c \
	$(DEST1)\ouvre.c \
	$(DEST1)\reorg.c \
	$(DEST1)\search.c \
	$(DEST1)\secteur.c \
	$(DEST1)\tampon.c \
	$(DEST1)\update.c \
	$(DEST1)\wind.c \
	$(DEST1)\changes.txt \
	$(DEST1)\changes.eng \
	$(DEST1)\make_rsc.c \
	$(DEST1)\zstart.s \
	$(DEST1)\register.c \
	$(DEST1)\messgs.txt

src_h:	$(DEST1)\boot.h \
	$(DEST1)\brut.h \
	$(DEST1)\curseur.h \
	$(DEST1)\config.h \
	$(DEST1)\deplace.h \
	$(DEST1)\desk.h \
	$(DEST1)\dialog.h \
	$(DEST1)\divers.h \
	$(DEST1)\fat.h \
	$(DEST1)\fenetre.h \
	$(DEST1)\info.h \
	$(DEST1)\init.h \
	$(DEST1)\lance.h \
	$(DEST1)\menu.h \
	$(DEST1)\ouvre.h \
	$(DEST1)\reorg.h \
	$(DEST1)\search.h \
	$(DEST1)\secteur.h \
	$(DEST1)\tampon.h \
	$(DEST1)\update.h \
	$(DEST1)\wind.h \
	$(DEST1)\globals.h \
	$(DEST1)\divers.s \
	$(DEST1)\fcnt.h \
	$(DEST1)\zorg.hrd \
	$(DEST1)\zorg_e.hrd \
	$(DEST1)\zorg.prj \
	$(DEST1)\zorg.rsc \
	$(DEST1)\zorg_e.rsc \
	$(DEST1)\zorg.h \
	$(DEST1)\zorg.inf \
	$(DEST1)\make_rsc.prj \
	$(DEST1)\zorg_inf.h
#$(DEST1)\zorg.prg \

doc: 	$(DEST2)\zorg.stg \
	$(DEST2)\register.stw \
	$(DEST2)\lisezmoi.stw \
	$(DEST2)\read_me.stw \
	$(DEST1)\makefile

divers:	$(DEST3)\lastclst.c \
	$(DEST3)\lastclst.ttp \
	$(DEST1)\transinf.c \
	$(DEST1)\transinf.h \
	$(DEST1)\transinf.tos \
	$(DEST1)\transinf.prj

$(DEST1)\boot.c: $(SRC1)\boot.c
	$(CP) $(SRC1)\boot.c $(DEST1)\boot.c

$(DEST1)\brut.c: $(SRC1)\brut.c
	$(CP) $(SRC1)\brut.c $(DEST1)\brut.c

$(DEST1)\curseur.c: $(SRC1)\curseur.c
	$(CP) $(SRC1)\curseur.c $(DEST1)\curseur.c

$(DEST1)\config.c: $(SRC1)\config.c
	$(CP) $(SRC1)\config.c $(DEST1)\config.c

$(DEST1)\deplace.c: $(SRC1)\deplace.c
	$(CP) $(SRC1)\deplace.c $(DEST1)\deplace.c

$(DEST1)\desk.c: $(SRC1)\desk.c
	$(CP) $(SRC1)\desk.c $(DEST1)\desk.c

$(DEST1)\dialog.c: $(SRC1)\dialog.c
	$(CP) $(SRC1)\dialog.c $(DEST1)\dialog.c

$(DEST1)\ouvre.c: $(SRC1)\ouvre.c
	$(CP) $(SRC1)\ouvre.c $(DEST1)\ouvre.c

$(DEST1)\fat.c: $(SRC1)\fat.c
	$(CP) $(SRC1)\fat.c $(DEST1)\fat.c

$(DEST1)\fenetre.c: $(SRC1)\fenetre.c
	$(CP) $(SRC1)\fenetre.c $(DEST1)\fenetre.c

$(DEST1)\info.c: $(SRC1)\info.c
	$(CP) $(SRC1)\info.c $(DEST1)\info.c

$(DEST1)\init.c: $(SRC1)\init.c
	$(CP) $(SRC1)\init.c $(DEST1)\init.c

$(DEST1)\lance.c: $(SRC1)\lance.c
	$(CP) $(SRC1)\lance.c $(DEST1)\lance.c

$(DEST1)\link.c: $(SRC1)\link.c
	$(CP) $(SRC1)\link.c $(DEST1)\link.c

$(DEST1)\main.c: $(SRC1)\main.c
	$(CP) $(SRC1)\main.c $(DEST1)\main.c

$(DEST1)\menu.c: $(SRC1)\menu.c
	$(CP) $(SRC1)\menu.c $(DEST1)\menu.c

$(DEST1)\reorg.c: $(SRC1)\reorg.c
	$(CP) $(SRC1)\reorg.c $(DEST1)\reorg.c

$(DEST1)\search.c: $(SRC1)\search.c
	$(CP) $(SRC1)\search.c $(DEST1)\search.c

$(DEST1)\secteur.c: $(SRC1)\secteur.c
	$(CP) $(SRC1)\secteur.c $(DEST1)\secteur.c

$(DEST1)\tampon.c: $(SRC1)\tampon.c
	$(CP) $(SRC1)\tampon.c $(DEST1)\tampon.c

$(DEST1)\update.c: $(SRC1)\update.c
	$(CP) $(SRC1)\update.c $(DEST1)\update.c

$(DEST1)\wind.c: $(SRC1)\wind.c
	$(CP) $(SRC1)\wind.c $(DEST1)\wind.c

$(DEST1)\changes.txt: $(SRC1)\changes.txt
	$(CP) $(SRC1)\changes.txt $(DEST1)\changes.txt

$(DEST1)\changes.eng: $(SRC1)\changes.eng
	$(CP) $(SRC1)\changes.eng $(DEST1)\changes.eng

$(DEST1)\make_rsc.c: $(SRC1)\make_rsc.c
	$(CP) $(SRC1)\make_rsc.c $(DEST1)\make_rsc.c

$(DEST1)\zstart.s: $(SRC1)\zstart.s
	$(CP) $(SRC1)\zstart.s $(DEST1)\zstart.s

$(DEST1)\register.c: $(SRC1)\register.c
	$(CP) $(SRC1)\register.c $(DEST1)\register.c

$(DEST1)\messgs.txt: $(SRC1)\messgs.txt
	$(CP) $(SRC1)\messgs.txt $(DEST1)\messgs.txt

$(DEST1)\boot.h: $(SRC1)\boot.h
	$(CP) $(SRC1)\boot.h $(DEST1)\boot.h

$(DEST1)\brut.h: $(SRC1)\brut.h
	$(CP) $(SRC1)\brut.h $(DEST1)\brut.h

$(DEST1)\curseur.h: $(SRC1)\curseur.h
	$(CP) $(SRC1)\curseur.h $(DEST1)\curseur.h

$(DEST1)\config.h: $(SRC1)\config.h
	$(CP) $(SRC1)\config.h $(DEST1)\config.h

$(DEST1)\deplace.h: $(SRC1)\deplace.h
	$(CP) $(SRC1)\deplace.h $(DEST1)\deplace.h

$(DEST1)\desk.h: $(SRC1)\desk.h
	$(CP) $(SRC1)\desk.h $(DEST1)\desk.h

$(DEST1)\dialog.h: $(SRC1)\dialog.h
	$(CP) $(SRC1)\dialog.h $(DEST1)\dialog.h

$(DEST1)\ouvre.h: $(SRC1)\ouvre.h
	$(CP) $(SRC1)\ouvre.h $(DEST1)\ouvre.h

$(DEST1)\fat.h: $(SRC1)\fat.h
	$(CP) $(SRC1)\fat.h $(DEST1)\fat.h

$(DEST1)\fenetre.h: $(SRC1)\fenetre.h
	$(CP) $(SRC1)\fenetre.h $(DEST1)\fenetre.h

$(DEST1)\info.h: $(SRC1)\info.h
	$(CP) $(SRC1)\info.h $(DEST1)\info.h

$(DEST1)\init.h: $(SRC1)\init.h
	$(CP) $(SRC1)\init.h $(DEST1)\init.h

$(DEST1)\lance.h: $(SRC1)\lance.h
	$(CP) $(SRC1)\lance.h $(DEST1)\lance.h

$(DEST1)\menu.h: $(SRC1)\menu.h
	$(CP) $(SRC1)\menu.h $(DEST1)\menu.h

$(DEST1)\reorg.h: $(SRC1)\reorg.h
	$(CP) $(SRC1)\reorg.h $(DEST1)\reorg.h

$(DEST1)\search.h: $(SRC1)\search.h
	$(CP) $(SRC1)\search.h $(DEST1)\search.h

$(DEST1)\secteur.h: $(SRC1)\secteur.h
	$(CP) $(SRC1)\secteur.h $(DEST1)\secteur.h

$(DEST1)\tampon.h: $(SRC1)\tampon.h
	$(CP) $(SRC1)\tampon.h $(DEST1)\tampon.h

$(DEST1)\update.h: $(SRC1)\update.h
	$(CP) $(SRC1)\update.h $(DEST1)\update.h

$(DEST1)\wind.h: $(SRC1)\wind.h
	$(CP) $(SRC1)\wind.h $(DEST1)\wind.h

$(DEST1)\globals.h: $(SRC1)\globals.h
	$(CP) $(SRC1)\globals.h $(DEST1)\globals.h

$(DEST1)\divers.s: $(SRC1)\divers.s
	$(CP) $(SRC1)\divers.s $(DEST1)\divers.s

$(DEST1)\divers.h: $(SRC1)\divers.h
	$(CP) $(SRC1)\divers.h $(DEST1)\divers.h

$(DEST1)\fcnt.h: $(SRC1)\fcnt.h
	$(CP) $(SRC1)\fcnt.h $(DEST1)\fcnt.h

$(DEST1)\zorg.hrd: $(SRC1)\zorg.hrd
	$(CP) $(SRC1)\zorg.hrd $(DEST1)\zorg.hrd

$(DEST1)\zorg_e.hrd: $(SRC1)\zorg_e.hrd
	$(CP) $(SRC1)\zorg_e.hrd $(DEST1)\zorg_e.hrd

$(DEST1)\zorg.prg: $(SRC1)\zorg.prg
	$(CP) $(SRC1)\zorg.prg $(DEST1)\zorg.prg

$(DEST1)\zorg.prj: $(SRC1)\zorg.prj
	$(CP) $(SRC1)\zorg.prj $(DEST1)\zorg.prj

$(DEST1)\zorg.h: $(SRC1)\zorg.h
	$(CP) $(SRC1)\zorg.h $(DEST1)\zorg.h

$(DEST1)\zorg.rsc: $(SRC1)\zorg.rsc
	$(CP) $(SRC1)\zorg.rsc $(DEST1)\zorg.rsc

$(DEST1)\zorg_e.rsc: $(SRC1)\zorg_e.rsc
	$(CP) $(SRC1)\zorg_e.rsc $(DEST1)\zorg_e.rsc

$(DEST1)\zorg.inf: $(SRC1)\zorg.inf
	$(CP) $(SRC1)\zorg.inf $(DEST1)\zorg.inf

$(DEST1)\makefile: $(SRC1)\makefile
	$(CP) $(SRC1)\makefile $(DEST1)\makefile

$(DEST1)\make_rsc.prj: $(SRC1)\make_rsc.prj
	$(CP) $(SRC1)\make_rsc.prj $(DEST1)\make_rsc.prj

$(DEST1)\zorg_inf.h: $(SRC1)\zorg_inf.h
	$(CP) $(SRC1)\zorg_inf.h $(DEST1)\zorg_inf.h

$(DEST2)\zorg.stg: $(SRC2)\zorg.stg
	$(CP) $(SRC2)\zorg.stg $(DEST2)\zorg.stg
	$(CP) $(HYP)\zorg.hyp $(DEST2)\zorg.hyp

$(DEST2)\register.stw: $(SRC2)\register.stw
	$(CP) $(SRC2)\register.stw $(DEST2)\register.stw

$(DEST2)\lisezmoi.stw: $(SRC2)\lisezmoi.stw
	$(CP) $(SRC2)\lisezmoi.stw $(DEST2)\lisezmoi.stw

$(DEST2)\read_me.stw: $(SRC2)\read_me.stw
	$(CP) $(SRC2)\read_me.stw $(DEST2)\read_me.stw

$(DEST3)\lastclst.c: $(SRC3)\lastclst.c
	$(CP) $(SRC3)\lastclst.c $(DEST3)\lastclst.c

$(DEST3)\lastclst.ttp: $(SRC3)\lastclst.ttp
	$(CP) $(SRC3)\lastclst.ttp $(DEST3)\lastclst.ttp

$(DEST1)\transinf.h: $(SRC1)\transinf.h
	$(CP) $(SRC1)\transinf.h $(DEST1)\transinf.h

$(DEST1)\transinf.c: $(SRC1)\transinf.c
	$(CP) $(SRC1)\transinf.c $(DEST1)\transinf.c

$(DEST1)\transinf.prj: $(SRC1)\transinf.prj
	$(CP) $(SRC1)\transinf.prj $(DEST1)\transinf.prj

$(DEST1)\transinf.tos: $(SRC1)\transinf.tos
	$(CP) $(SRC1)\transinf.tos $(DEST1)\transinf.tos

