/* Resource Datei Indizes fÅr EXAMPLE */

#define TREE             0   /* Formular/Dialog */
#define BUTTON_BACKGRD   2   /* BUTTON in Baum TREE */
#define BUTTON_BUTTON    3   /* BUTTON in Baum TREE */
#define BUTTON_HEADLINE  4   /* BUTTON in Baum TREE */
#define BUTTON_RAHMEN    5   /* BUTTON in Baum TREE */
#define BUTTON_SEPARATOR 6   /* BUTTON in Baum TREE */
#define BOX_SEPARATOR    7   /* BOX in Baum TREE */
#define ENDE             27  /* BUTTON in Baum TREE */
#define BOX_RAHMEN       28  /* BOX in Baum TREE */
#define BOX_HEADLINE     38  /* BOX in Baum TREE */
#define BOX_BUTTON       50  /* BOX in Baum TREE */
#define BOX_BACKGRD      71  /* BOX in Baum TREE */

#define TREE1            1   /* Formular/Dialog */
