
/* flicmenu.c generated by mm version 2 */

#include "flicker.h"
#include "flicmenu.h"

extern inverse_cursor(), black_block(), see_islidepot(),
	time_mode(), toggle_group(),
	tmnext_frame(), tmlast_frame(),
	mmsee_slider(), mmfeel_slider(),
	see_number_slider(), feel_number_slider(),
	tplay_forwards(), tplay_backwards(), tgo_first(), tgo_last(),
	trewind(), tfast_forward(),
	tappend(), tinsert(),
	virtual_next_frame(),
	see_trange(), change_trange(),
	wbnumber_arrows(), 
	incr_in_trange(), decr_in_trange(),
	incl_in_trange(), decl_in_trange(),
	stuff_tv(),
	make_10(),
	inc_in_trange(),
	left_arrow(), right_arrow(), inc_slider(), dec_slider(),
	madd_ten(),
	wbtext(), wbnumber(), white_slice();

extern struct cursor cdown, cleft, cright, csleft,
	cinsert, cappend, cright2, cleft2, csright, cup;

#define DOFF	0

extern struct slidepot frame_sl; 

extern WORD rd_more;
struct range trange =
	{
	1,
	1,
	1,
	1,
	};

struct flicmenu inc_tright_sel =
	{
	NONEXT,
	NOCHILD,
	217+51+1-4+49-9+2-1, DOFF+139+1+45,	12, 13,
	(char *)&cright,
	inverse_cursor,
	incr_in_trange,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu tright_time_sel =
	{
	&inc_tright_sel,
	NOCHILD,
	217+51+1-4+10+1+2+1, DOFF+139+1+45,	25, 13,
	(char *)&trange.v2,
	wbnumber,
	stuff_tv,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu dec_tright_sel =
	{
	&tright_time_sel,
	NOCHILD,
	217+51+1-4, DOFF+139+1+45,	12, 13,
	(char *)&cleft,
	inverse_cursor,
	decr_in_trange,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu tsegment_sel = 
	{
	&dec_tright_sel,
	NOCHILD,
	56, DOFF+139+1+45,	207, 13,
	(char *)&trange,
	see_trange,
	change_trange,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu inc_tleft_sel =
	{
	&tsegment_sel,
	NOCHILD,
	1+49-9+2-1, DOFF+139+1+45,	12, 13,
	(char *)&cright,
	inverse_cursor,
	incl_in_trange,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu tleft_time_sel =
	{
	&inc_tleft_sel,
	NOCHILD,
	1+10+1+2+1, DOFF+139+1+45,	25, 13,
	(char *)&trange.v1,
	wbnumber,
	stuff_tv,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu dec_tleft_sel =
	{
	&tleft_time_sel,
	NOCHILD,
	1, DOFF+139+1+45,	12, 13,
	(char *)&cleft,
	inverse_cursor,
	decl_in_trange,
	NOGROUP, 0,
	NOKEY,
	};
WORD select_mode;
struct flicmenu sel_all_sel =
	{
	&dec_tleft_sel,
	NOCHILD,
	214, DOFF+139+1+30,	104, 13,
	"To All",
	wbtext,
	time_mode,
	&select_mode, 2,
	NOKEY,
	};
struct flicmenu sel_segment_sel =
	{
	&sel_all_sel,
	NOCHILD,
	107, DOFF+139+1+30,	105, 13,
	"To Segment",
	wbtext,
	time_mode,
	&select_mode, 1,
	NOKEY,
	};
struct flicmenu sel_frame_sel =
	{
	&sel_segment_sel,
	NOCHILD,
	1, DOFF+139+1+30,	104, 13,
	"To Frame",
	wbtext,
	time_mode,
	&select_mode, 0,
	NOKEY,
	};

WORD tween_mode = 1;
struct flicmenu tween_sel =
	{
	&sel_frame_sel,
	NOCHILD,
	254, DOFF+139+1+15,	318-254, 13,
	"Tween",
	wbtext,
	toggle_group,
	&tween_mode, 1,
	't',
	};
struct slidepot speed_sl =
	{
	1,
	59,
	3,
	};
extern struct flicmenu speed_sel;
struct flicmenu tms_1f4 = 
	{
	&tween_sel,
	NOCHILD,
	240, DOFF+139+1+15,	12, 13,
	(char *)&speed_sel,
	right_arrow,
	inc_slider,
	NOGROUP, 0,
	NOKEY,
	};
struct flicmenu speed_sel = 
	{
	&tms_1f4,
	NOCHILD,
	82, DOFF+139+1+15,	156, 13,
	(char *)&speed_sl,
	see_number_slider,
	feel_number_slider,
	NOGROUP, 0,
	};
struct flicmenu tms_1f2 = 
	{
	&speed_sel,
	NOCHILD,
	68, DOFF+139+1+15,	12, 13,
	(char *)&speed_sel,
	left_arrow,
	dec_slider,
	NOGROUP, 0,
	NOKEY,
	};

struct flicmenu tms_advance = 
	{
	&tms_1f2,
	NOCHILD,
	1, DOFF+139+1+15,	65, 13,
	"More",
	wbtext,
	virtual_next_frame,
	&rd_more, 1,
	NOKEY,
	};

struct flicmenu tframes_sel = 
	{
	&tms_advance,
	NOCHILD,
	281, DOFF+139+1,	37, 13,
	(char *)&screen_ct,
	wbnumber,
	make_10,
	NOGROUP, 0,
	'\r',
	};
struct flicmenu tms_fa = 
	{
	&tframes_sel,
	NOCHILD,
	266, DOFF+139+1,	13, 13,
	(char *)&cdown,
	inverse_cursor,
	tgo_last,
	NOGROUP, 0,
	0x4400,	/* F10 */
	};
struct flicmenu tms_f9 = 
	{
	&tms_fa,
	NOCHILD,
	248, DOFF+139+1,	16, 13,
	(char *)&cright2,
	inverse_cursor,
	tfast_forward,
	NOGROUP, 0,
	0x4300,	/* F9 */
	};
struct flicmenu tms_f8 = 
	{
	&tms_f9,
	NOCHILD,
	232, DOFF+139+1,	14, 13,
	(char *)&cright,
	inverse_cursor,
	tplay_forwards,
	NOGROUP, 0,
	0x4200,	/* F8 */
	};
struct flicmenu tms_f8a = 
	{
	&tms_f8,
	NOCHILD,
	232, DOFF+139+1,	14, 13,
	NOTEXT,
	NOSEE,
	tplay_forwards,
	NOGROUP, 0,
	0x5000,	/* down arrow */
	};
struct flicmenu tms_f7 = 
	{
	&tms_f8a,
	NOCHILD,
	214, DOFF+139+1,	16, 13,
	(char *)&cappend,
	inverse_cursor,
	tappend,
	NOGROUP, 0,
	0x4100,	/* F7 */
	};
struct flicmenu tms_f4 = 
	{
	&tms_f7,
	NOCHILD,
	196, DOFF+139+1,	16, 13,
	(char *)&csright,
	inverse_cursor,
	tmnext_frame,
	NOGROUP, 0,
	0x4000,	/* F6 */
	};
struct flicmenu tms_f4a = 
	{
	&tms_f4,
	NOCHILD,
	196, DOFF+139+1,	16, 13,
	NOTEXT,
	NOSEE,
	tmnext_frame,
	NOGROUP, 0,
	0x4d00,	/* right arrow */
	};
struct flicmenu tframe_sel = 
	{
	&tms_f4a,
	NOCHILD,
	86, DOFF+139+1,	108, 13,
	(char *)&frame_sl,
	mmsee_slider,
	mmfeel_slider,
	NOGROUP, 0,
	};
struct flicmenu tms_f2 = 
	{
	&tframe_sel,
	NOCHILD,
	68, DOFF+139+1,	16, 13,
	(char *)&csleft,
	inverse_cursor,
	tmlast_frame,
	NOGROUP, 0,
	0x3f00,	/* F5 */
	};
struct flicmenu tms_f2a = 
	{
	&tms_f2,
	NOCHILD,
	68, DOFF+139+1,	16, 13,
	NOTEXT,
	NOSEE,
	tmlast_frame,
	NOGROUP, 0,
	0x4b00,	/* left arrow */
	};
struct flicmenu tms_f1 = 
	{
	&tms_f2a,
	NOCHILD,
	50, DOFF+139+1,	16, 13,
	(char *)&cinsert,
	inverse_cursor,
	tinsert,
	NOGROUP, 0,
	0x3e00,	/* F4 */
	};
struct flicmenu tms_f0 = 
	{
	&tms_f1,
	NOCHILD,
	34, DOFF+139+1,	14, 13,
	(char *)&cleft,
	inverse_cursor,
	tplay_backwards,
	NOGROUP, 0,
	0x3d00,	/* F3 */
	};
struct flicmenu tms_f0a = 
	{
	&tms_f0,
	NOCHILD,
	34, DOFF+139+1,	14, 13,
	NOTEXT,
	NOSEE,
	tplay_backwards,
	NOGROUP, 0,
	0x4800,	/* up arrow */
	};
struct flicmenu tms_ef = 
	{
	&tms_f0a,
	NOCHILD,
	16, DOFF+139+1,	16, 13,
	(char *)&cleft2,
	inverse_cursor,
	trewind,
	NOGROUP, 0,
	0x3c00,	/* F2 */
	};
struct flicmenu tms_ee = 
	{
	&tms_ef,
	NOCHILD,
	1, DOFF+139+1,	13, 13,
	(char *)&cup,
	inverse_cursor,
	tgo_first,
	NOGROUP, 0,
	0x3b00,	/* F1 */
	};
struct flicmenu menutime = 
	{
	NONEXT,
	&tms_ee,
	0, DOFF+139,	319, 60-DOFF,
	NOTEXT,
	white_slice,
	NOFEEL,
	NOGROUP, 0,
	};
