.TH AS6502 1L
.SH NAME
as6502, as65c00, asr65c00 \- cross assemblers for microcomputers
.SH SYNOPSIS
.nf
as6502 [-p cpu] [-l listfile] [-o hexfile] [-d] [-s symbolfile] input
as65c00 [-p cpu] [-l listfile] [-o hexfile] [-d] [-s symbolfile] input
asr65c00 [-p cpu] [-l listfile] [-o hexfile] [-d] [-s symbolfile] input
.fi
.SH DESCRIPTION
The as6502, as65c00, asr65c00 command assembles the input file into a
text output file representing the program memory for a microcomputer.

Options
.IP "-p cpu"
Override the instruction set selection.
.RS 10
Valid Values for Cpu
.RS 5
65, 65c, r65, r65c, 21
.RE
.RE
.IP "-l listfile"
Output a file formated with the memory address, data, and source input lines.
.IP "-o hexfile"
Output the memory data image in a form accepted by most prom programmers.
.IP "-h hexfile"
Same as \-o.
.IP \-d
Save the intermediate data file (see FILE) and abort the execution at the
end of processing.
.IP "-s symbolfile"
Print the symbol table values and names, one per line in the specified file.
.SH FILES
/usr/tmp/frtXXXXXX
.SH SEE ALSO
Frankenstein Cross Assemblers Users Manual (file base.doc)
Appendix for as6502 Frankenstein Assembler (file as6502.doc)
.SH NOTES
There is only one input file.

The program can select which subset of instructions is accepted.
The program first uses the name with which it is invoked.
This is scanned for a substring which indicates which set to use.
The -p options overrides this selction by performing the same substring
search.
Finally the input file can select which subset to use with the CPU statement.

There should only be one executable file with all of its names linked to it.
