.\" @(#) pi3 1.0 90/12/16 rosenkra
.\" name,sec,chapter,version,date,format style
.TH PI3 1 "" "" "" ONLINE
.SH NAME
pi3 \- display PI3 files (monochrome only)
.SH SYNOPSIS
.\"	pi3 file ...
.B pi3
.IR file ...
.SH DESCRIPTION
.B Pi3
displays one or more monochrome PI3 files on a monochrome monitor.
It checks to see if the files really are high resolution and will not
display those that are not.
It resets the color palette as needed, but resets the system back to
what it was before it exits.
.SH FILES
.nf
*.pi3     GEM/Degas high resolution image files
.fi
.SH "SEE ALSO"
mgif(1), picture(5)
.SH DIAGNOSTICS
Various warnings attempting to isolate corrupted files.
The usual messages about errors openning files, etc.
.SH NOTES
After an image is drawn, enter any key to see next image.
There is no "cycling" capability, though this would be trivial to add.
.SH AUTHOR
.nf
Bill Rosenkranz
rosenkra@convex.com
.fi
.SH VERSION
pi3 1.0 90/12/16 rosenkra
.EX
