#
# MakeFile
# g‚nŠre le code exc‚cutable de MidiConnect
#
CFLAGS= -A -DMWC
OBJ   = connect.o  con_appl.o con_aff.o con_slid.o

mconnect: $(OBJ)
       cc -o msnet.prg -VGEMAPP $(OBJ) -lmidi
       strip msnet.prg
       cp msnet.prg msnet.acc

connect.o: msnet.h con_defs.h
con_appl.o: con_defs.h
con_aff.o: msnet.h con_defs.h
con_slid.o: msnet.h con_defs.h
