#
# makefile to create the factor sample program
# 
# Note that this uses the built-in macros as opposed to explicit
# actions.
#
factor.prg:	factor.o atod.o
	$(CC) $(CFLAGS) -f -o factor.prg factor.o atod.o -lm
