#define TERMMENU 0  	/* TREE */
#define ABOUT 1  	/* TREE */
#define GENSETUP 2  	/* TREE */
#define DISSETUP 3  	/* TREE */
#define GRAFSET 4  	/* TREE */
#define PRTSETUP 5  	/* TREE */
#define COMMSET 6  	/* TREE */
#define TABSET 7  	/* TREE */
#define KEYSETUP 9  	/* TREE */
#define ENHCSET 10  	/* TREE */
#define TREE11 11  	/* TREE */
#define TREE12 12  	/* TREE */
#define TREE13 13  	/* TREE */
#define TREE14 14  	/* TREE */
#define TREE15 15  	/* TREE */
#define TREE16 16  	/* TREE */
#define TREE17 17  	/* TREE */
#define TREE18 8  	/* TREE */
#define TREE19 18  	/* TREE */
#define TREE20 19  	/* TREE */
#define TREE21 20  	/* TREE */
#define TREE22 21  	/* TREE */
#define TREE23 22  	/* TREE */
#define TREE24 23  	/* TREE */
#define TREE25 24  	/* TREE */
#define TREE26 25  	/* TREE */
#define TREE27 26  	/* TREE */
#define TREE28 27  	/* TREE */
#define TREE29 28  	/* TREE */
#define TREE30 29  	/* TREE */
#define TREE31 30  	/* TREE */
#define TREE32 31  	/* TREE */
#define TREE33 32  	/* TREE */
#define TREE34 33  	/* TREE */
#define TREE35 34  	/* TREE */
#define TREE36 35  	/* TREE */
#define TREE37 36  	/* TREE */
#define TREE38 37  	/* TREE */
#define TREE39 38  	/* TREE */
#define TREE40 39  	/* TREE */
#define TREE41 40  	/* TREE */
#define TREE42 41  	/* TREE */
#define TREE43 42  	/* TREE */
#define TREE44 43  	/* TREE */
#define TREE45 44  	/* TREE */
#define TREE46 45  	/* TREE */
#define TREE47 46  	/* TREE */
#define TREE48 47  	/* TREE */
#define TREE49 48  	/* TREE */
#define TREE50 49  	/* TREE */
#define TREE51 50  	/* TREE */
#define TREE52 51  	/* TREE */
#define TREE53 52  	/* TREE */
#define TREE54 53  	/* TREE */
#define TERMDESK 3  	/* OBJECT in TREE #0 */
#define TERMFILE 4  	/* OBJECT in TREE #0 */
#define TERMINFO 9  	/* OBJECT in TREE #0 */
#define TERMSET 5  	/* OBJECT in TREE #0 */
#define TERMGEN 26  	/* OBJECT in TREE #0 */
#define TERMCOMM 27  	/* OBJECT in TREE #0 */
#define TERMGRAF 28  	/* OBJECT in TREE #0 */
#define TERMDIS 29  	/* OBJECT in TREE #0 */
#define TERMTABS 30  	/* OBJECT in TREE #0 */
#define TERMPRT 31  	/* OBJECT in TREE #0 */
#define TERMENHC 32  	/* OBJECT in TREE #0 */
#define TERMKEY 33  	/* OBJECT in TREE #0 */
#define TERMOPTS 6  	/* OBJECT in TREE #0 */
#define TERMOK 8  	/* OBJECT in TREE #1 */
#define GENOK 2  	/* OBJECT in TREE #2 */
#define GENCANC 3  	/* OBJECT in TREE #2 */
#define TERMQUIT 24  	/* OBJECT in TREE #0 */
#define TERMSPIC 18  	/* OBJECT in TREE #0 */
#define TERMLPIC 19  	/* OBJECT in TREE #0 */
#define TERMUPLO 20  	/* OBJECT in TREE #0 */
#define TERMDOLO 21  	/* OBJECT in TREE #0 */
#define TERMNV 35  	/* OBJECT in TREE #0 */
#define GSLHAIR 3  	/* OBJECT in TREE #4 */
#define GSOK 4  	/* OBJECT in TREE #4 */
#define GSCANC 5  	/* OBJECT in TREE #4 */
#define GSDEL 7  	/* OBJECT in TREE #4 */
#define GSGIN 9  	/* OBJECT in TREE #4 */
#define GSGINEOT 11  	/* OBJECT in TREE #4 */
#define GSGINCR 10  	/* OBJECT in TREE #4 */
#define GSGINCRE 12  	/* OBJECT in TREE #4 */
#define GSGINNO 13  	/* OBJECT in TREE #4 */
#define GENONLIN 6  	/* OBJECT in TREE #2 */
#define GENLOCAL 7  	/* OBJECT in TREE #2 */
#define GENCR 12  	/* OBJECT in TREE #2 */
#define GENCRLF 13  	/* OBJECT in TREE #2 */
#define CS19200 5  	/* OBJECT in TREE #6 */
#define CS9600 6  	/* OBJECT in TREE #6 */
#define CS4800 8  	/* OBJECT in TREE #6 */
#define CS3600 9  	/* OBJECT in TREE #6 */
#define CS2400 7  	/* OBJECT in TREE #6 */
#define CS2000 10  	/* OBJECT in TREE #6 */
#define CS1800 11  	/* OBJECT in TREE #6 */
#define CS1200 12  	/* OBJECT in TREE #6 */
#define CS600 17  	/* OBJECT in TREE #6 */
#define CS300 18  	/* OBJECT in TREE #6 */
#define CS200 19  	/* OBJECT in TREE #6 */
#define CS150 20  	/* OBJECT in TREE #6 */
#define CS134 13  	/* OBJECT in TREE #6 */
#define CS110 14  	/* OBJECT in TREE #6 */
#define CS75 15  	/* OBJECT in TREE #6 */
#define CS50 16  	/* OBJECT in TREE #6 */
#define CSOK 21  	/* OBJECT in TREE #6 */
#define CSCANCEL 22  	/* OBJECT in TREE #6 */
#define CSRTS 28  	/* OBJECT in TREE #6 */
#define CSNORTS 29  	/* OBJECT in TREE #6 */
#define CSLECHO 33  	/* OBJECT in TREE #6 */
#define CSNOLECH 34  	/* OBJECT in TREE #6 */
#define CSIXON 37  	/* OBJECT in TREE #6 */
#define CSNOIXON 36  	/* OBJECT in TREE #6 */
#define CSSLOW 41  	/* OBJECT in TREE #6 */
#define CSFAST 42  	/* OBJECT in TREE #6 */
