#define CONF 0  	/* TREE */
#define PU_C_TYP 1  	/* TREE */
#define PU_C_PRT 2  	/* TREE */
#define CON_BOX 4  	/* OBJECT in TREE #0 */
#define CC_SCRPT 5  	/* OBJECT in TREE #0 */
#define CM_BOX 6  	/* OBJECT in TREE #0 */
#define CM_INIT 9  	/* OBJECT in TREE #0 */
#define CM_DIAL 10  	/* OBJECT in TREE #0 */
#define CM_HANG 11  	/* OBJECT in TREE #0 */
#define CM_CTOUT 12  	/* OBJECT in TREE #0 */
#define CM_RDLAY 13  	/* OBJECT in TREE #0 */
#define CM_CON1 16  	/* OBJECT in TREE #0 */
#define CM_CON2 17  	/* OBJECT in TREE #0 */
#define CM_CON3 18  	/* OBJECT in TREE #0 */
#define CM_RED1 20  	/* OBJECT in TREE #0 */
#define CM_RED2 21  	/* OBJECT in TREE #0 */
#define CM_RED3 22  	/* OBJECT in TREE #0 */
#define CM_ABO1 24  	/* OBJECT in TREE #0 */
#define CM_ABO2 25  	/* OBJECT in TREE #0 */
#define CM_ABO3 26  	/* OBJECT in TREE #0 */
#define CP_BOX 28  	/* OBJECT in TREE #0 */
#define CP_IP 30  	/* OBJECT in TREE #0 */
#define CP_MTU 31  	/* OBJECT in TREE #0 */
#define CP_PID 32  	/* OBJECT in TREE #0 */
#define CP_PPTXT 33  	/* OBJECT in TREE #0 */
#define CP_PPASS 34  	/* OBJECT in TREE #0 */
#define CP_FPPW 36  	/* OBJECT in TREE #0 */
#define CP_PPPW 37  	/* OBJECT in TREE #0 */
#define CP_TPPW 38  	/* OBJECT in TREE #0 */
#define CP_SLIP 41  	/* OBJECT in TREE #0 */
#define CP_PPP 43  	/* OBJECT in TREE #0 */
#define CP_VJHC 46  	/* OBJECT in TREE #0 */
#define CP_LAN 49  	/* OBJECT in TREE #0 */
#define CP_LTXT 50  	/* OBJECT in TREE #0 */
#define CA_BOX 52  	/* OBJECT in TREE #0 */
#define CA_USER 54  	/* OBJECT in TREE #0 */
#define CA_FULL 55  	/* OBJECT in TREE #0 */
#define CA_FQDN 57  	/* OBJECT in TREE #0 */
#define CA_PREV 60  	/* OBJECT in TREE #0 */
#define CA_DNS 61  	/* OBJECT in TREE #0 */
#define CA_NEXT 62  	/* OBJECT in TREE #0 */
#define CA_ADD 63  	/* OBJECT in TREE #0 */
#define CA_GETNS 65  	/* OBJECT in TREE #0 */
#define CA_NSTXT 66  	/* OBJECT in TREE #0 */
#define CG_BOX 68  	/* OBJECT in TREE #0 */
#define CG_PORT 72  	/* OBJECT in TREE #0 */
#define CG_DEFRT 75  	/* OBJECT in TREE #0 */
#define CG_MASQU 78  	/* OBJECT in TREE #0 */
#define CG_MTXT 79  	/* OBJECT in TREE #0 */
#define CG_LOGIN 81  	/* OBJECT in TREE #0 */
#define CG_CIX 84  	/* OBJECT in TREE #0 */
#define CG_RESI 87  	/* OBJECT in TREE #0 */
#define CG_RTXT 88  	/* OBJECT in TREE #0 */
#define CG_DEBUG 90  	/* OBJECT in TREE #0 */
#define CT_BOX 93  	/* OBJECT in TREE #0 */
#define CT_PREV 97  	/* OBJECT in TREE #0 */
#define CT_NUM 98  	/* OBJECT in TREE #0 */
#define CT_NEXT 99  	/* OBJECT in TREE #0 */
#define CT_ADD 100  	/* OBJECT in TREE #0 */
#define CT_FEE 101  	/* OBJECT in TREE #0 */
#define CI_TU 104  	/* OBJECT in TREE #0 */
#define CI_TC 105  	/* OBJECT in TREE #0 */
#define CI_SU 106  	/* OBJECT in TREE #0 */
#define CI_SC 107  	/* OBJECT in TREE #0 */
#define CI_RU 108  	/* OBJECT in TREE #0 */
#define CI_RC 109  	/* OBJECT in TREE #0 */
#define CD_BOX 112  	/* OBJECT in TREE #0 */
#define CD_TOUT 114  	/* OBJECT in TREE #0 */
#define CD_IBOX 115  	/* OBJECT in TREE #0 */
#define CD_PREV 118  	/* OBJECT in TREE #0 */
#define CD_STEP 119  	/* OBJECT in TREE #0 */
#define CD_NEXT 120  	/* OBJECT in TREE #0 */
#define CD_INS 121  	/* OBJECT in TREE #0 */
#define CD_DEL 122  	/* OBJECT in TREE #0 */
#define CD_TIME 123  	/* OBJECT in TREE #0 */
#define CD_REPT 124  	/* OBJECT in TREE #0 */
#define CD_FIND 125  	/* OBJECT in TREE #0 */
#define CD_RESP 126  	/* OBJECT in TREE #0 */
#define CN_BOX 128  	/* OBJECT in TREE #0 */
#define CN_PREV 132  	/* OBJECT in TREE #0 */
#define CN_OFF 133  	/* OBJECT in TREE #0 */
#define CN_NEXT 134  	/* OBJECT in TREE #0 */
#define CN_ADD 135  	/* OBJECT in TREE #0 */
#define CN_BIGBX 136  	/* OBJECT in TREE #0 */
#define CN_ED1 137  	/* OBJECT in TREE #0 */
#define CN_ED2 138  	/* OBJECT in TREE #0 */
#define CN_ED3 139  	/* OBJECT in TREE #0 */
#define CN_ED4 140  	/* OBJECT in TREE #0 */
#define CN_ED5 141  	/* OBJECT in TREE #0 */
#define CN_ED6 142  	/* OBJECT in TREE #0 */
#define CN_ED7 143  	/* OBJECT in TREE #0 */
#define CN_SLDBX 144  	/* OBJECT in TREE #0 */
#define CN_UP 145  	/* OBJECT in TREE #0 */
#define CN_BACK 146  	/* OBJECT in TREE #0 */
#define CN_SLDR 147  	/* OBJECT in TREE #0 */
#define CN_DOWN 148  	/* OBJECT in TREE #0 */
#define CC_M_NAM 150  	/* OBJECT in TREE #0 */
#define CC_SAVE 151  	/* OBJECT in TREE #0 */
#define CC_SET 152  	/* OBJECT in TREE #0 */
