#define O_ROUTE 0  	/* TREE */
#define OU_BIGBX 10  	/* OBJECT in TREE #0 */
#define OU_NET1 11  	/* OBJECT in TREE #0 */
#define OU_MSK1 12  	/* OBJECT in TREE #0 */
#define OU_PRT1 13  	/* OBJECT in TREE #0 */
#define OU_GTW1 14  	/* OBJECT in TREE #0 */
#define OU_NET2 15  	/* OBJECT in TREE #0 */
#define OU_MSK2 16  	/* OBJECT in TREE #0 */
#define OU_PRT2 17  	/* OBJECT in TREE #0 */
#define OU_GTW2 18  	/* OBJECT in TREE #0 */
#define OU_NET3 19  	/* OBJECT in TREE #0 */
#define OU_MSK3 20  	/* OBJECT in TREE #0 */
#define OU_PRT3 21  	/* OBJECT in TREE #0 */
#define OU_GTW3 22  	/* OBJECT in TREE #0 */
#define OU_NET4 23  	/* OBJECT in TREE #0 */
#define OU_MSK4 24  	/* OBJECT in TREE #0 */
#define OU_PRT4 25  	/* OBJECT in TREE #0 */
#define OU_GTW4 26  	/* OBJECT in TREE #0 */
#define OU_NET5 27  	/* OBJECT in TREE #0 */
#define OU_MSK5 28  	/* OBJECT in TREE #0 */
#define OU_PRT5 29  	/* OBJECT in TREE #0 */
#define OU_GTW5 30  	/* OBJECT in TREE #0 */
#define OU_NET6 31  	/* OBJECT in TREE #0 */
#define OU_MSK6 32  	/* OBJECT in TREE #0 */
#define OU_PRT6 33  	/* OBJECT in TREE #0 */
#define OU_GTW6 34  	/* OBJECT in TREE #0 */
#define OU_NET7 35  	/* OBJECT in TREE #0 */
#define OU_MSK7 36  	/* OBJECT in TREE #0 */
#define OU_PRT7 37  	/* OBJECT in TREE #0 */
#define OU_GTW7 38  	/* OBJECT in TREE #0 */
#define OU_NET8 39  	/* OBJECT in TREE #0 */
#define OU_MSK8 40  	/* OBJECT in TREE #0 */
#define OU_PRT8 41  	/* OBJECT in TREE #0 */
#define OU_GTW8 42  	/* OBJECT in TREE #0 */
#define OU_NET9 43  	/* OBJECT in TREE #0 */
#define OU_MSK9 44  	/* OBJECT in TREE #0 */
#define OU_PRT9 45  	/* OBJECT in TREE #0 */
#define OU_GTW9 46  	/* OBJECT in TREE #0 */
#define OU_NET10 47  	/* OBJECT in TREE #0 */
#define OU_MSK10 48  	/* OBJECT in TREE #0 */
#define OU_PRT10 49  	/* OBJECT in TREE #0 */
#define OU_GTW10 50  	/* OBJECT in TREE #0 */
#define OU_SLDBX 51  	/* OBJECT in TREE #0 */
#define OU_UP 52  	/* OBJECT in TREE #0 */
#define OU_PRNT 53  	/* OBJECT in TREE #0 */
#define OU_SLDR 54  	/* OBJECT in TREE #0 */
#define OU_DOWN 55  	/* OBJECT in TREE #0 */
