#define O_TRACE 0  	/* TREE */
#define OT_DOIT 1  	/* TREE */
#define OT_HOST 7  	/* OBJECT in TREE #0 */
#define OT_OK 9  	/* OBJECT in TREE #0 */
#define OT_DEST 5  	/* OBJECT in TREE #1 */
#define OT_STATE 6  	/* OBJECT in TREE #1 */
#define OT_BIGBX 10  	/* OBJECT in TREE #1 */
#define OT_HOP1 11  	/* OBJECT in TREE #1 */
#define OT_IP1 12  	/* OBJECT in TREE #1 */
#define OT_DN1 13  	/* OBJECT in TREE #1 */
#define OT_HOP2 14  	/* OBJECT in TREE #1 */
#define OT_IP2 15  	/* OBJECT in TREE #1 */
#define OT_DN2 16  	/* OBJECT in TREE #1 */
#define OT_HOP3 17  	/* OBJECT in TREE #1 */
#define OT_IP3 18  	/* OBJECT in TREE #1 */
#define OT_DN3 19  	/* OBJECT in TREE #1 */
#define OT_HOP4 20  	/* OBJECT in TREE #1 */
#define OT_IP4 21  	/* OBJECT in TREE #1 */
#define OT_DN4 22  	/* OBJECT in TREE #1 */
#define OT_HOP5 23  	/* OBJECT in TREE #1 */
#define OT_IP5 24  	/* OBJECT in TREE #1 */
#define OT_DN5 25  	/* OBJECT in TREE #1 */
#define OT_HOP6 26  	/* OBJECT in TREE #1 */
#define OT_IP6 27  	/* OBJECT in TREE #1 */
#define OT_DN6 28  	/* OBJECT in TREE #1 */
#define OT_HOP7 29  	/* OBJECT in TREE #1 */
#define OT_IP7 30  	/* OBJECT in TREE #1 */
#define OT_DN7 31  	/* OBJECT in TREE #1 */
#define OT_HOP8 32  	/* OBJECT in TREE #1 */
#define OT_IP8 33  	/* OBJECT in TREE #1 */
#define OT_DN8 34  	/* OBJECT in TREE #1 */
#define OT_HOP9 35  	/* OBJECT in TREE #1 */
#define OT_IP9 36  	/* OBJECT in TREE #1 */
#define OT_DN9 37  	/* OBJECT in TREE #1 */
#define OT_HOP10 38  	/* OBJECT in TREE #1 */
#define OT_IP10 39  	/* OBJECT in TREE #1 */
#define OT_DN10 40  	/* OBJECT in TREE #1 */
#define OT_SLDBX 41  	/* OBJECT in TREE #1 */
#define OT_UP 42  	/* OBJECT in TREE #1 */
#define OT_PRNT 43  	/* OBJECT in TREE #1 */
#define OT_SLDR 44  	/* OBJECT in TREE #1 */
#define OT_DOWN 45  	/* OBJECT in TREE #1 */
