
.c.o:
	e:\bin\mmcc.ttp $*.c

compile: dez.o drawcolr.o lxclip.o lyclip.o scanedge.o xclip.o yclip.o yxorline.o

improve: 
	mmimp.ttp dez.o drawcolr.o lxclip.o lyclip.o
	mmimp.ttp scanedge.o xclip.o yclip.o yxorline.o


