# Makefile for MicroWay NDP C

OBJ1=xscheme.obj xsdmem.obj xsimage.obj xsio.obj xsobj.obj \
xsprint.obj xsread.obj xssym.obj xsfun1.obj xsfun2.obj xsmath.obj \
msstuff.obj

OBJ2=xsinit.obj xscom.obj xsint.obj

CFLAGS=-ansi -O -on -OLM -v -DNDPC

.c.obj:
	mcc -c $(CFLAGS) $<

xs_ndp.ltl:	$(OBJ1) $(OBJ2) xsftab.obj
	mcc -o xs_ndp *.obj

$(OBJ1):	xscheme.h xsproto.h
$(OBJ2):	xscheme.h xsproto.h xsbcode.h
xsftab.obj:	xscheme.h xsproto.h osdefs.h osptrs.h
