# Makefile for Zortech C

OBJ1=xscheme.obj xsdmem.obj xsimage.obj xsio.obj xsobj.obj \
xsprint.obj xsread.obj xssym.obj xsfun1.obj xsfun2.obj xsmath.obj \
msstuff.obj

OBJ2=xsinit.obj xscom.obj xsint.obj

CFLAGS=-ml -b -o -A -DZTC

.c.obj:
	ztc -c $(CFLAGS) $<

xs_ztc.exe:	$(OBJ1) $(OBJ2) xsftab.obj
	ztc -oxs_ztc $(OBJ1) $(OBJ2) xsftab.obj

$(OBJ1):	xscheme.h xsproto.h
$(OBJ2):	xscheme.h xsproto.h xsbcode.h
xsftab.obj:	xscheme.h xsproto.h osdefs.h osptrs.h
