extern void rsrc_init(void);
extern void fix_tree(OBJECT *,int);

extern OBJECT POPUP_3D[];
#define POPUP_ROOT 0
#define POPUP_TITLE 1
#define P_TITLE_TEXT 2
#define POPUP_UP 3
#define POPUP_UP_IMG 4
#define POPUP_SLIDE_BACK 5
#define POPUP_SLIDE 6
#define POPUP_DOWN 7
#define POPUP_DOWN_IMG 8
#define P_CHOOSE0 9
#define P_CHOOSE19 28
extern OBJECT ALERTBOX[];
#define ALERT_ROOT 0
#define ALERT_BACK 1
#define ALERT_STRING1 2
#define ALERT_ICON 3
#define ALERT_BUTTON1 4
#define ALERT_BUTTON2 5
#define ALERT_BUTTON3 6
#define ALERT_STRING2 7
#define ALERT_STRING3 8
#define ALERT_STRING4 9
#define ALERT_STRING5 10
#define ALERT_DRAG 11
extern OBJECT ALERT_CICONS[];
#define ICON_1 1
#define ICON_2 2
extern OBJECT POPUP_MONO[];
