.c.o:
	mmcc.ttp $*.c
	mmimp.ttp $*.o

compile: active.o animdata.o animmenu.o bigrepla.o bringin.o centerpo.o \
 changedi.o code.o colormen.o confirm.o control.o cseq.o \
 cursorda.o digitgau.o displays.o findcolo.o hlstorgb.o io.o \
 mainmenu.o morphdat.o morphmen.o reindex.o rotate.o rotateme.o scalescr.o \
 scroller.o slider.o spikemen.o splitscr.o splittwe.o storagem.o \
 story.o text.o timemenu.o undo.o upstream.o vbop.o vclone.o vgeneric.o \
 vhook.o vloop.o vkill.o vmove.o vsample.o vspike.o vsupport.o workpoly.o \
 wsubs.o zmenu.o

improve:
	mmimp.ttp active.o animdata.o animmenu.o bigrepla.o bringin.o centerpo.o
	mmimp.ttp changedi.o code.o colormen.o confirm.o control.o cseq.o
	mmimp.ttp cursorda.o digitgau.o displays.o findcolo.o hlstorgb.o io.o 
	mmimp.ttp mainmenu.o morphdat.o morphmen.o reindex.o rotate.o rotateme.o scalescr.o
	mmimp.ttp scroller.o slider.o spikemen.o splitscr.o splittwe.o storagem.o
	mmimp.ttp story.o text.o timemenu.o undo.o upstream.o vbop.o vclone.o vgeneric.o
	mmimp.ttp vhook.o vloop.o vkill.o vmove.o vsample.o vspike.o vsupport.o workpoly.o
	mmimp.ttp wsubs.o zmenu.o 

