.TH getsockname 3 "MiNT-Net"
.SH NAME
getsockname \- get socket address
.SH SYNOPSIS
.B #include <sys/socket.h>
.SS \s-1AF_UNIX\s0 only:
.B #include <sys/un.h>
.PP
.PD 0
.B "int getsockname(int s, struct sockaddr \(**addr,"
.IP
.B "size_t \(**addrlen);"
.PD
.SH DESCRIPTION
.I s
is a socket descriptor.
.I getsockname
returns the address of the socket indicated by
.IR s .
.I addr
points to a socket address structure in which this address is returned.
.I addrlen
points to an object of type
.B size_t
which should be initialized to indicate the size of the address structure.
On return it contains the actual size of the address returned (in bytes).
If
.I addr
does not point to enough space to contain the whole address of the socket,
only the first
.I addrlen
bytes of the address are returned.
.SH RETURN VALUE
If the call is successful, 0 is returned.
If the call fails, \-1 is returned and and error code is stored in
.BR errno .
.SH DIAGNOSTICS
.I getsockname
fails if:
.TP 20
.SM [EBADF]
.I s
is not a valid descriptor.
.TP
.SM [EINVAL]
The socket has been shut down.
.I s
is a file, not a socket.
.TP
.SM [EOPNOTSUPP]
Operation not supported for
.SM AF_UNIX
sockets.
.SH SEE ALSO
bind(3),
socket(3),
getpeername(3).
