static vars=FALSE
short file=FALSE
blank lines=TRUE
object numbers=TRUE
init te_ptext=TRUE
no init function=TRUE
init function=rs_init
exit function=rs_exit
ciconinit function=rs_ciconinit
ciconexit function=rs_ciconexit
optimize images=FALSE
optimize strings=FALSE
optimize icontext=FALSE
optimize substrings=FALSE
optimize emtystrings=FALSE
includes=gem.h
ob_spec=long
ub_code=long
ub_parm=long
draw function=mydraw
obfix function=rsrc_obfix
bi_pdata=int
