* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*			bss_02.s                                      *
*            Variables locations used in Part 3.                      *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

* Screen lists
scoordsx	ds.w	100	x coordinates
scoordsy	ds.w	100	ditto   y
sedglst		ds.w	100	edge connections
snedges		ds.w	20	no. edges in each polygon
npoly		ds.w	1	no. polygons in this polyhedron
col_lst		ds.w	20	colours of polygons
* View frame lists
vcoordsx	ds.w	100	x coords
vcoordsy	ds.w	100	y coords
vcoordsz	ds.w	100	z coords
vncoords	ds.w	1	no. of vertices



	
