
CFLAGS = -n -Ie:\include

O=  ablits.o aline.o brush.o celpull.o circle.o clips.o clock.o \
	conv.o disk.o \
	drabrush.o fastrand.o filereq.o files.o findcol.o frames.o \
	gfx.o init_sys.o input.o \
	main.o memory.o multiops.o pentools.o \
	polar.o prim.o pull.o putdot.o \
	sine.o sqr_root.o undermou.o zoom.o zoomtab.o


flicker: $O
	ln -o flicker.prg -f flicker.lnk e:\lib\c.lib e:\lib\gem.lib
