#
#  Use "make -r" to make this file, or alias as in: 
#					set in .cmd mk=(make -r $*)
#
.SUFFIXES: .o .s .c

.s.o:
	mac$(MACFLAGS) $*.s
.c.o:
	@echo c68 -c $*.c
	@c:\alcyon\cp68.prg $(CFLAGS) $*.c j:$*.i
	@c:\alcyon\c068.prg j:$*.i j:$*.1 j:$*.2 j:$*.3 -f
	@rm j:$*.i
	@c:\alcyon\c168.prg j:$*.1 j:$*.2 j:$*.s
	@c:\bin\mac.prg -6 -o $*.o j:$*.s
	@rm j:$*.1 j:$*.2 j:$*.s

TEMP = k:\tmp
LIBS = gemlib

OBJS = driver.o acsi.o ide.o cmdblk.o cookie.o doit.o scsi.o\
	spscsi.o install.o

driver.prg : $(OBJS)
	echo $(OBJS) $(LIBS) >$(TEMP)
	aln -s -o driver.prg -c $(TEMP)
#   aln -l -o driver.prg -c $(TEMP) for the local symbles

#
#  assembly-language files
#
acsi.o : acsi.s defs.h spscsi.h
ide.o: ide.s ide.h defs.h
cmdblk.o : cmdblk.s defs.h
cookie.o : cookie.s
driver.o : driver.s defs.h 68030.s error.h spscsi.h
doit.o : doit.s defs.h
install.o : install.s defs.h spscsi.h
scsi.o : scsi.s scsi.h defs.h
spscsi.o : spscsi.s spscsi.h defs.h

