      Msg_Idx = Packed Record                        { Length: 804 bytes }
                  Case Integer of
                   1: (Board_Name  : String [26];
                       Max_Messages: Integer;
                       Tot_In_Use  : Integer;
                       Bytes_Msg   : Integer;
                       Msg_Number  : Packed Array [1..250] of Integer;
                       Msg_Pointer : Packed Array [1..250] of Byte;
                       To_User_Num : Packed Array [1..250] of Integer;
                       Reply_To    : Packed Array [1..250] of Integer);
                   2: (Buffer      : BlockIO);
                End;

      Msg_Dat = Packed Record
                  Case Integer of
                    1: (Title        : String [30];
                        Author       : String [30];
                        To_User      : String [30];
                        Time         : String [11];
                        Date         : String [8];
                        From_User_Num: Integer;
                        Cont_Flag    : Integer;
                        Edited_Flag  : Boolean;
                        Lines        : Byte;
                        Lth          : Integer;
                        Message      : Packed Array [1..4010] of Char);
                    2: (Buffer       : BlockIO);
                End;

