# This makefile has been written for GNU make
#
CC         = gcc
CPPFLAGS   = 
OPT        = -O2
WARN       = -Wall
LEX        = flex
LDLIBS     = -lm
DBHEAP     =
CFLAGS     = $(OPT) $(WARN)
LDFLAGS    = $(OPT)

include Makefile

