# This makefile has been written for NeXT make
#
CC         = cc
CPPFLAGS   = 
OPT        = -O2 -finline-functions
WARN       = -Wall
LEX        = flex
LDLIBS     =
DBHEAP     =
CFLAGS     = $(OPT) $(WARN)
LDFLAGS    = $(OPT)

-include Makefile

