
pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0FILES\KERNEL\KERNEL.PRG D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0FILES\KERNEL\KERNEL.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0VQSPL.ST\VQAUDIO.PRG D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\0VQSPL.ST\VQAUDIO.NRV

pack2e D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\88COMPR\ST.TC\TCVQ_ST.PRG D:\000STUFF\ATARI\ATARI_HD\C\0NEW\TDOME\88COMPR\ST.TC\TCVQ_ST.NRV

