/* resource set indices for DSEXTRA */

#define I_OFF      0 /* form/dialog */
#define INDI_OFF   2 /* BOX in tree I_OFF */

#define I_ON       1 /* form/dialog */

#define B_TXT      2 /* form/dialog */

#define B_TXTON    3 /* form/dialog */

#define BKGHEAD    4 /* form/dialog */

#define ACTI_OFF   5 /* form/dialog */

#define ACTI_ON    6 /* form/dialog */

#define BKG        7 /* form/dialog */

#define B_TXT_X    8 /* form/dialog */

