/* resource set indices for DSPROG */

#define MENUE      0 /* menu */
#define WHATABOU   9 /* STRING in tree MENUE */
#define SMPLOAD   18 /* STRING in tree MENUE */
#define SMPSAVE   19 /* STRING in tree MENUE */
#define SAVE_AVR  20 /* STRING in tree MENUE */
#define DODIR     22 /* STRING in tree MENUE */
#define DOSTATIS  24 /* STRING in tree MENUE */
#define PRGEXIT   26 /* STRING in tree MENUE */
#define CHGLOUD   28 /* STRING in tree MENUE */
#define DOFILT    29 /* STRING in tree MENUE */
#define DOOVSM    30 /* STRING in tree MENUE */
#define DOPACK    31 /* STRING in tree MENUE */
#define DOINVERT  32 /* STRING in tree MENUE */
#define DOPLAY    34 /* STRING in tree MENUE */
#define MN_ENV    36 /* STRING in tree MENUE */
#define SETFILT   37 /* Calls the DHFT-Setting dialog */
#define SETOVSM   38 /* STRING in tree MENUE */
#define SETPACK   39 /* STRING in tree MENUE */
#define SETPLAY   40 /* STRING in tree MENUE */
#define SETMWIRE  41 /* STRING in tree MENUE */
#define MBOARD    43 /* STRING in tree MENUE */
#define SAVEOPT   44 /* STRING in tree MENUE */

#define FILTOPT    1 /* form/dialog */
#define FLTOVON2   1 /* FBOXTEXT in tree FILTOPT */
#define FLTOVON1   2 /* BOX in tree FILTOPT */
#define FLTBAD1    3 /* BOX in tree FILTOPT */
#define FLTBAD2    4 /* FBOXTEXT in tree FILTOPT */
#define FLTPIT2    5 /* FBOXTEXT in tree FILTOPT */
#define FLTPIT1    6 /* BOX in tree FILTOPT */
#define FLTSLC1    7 /* BOX in tree FILTOPT */
#define FLTSLC2    8 /* FBOXTEXT in tree FILTOPT */

#define PACKOPT    2 /* form/dialog */
#define CVALDWN    2 /* FBOXTEXT in tree PACKOPT */
#define CVAL       3 /* FBOXTEXT in tree PACKOPT */
#define CVALUP     4 /* FBOXTEXT in tree PACKOPT */
#define PCKFILT    6 /* BOX in tree PACKOPT */
#define PK4PLUS    8 /* BOX in tree PACKOPT */
#define PK4BIT    10 /* BOX in tree PACKOPT */
#define PKALTER   12 /* BOX in tree PACKOPT */

#define PLAYOPT    3 /* form/dialog */
#define PLY06250   2 /* FBOXTEXT in tree PLAYOPT */
#define PLY12500   3 /* FBOXTEXT in tree PLAYOPT */
#define PLY25000   4 /* FBOXTEXT in tree PLAYOPT */
#define PLY50000   5 /* FBOXTEXT in tree PLAYOPT */
#define MANUSPD    6 /* FBOXTEXT in tree PLAYOPT */
#define SPDMINUS   7 /* FBOXTEXT in tree PLAYOPT */
#define SPDPLUS    8 /* FBOXTEXT in tree PLAYOPT */
#define OVSM_OFF  11 /* FBOXTEXT in tree PLAYOPT */
#define OVSM_ON   12 /* FBOXTEXT in tree PLAYOPT */
#define ONPSG     15 /* FBOXTEXT in tree PLAYOPT */
#define ONDMA     16 /* FBOXTEXT in tree PLAYOPT */
#define ONCODEC   17 /* FBOXTEXT in tree PLAYOPT */

#define ABOUTINF   4 /* form/dialog */

#define ASKTYPE    5 /* form/dialog */
#define STE_SND    3 /* BOX in tree ASKTYPE */
#define ST_SND     6 /* BOX in tree ASKTYPE */
#define PCK_SND    7 /* BOX in tree ASKTYPE */
#define TYP_CNC    9 /* FBOXTEXT in tree ASKTYPE */
#define TYP_OK    10 /* FBOXTEXT in tree ASKTYPE */

#define ERRDETEC   6 /* form/dialog */
#define ERR_CNC    1 /* FBOXTEXT in tree ERRDETEC */
#define ERR_OK     2 /* FBOXTEXT in tree ERRDETEC */
#define ERR_TXT1   4 /* STRING in tree ERRDETEC */
#define ERR_TXT2   5 /* STRING in tree ERRDETEC */

#define OVSMOPT    7 /* form/dialog */
#define OVSMOF2X   2 /* FBOXTEXT in tree OVSMOPT */
#define OVSMOF3X   3 /* FBOXTEXT in tree OVSMOPT */
#define OVSMOF2    4 /* BOX in tree OVSMOPT */
#define OVSMOF3    5 /* BOX in tree OVSMOPT */
#define OVSM_SFT   7 /* BOX in tree OVSMOPT */

#define SET_VOL    8 /* form/dialog */
#define VOL_VAL    2 /* FBOXTEXT in tree SET_VOL */
#define VOL_OK     5 /* FBOXTEXT in tree SET_VOL */
#define VOL_CNC    6 /* FBOXTEXT in tree SET_VOL */

#define SGL_STAT   9 /* form/dialog */
#define STATNAME   6 /* FBOXTEXT in tree SGL_STAT */
#define STATLEN    7 /* FBOXTEXT in tree SGL_STAT */
#define STATMAXI   8 /* FBOXTEXT in tree SGL_STAT */
#define STATFOLL   9 /* FBOXTEXT in tree SGL_STAT */
#define STAT_PRC  10 /* FBOXTEXT in tree SGL_STAT */

#define SET_MW    10 /* form/dialog */
#define MV_SBKG    2 /* BOX in tree SET_MW */
#define LV_SBKG    3 /* BOX in tree SET_MW */
#define RV_SBKG    4 /* BOX in tree SET_MW */
#define TR_SBKG    5 /* BOX in tree SET_MW */
#define BA_SBKG    6 /* BOX in tree SET_MW */
#define MVOL_SLD   7 /* FBOXTEXT in tree SET_MW */
#define LVOL_SLD   8 /* FBOXTEXT in tree SET_MW */
#define RVOL_SLD   9 /* FBOXTEXT in tree SET_MW */
#define TRB_SLD   10 /* FBOXTEXT in tree SET_MW */
#define BASS_SLD  11 /* FBOXTEXT in tree SET_MW */

#define COLBKG    11 /* form/dialog */
#define IC_T       1 /* ICON in tree COLBKG */
#define I1         2 /* ICON in tree COLBKG */
#define I2         3 /* ICON in tree COLBKG */
#define I3         4 /* ICON in tree COLBKG */
#define I4         5 /* ICON in tree COLBKG */
#define I5         6 /* ICON in tree COLBKG */
#define I6         7 /* ICON in tree COLBKG */
#define I7         8 /* ICON in tree COLBKG */
#define I8         9 /* ICON in tree COLBKG */
#define I9        10 /* ICON in tree COLBKG */
#define I10       11 /* ICON in tree COLBKG */
#define I11       12 /* ICON in tree COLBKG */
#define I12       13 /* ICON in tree COLBKG */
#define I13       14 /* ICON in tree COLBKG */
#define I14       15 /* ICON in tree COLBKG */
#define I15       16 /* ICON in tree COLBKG */
#define I16       17 /* ICON in tree COLBKG */
#define I17       18 /* ICON in tree COLBKG */
#define I18       19 /* ICON in tree COLBKG */
#define I19       20 /* ICON in tree COLBKG */
#define I20       21 /* ICON in tree COLBKG */
#define I21       22 /* ICON in tree COLBKG */
#define I22       23 /* ICON in tree COLBKG */
#define I23       24 /* ICON in tree COLBKG */
#define I24       25 /* ICON in tree COLBKG */
#define I25       26 /* ICON in tree COLBKG */
#define I26       27 /* ICON in tree COLBKG */
#define I27       28 /* ICON in tree COLBKG */
#define I28       29 /* ICON in tree COLBKG */
#define I29       30 /* ICON in tree COLBKG */
#define I30       31 /* ICON in tree COLBKG */
#define I31       32 /* ICON in tree COLBKG */
#define I32       33 /* ICON in tree COLBKG */
#define I33       34 /* ICON in tree COLBKG */
#define I34       35 /* ICON in tree COLBKG */
#define I35       36 /* ICON in tree COLBKG */
#define I36       37 /* ICON in tree COLBKG */
#define I37       38 /* ICON in tree COLBKG */
#define I38       39 /* ICON in tree COLBKG */
#define I39       40 /* ICON in tree COLBKG */
#define I40       41 /* ICON in tree COLBKG */

#define FLT_SHW   12 /* form/dialog */
#define FLT_SLDB   4 /* BOX in tree FLT_SHW */
#define FLT_SLD    5 /* BOX in tree FLT_SHW */
#define POW_DISP   6 /* IBOX in tree FLT_SHW */

#define SET_ENV   13 /* form/dialog */
#define SMP_EXT    2 /* FBOXTEXT in tree SET_ENV */
#define AVR_EXT    4 /* FBOXTEXT in tree SET_ENV */
#define PCK_EXT    5 /* FBOXTEXT in tree SET_ENV */

#define ICON_X    14 /* form/dialog */
#define CLK1_IC    1 /* ICON in tree ICON_X */
#define SPEC_ICN   2 /* ICON in tree ICON_X */
#define TRASH_IC   3 /* ICON in tree ICON_X */
#define CLK2_IC    4 /* ICON in tree ICON_X */
#define NOT_IC     5 /* ICON in tree ICON_X */
#define MIC_IC     6 /* ICON in tree ICON_X */
#define DSK_IC     7 /* ICON in tree ICON_X */
#define DRV_IC     8 /* ICON in tree ICON_X */
#define HD_IC      9 /* ICON in tree ICON_X */

#define ALLINONE  15 /* form/dialog */
#define MB06250    2 /* FBOXTEXT in tree ALLINONE */
#define MB12500    3 /* FBOXTEXT in tree ALLINONE */
#define MB25000    4 /* FBOXTEXT in tree ALLINONE */
#define MB50000    5 /* FBOXTEXT in tree ALLINONE */
#define MBMANU     6 /* FBOXTEXT in tree ALLINONE */
#define MBMINUS    7 /* FBOXTEXT in tree ALLINONE */
#define MBPLUS     8 /* FBOXTEXT in tree ALLINONE */
#define MBPSG     11 /* FBOXTEXT in tree ALLINONE */
#define MBDMA     12 /* FBOXTEXT in tree ALLINONE */
#define MBCODEC   13 /* FBOXTEXT in tree ALLINONE */
#define MBOVSM    14 /* FBOXTEXT in tree ALLINONE */
#define MB_OVSMF  16 /* FBOXTEXT in tree ALLINONE */
#define MB_FBAD   17 /* FBOXTEXT in tree ALLINONE */
#define MB_FPEAK  18 /* FBOXTEXT in tree ALLINONE */
#define MBFFLAT   19 /* FBOXTEXT in tree ALLINONE */
#define MB_OSHFT  22 /* FBOXTEXT in tree ALLINONE */
#define MB_OVSM2  23 /* FBOXTEXT in tree ALLINONE */
#define MB_OVSM3  24 /* FBOXTEXT in tree ALLINONE */
#define MB_CVMNS  27 /* FBOXTEXT in tree ALLINONE */
#define MB_SVPLS  28 /* FBOXTEXT in tree ALLINONE */
#define MB_PFILT  29 /* FBOXTEXT in tree ALLINONE */
#define MB_P4PLS  30 /* FBOXTEXT in tree ALLINONE */
#define MB_P4     31 /* FBOXTEXT in tree ALLINONE */
#define MB_PALT   32 /* FBOXTEXT in tree ALLINONE */
#define MB_CVAL   33 /* FBOXTEXT in tree ALLINONE */

