#
#	Makefile pour Awele version GEM
#

CC = gcc
CFLAGS = -O

OBJECT= gem.o alphabet.o move.o utils.o


.KEEP_STATE:

all: awele

awele: $(OBJECT)
		$(CC) $(CFLAGS) $(OBJECT) -o awele.prg
		
.o: .c
		$(CC) $(CFLAGS) -c $$ -D__GEM__
