/******************************************/
/* File : CPXBUILD.H                      */
/* -------------------------------------- */
/* Programma : CPXBUILD.PRG   Versie 1.00 */
/* (C) 1991 by MAXON Computer             */
/* Auteurs : Uwe Hax & Oliver Scholz      */
/* Van RCS vervaardigde include file      */
/******************************************/

#define BUILD 0			/* TREE */
#define CPXNAME 3		/* OBJECT IN TREE 0 */
#define COLLEFT 5		/* OBJECT IN TREE 0 */
#define COLRIGHT 7		/* OBJECT IN TREE 0 */
#define TEXTCOL 6		/* OBJECT IN TREE 0 */
#define CPXID 8			/* OBJECT IN TREE 0 */
#define ICONDATA 10		/* OBJECT IN TREE 0 */
#define ICONSMAL 12		/* OBJECT IN TREE 0 */
#define ICONBOX 11		/* OBJECT IN TREE 0 */
#define ICLEFT 14		/* OBJECT IN TREE 0 */
#define ICRIGHT 16		/* OBJECT IN TREE 0 */
#define ICCOL 15		/* OBJECT IN TREE 0 */
#define ICNNAME 17		/* OBJECT IN TREE 0 */
#define INVERT 18		/* OBJECT IN TREE 0 */
#define VERSION 9		/* OBJECT IN TREE 0 */
#define ICONWORK 19		/* OBJECT IN TREE 0 */
#define SETONLY 21		/* OBJECT IN TREE 0 */
#define RESFLAG 23		/* OBJECT IN TREE 0 */
#define BOOTFLAG 22		/* OBJECT IN TREE 0 */
#define LOAD 24			/* OBJECT IN TREE 0 */
#define OK 25			/* OBJECT IN TREE 0 */
#define STOPPEN 26		/* OBJECT IN TREE 0 */
