.TH STARCHART LOCAL 9/22/87
.SH NAME
stardsp, starpic, starpost, staruplot, startek, stariris, starhp, starlaser \- print astronomical star charts using Yale database.
.SH SYNOPSIS
.B star*
RA DE [ scale title maglim lbllim ]
.br
or
.br
.BI \-c\  constellation ...
.br
or
.br
.BI \-r\  Ra
.BI \-d\  Dl
[
.BI \-s\  scale
.BI \-t\  title
.BI \-m\  maglim
.BI \-l\  lbllim
.BI \-g\  grklim
.BI \-a\  (annotate)
.BI \-o\  (objects)
.BI \-b\  (bigchart)
.BI \-f\  ephem.star...
.BI \-y\  yale.star
.BI \-n\  messier.star
.BI \-w\  planet.star
]
.SH DESCRIPTION
These programs generate star charts based on data extracted from the Yale
public domain star catalog.
Output is to the terminal 
.RI ( stardsp ),
Unix PIC file format
.RI ( starpic ),
PostScript format
.RI ( starpost ),
Unix Plot(5) format
.RI ( staruplot ),
Tektronix vector format
.RI ( startek ),
Silicon Graphics Iris format
.RI ( stariris ),
Hewlett-Packard terminal vector format
.RI (starhp)
or in Hewlett-Packard Laserjet printer format
.RI ( starlaser ).
.PP
Star data is optionally overlayed with other cosmic objects, such as planets.
If limiting magnitudes are properly set and the Messier database is available,
Messier objects and some NGC objects are also printed.
.PP
The starchart center is specified by two parameters: Right
Ascension [0.00 to 24.00 hours] and Declination [-90.00 to +90.00 degrees].
An optional third parameter defines the N/S range of the output window, in
degrees of declination.  Digits after decimal point are taken as minutes:
object positions can therefore be taken directly from a star catalog.
.PP
An optional fourth parameter gives a title.
This conforms to the 'old' Yale star chart format.
Two new parameters can be added after title,
defining the magnitude limit and label printing magnitude limit.
These are discussed below.
All parameters can be given by using options,
which offers more flexibility.
Parameters are:
.TP
.B \-r
Right ascension.
.TP
.B \-d
Declination.
.TP
.B \-s
Scale.
.TP
.B \-t
Title. All these work as described above. Additional switches:
.TP
.B \-m
Star limiting magnitude. This sets limits on the faintest stars displayed
on the ``master'' view. Default limits are device driver dependent (more below).
The ``thumbnail'' finder view is set to a related limit.
.TP
.B \-l
Label limiting magnitude. The new Yale database contains both a small set of
familiar names (for stars and special objects), plus an extensive list of
labels (Greek Bayer letter or Flamsteed numbers). Star names (including planet
names) always print for this small set. To avoid clutter, the labels may be
omitted below a cut-off magnitude by specifying this value.
.TP
.B \-g
Greek/Flamsteed annotation magnitude. Labels printed for stars dimmer than
this value will use a Bayer or numerical label in favor of a proper name.
The default (2.05) includes nearly all well-known proper names including
Polaris, and excludes but a small number (such as Algol). Large values
generate charts full of obscure Arabian names, small (zero or negative) values
produce non-verbose charts, eg. ``a'', in Greek where possible, instead of
``Sirius''.
.TP
.B \-c
A three or four character mnemonic follows, which is a search string for a
matching line-item entry in the file
.IR con.locs .
If found, then the
initial values for Ra, Decl, Scale and Title are taken from that file.
Because the command line is parsed from left to right, subsequent switches
might change the scale, title, or otherwise fine-tune the new defaults.
.TP
.B \-f
A list of files follow, each containing ephemerides in the .star format, which
will overlay the output. This is also useful for generating constellation
boundaries, Milky Way isophots, and planet or satellite tracks. (The .star
format additionally includes records for vector and text annotation). Files
are processed sequentially. Thus, order may take on meaning for devices which
provide a 2-1/2D page description, such as PostScript.
.TP
.B \-b
This switch provides a single full-page of output, without a thumbnail-sized
finder chart. The legend placard is replaced with a single line banner giving
title, right ascension, declination and limiting magnitude. This mode is
useful for the construction of atlas pages. Because the page depicts the same
vertical scale in degrees of declination, the output will cover a slightly
reduced extent in right ascention.
.TP
.B \-a
This switch provides annotation-only (text) output: all stars and non-stellar
objects are omitted (including objects normally rendered by using alpha
characters). Borders and legends are left undisturbed. This feature is useful
in separating output detail, as when making (color) overhead transparencies.
.TP
.B \-o
This switch provides object-only output, and is the complement of the
above switch. When both switches appear together, all output is displayed.
This resembles the default case (neither switch), except in that case object
and annotation detail are written together. Here the software makes two
consecutive passes through all datasets and arranges output detail to be
written with all cosmic objects prefacing all related text annotations.
This is useful in providing data for PostScript files in which rendering
happens in a 2-1/2D back-to-front order, thus providing for a cleaner
overlaying of output.
.TP
.B \-y \-w \-p
These switches allow for the redefinition of the files yale.star, messier.star
and planet.star, respectively.
.PP
.SH OUTPUT
The present implementations draw two viewports: a ``master'' chart plus a
``thumbnail'' overview with low limiting magnitude.
Their location and the limiting magnitude is specified by records in
the device driver, allowing the chart layout be tuned on a per-device basis.
In all cases, the output is annotated with viewport boundaries, a legend and
axis labels. Variations are described for the
.B \-a \-o
and
.B -b
switches, above.
.PP
Objects are drawn in glyphs defined by each display driver. Vector-only
devices rely on the parent module ``starimages.c'' to provide shape tables;
other devices plot special characters (stardsp or starpic) or private symbols
(PostScript). The latter additionally provides distinctions between object
subclasses, e.g. planetary vs diffuse nebula. The code provides for this
generally, creation of new glyphs.
.PP
Sanson's sinusoidal projection is used to map coordinates.
This projection preserves both area and linearity in Declination (y axis).
It gives good conformality (angle correctness) near the equator, so it is
useful along the Ecliptic.
Lines of RA converge at the poles (unlike cylindrical projections),
though Cassiopeia and the Dipper reproduce well.
.SH EXAMPLES 
.nf
# Sagittarius: a nice bunch of Messier objects.
starpost -c sgr -a -o -t Sagittarius >sag.ps
.sp
# Orion: the belt lies near 5h40m in RA, just below the CE.
stardsp 5.32 -5 12 "Trapezium (Orion)" 8 5 | more
.fi
.SH FILES
.nf
.ta \w'messier.star    'u
yale.star	stellar information (mandatory)
messier.star	Messier objects (optional)
planet.star	Planets (optional)
con.locs	default mnemonic locations
.fi
.br
.sp
These default paths can be easily changed in the Makefile.
.SH BUGS
The present implementation expects
.I yale.star
sorted by decreasing magnitude so that output is sequential, and then cuts off
below a limiting magnitude.
For more detailed charts spatial sorting might be more appropriate.
No cutoff is performed for other .star files.
.PP
If <minutes> part of the parameters is greater than 59 it is silently
truncated to 59.
.PP
All .star file coordinates are for epoch E2000.0.
The Messier objects in
.I messier.star
were taken from precessed E1975.0 data.
The additional NGC objects were taken from data in the star atlas by
.I Norton
and precessed from E1950.0.
Descriptions and accurate magnitude values of all Messier objects were taken
from the 1988 edition of the Royal Astronomical Society of Canada (RASC)
handbook.
.SH FUTURE EXTENTIONS
A
.B \-p
switch will provide polar plotting; early code attempts using Stereographic
projection have lacked the ability to draw the horizon lines and tick
marks correctly. This and other extensions are discussed at the end of
``starchart.c'', and is suggested reading for anyone wishing to enhance
the software.
.SH AUTHOR/EDITOR
Alan Paeth, University of Waterloo (AWPaeth@watCGL)
.SH MAJOR CONTRIBUTORS
Petri Launiainen (pl@intrin.FI)
.br
Jyrki Yli-Nokari (jty@intrin.FI)
.br
Robert Tidd (inp@violet.berkeley.edu)
.br
Craig Counterman (ccount@royal.mit.edu)
