TARGET=uucoder.prg
OBJECTS=uucoder.o event.o encode.o decode.o fsel.o
HEADERS=uucoder.h
LIBRARIES=\lib\aesfast.a
CFLAGS=-v -O

$(TARGET) : $(OBJECTS) $(LIBRARIES) $(HEADERS)
	cc $(CFLAGS) -o $(TARGET) $(OBJECTS) $(LIBRARIES)
