/* resource set indices for TOSWIN_W */

#define CUTOPTS            0 /* form/dialog */
#define ADDCRLF            2 /* BOX in tree CUTOPTS */
#define ADDCR              3 /* BOX in tree CUTOPTS */
#define ADDLF              6 /* BOX in tree CUTOPTS */
#define ADDNONE            7 /* BOX in tree CUTOPTS */
#define STRIPEOL          11 /* BOX in tree CUTOPTS */
#define OBEYEOL           12 /* BOX in tree CUTOPTS */
#define EDOK              15 /* BUTTON in tree CUTOPTS */
#define EDCANCEL          16 /* BUTTON in tree CUTOPTS */

#define DESKTOP            1 /* free form */
#define CLIPICN            1 /* ICON in tree DESKTOP */

#define MENUDEF            2 /* form/dialog */
#define MDDONE             7 /* BUTTON in tree MENUDEF */
#define MENUFRAM           8 /* BOX in tree MENUDEF */
#define MENUSTR            9 /* STRING in tree MENUDEF */
#define ENTRYSTR          10 /* STRING in tree MENUDEF */
#define MDPREV            11 /* BOXCHAR in tree MENUDEF */
#define MDNEXT            12 /* BOXCHAR in tree MENUDEF */
#define KEYFRAM           13 /* BOX in tree MENUDEF */
#define HEXSTR            14 /* STRING in tree MENUDEF */
#define ASCIISTR          15 /* STRING in tree MENUDEF */

#define WINSIZE            3 /* form/dialog */
#define WINSIZOK           2 /* BUTTON in tree WINSIZE */
#define COLBOX             3 /* FTEXT in tree WINSIZE */
#define ROWBOX             5 /* FTEXT in tree WINSIZE */
#define WINSZCAN           6 /* BUTTON in tree WINSIZE */
#define SCRBOX             9 /* FTEXT in tree WINSIZE */

#define FNTDIAL            4 /* form/dialog */
#define FNTNMBOX           3 /* BOX in tree FNTDIAL */
#define FNTNMSTR           4 /* STRING in tree FNTDIAL */
#define SIZNMBOX           6 /* BOX in tree FNTDIAL */
#define SIZNMPTS           7 /* FTEXT in tree FNTDIAL */
#define FONTBOX            9 /* BOX in tree FNTDIAL */
#define FNTLIN1           10 /* STRING in tree FNTDIAL */
#define FNTLIN2           11 /* STRING in tree FNTDIAL */
#define FNTLIN3           12 /* STRING in tree FNTDIAL */
#define FNTLIN4           13 /* STRING in tree FNTDIAL */
#define FNTLIN5           14 /* STRING in tree FNTDIAL */
#define FNTLIN6           15 /* STRING in tree FNTDIAL */
#define FNTLIN7           16 /* STRING in tree FNTDIAL */
#define FNTLIN8           17 /* STRING in tree FNTDIAL */
#define FNTUPARR          18 /* BOXCHAR in tree FNTDIAL */
#define SIZEBOX           19 /* BOX in tree FNTDIAL */
#define SIZLIN1           20 /* STRING in tree FNTDIAL */
#define SIZLIN2           21 /* STRING in tree FNTDIAL */
#define SIZLIN3           22 /* STRING in tree FNTDIAL */
#define SIZLIN4           23 /* STRING in tree FNTDIAL */
#define SIZLIN5           24 /* STRING in tree FNTDIAL */
#define SIZLIN6           25 /* STRING in tree FNTDIAL */
#define SIZLIN7           26 /* STRING in tree FNTDIAL */
#define SIZLIN8           27 /* STRING in tree FNTDIAL */
#define SIZUPARR          28 /* BOXCHAR in tree FNTDIAL */
#define FNTSLIBX          29 /* BOX in tree FNTDIAL */
#define FNTSLIDE          30 /* BOX in tree FNTDIAL */
#define SIZSLIBX          31 /* BOX in tree FNTDIAL */
#define SIZSLIDE          32 /* BOX in tree FNTDIAL */
#define FNTDNARR          33 /* BOXCHAR in tree FNTDIAL */
#define SIZDNARR          34 /* BOXCHAR in tree FNTDIAL */
#define FNTOK             35 /* BUTTON in tree FNTDIAL */
#define FNTCAN            36 /* BUTTON in tree FNTDIAL */

#define GADGDIAL           5 /* form/dialog */
#define GCLOSER            3 /* BOXCHAR in tree GADGDIAL */
#define GVSLIDE            4 /* BOX in tree GADGDIAL */
#define GHSLIDE            5 /* BOX in tree GADGDIAL */
#define GFULLER            6 /* BOXCHAR in tree GADGDIAL */
#define GSIZER             7 /* BOXCHAR in tree GADGDIAL */
#define GTITLE             8 /* BOXTEXT in tree GADGDIAL */
#define GMENU              9 /* BOXTEXT in tree GADGDIAL */
#define GALLGAD           10 /* BUTTON in tree GADGDIAL */
#define GTOPGAD           11 /* BUTTON in tree GADGDIAL */
#define GNOGAD            12 /* BUTTON in tree GADGDIAL */
#define GADGOK            13 /* BUTTON in tree GADGDIAL */
#define GADGCAN           14 /* BUTTON in tree GADGDIAL */

#define ENVDIAL            6 /* form/dialog */
#define POSIXBOX           5 /* BOX in tree ENVDIAL */
#define TCAPBOX            6 /* BOX in tree ENVDIAL */
#define TERMBOX            7 /* BOX in tree ENVDIAL */
#define ARGVBOX            9 /* BOX in tree ENVDIAL */
#define ENVOK             10 /* BUTTON in tree ENVDIAL */
#define ENVCAN            11 /* BUTTON in tree ENVDIAL */

#define TITLDIAL           7 /* form/dialog */
#define TITLSTR            2 /* FTEXT in tree TITLDIAL */
#define TITLOK             3 /* BUTTON in tree TITLDIAL */
#define TITLCAN            4 /* BUTTON in tree TITLDIAL */

#define QUOTEIT            8 /* form/dialog */

#define ARGDIAL            9 /* form/dialog */
#define ARGSTR             2 /* FTEXT in tree ARGDIAL */
#define ARGOK              3 /* BUTTON in tree ARGDIAL */
#define ARGCAN             4 /* BUTTON in tree ARGDIAL */

#define SFILE              0 /* Free string */

#define SEDIT              1 /* Free string */

#define SGLOBAL            2 /* Free string */

#define SWINDOW            3 /* Free string */

#define SGADGETS           4 /* Free string */

#define SOPNSTD            5 /* Free string */

#define SOPNALT            6 /* Free string */

#define SCLOSE             7 /* Free string */

#define SQUIT              8 /* Free string */

#define SLOADCFG           9 /* Free string */

#define SSAVECFG          10 /* Free string */

#define SSETMENU          11 /* Free string */

#define SCOPY             12 /* Free string */

#define SPASTE            13 /* Free string */

#define SPASTEOP          14 /* Free string */

#define SALIGNW           15 /* Free string */

#define SAPPMENU          16 /* Free string */

#define SAUTOCL           17 /* Free string */

#define SFLOURIS          18 /* Free string */

#define SPTTYPE           19 /* Free string */

#define SSMOOTH           20 /* Free string */

#define SSETSTD           21 /* Free string */

#define SSETALT           22 /* Free string */

#define SSETDFNT          23 /* Free string */

#define SSETDGAD          24 /* Free string */

#define SENVIRON          25 /* Free string */

#define SREDRAW           26 /* Free string */

#define SBURY             27 /* Free string */

#define SICONIFY          28 /* Free string */

#define SLITERAL          29 /* Free string */

#define SSETWSIZ          30 /* Free string */

#define SSETWFNT          31 /* Free string */

#define SSETWGAD          32 /* Free string */

#define SSETWTIT          33 /* Free string */

#define STOGFULL          34 /* Free string */

#define SMOVE             35 /* Free string */

#define SSCRUP            36 /* Free string */

#define SSCRDOWN          37 /* Free string */

#define SSCRLEFT          38 /* Free string */

#define SSCRRIGH          39 /* Free string */

#define LOADCFG           40 /* Free string */

#define SAVECFG           41 /* Free string */

#define TOSPROGS          42 /* Free string */

#define ABOUTTW           43 /* Free string */

#define EXECPRG           44 /* Free string */

#define SAVWPOS           45 /* Alert string */

#define UNABLE1           46 /* Alert string */

#define NOSCRAP           47 /* Alert string */

#define SCRAPERR          48 /* Alert string */

#define SCRAPDAT          49 /* Alert string */

#define NORSC             50 /* Alert string */

#define BADRSC            51 /* Alert string */

#define NOOPEN            52 /* Alert string */

#define NOTEXT            53 /* Alert string */

#define NOMEM             54 /* Alert string */

#define NOCUT             55 /* Alert string */

#define NOTDESK           56 /* Alert string */

#define NOWINS            57 /* Alert string */

#define NOPTY             58 /* Alert string */

#define NOPROC            59 /* Alert string */

#define AUTORAIS          60 /* Free string */

