OBJS =	d2.o decl.o expr.o fix.o fun.o g2.o gen.o gsub.o gunk.o \
	main.o md.o nodes.o out.o p2.o pre.o tok.o subs.o

H =	bstok.h cookie.h flags.h gen.h nodes.h ops.h param.h \
	sttok.h tok.h tytok.h

CFLAGS = -O

.c.o:
	$(CC) -c $(CFLAGS) $<
	ar rv hcc.lib $*.o

.s.o:
	$(CC) -c $(CFLAGS) $<
	ar rv hcc.lib $*.o

hcc.ttp: $(OBJS)
	cc -f hcc.lib -o hcc.ttp

$(OBJS) : $(H)

clean:
	$(RM) *.o hcc.lib

clobber:
	$(RM) *.o hcc.lib hcc.ttp
