REM FILENAME INSTI1.BAT
REM FUNCTION : PREPARE HARD DISK; TRANSFER FILES FROM FLOPPY TO
REM THE GEMAPPS SUBDIRECTORY.
C:
CD C:\
MD GEMAPPS
A:
COPY @A:ISV1.PRN C:\GEMAPPS
REM TRANSFER IS COMPLETE
REM TO EJECT DISKETTE; ENTER THE APPLE KEY AND NUMERIC ENTER KEY.
