### 	Makefile

COPTS	=       -cf -v #-O
CMODEL	=	-w -r0 -b0
CREFS	=	
DEFINES =	
LMODEL	=	snb
LDOPTS  =       -N -td -Lanbg #-Lnbg   
#
CFLAGS	=	$(COPTS) $(CMODEL) $(CREFS) $(DEFINES)
ASFLAGS =
LDFLAGS =	$(COPTS) $(CMODEL) $(LDOPTS)
MAPOPTS =	#MAP $*.map

MENUTOOL  =	test.o menubind.o crysif.o crystal.o

.c.o:
	lc -c $(CFLAGS) -o$@ $<

.s.o:
	mac $*.s
	dr2lc $@

test.prg:	$(MENUTOOL)
				lc $(LDFLAGS)=$@ $(MENUTOOL)
				@gstfix $@

test.o:		mn_tools.h menubind.h test.h 
menubind.o:
crysif.o:
crystal.o:
