/* COLRSC.H
 *==========================================================================
 * DATE: April 3, 1990
 * DESCRIPTION: INCLUDE.H file from RESOURCE
 */
 
 
#if USA
 #include "resource\usa\usa.h" 
#endif

#if	UK
 #include "resource\uk\uk.h" 
#endif


#if FRANCE
 #include "resource\france\france.h" 
#endif

#if GERMANY
 #include "resource\germany\germany.h" 
#endif

#if ITALY
 #include "resource\italy\italy.h" 
#endif

#if SPAIN
 #include "resource\spain\spain.h" 
#endif

#if SWEDEN
 #include "resource\sweden\sweden.h" 
#endif

