void APIENTRY (*glBegin)( long mode );
void (*glClear)( long mask );
void APIENTRY (*glClearColor)( float red, float green, float blue, float alpha );
void APIENTRY (*glColor3f)( float red, float green, float blue );
void APIENTRY (*glDisable)( long cap );
void APIENTRY (*glEnable)( long cap );
void APIENTRY (*glEnd)(void);
void APIENTRY (*glLightfv)( long light, long pname, float *params );
void APIENTRY (*glLoadIdentity)( void );
void APIENTRY (*glMaterialfv)( long face, long pname, float *params );
void APIENTRY (*glMatrixMode)( long mode );
void APIENTRY (*glOrtho)( float left, float right,float bottom, float top,float nearval, float farval );
void APIENTRY (*glPopMatrix)( void );
void APIENTRY (*glPushMatrix)( void );
void APIENTRY (*glRotatef)( float angle, float x, float y, float z );
void APIENTRY (*glTexEnvi)( long target, long pname, long param );
void APIENTRY (*glTexParameteri)( long target, long pname, long param );
void APIENTRY (*glTranslatef)( float x, float y, float z );
void APIENTRY (*glVertex2f)( float x, float y );
void APIENTRY (*glVertex3f)( float x, float y, float z );
void* APIENTRY (*OSMesaCreateLDG)( long format, long type, long WIDTH, long HEIGHT );
void APIENTRY (*OSMesaDestroyLDG)(void);
void APIENTRY (*glArrayElement)( long i );
void APIENTRY (*glBindTexture)( long target, unsigned long texture );
void APIENTRY (*glCallList)( unsigned long list );
void APIENTRY (*glClearDepth)( float depth );
void APIENTRY (*glColor4f)( GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha );
void APIENTRY (*glColor3fv)(  GLfloat *v );
void APIENTRY (*glColor4fv)(  GLfloat *v );
void APIENTRY (*glColorMaterial)( long face, long mode );
void APIENTRY (*glColorPointer)( long size, long type, long stride,  GLvoid *ptr );
void APIENTRY (*glCullFace)( long mode );
void APIENTRY (*glDeleteTextures)( long n,  unsigned long *textures);
void APIENTRY (*glDisableClientState)( long cap );
void APIENTRY (*glEnableClientState)( long cap );
void APIENTRY (*glEndList)( void );
void APIENTRY (*glEdgeFlag)( unsigned long flag );
void APIENTRY (*glFlush)( void );
void APIENTRY (*glFrontFace)( long mode );
void APIENTRY (*glFrustum)( float left, float right, float bottom, float top, float nearval, float farval );
unsigned long APIENTRY (*glGenLists)( long range );
void APIENTRY (*glGenTextures)( long n, unsigned long *textures );
void APIENTRY (*glGetFloatv)( long pname, GLfloat *params );
void APIENTRY (*glGetIntegerv)( long pname, long *params );
void APIENTRY (*glHint)( long target, long mode );
void APIENTRY (*glInitNames)( void );
unsigned long APIENTRY (*glIsList)( unsigned long list );
void APIENTRY (*glLightf)( long light, long pname, GLfloat param );
void APIENTRY (*glLightModeli)( long pname, long param );
void APIENTRY (*glLightModelfv)( long pname,  GLfloat *params );
void APIENTRY (*glLoadMatrixf)(  GLfloat *m );
void APIENTRY (*glLoadName)( unsigned long name );
void APIENTRY (*glMaterialf)( long face, long pname, GLfloat param );
void APIENTRY (*glMultMatrixf)(  GLfloat *m );
void APIENTRY (*glNewList)( unsigned long list, long mode );
void APIENTRY (*glNormal3f)( GLfloat nx, GLfloat ny, GLfloat nz );
void APIENTRY (*glNormal3fv)(  GLfloat *v );
void APIENTRY (*glNormalPointer)( long type, long stride,  GLvoid *ptr );
void APIENTRY (*glPixelStorei)( long pname, long param );
void APIENTRY (*glPolygonMode)( long face, long mode );
void APIENTRY (*glPolygonOffset)( GLfloat factor, GLfloat units );
void APIENTRY (*glPopName)( void );
void APIENTRY (*glPushName)( unsigned long name );
long APIENTRY (*glRenderMode)( long mode );
void APIENTRY (*glSelectBuffer)( long size, unsigned long *buffer );
void APIENTRY (*glScalef)( GLfloat x, GLfloat y, GLfloat z );
void APIENTRY (*glShadeModel)( long mode );
void APIENTRY (*glTexCoord2f)( GLfloat s, GLfloat t );
void APIENTRY (*glTexCoord4f)( GLfloat s, GLfloat t, GLfloat r, GLfloat q );
void APIENTRY (*glTexCoord2fv)(  GLfloat *v );
void APIENTRY (*glTexCoordPointer)( long size, long type, long stride,  GLvoid *ptr );
void APIENTRY (*glTexImage2D)( long target, long level, long internalformat, long width, long height, long border, long format, long type,  GLvoid *pixels );
void APIENTRY (*glVertex4f)( GLfloat x, GLfloat y, GLfloat z, GLfloat w );
void APIENTRY (*glVertex3fv)(  GLfloat *v );
void APIENTRY (*glVertexPointer)( long size, long type, long stride,  GLvoid *ptr );
void APIENTRY (*glViewport)( long x, long y, long width, long height );
void APIENTRY (*swapbuffer)(void *buf);
long APIENTRY (*max_width)(void);
long APIENTRY (*max_height)(void);
void APIENTRY (*glDeleteLists)( unsigned long list, long range );
void APIENTRY (*gluLookAt)( float eyex, float eyey, float eyez, float centerx, float centery, float centerz, float upx, float upy, float upz );
void APIENTRY (*exception_error)(void APIENTRY (*exception)(long param));

void init_tiny(LDG *ptldg)
{
glBegin = ldg_find("glBegin",ptldg);
glClear = ldg_find("glClear",ptldg);
glClearColor = ldg_find("glClearColor",ptldg);
glColor3f = ldg_find("glColor3f",ptldg);
glDisable = ldg_find("glDisable",ptldg);
glEnable = ldg_find("glEnable",ptldg);
glEnd = ldg_find("glEnd",ptldg);
glLightfv = ldg_find("glLightfv",ptldg);
glLoadIdentity = ldg_find("glLoadIdentity",ptldg);
glMaterialfv = ldg_find("glMaterialfv",ptldg);
glMatrixMode = ldg_find("glMatrixMode",ptldg);
glOrtho = ldg_find("glOrtho",ptldg);
glPopMatrix = ldg_find("glPopMatrix",ptldg);
glPushMatrix = ldg_find("glPushMatrix",ptldg);
glRotatef = ldg_find("glRotatef",ptldg);
glTexEnvi = ldg_find("glTexEnvi",ptldg);
glTexParameteri = ldg_find("glTexParameteri",ptldg);
glTranslatef = ldg_find("glTranslatef",ptldg);
glVertex2f = ldg_find("glVertex2f",ptldg);
glVertex3f = ldg_find("glVertex3f",ptldg);
OSMesaCreateLDG = ldg_find("OSMesaCreateLDG",ptldg);
OSMesaDestroyLDG = ldg_find("OSMesaDestroyLDG",ptldg);
glArrayElement = ldg_find("glArrayElement",ptldg);
glBindTexture = ldg_find("glBindTexture",ptldg);
glCallList = ldg_find("glCallList",ptldg);
glClearDepth = ldg_find("glClearDepth",ptldg);
glColor4f = ldg_find("glColor4f",ptldg);
glColor3fv = ldg_find("glColor3fv",ptldg);
glColor4fv = ldg_find("glColor4fv",ptldg);
glColorMaterial = ldg_find("glColorMaterial",ptldg);
glColorPointer = ldg_find("glColorPointer",ptldg);
glCullFace = ldg_find("glCullFace",ptldg);
glDeleteTextures = ldg_find("glDeleteTextures",ptldg);
glDisableClientState = ldg_find("glDisableClientState",ptldg);
glEnableClientState = ldg_find("glEnableClientState",ptldg);
glEndList = ldg_find("glEndList",ptldg);
glEdgeFlag = ldg_find("glEdgeFlag",ptldg);
glFlush = ldg_find("glFlush",ptldg);
glFrontFace = ldg_find("glFrontFace",ptldg);
glFrustum = ldg_find("glFrustum",ptldg);
glGenLists = ldg_find("glGenLists",ptldg);
glGenTextures = ldg_find("glGenTextures",ptldg);
glGetFloatv = ldg_find("glGetFloatv",ptldg);
glGetIntegerv = ldg_find("glGetIntegerv",ptldg);
glHint = ldg_find("glHint",ptldg);
glInitNames = ldg_find("glInitNames",ptldg);
glIsList = ldg_find("glIsList",ptldg);
glLightf = ldg_find("glLightf",ptldg);
glLightModeli = ldg_find("glLightModeli",ptldg);
glLightModelfv = ldg_find("glLightModelfv",ptldg);
glLoadMatrixf = ldg_find("glLoadMatrixf",ptldg);
glLoadName = ldg_find("glLoadName",ptldg);
glMaterialf = ldg_find("glMaterialf",ptldg);
glMultMatrixf = ldg_find("glMultMatrixf",ptldg);
glNewList = ldg_find("glNewList",ptldg);
glNormal3f = ldg_find("glNormal3f",ptldg);
glNormal3fv = ldg_find("glNormal3fv",ptldg);
glNormalPointer = ldg_find("glNormalPointer",ptldg);
glPixelStorei = ldg_find("glPixelStorei",ptldg);
glPolygonMode = ldg_find("glPolygonMode",ptldg);
glPolygonOffset = ldg_find("glPolygonOffset",ptldg);
glPopName = ldg_find("glPopName",ptldg);
glPushName = ldg_find("glPushName",ptldg);
glRenderMode = ldg_find("glRenderMode",ptldg);
glSelectBuffer = ldg_find("glSelectBuffer",ptldg);
glScalef = ldg_find("glScalef",ptldg);
glShadeModel = ldg_find("glShadeModel",ptldg);
glTexCoord2f = ldg_find("glTexCoord2f",ptldg);
glTexCoord4f = ldg_find("glTexCoord4f",ptldg);
glTexCoord2fv = ldg_find("glTexCoord2fv",ptldg);
glTexCoordPointer = ldg_find("glTexCoordPointer",ptldg);
glTexImage2D = ldg_find("glTexImage2D",ptldg);
glVertex4f = ldg_find("glVertex4f",ptldg);
glVertex3fv = ldg_find("glVertex3fv",ptldg);
glVertexPointer = ldg_find("glVertexPointer",ptldg);
glViewport = ldg_find("glViewport",ptldg);
swapbuffer = ldg_find("swapbuffer",ptldg);
max_width  = ldg_find("max_width",ptldg);
max_height = ldg_find("max_height",ptldg);
glDeleteLists = ldg_find("glDeleteLists",ptldg);
gluLookAt  = ldg_find("gluLookAt",ptldg);
exception_error = ldg_find("exception_error",ptldg); 
}
