# Sozobon-C Makefile for Boinkout2

OBS = avfuncs.o boinkout.o bout2.o bout3.o bout4.o dialogs.o \
      levels.o ximgload.o fileio.o window.o extras.o bo_sound.o \
      external.o

boinkout:  $(OBS)
	$(CC) $(OBS) aes vdi -oboinkout.prg


clean:
	$(RM) *.o *.bak
