# Sozobon-C Makefile for Boinkout2

OBS = boinkout.o bout2.o bout3.o bout4.o levels.o \
      ximgload.o fileio.o window.o extras.o bo_sound.o

boinkout:  $(OBS)
	$(CC) $(OBS) aes vdi -oboinkout.prg


clean:
	$(RM) *.o *.bak
