# Makefile for the SOZOBON MAGIC interface library (16 bit int default)

### NEEDS SOZOBON MAKE ! ###

CC       =  cc
SHELL    =  u:/bin/sh.ttp
DELETE   =  rm -f

# common subset of options;
COPTS    =  -O

# normal CFLAGS
CFLAGS   =  $(COPTS)

# libs
LLIBS    =  magic.a xaesfast.a xvdifast.a

# flags for PFLAGS
PFLAGS   =  +fload +fram +fmem

# executables
MAGICDEM =  magicdem\magicdem.prg
GDOS     =  gdos\gdos.tos
WINDOW   =  window\window.prg

# objects
OBJCS1   =  magicdem\magicdem.o magicdem\magiclin.o
OBJCS2   =  gdos\gdos.o
OBJCS3   =  window\window.o

all: $(MAGICDEM) $(GDOS) $(WINDOW)

$(MAGICDEM): $(OBJCS1)
	$(CC) -o $@ $(OBJCS1) $(LLIBS)
	pflags $(PFLAGS) $@

$(GDOS): $(OBJCS2)
	$(CC) -o $@ $(OBJCS2) $(LLIBS)
	pflags $(PFLAGS) $@

$(WINDOW): $(OBJCS3)
	$(CC) -o $@ $(OBJCS3) $(LLIBS)
	pflags $(PFLAGS) $@

clean:
	$(DELETE) $(OBJCS1) $(OBJCS2) $(OBJCS3)

realclean: clean
	$(DELETE) $(M_DEMO) $(GDOS) $(WINDOW)
